// apps/web/src/routes/(app)/expenses/new/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import VendorPicker from '$lib/components/VendorPicker.svelte';
  import { trackFlowAbandonment } from '$lib/flow-abandonment';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
  const values = $derived(form?.values ?? {});
  const fieldErrors = $derived(form?.fieldErrors ?? {});

  // True while a Suggest request is in flight, so the UI can show a spinner and
  // hide the previous result banner until the new response lands.
  let suggesting = $state(false);

  // Photo-first (TMC-295 / TMC-235). Opening this page asks ONE question —
  // type it in, or start from a receipt — every time (a remembered choice is
  // state nobody can see, and a no-receipt expense must not be trapped behind
  // it). The chosen file lives in the always-mounted file input, so it
  // survives the ?/extract round-trip and rides the ?/save submit, where the
  // server creates the expense with the receipt attached in one call.
  // ?duplicate skips the chooser (that entry point already answered it).
  let manualChosen = $state(false);
  let extracting = $state(false);
  let attachedName = $state<string | null>(null);
  let fileInput: HTMLInputElement | null = $state(null);
  let extractBtn: HTMLButtonElement | null = $state(null);
  const showChooser = $derived(
    !form && !data.skipChooser && !manualChosen && !attachedName && !extracting,
  );

  function onFileChosen() {
    const chosen = fileInput?.files?.[0];
    if (!chosen) return;
    attachedName = chosen.name;
    // Reading starts immediately — the form comes back prefilled (or plainly
    // empty with the photo kept, when the read fails). requestSubmit with the
    // hidden button honours its formaction + formnovalidate.
    if (extractBtn) {
      extracting = true;
      extractBtn.form?.requestSubmit(extractBtn);
    }
  }

  function removeReceipt() {
    if (fileInput) fileInput.value = '';
    attachedName = null;
  }

  // enhance resets the form on a successful action by default. The Suggest
  // action succeeds even when no category fits, so a reset would wipe the
  // user's typed merchant/amount — keep values (apply the result, don't reset).
  // It also drives the `suggesting` flag for the Suggest button (detected via
  // the resolved action, which reflects the submitter's formaction), and the
  // `extracting` flag for the receipt read the same way.
  const onsubmit = ({ action }: { action: URL }) => {
    const isSuggest = action.search.includes('suggest');
    const isExtract = action.search.includes('extract');
    if (isSuggest) suggesting = true;
    if (isExtract) extracting = true;
    return async ({
      result,
      update,
    }: {
      result: { type: string };
      update: (o?: { reset?: boolean }) => Promise<void>;
    }) => {
      // A successful save redirects away — mark submitted so that redirect nav
      // isn't logged as abandonment. A failed save re-renders in place (no nav),
      // so leave the tracker armed. Suggest/extract are neither, and never mark it.
      if (!isSuggest && !isExtract && result.type === 'redirect') flow.markSubmitted();
      await update({ reset: false });
      suggesting = false;
      extracting = false;
    };
  };

  // expense_flow_abandoned: emit the furthest section reached if the user leaves
  // without saving. Reachable steps: 'amount' (vendor/amount/date) → 'category'.
  const flow = trackFlowAbandonment('expense_flow_abandoned', ['amount', 'category']);

  type FieldKey = 'merchant' | 'vendorContactId' | 'amount' | 'expenseDate' | 'categoryAccountId' | 'paymentAccountId' | 'memo';

  // Priority: a submitted value (the user just typed it, via a fail()/suggest
  // re-render) > a ?duplicate prefill from load > empty. So duplicating seeds
  // the field but a re-submit always wins.
  function v(key: FieldKey): string {
    const submitted = (values as Record<string, unknown>)[key];
    if (typeof submitted === 'string') return submitted;
    const seeded = (data.prefill as Record<string, string> | undefined)?.[key];
    return typeof seeded === 'string' ? seeded : '';
  }
  function err(key: FieldKey): string | undefined {
    return (fieldErrors as Record<string, string>)[key];
  }

  // Date defaults to today on a fresh load; a fail()-re-render keeps whatever
  // the user typed.
  const dateValue = $derived(v('expenseDate') || data.today);
  const categoryValue = $derived(v('categoryAccountId'));
  const paymentValue = $derived(v('paymentAccountId') || data.defaultPaymentId);
</script>

<a href="/expenses" class="eyebrow text-fg/60 hover:text-fg">← Expenses</a>
<h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
  New expense<span class="text-accent">.</span>
</h1>

<!-- The plain front door for capital purchases: durable gear gets handled
     differently underneath (kept as an asset, optionally financed, written off
     or spread over time), so route a "yes" into the big-purchase flow rather
     than booking it as a normal cost. -->
<a
  href="/purchases/new"
  class="mt-6 flex items-center justify-between gap-4 rounded-sm border border-fg/15 bg-surface-2 px-5 py-4 hover:border-accent"
>
  <div>
    <span class="font-serif text-fg">Will you use this for years?</span>
    <p class="mt-0.5 text-xs text-fg/55">
      Something big like a mower, trailer, or truck — log it as a big purchase instead.
    </p>
  </div>
  <span class="font-mono text-xs uppercase tracking-widest text-accent">Big purchase →</span>
</a>

{#if form?.formError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger" data-form-error role="alert" tabindex="-1">
    {form.formError}
  </div>
{/if}

{#if extracting}
  <div class="mt-6 flex items-center gap-2 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg/80">
    <span class="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-accent border-t-transparent"></span>
    Reading your receipt…
  </div>
{:else if form?.extracted}
  <div class="mt-6 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg/80">
    {form.extracted === 'full'
      ? 'Read from your receipt — check the details and save.'
      : 'Read part of your receipt — fill in the rest and save. The photo saves with the expense.'}
  </div>
{:else if form?.receiptNotice}
  <div class="mt-6 rounded-sm border border-fg/15 bg-surface-2 px-4 py-3 text-sm text-fg/70">
    {form.receiptNotice}
  </div>
{:else if form?.receiptError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.receiptError}
  </div>
{/if}

{#if suggesting}
  <div class="mt-6 flex items-center gap-2 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg/80">
    <span class="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-accent border-t-transparent"></span>
    Finding the best category…
  </div>
{:else if form?.suggested}
  <div class="mt-6 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg/80">
    Suggested a category from what you typed — review it and save.
  </div>
{:else if form?.suggestNotice}
  <div class="mt-6 rounded-sm border border-fg/15 bg-surface-2 px-4 py-3 text-sm text-fg/70">
    {form.suggestNotice}
  </div>
{:else if form?.suggestError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.suggestError}
  </div>
{/if}

<!-- The one prompt (TMC-295): manual or receipt-first, asked on every fresh
     open. "Type it in" and nothing else stands between a bank fee and the
     form; the receipt path opens the file picker and reads the photo. -->
{#if showChooser}
  <div class="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2">
    <button
      type="button"
      onclick={() => fileInput?.click()}
      class="rounded-sm border border-fg/15 bg-surface-2 px-5 py-6 text-left hover:border-accent"
    >
      <span class="font-serif text-lg text-fg">Start with the receipt</span>
      <p class="mt-1 text-sm text-fg/60">
        Upload a photo or PDF — the details fill themselves in, you check and save.
      </p>
    </button>
    <button
      type="button"
      onclick={() => (manualChosen = true)}
      class="rounded-sm border border-fg/15 bg-surface-2 px-5 py-6 text-left hover:border-accent"
    >
      <span class="font-serif text-lg text-fg">Type it in</span>
      <p class="mt-1 text-sm text-fg/60">No receipt, or you'd rather enter it by hand.</p>
    </button>
  </div>
  {#if data.aiHint}
    <p class="mt-3 text-xs text-fg/55">
      Receipts aren't read automatically on this server — the photo still saves with the expense.
      Turn reading on in <a href="/settings/ai" class="text-accent hover:text-fg">Settings → AI</a>.
    </p>
  {/if}
{/if}

<form
  method="post"
  action="?/save"
  enctype="multipart/form-data"
  class="mt-8 space-y-6"
  class:hidden={showChooser}
  use:enhance={onsubmit}
>
  <!-- Always mounted so the chosen file survives the ?/extract re-render and
       rides the ?/save submit (the server then creates expense + receipt in
       one call). The hidden button carries ?/extract for requestSubmit. -->
  <input
    bind:this={fileInput}
    type="file"
    name="file"
    accept="image/jpeg,image/png,application/pdf"
    class="hidden"
    onchange={onFileChosen}
  />
  <button
    bind:this={extractBtn}
    type="submit"
    formaction="?/extract"
    formnovalidate
    class="hidden"
    aria-label="Read the receipt"
    tabindex="-1"
  ></button>

  {#if attachedName}
    <div class="flex items-center justify-between gap-3 rounded-sm border border-fg/15 bg-surface-2 px-4 py-3">
      <span class="truncate text-sm text-fg/80">📎 {attachedName} — saves with the expense</span>
      <button
        type="button"
        onclick={removeReceipt}
        class="font-mono text-xs uppercase tracking-widest text-danger hover:opacity-80"
      >
        Remove
      </button>
    </div>
  {:else}
    <button
      type="button"
      onclick={() => fileInput?.click()}
      class="font-mono text-xs uppercase tracking-widest text-accent hover:text-fg"
    >
      📎 Start with a receipt photo
    </button>
  {/if}

  <div class="grid grid-cols-1 gap-6 sm:grid-cols-2" onfocusin={() => flow.reach('amount')}>
    <div>
      <label for="merchant" class="label">
        Vendor<span class="text-accent">*</span>
      </label>
      <!-- Keyed remount: VendorPicker seeds from its initial props ONCE at
           mount, which is right on a fresh page load (edit's extract prefill
           navigates) but wrong here — the photo-first form is already mounted
           while ?/extract runs, so the extracted merchant changed a prop the
           picker deliberately ignores and the Vendor field stayed empty while
           amount/date filled. Re-keying on the server-provided pair restores
           fresh-mount semantics exactly when the server hands back new values,
           and never remounts during plain typing (typing changes the picker's
           internal state, not these). -->
      {#key `${v('merchant')}|${v('vendorContactId')}`}
        <VendorPicker
          initialMerchant={v('merchant')}
          initialVendorContactId={v('vendorContactId')}
          required
        />
      {/key}
      {#if err('merchant')}
        <p class="mt-1 text-xs text-danger">{err('merchant')}</p>
      {/if}
    </div>
    <div>
      <label for="amount" class="label">
        Amount<span class="text-accent">*</span>
      </label>
      <input
        id="amount"
        name="amount"
        type="text"
        inputmode="decimal"
        required
        placeholder="0.00"
        value={v('amount')}
        class="mt-1 w-full rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
      />
      {#if err('amount')}
        <p class="mt-1 text-xs text-danger">{err('amount')}</p>
      {/if}
    </div>
  </div>

  <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
    <div onfocusin={() => flow.reach('amount')}>
      <label for="expenseDate" class="label">
        Date<span class="text-accent">*</span>
      </label>
      <input
        id="expenseDate"
        name="expenseDate"
        type="date"
        required
        value={dateValue}
        class="field mt-1"
      />
      {#if err('expenseDate')}
        <p class="mt-1 text-xs text-danger">{err('expenseDate')}</p>
      {/if}
    </div>
    <div onfocusin={() => flow.reach('category')}>
      <div class="flex items-baseline justify-between">
        <label for="categoryAccountId" class="label">
          Category<span class="text-accent">*</span>
        </label>
        <!-- formnovalidate: suggest with just a merchant typed, without tripping
             the other required fields. Submits to the ?/suggest action. -->
        <button
          type="submit"
          formaction="?/suggest"
          formnovalidate
          disabled={suggesting}
          class="flex items-center gap-1.5 font-mono text-xs uppercase tracking-widest text-accent hover:text-fg disabled:opacity-60"
        >
          {#if suggesting}
            <span class="inline-block h-3 w-3 animate-spin rounded-full border border-accent border-t-transparent"></span>
            Suggesting…
          {:else}
            ✨ Suggest
          {/if}
        </button>
      </div>
      <select
        id="categoryAccountId"
        name="categoryAccountId"
        required
        class="field mt-1"
      >
        <option value="" disabled selected={categoryValue === ''}>Select a category…</option>
        {#each data.categories as cat (cat.id)}
          <option value={cat.id} selected={categoryValue === cat.id}>{cat.label}</option>
        {/each}
      </select>
      {#if err('categoryAccountId')}
        <p class="mt-1 text-xs text-danger">{err('categoryAccountId')}</p>
      {/if}
    </div>
  </div>

  {#if data.paymentPickerVisible}
    <div class="sm:w-1/2 sm:pr-3">
      <label for="paymentAccountId" class="label">
        Paid from
      </label>
      <select
        id="paymentAccountId"
        name="paymentAccountId"
        class="field mt-1"
      >
        {#each data.paymentAccounts as acc (acc.id)}
          <option value={acc.id} selected={paymentValue === acc.id}>{acc.label}</option>
        {/each}
      </select>
      {#if err('paymentAccountId')}
        <p class="mt-1 text-xs text-danger">{err('paymentAccountId')}</p>
      {/if}
    </div>
  {:else}
    <input type="hidden" name="paymentAccountId" value={data.defaultPaymentId} />
  {/if}

  <div>
    <label for="memo" class="label">Memo</label>
    <textarea
      id="memo"
      name="memo"
      rows="3"
      maxlength="5000"
      class="field mt-1"
      >{v('memo')}</textarea
    >
  </div>

  <div class="flex items-center gap-4">
    <button
      type="submit"
      class="btn"
    >
      Save expense
    </button>
    <a href="/expenses" class="text-sm text-fg/60 hover:text-fg">Cancel</a>
  </div>
</form>

// apps/mobile/src/app/(app)/expenses/new.tsx
import { expenseCreateSchema, localToday } from '@thalermark/validation';
import * as ImagePicker from 'expo-image-picker';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { type ReactNode, useCallback, useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Image,
  KeyboardAvoidingView,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DateField } from '../../../components/DateField';
import { KIND_LABEL } from '../../../components/MoneyAccountPicker';
import { SuggestButton, SuggestNotice } from '../../../components/SuggestCategory';
import { VendorField } from '../../../components/VendorField';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { apiErrorMessage } from '../../../lib/api-errors';
import { type SuggestResult, suggestCategory } from '../../../lib/categorize';
import { resolveVendor } from '../../../lib/expense-vendor';
import { useFlowAbandonment } from '../../../lib/flow-abandonment';
import {
  READ_OK_NOTICE,
  READ_PARTIAL_NOTICE,
  extractionPrefill,
  hasPrefill,
  readFailureNotice,
} from '../../../lib/receipt-first';
import { createExpenseWithReceipt, extractLooseReceipt } from '../../../lib/upload';

// Mirror of apps/web's /expenses/new. An expense posts against two chart-of-
// accounts rows (category = an 'expense' account, payment = an 'asset'
// account), so the form fetches the company's COA and offers two pickers. A
// "✨ Suggest" affordance asks the AI categorizer to pre-fill the category from
// the typed merchant (opt-in; soft-fails when no LLM is configured).
//
// Photo-first (TMC-295 / TMC-283): opening this screen asks ONE question —
// type it in, or start from the receipt. The prompt appears every time (a
// remembered choice is state nobody can see, and someone logging a bank fee
// with no receipt must not be trapped in a camera-first path). A captured
// photo is read by the vision model and the form comes back prefilled and
// editable; the photo rides in state and the ONE save creates the expense
// with the receipt already attached (/api/expenses/with-receipt). Nothing is
// created at capture — an expense posts journal entries, so an abandoned
// photo must leave no ledger rows. Every read failure falls back to this same
// form with the photo kept.
type Account = { id: string; code: string; name: string; kind?: string | null };

type ReceiptAsset = { uri: string; mimeType?: string | null; fileName?: string | null };

const todayIso = () => new Date().toISOString().slice(0, 10);

export default function NewExpense() {
  const router = useRouter();
  // Duplicate-as-template: ?duplicate=<id> seeds the form from an existing
  // expense (merchant / amount / category / paid-with / memo). The DATE is not
  // copied — a duplicate is a fresh occurrence, so it defaults to today. The
  // receipt is not copied either. Mirrors web's /expenses/new?duplicate=.
  const { duplicate } = useLocalSearchParams<{ duplicate?: string }>();

  const [companyId, setCompanyId] = useState<string | null>(null);
  const [categories, setCategories] = useState<Account[]>([]);
  const [payments, setPayments] = useState<Account[]>([]);
  const [bootstrapped, setBootstrapped] = useState(false);

  const [merchant, setMerchant] = useState('');
  // Vendor link state: '' (unlinked) | <uuid> | VENDOR_NEW. Resolved on submit.
  const [vendorContactId, setVendorContactId] = useState('');
  const [amount, setAmount] = useState('');
  const [expenseDate, setExpenseDate] = useState(todayIso());
  const [memo, setMemo] = useState('');
  const [categoryId, setCategoryId] = useState<string | null>(null);
  const [paymentId, setPaymentId] = useState<string | null>(null);
  const [picker, setPicker] = useState<'category' | 'payment' | null>(null);

  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [suggesting, setSuggesting] = useState(false);
  const [suggestNotice, setSuggestNotice] = useState<SuggestResult | null>(null);

  // Photo-first state. The chooser shows on every fresh open of this screen;
  // ?duplicate skips it because that entry point already answered the question
  // (it seeds the form from an existing expense). aiReady is a best-effort
  // probe: false only when the server DEFINITELY has no AI connection (the
  // settings read is admin-gated, so members stay at null = unknown and the
  // extract attempt itself is the authority).
  const [chooser, setChooser] = useState(!duplicate);
  const [aiReady, setAiReady] = useState<boolean | null>(null);
  const [receiptAsset, setReceiptAsset] = useState<ReceiptAsset | null>(null);
  const [reading, setReading] = useState(false);
  const [receiptNotice, setReceiptNotice] = useState<{ kind: 'ok' | 'info'; text: string } | null>(
    null,
  );
  // The capture can land before the bootstrap resolves companyId/categories,
  // so extraction runs from the effect below (fresh values) exactly once.
  const extractStarted = useRef(false);

  async function capture(source: 'camera' | 'library') {
    const perm =
      source === 'camera'
        ? await ImagePicker.requestCameraPermissionsAsync()
        : await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!perm.granted) {
      // Not a dead end: drop to the manual form with a plain sentence.
      setChooser(false);
      setReceiptNotice({
        kind: 'info',
        text: source === 'camera' ? 'Camera permission denied.' : 'Photo access denied.',
      });
      return;
    }
    const result =
      source === 'camera'
        ? await ImagePicker.launchCameraAsync({ quality: 0.7 })
        : await ImagePicker.launchImageLibraryAsync({ quality: 0.7, mediaTypes: ['images'] });
    // Cancelling the picker returns to the chooser — the question is still open.
    if (result.canceled || !result.assets[0]) return;
    extractStarted.current = false;
    setReceiptNotice(null);
    setReceiptAsset(result.assets[0]);
    setChooser(false);
  }

  function removeReceipt() {
    setReceiptAsset(null);
    setReceiptNotice(null);
    extractStarted.current = false;
  }

  // Read the captured receipt once the company + categories are loaded. On any
  // failure the photo is KEPT and the form stays usable — the person loses the
  // typing they were saved, not the work they did (TMC-295).
  useEffect(() => {
    if (!receiptAsset || extractStarted.current) return;
    // Wait for the whole bootstrap, not just companyId: the category list has
    // to be final before the suggested-category filter runs against it.
    if (!bootstrapped || !companyId) return;
    extractStarted.current = true;
    if (aiReady === false) {
      setReceiptNotice({ kind: 'info', text: readFailureNotice('ai_not_configured') });
      return;
    }
    let active = true;
    (async () => {
      setReading(true);
      try {
        const res = await extractLooseReceipt(companyId, receiptAsset);
        if (!active) return;
        if (!res.ok) {
          setReceiptNotice({ kind: 'info', text: readFailureNotice(res.error) });
          return;
        }
        const prefill = extractionPrefill(res.body, new Set(categories.map((c) => c.id)));
        if (prefill.merchant) setMerchant(prefill.merchant);
        if (prefill.amount) setAmount(prefill.amount);
        if (prefill.expenseDate) setExpenseDate(prefill.expenseDate);
        if (prefill.categoryAccountId) setCategoryId(prefill.categoryAccountId);
        if (!hasPrefill(prefill)) {
          setReceiptNotice({ kind: 'info', text: readFailureNotice('nothing_read') });
        } else {
          const full = prefill.merchant && prefill.amount && prefill.expenseDate;
          setReceiptNotice({ kind: 'ok', text: full ? READ_OK_NOTICE : READ_PARTIAL_NOTICE });
        }
      } finally {
        if (active) setReading(false);
      }
    })();
    return () => {
      active = false;
    };
  }, [receiptAsset, bootstrapped, companyId, categories, aiReady]);

  // expense_flow_abandoned: on leaving without saving, emit the furthest section
  // engaged — 'category' if a category is picked, else 'amount' if vendor/amount
  // typed, else nothing.
  const flow = useFlowAbandonment('expense_flow_abandoned', () =>
    categoryId ? 'category' : merchant || amount ? 'amount' : null,
  );

  async function onSuggest() {
    if (!companyId) return;
    setSuggesting(true);
    setSuggestNotice(null);
    const result = await suggestCategory({ companyId, merchant, memo, amount });
    if (result.kind === 'applied') setCategoryId(result.categoryAccountId);
    setSuggestNotice(result);
    setSuggesting(false);
  }

  const didBootstrap = useRef(false);
  useFocusEffect(
    useCallback(() => {
      if (didBootstrap.current) return;
      didBootstrap.current = true;
      let active = true;
      (async () => {
        const compRes = await api.api.companies.$get();
        if (!active || !compRes.ok) return;
        const { companies } = await compRes.json();
        const company = await pickActiveCompany(companies);
        if (!company) return;
        setCompanyId(company.id);
        // Re-date through the company's timezone now that we know it
        // (TMC-303). The useState seed ran on the device clock in UTC, which
        // dates an evening expense tomorrow.
        setExpenseDate(localToday(company.timezone));
        const [catRes, payRes] = await Promise.all([
          api.api.companies[':id'].accounts.$get({
            param: { id: company.id },
            query: { type: 'expense' },
          }),
          // Money accounts, NOT `type=asset` (TMC-207). That query also returns
          // Accounts Receivable, Vehicles & Equipment and Accumulated
          // Depreciation, so the picker was offering "paid for fuel out of
          // Accumulated Depreciation" — a balanced entry that is nonsense. It
          // also excluded credit cards, which are a LIABILITY money genuinely
          // moves through and the main case this feature exists for.
          api.api['money-accounts'].$get({ query: { companyId: company.id } }),
        ]);
        if (!active) return;
        if (catRes.ok) setCategories((await catRes.json()).accounts);
        if (payRes.ok) {
          const { moneyAccounts } = await payRes.json();
          setPayments(
            moneyAccounts.map((a) => ({ id: a.id, code: a.code, name: a.name, kind: a.kind })),
          );
          setPaymentId((p) => p ?? moneyAccounts[0]?.id ?? null);
        }

        // Best-effort AI probe for the chooser's "receipts won't be read" line.
        // The settings read is admin-gated (settings:manage), so a 403 leaves
        // aiReady at null = unknown and nothing is claimed either way — the
        // extract attempt is the authority, and its fallback covers everyone.
        try {
          const aiRes = await api.api.settings.ai.$get();
          if (active && aiRes.ok) setAiReady((await aiRes.json()).connection !== null);
        } catch {}

        // Duplicate prefill — seed from the source expense (date + receipt
        // intentionally excluded; see the param note above).
        if (duplicate) {
          const srcRes = await api.api.expenses[':id'].$get({ param: { id: duplicate } });
          if (active && srcRes.ok) {
            const src = await srcRes.json();
            setMerchant(src.merchant ?? '');
            // A duplicate paid to the same vendor keeps the link.
            setVendorContactId(src.vendorContactId ?? '');
            setAmount(src.amount);
            setMemo(src.memo ?? '');
            setCategoryId(src.categoryAccountId);
            setPaymentId(src.paymentAccountId);
          }
        }
      })()
        .catch(() => {})
        .finally(() => {
          if (active) setBootstrapped(true);
        });
      return () => {
        active = false;
      };
    }, [duplicate]),
  );

  const categoryName = categories.find((a) => a.id === categoryId)?.name ?? null;
  const paymentName = payments.find((a) => a.id === paymentId)?.name ?? null;
  const noCompany = bootstrapped && companyId === null;
  const canSubmit =
    !submitting &&
    !noCompany &&
    merchant.trim().length > 0 &&
    amount.trim().length > 0 &&
    categoryId !== null &&
    paymentId !== null;

  async function onSubmit() {
    if (!companyId || !categoryId || !paymentId) return;
    setFormError(null);
    setFieldErrors({});

    const payload = {
      companyId,
      categoryAccountId: categoryId,
      paymentAccountId: paymentId,
      amount: amount.trim(),
      expenseDate: expenseDate.trim(),
      merchant: merchant.trim(),
      memo: memo.trim() === '' ? undefined : memo.trim(),
    };
    const parsed = expenseCreateSchema.safeParse(payload);
    if (!parsed.success) {
      const errs: Record<string, string> = {};
      for (const issue of parsed.error.issues) {
        const key = String(issue.path[0] ?? '_');
        if (!errs[key]) errs[key] = issue.message;
      }
      setFieldErrors(errs);
      return;
    }

    setSubmitting(true);
    try {
      // Resolve the Vendor field after the core fields validate (so an inline
      // "+ Add vendor" never creates an orphan contact for an invalid expense).
      const vendor = await resolveVendor(companyId, vendorContactId, merchant);
      if (!vendor.ok) {
        setFormError('That vendor could not be created. Try again.');
        return;
      }
      // Photo-first: with a receipt in hand, the ONE save goes to the
      // multipart create-with-receipt endpoint — both-or-neither on the
      // server, so a failed upload never yields an expense that claims a
      // receipt it does not have. Without one, the plain JSON create.
      if (receiptAsset) {
        const fields: Record<string, string> = {
          companyId: parsed.data.companyId,
          categoryAccountId: parsed.data.categoryAccountId,
          paymentAccountId: parsed.data.paymentAccountId,
          amount: parsed.data.amount,
          expenseDate: parsed.data.expenseDate,
          merchant: parsed.data.merchant,
        };
        if (parsed.data.memo) fields.memo = parsed.data.memo;
        if (vendor.value) fields.vendorContactId = vendor.value;
        const res = await createExpenseWithReceipt(fields, receiptAsset);
        if (!res.ok) {
          setFormError(apiErrorMessage(res.error, 'That could not be created. Try again.'));
          return;
        }
        flow.markSubmitted();
        router.replace(`/expenses/${res.body.id}`);
        return;
      }
      const res = await api.api.expenses.$post({
        json: { ...parsed.data, vendorContactId: vendor.value ?? undefined },
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        setFormError(apiErrorMessage(body?.error, 'That could not be created. Try again.', body));
        return;
      }
      const created = await res.json();
      flow.markSubmitted();
      router.replace(`/expenses/${created.id}`);
    } catch {
      setFormError('That could not be created. Try again.');
    } finally {
      setSubmitting(false);
    }
  }

  const pickerList = picker === 'category' ? categories : payments;

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              ← Expenses
            </Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">New expense</Text>

          {/* Plain front door for capital purchases — durable gear is handled
              differently underneath (kept as an asset, optionally financed,
              written off or spread), so route a "yes" into the big-purchase
              flow rather than booking it as a normal cost. */}
          <Pressable
            onPress={() => router.push('/purchases/new')}
            className="mt-6 flex-row items-center justify-between gap-3 rounded-sm border border-ink/15 bg-cream-warm px-5 py-4 active:bg-cream"
          >
            <View className="flex-1">
              <Text className="font-serif text-ink">Will you use this for years?</Text>
              <Text className="mt-0.5 text-xs text-ink/55">
                Something big like a mower, trailer, or truck — log it as a big purchase instead.
              </Text>
            </View>
            <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
              Big →
            </Text>
          </Pressable>

          {formError ? (
            <View className="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
              <Text className="text-sm text-oxblood">{formError}</Text>
            </View>
          ) : null}

          {/* Photo-first strip (TMC-283). The captured receipt rides here until
              save — visible so nobody wonders whether the photo made it, and
              removable so the flow can still end as a plain manual expense. */}
          {reading ? (
            <View className="mt-6 flex-row items-center gap-3 rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3">
              <ActivityIndicator className="text-ink" />
              <Text className="text-sm text-ink/80">Reading your receipt…</Text>
            </View>
          ) : null}
          {receiptNotice ? (
            <View
              className={
                receiptNotice.kind === 'ok'
                  ? 'mt-6 rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3'
                  : 'mt-6 rounded-sm border border-ink/15 bg-cream-warm px-4 py-3'
              }
            >
              <Text className="text-sm text-ink/80">{receiptNotice.text}</Text>
            </View>
          ) : null}
          {receiptAsset ? (
            <View className="mt-6 flex-row items-center gap-3 rounded-sm border border-ink/15 bg-cream-warm px-4 py-3">
              <Image
                source={{ uri: receiptAsset.uri }}
                className="h-16 w-12 rounded-sm border border-ink/10 bg-cream"
                resizeMode="cover"
              />
              <Text className="flex-1 text-sm text-ink/80">
                Receipt attached — it saves with the expense.
              </Text>
              <Pressable onPress={removeReceipt} hitSlop={8}>
                <Text className="font-mono text-xs uppercase tracking-widest text-oxblood">
                  Remove
                </Text>
              </Pressable>
            </View>
          ) : (
            <Pressable onPress={() => setChooser(true)} className="mt-6 self-start">
              <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
                📷 Start with a receipt photo
              </Text>
            </Pressable>
          )}

          <View className="mt-8 gap-5">
            <VendorField
              label="Vendor *"
              companyId={companyId}
              merchant={merchant}
              setMerchant={setMerchant}
              vendorContactId={vendorContactId}
              setVendorContactId={setVendorContactId}
              error={fieldErrors.merchant}
            />
            <Field
              label="Amount *"
              value={amount}
              onChangeText={setAmount}
              error={fieldErrors.amount}
              keyboardType="decimal-pad"
            />
            <DateField
              label="Date *"
              value={expenseDate}
              onChange={setExpenseDate}
              error={fieldErrors.expenseDate}
            />

            <View>
              <PickerField
                label="Category *"
                value={categoryName}
                placeholder="Select a category…"
                onPress={() => setPicker('category')}
                error={fieldErrors.categoryAccountId}
                headerRight={<SuggestButton suggesting={suggesting} onPress={onSuggest} />}
              />
              {suggestNotice ? <SuggestNotice result={suggestNotice} /> : null}
            </View>
            <PickerField
              label="Paid with *"
              value={paymentName}
              placeholder="Select an account…"
              onPress={() => setPicker('payment')}
              error={fieldErrors.paymentAccountId}
            />

            <Field label="Memo" value={memo} onChangeText={setMemo} />

            {noCompany ? (
              <Text className="text-xs text-oxblood">No company in this workspace.</Text>
            ) : null}

            <Pressable
              onPress={onSubmit}
              disabled={!canSubmit}
              className="mt-2 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
            >
              {submitting ? (
                <ActivityIndicator className="text-cream" />
              ) : (
                <Text className="text-center text-sm font-medium text-cream">Create expense</Text>
              )}
            </Pressable>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>

      {/* The one prompt (TMC-295): manual or camera, asked EVERY time. Backdrop
          tap and "Type it in" both land on the manual form — a no-receipt
          expense (a bank fee) must never be forced through a camera path.
          Cancelling the system camera returns here with the question open. */}
      <Modal
        visible={chooser}
        animationType="slide"
        transparent
        onRequestClose={() => setChooser(false)}
      >
        <Pressable className="flex-1 justify-end bg-ink/40" onPress={() => setChooser(false)}>
          <Pressable className="rounded-t-lg bg-cream px-6 pb-10 pt-5" onPress={() => {}}>
            <Text className="font-serif text-xl text-ink">How do you want to log it?</Text>
            <View className="mt-4 gap-2">
              <Pressable
                onPress={() => capture('camera')}
                className="rounded-sm bg-ink px-4 py-3 active:bg-gold-deep"
              >
                <Text className="text-center text-sm font-medium text-cream">Snap the receipt</Text>
              </Pressable>
              <Pressable
                onPress={() => capture('library')}
                className="rounded-sm border border-ink/20 px-4 py-3 active:bg-ink/5"
              >
                <Text className="text-center text-sm text-ink">Choose a photo</Text>
              </Pressable>
              <Pressable
                onPress={() => setChooser(false)}
                className="rounded-sm border border-ink/20 px-4 py-3 active:bg-ink/5"
              >
                <Text className="text-center text-sm text-ink">Type it in</Text>
              </Pressable>
            </View>
            {aiReady === false ? (
              <Text className="mt-3 text-xs text-ink-subtle">
                Receipts aren't read automatically on this server — the photo still saves with the
                expense. Turn reading on in Settings → AI.
              </Text>
            ) : null}
          </Pressable>
        </Pressable>
      </Modal>

      <Modal
        visible={picker !== null}
        animationType="slide"
        transparent
        onRequestClose={() => setPicker(null)}
      >
        <Pressable className="flex-1 justify-end bg-ink/40" onPress={() => setPicker(null)}>
          <Pressable
            className="max-h-[70%] rounded-t-lg bg-cream px-6 pb-10 pt-5"
            onPress={() => {}}
          >
            <Text className="font-serif text-xl text-ink">
              {picker === 'category' ? 'Choose category' : 'Paid with'}
            </Text>
            <ScrollView className="mt-4">
              {pickerList.map((a) => (
                <Pressable
                  key={a.id}
                  onPress={() => {
                    if (picker === 'category') setCategoryId(a.id);
                    else setPaymentId(a.id);
                    setPicker(null);
                  }}
                  className="border-b border-ink/10 py-3"
                >
                  <Text className="text-ink">{a.name}</Text>
                  {picker === 'payment' && a.kind ? (
                    <Text className="text-xs text-ink-subtle">{KIND_LABEL[a.kind] ?? ''}</Text>
                  ) : null}
                </Pressable>
              ))}
            </ScrollView>
          </Pressable>
        </Pressable>
      </Modal>
    </SafeAreaView>
  );
}

function Field({
  label,
  value,
  onChangeText,
  error,
  keyboardType,
  autoCapitalize,
}: {
  label: string;
  value: string;
  onChangeText: (t: string) => void;
  error?: string;
  keyboardType?: 'decimal-pad';
  autoCapitalize?: 'none';
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">{label}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        keyboardType={keyboardType}
        autoCapitalize={autoCapitalize}
        className="mt-1 rounded-sm border border-field bg-cream-warm px-3 py-2 text-ink"
      />
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}

function PickerField({
  label,
  value,
  placeholder,
  onPress,
  error,
  headerRight,
}: {
  label: string;
  value: string | null;
  placeholder: string;
  onPress: () => void;
  error?: string;
  headerRight?: ReactNode;
}) {
  return (
    <View>
      <View className="flex-row items-center justify-between">
        <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">{label}</Text>
        {headerRight ?? null}
      </View>
      <Pressable
        onPress={onPress}
        className="mt-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-3"
      >
        <Text className={value ? 'text-ink' : 'text-ink-subtle'}>{value ?? placeholder}</Text>
      </Pressable>
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}
