// apps/web/src/lib/charts/ColumnChart.svelte
<script lang="ts" generics="Row">
  import {
    type ColumnChartProps,
    formatValue,
    maxValue,
    toNumber,
    toneForIndex,
  } from '@thalermark/charts';
  import { Html, LayerCake, Svg } from 'layercake';
  import { scaleBand } from 'd3-scale';
  import ChartFrame from './ChartFrame.svelte';
  import { toneFill } from './tone.js';

  // Vertical bars over a categorical or time axis.
  //
  // WHY THE TICK LABELS LIVE IN A LAYERCAKE <Html> LAYER. The chart this
  // replaces drew its bars in one flex row and its month labels in a SECOND,
  // parallel flex row, keeping them aligned by duplicating `gap-1.5`,
  // `min-w-6` and `flex-1` across both. That is alignment by coincidence: edit
  // one row's spacing and the labels silently slide off the bars. Here both
  // layers are positioned by LayerCake against the same padded box and the same
  // band scale, so they cannot drift — the labels sit at the band's own centre
  // by construction.
  //
  // WHY `ssr` + `percentRange`. Coordinates come out as percentages instead of
  // pixels, so the marks need no measured container and render on the SERVER.
  // Combined with ChartFrame's table that means the chart exists — really
  // exists, as geometry — before any JavaScript runs.

  // The band scale as this component consumes it — the domain value in, the
  // band's left edge out, plus its width. d3's ScaleBand type would do, but
  // naming the two members used keeps the LayerCake seam explicit.
  type BandScale = {
    (value: string): number | undefined;
    bandwidth(): number;
  };

  let { data, x, series, caption, format = 'money', height = 224, empty }: ColumnChartProps<Row> =
    $props();

  // Reserved strip below the plot for the tick labels. The <Html> layer renders
  // into it by overflowing the padded box, which is why LayerCake's padding and
  // this constant have to agree.
  const LABEL_BAND = 22;

  // Widest a single band may be drawn, as a percentage of the plot. Twelve
  // months land near 6%, so the usual case never meets this; it exists to stop a
  // three-row series rendering as three slabs.
  const MAX_SLOT_PCT = 10;

  const rows = $derived([...data]);

  // The domain is the x key's value per row, so the band scale and the labels
  // agree on identity even when two rows format to the same tick text.
  const domain = $derived(rows.map((row) => String((row as Record<string, unknown>)[x.key])));

  // One shared ceiling across every series, so two series are comparable by
  // eye. maxValue returns null for an all-unknown series — distinct from 0,
  // which is a real flat chart.
  const ceiling = $derived.by(() => {
    const all = rows.flatMap((row) =>
      series.map((s) => (row as Record<string, unknown>)[s.key] as string | null),
    );
    return maxValue(all);
  });
</script>

<ChartFrame {data} {x} {series} {caption} {format} {height} {empty}>
  {#snippet chart()}
    <div class="h-full w-full">
      <LayerCake
        data={rows}
        x={(d: Row) => String((d as Record<string, unknown>)[x.key])}
        xScale={scaleBand().paddingInner(0.28).paddingOuter(0.14)}
        xDomain={domain}
        yDomain={[0, ceiling ?? 0]}
        padding={{ top: 4, right: 0, bottom: LABEL_BAND, left: 0 }}
        ssr
        percentRange
      >
        <!-- LayerCake is JSDoc-typed, so its snippet parameters arrive as
             `any`. Annotated here with the slice actually used, which is also
             the honest contract: this chart needs a band scale and nothing
             else from the coordinate context. -->
        {#snippet children({ xScale }: { xScale: BandScale })}
          <Svg>
            <!-- Three gridlines and no numeric axis, matching the chart being
                 replaced. The exact figures are one hover away and always in
                 the accessible table; a y-axis of compacted money on a 24px
                 tick is noise this layout does not need. -->
            {#each [0.25, 0.5, 0.75] as at (at)}
              <line
                x1="0%"
                x2="100%"
                y1="{at * 100}%"
                y2="{at * 100}%"
                stroke="rgb(var(--fg) / 0.07)"
                stroke-width="1"
              />
            {/each}

            {#each rows as row, rowIndex (domain[rowIndex])}
              {@const bandStart = xScale(domain[rowIndex]) ?? 0}
              {@const bandWidth = xScale.bandwidth()}
              <!-- A band scale divides the full width among however many rows
                   there are, so three months produce bars a third of the chart
                   wide — slabs rather than columns, which reads as a different
                   kind of graphic entirely. Cap the drawn slot and centre it in
                   its band: a twelve-month series is already narrower than the
                   cap and is untouched, while a sparse one stays legible as a
                   bar chart. -->
              {@const slot = Math.min(bandWidth, MAX_SLOT_PCT)}
              {@const slotStart = bandStart + (bandWidth - slot) / 2}
              {#each series as s, seriesIndex (s.key)}
                {@const value = toNumber((row as Record<string, unknown>)[s.key] as string | null)}
                {#if value !== null && ceiling !== null && ceiling > 0}
                  {@const topPct = 100 - (value / ceiling) * 100}
                  <!-- Several series share a band, each taking an equal slice.
                       With one series that is the whole band, so the common
                       case pays nothing for the general one. -->
                  <rect
                    x="{slotStart + (slot / series.length) * seriesIndex}%"
                    y="{topPct}%"
                    width="{slot / series.length}%"
                    height="{100 - topPct}%"
                    rx="2"
                    fill={toneFill(s.tone ?? toneForIndex(seriesIndex))}
                  >
                    <title
                      >{x.label(row)}: {formatValue(
                        (row as Record<string, unknown>)[s.key] as string | null,
                        format,
                      )}</title
                    >
                  </rect>
                {/if}
              {/each}
            {/each}
          </Svg>

          <Html pointerEvents={false}>
            {#each rows as row, rowIndex (domain[rowIndex])}
              {@const bandStart = xScale(domain[rowIndex]) ?? 0}
              <span
                class="absolute truncate text-center font-mono text-[10px] uppercase tracking-wide text-fg/50"
                style="left: {bandStart}%; width: {xScale.bandwidth()}%; top: 100%; padding-top: 6px;"
              >
                {x.label(row)}
              </span>
            {/each}
          </Html>
        {/snippet}
      </LayerCake>
    </div>
  {/snippet}
</ChartFrame>

// apps/mobile/src/components/charts/ColumnChart.tsx
import {
  type ColumnChartProps,
  formatValue,
  maxValue,
  toNumber,
  toneForIndex,
} from '@thalermark/charts';
import { Text, View } from 'react-native';
import { Bar, CartesianChart } from 'victory-native';
import { toneColor } from './tone';

// Vertical bars over a categorical or time axis — the mobile half of the
// vocabulary, sharing ColumnChartProps with the Svelte implementation so a
// divergence between the two is a compile error rather than a discovery.
//
// THE TICK LABELS ARE RN <Text>, NOT DRAWN BY SKIA, and that is not a
// stylistic preference. victory-native's axis labels need an SkFont, and this
// app loads no custom fonts at all — there is no useFonts call anywhere in
// apps/mobile/src and no font files in assets, so `font-serif` and `font-mono`
// already fall back to system faces everywhere else. Handing Skia a font it
// does not have draws nothing. Rendering the ticks as ordinary Text also keeps
// them on the same `font-mono text-[10px] uppercase tracking-wide text-ink/50`
// as the web ticks and as the chart this replaces. The canvas draws marks;
// Thalermark typography draws words.
//
// The label row is laid out with the same flex-1 columns as the bars, so the
// two cannot drift — the same guarantee the web version gets from sharing a
// band scale.
export function ColumnChart<Row extends Record<string, unknown>>({
  data,
  x,
  series,
  caption,
  format = 'money',
  height = 192,
  empty,
}: ColumnChartProps<Row>) {
  const rows = [...data];

  if (rows.length === 0) {
    return <Text className="mt-8 text-ink/70">{empty ?? 'Nothing to show for this period.'}</Text>;
  }

  // One shared ceiling across every series so two series stay comparable by
  // eye. null (nothing known) is distinct from 0 (a real flat chart).
  const ceiling = maxValue(rows.flatMap((row) => series.map((s) => row[s.key] as string | null)));

  // victory-native wants numbers. The conversion happens here, at the boundary,
  // and a null becomes a MISSING KEY rather than a zero — a bar that is not
  // drawn, instead of a bar of height nothing that reads as a recorded zero.
  const points = rows.map((row, index) => {
    const point: Record<string, number> = { index };
    for (const s of series) {
      const n = toNumber(row[s.key] as string | null);
      if (n !== null) point[s.key] = n;
    }
    return point;
  });

  return (
    // The canvas is decorative: every value in it is also in the label row and
    // the rows beneath the chart, so a screen reader gets the caption and then
    // the real content rather than a wall of unlabelled shapes.
    <View accessible accessibilityLabel={caption}>
      <View style={{ height }} importantForAccessibility="no-hide-descendants">
        <CartesianChart
          data={points}
          xKey="index"
          yKeys={series.map((s) => s.key) as never}
          domain={{ y: [0, ceiling && ceiling > 0 ? ceiling : 1] }}
        >
          {({ points: rendered, chartBounds }) =>
            series.map((s, seriesIndex) => (
              <Bar
                key={s.key}
                points={(rendered as Record<string, never>)[s.key]}
                chartBounds={chartBounds}
                color={toneColor(s.tone ?? toneForIndex(seriesIndex))}
                roundedCorners={{ topLeft: 2, topRight: 2 }}
                barWidth={undefined}
              />
            ))
          }
        </CartesianChart>
      </View>

      <View className="mt-2 flex-row gap-1">
        {rows.map((row) => (
          <Text
            // Keyed on the axis VALUE, not the formatted tick and not the index:
            // two months can render the same short label ('Jan' in a multi-year
            // window) but never share an underlying key.
            key={String(row[x.key])}
            className="flex-1 text-center font-mono text-[10px] uppercase tracking-wide text-ink/50"
            numberOfLines={1}
          >
            {x.label(row)}
          </Text>
        ))}
      </View>
    </View>
  );
}

// Re-exported so a screen can render the same figures as text beside the chart
// without importing the formatting rules separately.
export { formatValue };
