// apps/mobile/src/app/(app)/purchases/[id].tsx
import { loanPaymentSchema } from '@thalermark/validation';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { type AuditEvent, AuditHistory } from '../../../components/AuditHistory';
import { api } from '../../../lib/api';
import { apiErrorMessage } from '../../../lib/api-errors';
import { useMay } from '../../../lib/role';

// Mirror of apps/web's /purchases/[id]. The plain answer up top ("you still owe
// $X"), the tax answer, a record-a-payment form while a balance remains, and a
// remove action. Accounting stays hidden.
type Purchase = {
  description: string;
  amount: string;
  purchaseDate: string;
  funding: string;
  owing: string;
  vendorName: string | null;
  schedule: {
    perYear: string;
    firstYear: string;
    total: string;
    postedToDate: string;
    rows: { year: number; amount: string }[];
  } | null;
};

// The plain "spread it out" sentence. Under the standard (half-year) convention
// the purchase year really is smaller than the rest, so say both numbers rather
// than average them into one that matches neither. Mirrors apps/web.
function spreadSentence(s: NonNullable<Purchase['schedule']>): string {
  const first = s.rows[0]?.year;
  const last = s.rows[s.rows.length - 1]?.year;
  if (s.firstYear !== s.perYear) {
    return `Spread out — about ${money(s.firstYear)} in ${first}, then about ${money(s.perYear)} a year through ${last}.`;
  }
  return `Spread out — about ${money(s.perYear)} a year, ${first} through ${last}.`;
}

// A year's share is counted once that year has closed, so a purchase made this
// year legitimately shows nothing yet. Say so, or the zero reads as a bug.
function spreadProgress(s: NonNullable<Purchase['schedule']>): string {
  if (Number(s.postedToDate) === 0) {
    return `Nothing counted yet — ${s.rows[0]?.year}'s share is added once that year is over.`;
  }
  return `${money(s.postedToDate)} of ${money(s.total)} counted so far.`;
}
type DetailState =
  | { state: 'loading' }
  | { state: 'ready'; purchase: Purchase }
  | { state: 'error' };

const todayIso = () => new Date().toISOString().slice(0, 10);
const money = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

export default function PurchaseDetail() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [detail, setDetail] = useState<DetailState>({ state: 'loading' });
  const [auditEvents, setAuditEvents] = useState<AuditEvent[]>([]);
  const [acting, setActing] = useState(false);

  // Record-a-payment form.
  const [payAmount, setPayAmount] = useState('');
  const [payInterest, setPayInterest] = useState('');
  const [payDate, setPayDate] = useState(todayIso());
  const [payError, setPayError] = useState<string | null>(null);

  const load = useCallback(async () => {
    const res = await api.api.purchases[':id'].$get({ param: { id } });
    if (!res.ok) {
      setDetail({ state: 'error' });
      return;
    }
    const p = await res.json();
    setDetail({
      state: 'ready',
      purchase: {
        description: p.description,
        amount: p.amount,
        purchaseDate: p.purchaseDate,
        funding: p.funding,
        owing: p.owing,
        vendorName: p.vendorName ?? null,
        schedule: p.schedule,
      },
    });
    try {
      const auditRes = await api.api['audit-events'].$get({
        query: { entityType: 'capital_purchase', entityId: id },
      });
      if (auditRes.ok) setAuditEvents((await auditRes.json()).events);
    } catch {}
  }, [id]);

  useFocusEffect(
    useCallback(() => {
      let active = true;
      load().catch(() => {
        if (active) setDetail({ state: 'error' });
      });
      return () => {
        active = false;
      };
    }, [load]),
  );

  const canWrite = useMay('expenses:write');
  const purchase = detail.state === 'ready' ? detail.purchase : null;
  const financed = purchase?.funding === 'financed';
  const stillOwes = purchase ? Number(purchase.owing) > 0 : false;

  async function onRecordPayment() {
    setPayError(null);
    const parsed = loanPaymentSchema.safeParse({
      amount: payAmount.trim(),
      interest: payInterest.trim() === '' ? undefined : payInterest.trim(),
      paidOn: payDate.trim(),
    });
    if (!parsed.success) {
      setPayError(parsed.error.issues[0]?.message ?? 'Invalid payment.');
      return;
    }
    setActing(true);
    try {
      const res = await api.api.purchases[':id'].payments.$post({
        param: { id },
        json: parsed.data,
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        setPayError(
          body?.error === 'payment_exceeds_balance'
            ? "That's more than you still owe."
            : apiErrorMessage(body?.error, 'Could not record the payment.', body),
        );
        return;
      }
      setPayAmount('');
      setPayInterest('');
      await load();
    } finally {
      setActing(false);
    }
  }

  function onRemove() {
    Alert.alert('Remove this purchase?', 'This removes it from your books.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Remove',
        style: 'destructive',
        onPress: async () => {
          setActing(true);
          try {
            const res = await api.api.purchases[':id'].$delete({ param: { id } });
            if (res.ok) {
              router.replace('/purchases');
            } else {
              const body = (await res.json().catch(() => null)) as { error?: string } | null;
              Alert.alert(
                'Could not remove',
                body?.error === 'has_payments'
                  ? "You've already recorded payments on this, so it can't be removed."
                  : 'Please try again.',
              );
            }
          } finally {
            setActing(false);
          }
        },
      },
    ]);
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
        <Text
          onPress={() => router.push('/purchases')}
          className="font-mono text-xs uppercase tracking-widest text-ink-subtle"
        >
          ← Big purchases
        </Text>

        {detail.state === 'loading' ? (
          <View className="mt-12 items-center">
            <ActivityIndicator className="text-ink" />
          </View>
        ) : detail.state === 'error' || !purchase ? (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load this.</Text>
        ) : (
          <>
            <Text className="mt-3 font-serif text-3xl font-light text-ink">
              {purchase.description}
            </Text>

            {financed ? (
              <View className="mt-6 rounded-sm border border-ink/10 bg-cream-warm px-5 py-4">
                {stillOwes ? (
                  <>
                    <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                      You still owe
                    </Text>
                    <Text className="mt-1 font-mono text-2xl tabular-nums text-ink">
                      {money(purchase.owing)}
                    </Text>
                  </>
                ) : (
                  <Text className="font-serif text-ink">
                    Paid off — you don't owe anything more on this.
                  </Text>
                )}
              </View>
            ) : null}

            <View className="mt-8 gap-3">
              <Row label="Cost" value={money(purchase.amount)} />
              <Row label="Bought" value={purchase.purchaseDate} />
              {purchase.vendorName ? <Row label="From" value={purchase.vendorName} /> : null}
              <Row
                label="On taxes"
                value={
                  purchase.schedule
                    ? spreadSentence(purchase.schedule)
                    : 'Deducted in full the year you bought it.'
                }
              />
              {purchase.schedule ? (
                <Text className="text-right text-sm text-ink-subtle">
                  {spreadProgress(purchase.schedule)}
                </Text>
              ) : null}
            </View>

            {canWrite && financed && stillOwes ? (
              <View className="mt-8 rounded-sm border border-ink/10 bg-cream-warm p-5">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                  Record a payment
                </Text>
                {payError ? <Text className="mt-2 text-xs text-oxblood">{payError}</Text> : null}
                <View className="mt-3 gap-3">
                  <PayField label="Amount paid *" value={payAmount} onChangeText={setPayAmount} />
                  <PayField
                    label="Of that, interest (optional)"
                    value={payInterest}
                    onChangeText={setPayInterest}
                  />
                  <PayField label="Date *" value={payDate} onChangeText={setPayDate} />
                  <Pressable
                    onPress={onRecordPayment}
                    disabled={acting}
                    className="mt-1 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                  >
                    {acting ? (
                      <ActivityIndicator className="text-cream" />
                    ) : (
                      <Text className="text-center text-sm font-medium text-cream">
                        Record payment
                      </Text>
                    )}
                  </Pressable>
                </View>
              </View>
            ) : null}

            {canWrite ? (
              <Pressable
                onPress={onRemove}
                disabled={acting}
                className="mt-8 self-start rounded-sm border border-oxblood/30 px-4 py-3 active:bg-oxblood/5 disabled:opacity-50"
              >
                <Text className="font-mono text-xs uppercase tracking-widest text-oxblood">
                  Remove this purchase
                </Text>
              </Pressable>
            ) : null}

            <AuditHistory events={auditEvents} />
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View className="flex-row justify-between gap-4">
      <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">{label}</Text>
      <Text className="flex-1 text-right text-ink">{value}</Text>
    </View>
  );
}

function PayField({
  label,
  value,
  onChangeText,
}: {
  label: string;
  value: string;
  onChangeText: (t: string) => void;
}) {
  const isDate = label.startsWith('Date');
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">{label}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        keyboardType={isDate ? undefined : 'decimal-pad'}
        placeholder={isDate ? 'YYYY-MM-DD' : '0.00'}
        autoCapitalize="none"
        className="mt-1 rounded-sm border border-field bg-cream px-3 py-2 text-ink"
      />
    </View>
  );
}

// apps/web/src/routes/(app)/purchases/[id]/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import AuditHistory from '$lib/components/AuditHistory.svelte';
  import { may } from '$lib/perms';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
  const p = $derived(data.purchase);
  const canWrite = $derived(may(data.role, 'expenses:write'));
  const money = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  const financed = $derived(p.funding === 'financed');
  const stillOwes = $derived(Number(p.owing) > 0);

  // "Spread it out" reads as a plain sentence, and the first year is genuinely
  // smaller than the rest under the standard (half-year) convention — so say the
  // two numbers rather than average them into a single misleading one.
  const spread = $derived(p.schedule);
  const firstYearNum = $derived(spread?.rows[0]?.year ?? null);
  const lastYearNum = $derived(spread?.rows.at(-1)?.year ?? null);
  // A year's share posts once that year has closed, so a purchase made this year
  // shows nothing deducted yet. Saying so beats letting it read as a bug.
  const nothingDeductedYet = $derived(!!spread && Number(spread.postedToDate) === 0);
</script>

<a href="/purchases" class="eyebrow text-fg/60 hover:text-fg">← Big purchases</a>
<div class="mt-3 flex items-baseline justify-between gap-6">
  <h1 class="font-serif text-4xl font-light leading-none tracking-tight text-fg">
    {p.description}<span class="text-accent">.</span>
  </h1>
</div>

{#if form?.deleteError}
  <div class="mt-4 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.deleteError}
  </div>
{/if}

<!-- The plain answer up top: what you still owe (if financed). -->
{#if financed}
  <div class="mt-6 rounded-sm border border-fg/10 bg-surface-2 px-5 py-4">
    {#if stillOwes}
      <span class="label">You still owe</span>
      <p class="mt-1 font-mono text-2xl tabular-nums text-fg">{money(p.owing)}</p>
    {:else}
      <p class="font-serif text-fg">Paid off — you don't owe anything more on this.</p>
    {/if}
  </div>
{/if}

<dl class="mt-8 grid grid-cols-1 gap-x-12 gap-y-6 sm:grid-cols-2">
  <div>
    <dt class="label">Cost</dt>
    <dd class="mt-1 font-mono tabular-nums text-fg">{money(p.amount)}</dd>
  </div>
  <div>
    <dt class="label">Bought</dt>
    <dd class="mt-1 font-mono tabular-nums text-fg">{p.purchaseDate}</dd>
  </div>
  {#if p.vendorName}
    <div>
      <dt class="label">From</dt>
      <dd class="mt-1 text-fg">{p.vendorName}</dd>
    </div>
  {/if}
  <div>
    <dt class="label">On taxes</dt>
    <dd class="mt-1 text-fg/80">
      {#if spread}
        {#if spread.firstYear !== spread.perYear}
          Spread out — about {money(spread.firstYear)} in {firstYearNum}, then about
          {money(spread.perYear)} a year through {lastYearNum}.
        {:else}
          Spread out — about {money(spread.perYear)} a year, {firstYearNum} through {lastYearNum}.
        {/if}
        <span class="mt-1 block text-sm text-fg/60">
          {#if nothingDeductedYet}
            Nothing counted yet — {firstYearNum}'s share is added once that year is over.
          {:else}
            {money(spread.postedToDate)} of {money(spread.total)} counted so far.
          {/if}
        </span>
      {:else}
        Deducted in full the year you bought it.
      {/if}
    </dd>
  </div>
</dl>

<!-- Record a payment toward a financed purchase while a balance remains. -->
{#if canWrite && financed && stillOwes}
  <div class="mt-10 rounded-sm border border-fg/10 bg-surface-2 p-5">
    <span class="label">Record a payment</span>
    {#if form?.paymentError}
      <p class="mt-2 text-xs text-danger">{form.paymentError}</p>
    {/if}
    <form method="post" action="?/recordPayment" class="mt-3 space-y-4" use:enhance>
      <div class="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <div>
          <label for="amount" class="label">Amount paid<span class="text-accent">*</span></label>
          <input
            id="amount"
            name="amount"
            type="text"
            inputmode="decimal"
            required
            placeholder="0.00"
            class="mt-1 w-full rounded-sm border border-fg/15 bg-surface px-3 py-2 font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
          />
        </div>
        <div>
          <label for="interest" class="label">
            Of that, interest <span class="font-normal normal-case tracking-normal text-fg/40">(optional)</span>
          </label>
          <input
            id="interest"
            name="interest"
            type="text"
            inputmode="decimal"
            placeholder="0.00"
            class="mt-1 w-full rounded-sm border border-fg/15 bg-surface px-3 py-2 font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
          />
        </div>
        <div>
          <label for="paidOn" class="label">Date<span class="text-accent">*</span></label>
          <input id="paidOn" name="paidOn" type="date" required value={data.today} class="field mt-1" />
        </div>
      </div>
      <button type="submit" class="btn">Record payment</button>
    </form>
  </div>
{/if}

{#if canWrite}
  <form method="post" action="?/delete" class="mt-8 border-t border-fg/10 pt-6" use:enhance>
    <p class="text-sm text-fg/60">Logged this by mistake? Remove it from your books.</p>
    <button
      type="submit"
      class="mt-3 rounded-sm border border-danger/30 px-3 py-1 font-mono text-xs uppercase tracking-widest text-danger/80 hover:border-danger hover:text-danger"
    >
      Remove this purchase
    </button>
  </form>
{/if}

<AuditHistory events={data.auditEvents} />
