// apps/web/src/routes/(app)/mileage/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { mileageValue, standardMileageRateFor } from '@thalermark/validation';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  const canWrite = $derived(may(data.role, 'expenses:write'));
  const summary = $derived(data.summary);

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
  // Miles are stored at 4dp so valuation multiplies exactly; nobody wants to
  // read "24.5000".
  const miles = (s: string) => Number(s).toLocaleString('en-US', { maximumFractionDigits: 1 });

  type Row = (typeof data.trips)[number];
  let rows = $state<Row[]>(untrack(() => data.trips));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.trips;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<Row>('/mileage/more', cursor);
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }

  const today = new Date().toISOString().slice(0, 10);
  const vehicles = $derived(data.vehicles);
  const vehicleName = $derived(
    (id: string | null) => vehicles.find((v) => v.id === id)?.label ?? null,
  );
  // Prefill from the last trip, falling back to the only vehicle there is. One
  // truck is the common case, so picking it every time is pure friction.
  const defaultVehicleId = $derived(
    rows[0]?.vehicleId ?? (vehicles.length === 1 ? vehicles[0]?.id : '') ?? '',
  );
  // Part IV can't be finished without these, so the page says so rather than
  // waiting for April. A work-only vehicle answers once and is done for good.
  const needsAnswers = $derived(
    vehicles.filter((v) => v.personalUse === null || v.placedInServiceOn === null),
  );
  const todayRate = standardMileageRateFor(today);
</script>

<div class="flex flex-wrap items-baseline justify-between gap-4">
  <h1 class="font-serif text-3xl text-fg">Mileage</h1>
  {#if summary}
    <!--
      The heading carries DOLLARS, not miles. Miles are the input; what the user
      wants to know is what the driving is worth, and it is routinely the biggest
      deduction on their return.
    -->
    <p class="text-right">
      <span class="font-mono text-2xl tabular-nums text-accent">{fmt(summary.amount)}</span>
      <span class="label ml-2">{miles(summary.miles)} miles in {data.year}</span>
    </p>
  {/if}
</div>

<p class="mt-2 max-w-2xl text-sm text-fg/70">
  Business driving, at the IRS standard rate. Logging a trip records a deduction — it never moves
  money, so nothing here touches your books.
</p>

{#if summary && Number(summary.unratedMiles) > 0}
  <!--
    Miles we cannot price. Saying so is the point: quietly valuing them at last
    year's rate would produce a number that looks right and is wrong on a return.
  -->
  <div class="callout mt-6">
    <p>
      {miles(summary.unratedMiles)} miles are on dates the IRS hasn't published a rate for yet, so they're
      not in the total above. They'll be counted as soon as the rate is out.
    </p>
  </div>
{/if}

{#if canWrite}
  <form method="POST" action="?/log" class="mt-8 rounded-sm border border-fg/15 bg-surface-2 p-5">
    <div class="grid gap-4 sm:grid-cols-[9rem_7rem_1fr_9rem_auto] sm:items-end">
      <label class="block">
        <span class="label">Date</span>
        <input
          type="date"
          name="tripDate"
          required
          value={form?.values?.tripDate ?? today}
          class="field mt-1 w-full"
        />
      </label>
      <label class="block">
        <span class="label">Miles</span>
        <input
          type="text"
          inputmode="decimal"
          name="miles"
          required
          placeholder="24.5"
          value={form?.values?.miles ?? ''}
          class="field mt-1 w-full"
        />
      </label>
      <label class="block">
        <span class="label">What for</span>
        <input
          type="text"
          name="purpose"
          required
          placeholder="Drove to the Miller place"
          value={form?.values?.purpose ?? ''}
          class="field mt-1 w-full"
        />
      </label>
      <label class="block">
        <span class="label">Vehicle</span>
        <select name="vehicleId" class="field mt-1 w-full">
          <!-- Blank is allowed: a trip logged before any vehicle is set up is
               still a real deduction. Those miles show up as unassigned on the
               worksheet rather than being dropped. -->
          <option value="">—</option>
          {#each vehicles as v (v.id)}
            <option value={v.id} selected={(form?.values?.vehicleId ?? defaultVehicleId) === v.id}>
              {v.label}
            </option>
          {/each}
        </select>
      </label>
      <button type="submit" class="btn">Log</button>
    </div>

    {#if form?.fieldErrors?.purpose}
      <p class="mt-3 text-sm text-danger">
        Say what the trip was for — that's what makes the deduction stick if it's ever questioned.
      </p>
    {:else if form?.fieldErrors?.miles}
      <p class="mt-3 text-sm text-danger">Enter the miles driven, as a number.</p>
    {:else if form?.formError}
      <p class="mt-3 text-sm text-danger">{form.formError}</p>
    {:else if form?.logged}
      <p class="mt-3 text-sm text-fg/60">Logged.</p>
    {/if}

    {#if todayRate}
      <p class="mt-3 text-xs text-fg/50">
        Today's rate is {Number(todayRate).toFixed(3).replace(/0$/, '')} per mile.
      </p>
    {/if}
  </form>
{/if}

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">No trips logged yet.</p>
{:else}
  <ul class="mt-6 divide-y divide-fg/10 rounded-sm border border-fg/10 bg-surface-2">
    {#each rows as trip (trip.id)}
      {@const value = mileageValue(trip.miles, trip.tripDate)}
      <li class="flex items-center justify-between gap-4 px-5 py-4">
        <span class="min-w-0 flex-1">
          <span class="font-serif text-lg text-fg">{trip.purpose}</span>
          <span class="label mt-1 block">
            {trip.tripDate} · {miles(trip.miles)} miles{vehicleName(trip.vehicleId)
              ? ` · ${vehicleName(trip.vehicleId)}`
              : ''}
          </span>
        </span>
        <span class="shrink-0 text-right">
          {#if value}
            <span class="font-mono tabular-nums text-fg">{fmt(value)}</span>
          {:else}
            <span class="label">no rate yet</span>
          {/if}
        </span>
        {#if canWrite}
          <span class="flex shrink-0 items-center gap-3">
            <!--
              "Again" is the frequent-route shortcut: the same drive, today.
              Posting through the ordinary log action keeps one write path.
            -->
            <form method="POST" action="?/log">
              <input type="hidden" name="tripDate" value={today} />
              <input type="hidden" name="miles" value={trip.miles} />
              <input type="hidden" name="purpose" value={trip.purpose} />
              <input type="hidden" name="vehicleId" value={trip.vehicleId ?? ''} />
              <button type="submit" class="link text-sm">Again</button>
            </form>
            <form method="POST" action="?/remove">
              <input type="hidden" name="id" value={trip.id} />
              <button type="submit" class="link text-sm text-fg/50">Delete</button>
            </form>
          </span>
        {/if}
      </li>
    {/each}
  </ul>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}

<!--
  Vehicles, and the Schedule C Part IV answers that belong to them rather than to
  a year. Here rather than in Settings on purpose: the trip form needs the picker
  anyway, and Settings is gated on settings:manage which `accountant` does not
  hold — and the accountant is often exactly who finishes Part IV.
-->
{#if canWrite}
  <h2 class="mt-12 font-serif text-2xl font-light text-fg">Your vehicles</h2>
  <p class="mt-1 max-w-2xl text-sm text-fg/70">
    The IRS asks a few questions about each vehicle you drive for work. Answering them now means
    there's nothing left to work out at tax time.
  </p>

  {#if needsAnswers.length > 0}
    <p class="callout mt-4">
      {needsAnswers.length === 1
        ? `${needsAnswers[0]?.label} is missing some answers.`
        : `${needsAnswers.length} vehicles are missing some answers.`} Your return needs them, so it's
      worth a minute now.
    </p>
  {/if}

  <form method="POST" action="?/addVehicle" class="mt-4 flex flex-wrap items-end gap-3">
    <label class="block">
      <span class="label">Add a vehicle</span>
      <input type="text" name="label" placeholder="F-150" class="field mt-1 w-56" />
    </label>
    <button type="submit" class="btn">Add</button>
    {#if form?.vehicleError}
      <span class="text-sm text-danger">{form.vehicleError}</span>
    {:else if form?.vehicleAdded}
      <span class="text-sm text-fg/60">Added.</span>
    {:else if form?.vehicleSaved}
      <span class="text-sm text-fg/60">Saved.</span>
    {/if}
  </form>

  {#each vehicles as v (v.id)}
    <form
      method="POST"
      action="?/saveVehicle"
      class="mt-4 rounded-sm border border-fg/15 bg-surface-2 p-5"
    >
      <input type="hidden" name="id" value={v.id} />
      <div class="flex flex-wrap items-baseline justify-between gap-3">
        <span class="font-serif text-lg text-fg">{v.label}</span>
        <button type="submit" formaction="?/retireVehicle" class="link text-xs text-fg/50">
          No longer used
        </button>
      </div>

      <div class="mt-4 grid gap-4 sm:grid-cols-3">
        <label class="block">
          <span class="label">First used for work</span>
          <input
            type="date"
            name="placedInServiceOn"
            value={v.placedInServiceOn ?? ''}
            class="field mt-1 w-full"
          />
        </label>
        <label class="block">
          <span class="label">Also driven personally?</span>
          <select name="personalUse" class="field mt-1 w-full">
            <option value="" selected={v.personalUse === null}>—</option>
            <!--
              'none' is what makes the year-end question disappear for this
              vehicle: its total miles ARE the business miles already logged, so
              there is nothing left to estimate.
            -->
            <option value="none" selected={v.personalUse === 'none'}>No, work only</option>
            <option value="some" selected={v.personalUse === 'some'}>Yes, sometimes</option>
          </select>
        </label>
        <label class="block">
          <span class="label">Another car for personal use?</span>
          <select name="anotherVehicleAvailable" class="field mt-1 w-full">
            <option value="" selected={v.anotherVehicleAvailable === null}>—</option>
            <option value="yes" selected={v.anotherVehicleAvailable === true}>Yes</option>
            <option value="no" selected={v.anotherVehicleAvailable === false}>No</option>
          </select>
        </label>
      </div>
      <p class="mt-3 max-w-prose text-xs text-fg/50">
        If this is a work-only truck and you drive something else on weekends, that's "No, work
        only" and "Yes" — which is the strongest answer you can give.
      </p>
      <button type="submit" class="btn mt-4">Save</button>
    </form>
  {/each}
{/if}

// apps/mobile/src/app/(app)/mileage/index.tsx
import { mileageValue, standardMileageRateFor } from '@thalermark/validation';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../lib/use-paginated-list';

// Mirror of apps/web's /mileage. THE primary surface for this feature — mileage
// is logged in a truck, not at a desk, so the form is the first thing on screen
// and pre-fills everything it can.
//
// Nothing here posts to the ledger. See the header on
// packages/db/src/schema/mileage_trips.ts.
type TripRow = {
  id: string;
  tripDate: string;
  miles: string;
  purpose: string;
  vehicleId: string | null;
};

// Schedule C Part IV is a per-vehicle disclosure. The phone picks a vehicle;
// the Part IV answers themselves are answered on the web, where year-end work
// happens.
type VehicleRow = { id: string; label: string };

type MileageSummary = {
  year: number;
  tripCount: number;
  miles: string;
  amount: string;
  unratedMiles: string;
};

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
// Stored at 4dp so valuation multiplies exactly; nobody wants to read "24.5000".
const showMiles = (s: string) => Number(s).toLocaleString('en-US', { maximumFractionDigits: 1 });

export default function MileageList() {
  const canWrite = useMay('expenses:write');
  const today = new Date().toISOString().slice(0, 10);

  // Same active-company resolution every company-scoped mobile screen does —
  // RLS pins the account, never the company, so the id has to be sent.
  const [companyId, setCompanyId] = useState<string | null>(null);

  const [tripDate, setTripDate] = useState(today);
  const [miles, setMiles] = useState('');
  const [purpose, setPurpose] = useState('');
  const [vehicles, setVehicles] = useState<VehicleRow[]>([]);
  const [vehicleId, setVehicleId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [summary, setSummary] = useState<MileageSummary | null>(null);

  const fetchPage = useCallback(async (cursor: string | null) => {
    const query: Record<string, string> = pageQuery(cursor);
    const res = await api.api['mileage-trips'].$get({ query });
    if (!res.ok) return null;
    const { trips, nextCursor } = await res.json();
    return {
      rows: trips.map(
        (t): TripRow => ({
          id: t.id,
          tripDate: t.tripDate,
          miles: t.miles,
          purpose: t.purpose,
          vehicleId: t.vehicleId,
        }),
      ),
      nextCursor,
    };
  }, []);

  const { list, loadingMore, loadMore, reload } = usePaginatedList(fetchPage);

  const refreshSummary = useCallback((id: string | null) => {
    if (!id) return;
    api.api.companies[':id'].mileage
      .$get({ param: { id }, query: { year: String(new Date().getFullYear()) } })
      .then(async (res) => {
        if (res.ok) setSummary((await res.json()) as MileageSummary);
      })
      .catch(() => {});
  }, []);

  useFocusEffect(
    useCallback(() => {
      let active = true;
      (async () => {
        const res = await api.api.companies.$get();
        if (!active || !res.ok) return;
        const { companies } = await res.json();
        const company = await pickActiveCompany(companies);
        if (!active) return;
        setCompanyId(company?.id ?? null);
        refreshSummary(company?.id ?? null);
        if (!company) return;
        const vRes = await api.api.vehicles.$get({ query: { companyId: company.id } });
        if (!active || !vRes.ok) return;
        const rows = (await vRes.json()).vehicles as VehicleRow[];
        setVehicles(rows);
        // One truck is the common case — preselect it rather than making the
        // driver tap it every time.
        setVehicleId((prev) => prev ?? (rows.length === 1 ? (rows[0]?.id ?? null) : null));
      })().catch(() => {});
      return () => {
        active = false;
      };
    }, [refreshSummary]),
  );

  async function log(values: {
    tripDate: string;
    miles: string;
    purpose: string;
    vehicleId: string | null;
  }) {
    if (!companyId || saving) return;
    setSaving(true);
    setError(null);
    try {
      const res = await api.api['mileage-trips'].$post({
        json: {
          companyId,
          tripDate: values.tripDate,
          miles: values.miles,
          purpose: values.purpose,
          ...(values.vehicleId ? { vehicleId: values.vehicleId } : {}),
        },
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        setError(errorMessage(body?.error));
        return;
      }
      setMiles('');
      setPurpose('');
      setTripDate(today);
      reload();
      refreshSummary(companyId);
    } catch {
      setError("Couldn't save that trip.");
    } finally {
      setSaving(false);
    }
  }

  const canSubmit = miles.trim() !== '' && purpose.trim() !== '' && !saving;
  const todayRate = standardMileageRateFor(today);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <FlatList
        data={list.state === 'ready' ? list.rows : []}
        keyExtractor={(t) => t.id}
        onEndReached={loadMore}
        onEndReachedThreshold={0.4}
        ListHeaderComponent={
          <View className="px-6 pt-6">
            <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
              Mileage
            </Text>
            {/*
              DOLLARS in the heading, not miles. Miles are the input; what the
              user wants to know is what the driving is worth.
            */}
            <Text className="mt-2 font-serif text-3xl font-light text-ink">
              {summary ? fmt(summary.amount) : '—'}
            </Text>
            {summary ? (
              <Text className="mt-1 text-sm text-ink-subtle">
                {showMiles(summary.miles)} miles in {summary.year}
              </Text>
            ) : null}

            {summary && Number(summary.unratedMiles) > 0 ? (
              <Text className="mt-3 text-sm text-ink-muted">
                {showMiles(summary.unratedMiles)} miles are on dates the IRS hasn't set a rate for
                yet, so they're not counted above.
              </Text>
            ) : null}

            {canWrite ? (
              <View className="mt-6 rounded-sm border border-ink/15 bg-cream-warm p-4">
                <TextInput
                  value={tripDate}
                  onChangeText={setTripDate}
                  placeholder="YYYY-MM-DD"
                  autoCapitalize="none"
                  className="rounded-sm border border-field px-3 py-2 text-ink"
                />
                <TextInput
                  value={miles}
                  onChangeText={setMiles}
                  placeholder="Miles, e.g. 24.5"
                  keyboardType="decimal-pad"
                  className="mt-3 rounded-sm border border-field px-3 py-2 text-ink"
                />
                <TextInput
                  value={purpose}
                  onChangeText={setPurpose}
                  placeholder="What for, e.g. Drove to the Miller place"
                  className="mt-3 rounded-sm border border-field px-3 py-2 text-ink"
                />
                {/* Chips rather than a native picker: a workspace has one or two
                    vehicles, and a modal for two options is friction in a truck.
                    Vehicles are added on the web, alongside the Part IV answers
                    they exist to carry. */}
                {vehicles.length > 0 ? (
                  <View className="mt-3 flex-row flex-wrap gap-2">
                    {vehicles.map((v) => (
                      <Pressable
                        key={v.id}
                        onPress={() => setVehicleId(vehicleId === v.id ? null : v.id)}
                        className={`rounded-sm border px-3 py-2 ${
                          vehicleId === v.id ? 'border-gold-deep bg-gold-deep/10' : 'border-ink/15'
                        }`}
                      >
                        <Text className="text-sm text-ink">{v.label}</Text>
                      </Pressable>
                    ))}
                  </View>
                ) : null}
                <Pressable
                  disabled={!canSubmit}
                  onPress={() => log({ tripDate, miles, purpose, vehicleId })}
                  className={`mt-4 rounded-sm px-4 py-3 ${canSubmit ? 'bg-ink active:bg-gold-deep' : 'bg-ink/30'}`}
                >
                  <Text className="text-center text-sm font-medium text-cream">
                    {saving ? 'Saving…' : 'Log trip'}
                  </Text>
                </Pressable>
                {error ? <Text className="mt-3 text-sm text-red-700">{error}</Text> : null}
                {todayRate ? (
                  <Text className="mt-3 text-xs text-ink-subtle">
                    Today's rate is {Number(todayRate).toFixed(3).replace(/0$/, '')} per mile.
                  </Text>
                ) : null}
              </View>
            ) : null}
          </View>
        }
        renderItem={({ item }) => {
          const value = mileageValue(item.miles, item.tripDate);
          return (
            <View className="mx-6 mt-3 flex-row items-center justify-between rounded-sm border border-ink/10 bg-cream-warm px-4 py-3">
              <View className="mr-3 flex-1">
                <Text className="font-serif text-lg text-ink">{item.purpose}</Text>
                <Text className="mt-1 text-xs text-ink-subtle">
                  {item.tripDate} · {showMiles(item.miles)} miles
                  {vehicles.find((v) => v.id === item.vehicleId)?.label
                    ? ` · ${vehicles.find((v) => v.id === item.vehicleId)?.label}`
                    : ''}
                </Text>
              </View>
              <View className="items-end">
                <Text className="font-mono text-ink">{value ? fmt(value) : 'no rate yet'}</Text>
                {canWrite ? (
                  // The frequent-route shortcut: the same drive, today.
                  <Pressable
                    onPress={() =>
                      log({
                        tripDate: today,
                        miles: item.miles,
                        purpose: item.purpose,
                        vehicleId: item.vehicleId,
                      })
                    }
                  >
                    <Text className="mt-1 text-xs text-gold-deep">Again</Text>
                  </Pressable>
                ) : null}
              </View>
            </View>
          );
        }}
        ListEmptyComponent={
          list.state === 'loading' ? (
            <ActivityIndicator className="mt-8" />
          ) : list.state === 'error' ? (
            <Text className="mt-8 px-6 text-ink-subtle">Couldn't load your trips.</Text>
          ) : (
            <Text className="mt-8 px-6 text-ink-subtle">No trips logged yet.</Text>
          )
        }
        ListFooterComponent={
          loadingMore ? <ActivityIndicator className="my-6" /> : <View className="h-8" />
        }
      />
    </SafeAreaView>
  );
}

function errorMessage(code: string | undefined): string {
  if (code === 'period_closed') {
    return "That year's books are closed, so it can't take a new trip.";
  }
  if (code === 'company_retired') {
    return 'This business has been retired, so it no longer records new activity.';
  }
  return "Couldn't save that trip.";
}
