// apps/web/src/routes/(app)/estimates/[id]/+page.svelte
<script lang="ts">
  import AuditHistory from '$lib/components/AuditHistory.svelte';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
  const est = $derived(data.estimate);
  const customer = $derived(data.customer);

  // Mirrors the API state machine. mark-sent only fires from draft;
  // mark-accepted / mark-declined fire from draft or sent (the operator
  // can capture a verbal close without going through send). Accepted +
  // declined are terminal, so their buttons disappear.
  // Send covers both first-send (draft → sent + email) and resend (sent →
  // email only) — API handles the dispatch. /mark-sent stays for the
  // delivered-out-of-band path so a paper handoff still flips status
  // without firing an email.
  const canSend = $derived(est.status === 'draft' || est.status === 'sent');
  const canMarkSent = $derived(est.status === 'draft');
  const canMarkAccepted = $derived(est.status === 'draft' || est.status === 'sent');
  const canMarkDeclined = $derived(est.status === 'draft' || est.status === 'sent');
  const canEdit = $derived(est.status === 'draft');
  // Convert is the "estimate → invoice" link action (slice 8.7d). Gated to
  // accepted estimates with no existing converted invoice; once converted,
  // the button is replaced with a link to the new invoice further down.
  const canConvert = $derived(est.status === 'accepted' && est.convertedInvoiceId == null);
  const hasActions = $derived(
    canSend || canMarkSent || canMarkAccepted || canMarkDeclined || canConvert,
  );

  let showOverride = $state(false);
  const sendLabel = $derived(est.status === 'sent' ? 'Resend estimate' : 'Send estimate');

  // Advisory expiry: status doesn't flip to 'expired' in MVP (no background
  // sweep yet). Read sites compute the warning off expires_on < today, but
  // only on sent estimates — drafts haven't gone out, accepted/declined are
  // closed records, and an expires_on in the past on those carries no
  // operational signal.
  const todayIso = new Date().toISOString().slice(0, 10);
  const isExpired = $derived(
    est.status === 'sent' && est.expiresOn != null && est.expiresOn < todayIso,
  );

  // Share URL surfaces once mark-sent mints the token. Same pattern as the
  // invoice detail page — absolute URL built off origin so it works behind
  // any proxy. The unauthed /e/[token] public page lands in slice 8.7e;
  // until then the URL still works for any internal preview tooling.
  const publicUrl = $derived(est.publicToken ? `${data.origin}/e/${est.publicToken}` : null);
</script>

<a href="/estimates" class="eyebrow text-ink/60 hover:text-ink">← Estimates</a>
<div class="mt-3 flex items-baseline justify-between gap-6">
  <h1 class="font-serif text-4xl font-light leading-none tracking-tight text-ink">
    Estimate {est.number}<span class="text-gold-deep">.</span>
  </h1>
  <div class="flex items-center gap-3">
    {#if canEdit}
      <a
        href="/estimates/{est.id}/edit"
        class="rounded-sm border border-ink/20 px-3 py-1 font-mono text-xs uppercase tracking-widest text-ink/70 hover:border-gold-deep hover:text-gold-deep"
      >
        Edit
      </a>
    {/if}
    <!-- Duplicate-as-template: any status. Posts to ?/duplicate → new draft's edit page. -->
    <form method="post" action="?/duplicate">
      <button
        type="submit"
        class="rounded-sm border border-ink/20 px-3 py-1 font-mono text-xs uppercase tracking-widest text-ink/70 hover:border-gold-deep hover:text-gold-deep"
      >
        Duplicate
      </button>
    </form>
    <span class="font-mono text-xs uppercase tracking-widest text-ink/60">{est.status}</span>
  </div>
</div>

{#if form?.transitionError}
  <div class="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3 text-sm text-oxblood">
    {form.transitionError}
  </div>
{/if}

{#if data.sentTo}
  <div class="mt-6 rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3 text-sm text-ink">
    Sent to <span class="font-medium">{data.sentTo}</span>.
  </div>
{/if}

{#if isExpired}
  <div class="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3 text-sm text-oxblood">
    This estimate's validity expired on <span class="font-medium">{est.expiresOn}</span>.
  </div>
{/if}

{#if hasActions}
  <div class="mt-6 flex flex-wrap items-center gap-3">
    {#if canSend}
      <form method="post" action="?/send" class="flex flex-wrap items-center gap-2">
        {#if showOverride}
          <input
            type="email"
            name="to"
            placeholder={customer?.email ?? 'recipient@example.com'}
            class="rounded-sm border border-ink/20 bg-cream-warm px-3 py-2 text-sm text-ink placeholder:text-ink/40 focus:border-gold-deep focus:outline-none"
          />
        {/if}
        <button
          type="submit"
          class="rounded-sm bg-ink px-4 py-2 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
        >
          {sendLabel}
        </button>
        {#if !showOverride}
          <button
            type="button"
            onclick={() => {
              showOverride = true;
            }}
            class="text-xs uppercase tracking-widest text-ink/50 hover:text-gold-deep"
          >
            Send to another address
          </button>
        {/if}
      </form>
    {/if}
    {#if canMarkAccepted}
      <form method="post" action="?/markAccepted">
        <button
          type="submit"
          class="rounded-sm border border-ink/20 bg-cream-warm px-4 py-2 text-sm font-medium text-ink transition-colors hover:border-gold-deep hover:text-gold-deep"
        >
          Mark accepted
        </button>
      </form>
    {/if}
    {#if canMarkDeclined}
      <form method="post" action="?/markDeclined">
        <button
          type="submit"
          class="rounded-sm border border-oxblood/30 px-4 py-2 text-sm font-medium text-oxblood transition-colors hover:bg-oxblood/5"
        >
          Mark declined
        </button>
      </form>
    {/if}
    {#if canConvert}
      <form method="post" action="?/convert">
        <button
          type="submit"
          class="rounded-sm bg-ink px-4 py-2 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
        >
          Convert to invoice
        </button>
      </form>
    {/if}
  </div>
  {#if canMarkSent}
    <form method="post" action="?/markSent" class="mt-2">
      <button
        type="submit"
        class="text-xs uppercase tracking-widest text-ink/50 hover:text-gold-deep"
      >
        Mark sent without email
      </button>
    </form>
  {/if}
{/if}

{#if est.convertedInvoiceId}
  <div class="mt-6 rounded-sm border border-gold-deep/40 bg-gold-deep/5 px-4 py-3 text-sm text-ink">
    Converted to
    <a href="/invoices/{est.convertedInvoiceId}" class="font-medium text-gold-deep hover:underline">
      invoice →
    </a>
  </div>
{/if}

{#if publicUrl}
  <div class="mt-6 rounded-sm border border-ink/10 bg-cream-warm p-4">
    <p class="font-mono text-xs uppercase tracking-widest text-ink/50">Share link</p>
    <div class="mt-2 flex flex-wrap items-center gap-3 text-sm">
      <a href={publicUrl} target="_blank" rel="noopener" class="break-all text-gold-deep hover:underline">
        {publicUrl}
      </a>
    </div>
    <p class="mt-2 text-xs text-ink/50">
      Anyone with this link can view the estimate.
    </p>
  </div>
{/if}

<dl class="mt-8 grid grid-cols-1 gap-x-12 gap-y-6 sm:grid-cols-3">
  <div>
    <dt class="font-mono text-xs uppercase tracking-widest text-ink/50">Customer</dt>
    <dd class="mt-1 text-ink">
      {#if customer}
        <a href="/customers/{customer.id}" class="hover:text-gold-deep">{customer.name}</a>
      {:else}
        —
      {/if}
    </dd>
  </div>
  <div>
    <dt class="font-mono text-xs uppercase tracking-widest text-ink/50">Issued</dt>
    <dd class="mt-1 text-ink">{est.issueDate}</dd>
  </div>
  <div>
    <dt class="font-mono text-xs uppercase tracking-widest text-ink/50">Expires</dt>
    <dd class="mt-1 text-ink">{est.expiresOn ?? '—'}</dd>
  </div>
</dl>

<div class="mt-10 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
  <table class="w-full text-left text-sm">
    <thead class="bg-cream">
      <tr class="font-mono text-xs uppercase tracking-widest text-ink/50">
        <th class="px-5 py-3">Description</th>
        <th class="px-5 py-3 text-right">Qty</th>
        <th class="px-5 py-3 text-right">Unit price</th>
        <th class="px-5 py-3 text-right">Amount</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-ink/10">
      {#each est.lineItems as li (li.id)}
        <tr>
          <td class="px-5 py-4 text-ink">{li.description}</td>
          <td class="px-5 py-4 text-right font-mono tabular-nums text-ink/80">{li.quantity}</td>
          <td class="px-5 py-4 text-right font-mono tabular-nums text-ink/80">{li.unitPrice}</td>
          <td class="px-5 py-4 text-right font-mono tabular-nums text-ink">{li.amount}</td>
        </tr>
      {/each}
    </tbody>
    <tfoot class="bg-cream">
      <tr>
        <td colspan="3" class="px-5 py-3 text-right font-mono text-xs uppercase tracking-widest text-ink/50">
          Subtotal
        </td>
        <td class="px-5 py-3 text-right font-mono tabular-nums text-ink">{est.subtotal}</td>
      </tr>
      <tr>
        <td colspan="3" class="px-5 py-3 text-right font-mono text-xs uppercase tracking-widest text-ink/50">
          Tax
        </td>
        <td class="px-5 py-3 text-right font-mono tabular-nums text-ink">{est.tax}</td>
      </tr>
      <tr>
        <td colspan="3" class="px-5 py-3 text-right font-mono text-xs uppercase tracking-widest text-ink/50">
          Total ({est.currency})
        </td>
        <td class="px-5 py-3 text-right font-mono tabular-nums text-lg text-ink">{est.total}</td>
      </tr>
    </tfoot>
  </table>
</div>

{#if est.notes}
  <div class="mt-8">
    <h2 class="font-mono text-xs uppercase tracking-widest text-ink/50">Notes</h2>
    <p class="mt-2 whitespace-pre-wrap text-ink/80">{est.notes}</p>
  </div>
{/if}

<AuditHistory events={data.auditEvents} />

// apps/mobile/src/app/(app)/estimates/[id].tsx
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../lib/api';

// Estimate detail + actions (mirror of apps/web's /estimates/[id]):
// mark-sent / mark-accepted / mark-declined / send / convert-to-invoice. No
// payment semantics (estimates aren't a debt). Edit / duplicate deferred.
type LineItem = {
  position: number;
  description: string;
  quantity: string;
  unitPrice: string;
  amount: string;
};
type Estimate = {
  status: string;
  number: string;
  customerId: string;
  issueDate: string;
  expiresOn: string | null;
  currency: string;
  subtotal: string;
  tax: string | null;
  total: string;
  notes: string | null;
  publicToken: string | null;
  convertedInvoiceId: string | null;
  lineItems: LineItem[];
};
type DetailState =
  | { state: 'loading' }
  | {
      state: 'ready';
      estimate: Estimate;
      customerName: string | null;
      customerEmail: string | null;
    }
  | { state: 'error' };

const TRANSITION_ERRORS: Record<string, string> = {
  invalid_transition: 'This estimate can no longer be changed.',
  invalid_recipient: 'Add a customer email or enter one to send.',
  email_not_configured: "Email isn't configured on this server.",
  customer_not_found: 'The customer for this estimate no longer exists.',
};

const apiOrigin = (process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000').replace(/\/$/, '');
const todayIso = () => new Date().toISOString().slice(0, 10);

export default function EstimateDetail() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [detail, setDetail] = useState<DetailState>({ state: 'loading' });
  const [acting, setActing] = useState(false);
  const [transitionError, setTransitionError] = useState<string | null>(null);
  const [sentTo, setSentTo] = useState<string | null>(null);
  const [showOverride, setShowOverride] = useState(false);
  const [overrideEmail, setOverrideEmail] = useState('');

  const load = useCallback(async () => {
    const res = await api.api.estimates[':id'].$get({ param: { id } });
    if (!res.ok) {
      setDetail({ state: 'error' });
      return;
    }
    const est = await res.json();
    let customerName: string | null = null;
    let customerEmail: string | null = null;
    const custRes = await api.api.customers[':id'].$get({ param: { id: est.customerId } });
    if (custRes.ok) {
      const c = await custRes.json();
      customerName = c.name;
      customerEmail = c.email ?? null;
    }
    setDetail({
      state: 'ready',
      customerName,
      customerEmail,
      estimate: {
        status: est.status,
        number: est.number,
        customerId: est.customerId,
        issueDate: est.issueDate,
        expiresOn: est.expiresOn ?? null,
        currency: est.currency,
        subtotal: est.subtotal,
        tax: est.tax ?? null,
        total: est.total,
        notes: est.notes ?? null,
        publicToken: est.publicToken ?? null,
        convertedInvoiceId: est.convertedInvoiceId ?? null,
        lineItems: est.lineItems,
      },
    });
  }, [id]);

  useFocusEffect(
    useCallback(() => {
      let active = true;
      load().catch(() => {
        if (active) setDetail({ state: 'error' });
      });
      return () => {
        active = false;
      };
    }, [load]),
  );

  const est = detail.state === 'ready' ? detail.estimate : null;
  const status = est?.status;
  const canSend = status === 'draft' || status === 'sent';
  const canMarkSent = status === 'draft';
  const canMarkAccepted = status === 'draft' || status === 'sent';
  const canMarkDeclined = status === 'draft' || status === 'sent';
  const canConvert = status === 'accepted' && est?.convertedInvoiceId == null;
  const hasActions = canSend || canMarkSent || canMarkAccepted || canMarkDeclined || canConvert;
  const expiredNotice =
    status === 'sent' && est?.expiresOn != null && est.expiresOn < todayIso()
      ? est.expiresOn
      : null;

  async function act(
    fn: () => Promise<{ ok: boolean; json: () => Promise<unknown> }>,
    onOk?: (body: unknown) => void,
  ) {
    setActing(true);
    setTransitionError(null);
    try {
      const res = await fn();
      const body = await res.json().catch(() => null);
      if (!res.ok) {
        const code = (body as { error?: string } | null)?.error ?? '';
        setTransitionError(TRANSITION_ERRORS[code] ?? code ?? 'Action failed.');
        return;
      }
      onOk?.(body);
      await load();
    } catch {
      setTransitionError('Action failed.');
    } finally {
      setActing(false);
    }
  }

  function onSend() {
    const to = showOverride ? overrideEmail.trim() : '';
    const recipient = to || (detail.state === 'ready' ? detail.customerEmail : null);
    act(
      () => api.api.estimates[':id'].send.$post({ param: { id }, json: to ? { to } : {} }),
      () => {
        setSentTo(recipient);
        setShowOverride(false);
      },
    );
  }

  function onConvert() {
    act(
      () => api.api.estimates[':id'].convert.$post({ param: { id } }),
      (body) => {
        const invId = (body as { id?: string } | null)?.id;
        if (invId) router.replace(`/invoices/${invId}`);
      },
    );
  }

  const publicUrl = est?.publicToken ? `${apiOrigin}/i/${est.publicToken}` : null;

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
        <Text
          onPress={() => router.push('/estimates')}
          className="font-mono text-xs uppercase tracking-widest text-ink/60"
        >
          ← Estimates
        </Text>

        {detail.state === 'loading' ? (
          <View className="mt-12 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        ) : detail.state === 'error' || !est ? (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load this estimate.</Text>
        ) : (
          <>
            <View className="mt-3 flex-row items-center justify-between">
              <Text className="font-serif text-3xl font-light text-ink">{est.number}</Text>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
                {est.status}
              </Text>
            </View>

            {transitionError ? (
              <View className="mt-4 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
                <Text className="text-sm text-oxblood">{transitionError}</Text>
              </View>
            ) : null}
            {sentTo ? (
              <View className="mt-4 rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3">
                <Text className="text-sm text-ink">
                  Sent to <Text className="font-medium">{sentTo}</Text>.
                </Text>
              </View>
            ) : null}
            {expiredNotice ? (
              <View className="mt-4 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
                <Text className="text-sm text-ink">
                  This estimate's validity expired on{' '}
                  <Text className="font-medium">{expiredNotice}</Text>.
                </Text>
              </View>
            ) : null}

            {/* Action toolbar */}
            {hasActions ? (
              <View className="mt-6 space-y-3">
                {canSend ? (
                  <View>
                    {showOverride ? (
                      <TextInput
                        value={overrideEmail}
                        onChangeText={setOverrideEmail}
                        placeholder={detail.customerEmail ?? 'recipient@example.com'}
                        keyboardType="email-address"
                        autoCapitalize="none"
                        className="mb-2 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
                      />
                    ) : null}
                    <View className="flex-row gap-2">
                      <Pressable
                        onPress={onSend}
                        disabled={acting}
                        className="flex-1 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                      >
                        <Text className="text-center text-sm font-medium text-cream">
                          {est.status === 'sent' ? 'Resend estimate' : 'Send estimate'}
                        </Text>
                      </Pressable>
                      <Pressable
                        onPress={() => setShowOverride((v) => !v)}
                        className="rounded-sm border border-ink/20 px-3 py-3 active:bg-ink/5"
                      >
                        <Text className="font-mono text-xs uppercase tracking-widest text-ink/70">
                          {showOverride ? 'Cancel' : 'To…'}
                        </Text>
                      </Pressable>
                    </View>
                  </View>
                ) : null}

                {canMarkAccepted || canMarkDeclined ? (
                  <View className="flex-row gap-2">
                    {canMarkAccepted ? (
                      <Pressable
                        onPress={() =>
                          act(() =>
                            api.api.estimates[':id']['mark-accepted'].$post({ param: { id } }),
                          )
                        }
                        disabled={acting}
                        className="flex-1 rounded-sm border border-ink/20 px-4 py-3 active:bg-ink/5 disabled:opacity-50"
                      >
                        <Text className="text-center text-sm font-medium text-ink">
                          Mark accepted
                        </Text>
                      </Pressable>
                    ) : null}
                    {canMarkDeclined ? (
                      <Pressable
                        onPress={() =>
                          act(() =>
                            api.api.estimates[':id']['mark-declined'].$post({ param: { id } }),
                          )
                        }
                        disabled={acting}
                        className="flex-1 rounded-sm border border-oxblood/30 px-4 py-3 active:bg-oxblood/5 disabled:opacity-50"
                      >
                        <Text className="text-center text-sm font-medium text-oxblood">
                          Decline
                        </Text>
                      </Pressable>
                    ) : null}
                  </View>
                ) : null}

                {canConvert ? (
                  <Pressable
                    onPress={onConvert}
                    disabled={acting}
                    className="rounded-sm bg-gold-deep px-4 py-3 active:opacity-80 disabled:opacity-50"
                  >
                    <Text className="text-center text-sm font-medium text-cream">
                      Convert to invoice
                    </Text>
                  </Pressable>
                ) : null}

                {canMarkSent ? (
                  <Pressable
                    onPress={() =>
                      act(() => api.api.estimates[':id']['mark-sent'].$post({ param: { id } }))
                    }
                    disabled={acting}
                  >
                    <Text className="text-xs uppercase tracking-widest text-ink/50">
                      Mark sent without email
                    </Text>
                  </Pressable>
                ) : null}
              </View>
            ) : null}

            {/* Converted-to link */}
            {est.convertedInvoiceId ? (
              <Pressable
                onPress={() => router.replace(`/invoices/${est.convertedInvoiceId}`)}
                className="mt-6 rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3"
              >
                <Text className="text-sm text-ink">Converted to an invoice — view it →</Text>
              </Pressable>
            ) : null}

            {/* Share link */}
            {publicUrl ? (
              <View className="mt-6 rounded-sm border border-ink/10 bg-cream-warm p-4">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Share link
                </Text>
                <Text className="mt-2 text-sm text-gold-deep">{publicUrl}</Text>
                <Text className="mt-2 text-xs text-ink/50">
                  Anyone with this link can view the estimate.
                </Text>
              </View>
            ) : null}

            {/* Meta */}
            <View className="mt-8 space-y-2">
              <Meta label="Customer" value={detail.customerName ?? '—'} />
              <Meta label="Issued" value={est.issueDate} />
              {est.expiresOn ? <Meta label="Valid until" value={est.expiresOn} /> : null}
            </View>

            {/* Line items + totals */}
            <View className="mt-8 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
              {est.lineItems.map((li) => (
                <View key={li.position} className="border-b border-ink/10 px-4 py-3">
                  <Text className="text-ink">{li.description}</Text>
                  <View className="mt-1 flex-row justify-between">
                    <Text className="font-mono text-xs text-ink/50">
                      {String(Number(li.quantity))} × {li.unitPrice}
                    </Text>
                    <Text className="font-mono tabular-nums text-ink">{li.amount}</Text>
                  </View>
                </View>
              ))}
              <View className="px-4 py-3">
                <Meta label="Subtotal" value={est.subtotal} mono />
                <View className="mt-1">
                  <Meta label="Tax" value={est.tax ?? '0.00'} mono />
                </View>
                <View className="mt-2 border-t border-ink/10 pt-2">
                  <Meta label="Total" value={`${est.currency} ${est.total}`} mono emphasize />
                </View>
              </View>
            </View>

            {est.notes ? (
              <View className="mt-6">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Notes
                </Text>
                <Text className="mt-1 text-ink/80">{est.notes}</Text>
              </View>
            ) : null}
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function Meta({
  label,
  value,
  mono,
  emphasize,
}: {
  label: string;
  value: string;
  mono?: boolean;
  emphasize?: boolean;
}) {
  return (
    <View className="flex-row justify-between">
      <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">{label}</Text>
      <Text
        className={`text-ink ${mono ? 'font-mono tabular-nums' : ''} ${emphasize ? 'text-lg' : ''}`}
      >
        {value}
      </Text>
    </View>
  );
}
