// apps/mobile/src/app/(app)/more/reports/estimate-win-rate.tsx
import { useState } from 'react';
import { Text, View } from 'react-native';
import { PeriodSelector } from '../../../../components/PeriodSelector';
import { ReportBody, ReportScaffold } from '../../../../components/ReportLayout';
import { api } from '../../../../lib/api';
import { fmt, ytdWindow } from '../../../../lib/report-periods';
import { useReport } from '../../../../lib/use-report';

// Mirror of web's /reports/estimate-win-rate — how many quotes turn into work.
const ROWS: { status: string; label: string; tone: string }[] = [
  { status: 'accepted', label: 'Accepted', tone: 'text-ink' },
  { status: 'declined', label: 'Declined', tone: 'text-oxblood' },
  { status: 'expired', label: 'Expired', tone: 'text-ink/60' },
  { status: 'sent', label: 'Sent (awaiting)', tone: 'text-ink/60' },
  { status: 'draft', label: 'Draft', tone: 'text-ink/60' },
];

export default function EstimateWinRateReport() {
  const [{ from, to }, setWindow] = useState(ytdWindow());
  const { data, error } = useReport(
    (companyId) =>
      api.api.companies[':id']['estimate-win-rate']
        .$get({ param: { id: companyId }, query: { from, to } })
        .then((res) => (res.ok ? res.json() : null)),
    [from, to],
  );

  return (
    <ReportScaffold
      title="Estimate win rate"
      selector={
        <PeriodSelector from={from} to={to} onChange={(f, t) => setWindow({ from: f, to: t })} />
      }
      note={`${from} → ${to}. Of the estimates you've heard back on (accepted, declined, or expired), how many turned into work.`}
    >
      <ReportBody data={data} error={error}>
        {(d) => {
          const winPct = d.winRate === null ? null : Math.round(Number(d.winRate) * 100);
          const byStatus = new Map(d.byStatus.map((s) => [s.status as string, s]));
          return (
            <>
              <View className="mt-8 rounded-sm border border-ink/10 bg-cream-warm p-5">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Win rate
                </Text>
                <Text className="mt-2 font-serif text-4xl font-light text-ink">
                  {winPct === null ? '—' : `${winPct}%`}
                </Text>
                <Text className="mt-1 text-xs text-ink/50">
                  {winPct === null
                    ? 'Nothing decided yet'
                    : `${d.acceptedCount} of ${d.decidedCount} decided`}
                </Text>
              </View>

              <View className="mt-4 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
                <View className="flex-row bg-cream px-4 py-3">
                  <Text className="flex-1 font-mono text-xs uppercase tracking-widest text-ink/50">
                    Status
                  </Text>
                  <Text className="w-16 text-right font-mono text-xs uppercase tracking-widest text-ink/50">
                    Count
                  </Text>
                  <Text className="w-28 text-right font-mono text-xs uppercase tracking-widest text-ink/50">
                    Value
                  </Text>
                </View>
                {ROWS.map((r) => {
                  const row = byStatus.get(r.status);
                  return (
                    <View
                      key={r.status}
                      className="flex-row items-center border-t border-ink/10 px-4 py-3"
                    >
                      <Text className={`flex-1 ${r.tone}`}>{r.label}</Text>
                      <Text className="w-16 text-right font-mono text-sm tabular-nums text-ink/70">
                        {row?.count ?? 0}
                      </Text>
                      <Text className="w-28 text-right font-mono text-sm tabular-nums text-ink">
                        {fmt(row?.value ?? '0.00')}
                      </Text>
                    </View>
                  );
                })}
              </View>
            </>
          );
        }}
      </ReportBody>
    </ReportScaffold>
  );
}

// apps/web/src/routes/(app)/reports/estimate-win-rate/+page.svelte
<script lang="ts">
  import PeriodSelector from '$lib/components/PeriodSelector.svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  const { report, presets, activeKey } = $derived(data);

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  const byStatus = $derived(new Map(report.byStatus.map((s) => [s.status, s])));
  // Win-first display order with friendly labels.
  const ROWS = [
    { status: 'accepted', label: 'Accepted', tone: 'text-ink' },
    { status: 'declined', label: 'Declined', tone: 'text-oxblood' },
    { status: 'expired', label: 'Expired', tone: 'text-ink/60' },
    { status: 'sent', label: 'Sent (awaiting)', tone: 'text-ink/60' },
    { status: 'draft', label: 'Draft', tone: 'text-ink/60' },
  ];

  const winPct = $derived(report.winRate === null ? null : Math.round(Number(report.winRate) * 100));
</script>

<div>
  <span class="eyebrow">Reports</span>
  <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
    Estimate win rate<span class="text-gold-deep">.</span>
  </h1>
</div>

<PeriodSelector {presets} {activeKey} from={report.from} to={report.to} />

<p class="mt-4 text-sm text-ink/60">
  {report.from} → {report.to}. Of the estimates you've heard back on (accepted, declined, or
  expired), how many turned into work.
</p>

<div class="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-3">
  <div class="rounded-sm border border-ink/10 bg-cream-warm p-5">
    <div class="font-mono text-xs uppercase tracking-widest text-ink/50">Win rate</div>
    <div class="mt-2 font-serif text-4xl font-light text-ink">
      {winPct === null ? '—' : `${winPct}%`}
    </div>
    <div class="mt-1 text-xs text-ink/50">
      {#if winPct === null}
        Nothing decided yet
      {:else}
        {report.acceptedCount} of {report.decidedCount} decided
      {/if}
    </div>
  </div>
</div>

<div class="mt-4 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
  <table class="w-full text-left text-sm">
    <thead class="bg-cream">
      <tr class="font-mono text-xs uppercase tracking-widest text-ink/50">
        <th class="px-5 py-3">Status</th>
        <th class="w-24 px-5 py-3 text-right">Count</th>
        <th class="w-36 px-5 py-3 text-right">Value</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-ink/10">
      {#each ROWS as r (r.status)}
        {@const row = byStatus.get(r.status)}
        <tr>
          <td class="px-5 py-3 {r.tone}">{r.label}</td>
          <td class="px-5 py-3 text-right font-mono tabular-nums text-ink/70">{row?.count ?? 0}</td>
          <td class="px-5 py-3 text-right font-mono tabular-nums text-ink">
            {fmt(row?.value ?? '0.00')}
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>
