// apps/mobile/src/app/(app)/index.tsx
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MetricStrip } from '../../components/MetricStrip';
import { pickActiveCompany } from '../../lib/active-company';
import { api } from '../../lib/api';
import { signOut } from '../../lib/auth-client';
import { useMay } from '../../lib/role';
import { trackEvent } from '../../lib/telemetry';

// Position dashboard + AI insights (mirror of apps/web's (app)/+page.svelte).
// Replaces the Phase-6 shell placeholder. Money figures are decimal strings
// from the API — formatted for display only. Anomalies are deterministic;
// cash-flow nudges are AI (Pro+/BYOK) and degrade to empty on a 503.
type Period = 'month' | '30d' | 'ytd';
type Dashboard = { moneyIn: string; moneyOut: string; owed: string; owing: string };
type Anomalies = {
  overall: { pctOver: number; recent: string; typical: string } | null;
  categories: { code: string; name: string; recent: string; typical: string; pctOver: number }[];
};
type Nudge = { text: string; tone: string };
// Point-in-time entity counts for the "Right now" tiles (mirror of web). Counts
// only — the money tiles above own the dollars, so no duplicate of "Owed to you".
type Counts = {
  overdue: number;
  awaiting: number;
  drafts: number;
  openEstimates: number;
  acceptedEstimates: number;
  undelivered: number;
};

const PERIODS: { key: Period; label: string }[] = [
  { key: 'month', label: 'This month' },
  { key: '30d', label: 'Last 30 days' },
  { key: 'ytd', label: 'Year to date' },
];

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

const flowLabel = (p: Period) =>
  p === 'ytd' ? 'this year' : p === '30d' ? 'last 30 days' : 'this month';

const toneClass = (tone: string) =>
  tone === 'warning'
    ? 'border-oxblood/30 bg-oxblood/5'
    : tone === 'good'
      ? 'border-gold-deep/30 bg-gold-deep/5'
      : 'border-ink/15 bg-cream-warm';

export default function Home() {
  const router = useRouter();
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [companyName, setCompanyName] = useState<string | null>(null);
  const [period, setPeriod] = useState<Period>('month');
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [counts, setCounts] = useState<Counts | null>(null);
  const [loading, setLoading] = useState(true);
  const [anomalies, setAnomalies] = useState<Anomalies>({ overall: null, categories: [] });
  const [nudges, setNudges] = useState<Nudge[]>([]);
  const [nudgesLoading, setNudgesLoading] = useState(false);
  const [pendingInvites, setPendingInvites] = useState(0);
  // First-run telemetry consent (TELEMETRY.md). Account-wide, so only the
  // settings:manage roles are asked; others never see it. `consentNeeded` flips
  // off the moment they answer (locally) or once the account has decided.
  const canManageSettings = useMay('settings:manage');
  const [consentNeeded, setConsentNeeded] = useState(false);
  const [consentBusy, setConsentBusy] = useState(false);

  // Resolve the active company once on focus (Home is the first authed screen),
  // plus any pending workspace invitations for the notice below.
  useFocusEffect(
    useCallback(() => {
      let active = true;
      api.api.companies
        .$get()
        .then(async (res) => {
          if (!active || !res.ok) return;
          const { companies } = await res.json();
          const c = await pickActiveCompany(companies);
          if (c) {
            setCompanyId(c.id);
            setCompanyName(c.name);
          }
        })
        .catch(() => {});

      // Pending invitations (bootstrap route) → a notice that deep-links to the
      // Workspace screen, where they can accept/decline.
      api.api.me.invitations
        .$get()
        .then(async (res) => {
          if (!active || !res.ok) return;
          setPendingInvites((await res.json()).invitations.length);
        })
        .catch(() => {});

      // First-run telemetry consent. Gated settings:manage on the API, so only
      // ask roles that can actually decide; show the prompt until the account
      // has answered and the deployment hasn't disabled telemetry.
      if (canManageSettings) {
        api.api.account.telemetry
          .$get()
          .then(async (res) => {
            if (!active || !res.ok) return;
            const t = await res.json();
            setConsentNeeded(!t.decided && !t.disabled);
          })
          .catch(() => {});
      }

      return () => {
        active = false;
      };
    }, [canManageSettings]),
  );

  // Position + insights, re-fetched when the company or period changes.
  useEffect(() => {
    if (!companyId) return;
    let active = true;
    setLoading(true);
    api.api.companies[':id'].dashboard
      .$get({ param: { id: companyId }, query: { period, from: undefined, to: undefined } })
      .then(async (res) => {
        if (!active || !res.ok) return;
        const d = await res.json();
        setDashboard({ moneyIn: d.moneyIn, moneyOut: d.moneyOut, owed: d.owed, owing: d.owing });
      })
      .catch(() => {})
      .finally(() => {
        if (active) setLoading(false);
      });

    api.api.companies[':id']['spending-anomalies']
      .$get({ param: { id: companyId } })
      .then(async (res) => {
        if (!active || !res.ok) return;
        const a = await res.json();
        setAnomalies({ overall: a.overall ?? null, categories: a.categories ?? [] });
      })
      .catch(() => {});

    // AI nudges: separate, best-effort. 503 (AI off) / 502 (model error) →
    // no nudges rather than a broken dashboard.
    setNudgesLoading(true);
    api.api.companies[':id']['cash-flow-nudges']
      .$get({ param: { id: companyId } })
      .then(async (res) => {
        if (!active) return;
        if (res.ok) setNudges((await res.json()).nudges ?? []);
        else setNudges([]);
      })
      .catch(() => {})
      .finally(() => {
        if (active) setNudgesLoading(false);
      });

    return () => {
      active = false;
    };
  }, [companyId, period]);

  // Point-in-time counts (NOT period-bound → keyed on companyId only, so the
  // period toggle doesn't refetch them). Company-scoped to match the dashboard.
  // Best-effort: a non-OK degrades to zeros rather than failing the screen.
  useEffect(() => {
    if (!companyId) return;
    let active = true;
    Promise.all([
      api.api.invoices.summary.$get({ query: { companyId } }),
      api.api.estimates.summary.$get({ query: { companyId } }),
    ])
      .then(async ([invRes, estRes]) => {
        if (!active) return;
        const inv = invRes.ok ? await invRes.json() : null;
        const est = estRes.ok ? await estRes.json() : null;
        setCounts({
          overdue: inv?.overdue.count ?? 0,
          awaiting: inv?.awaiting.count ?? 0,
          drafts: inv?.draft.count ?? 0,
          openEstimates: est?.open.count ?? 0,
          // The customer said yes and nothing has been billed for it (TMC-230).
          // Accepting is the highest-value event in the product, and the
          // estimate used to leave the "open" tile on acceptance, so the one
          // surface tracking it stopped showing it exactly when it became
          // actionable.
          acceptedEstimates: est?.acceptedUnbilled.count ?? 0,
          // Invoices whose email did not arrive (TMC-226). Before this the only
          // trace of a bounce was a server log line, so an invoice that reached
          // nobody looked exactly like one being ignored.
          undelivered: inv?.undelivered.count ?? 0,
        });
      })
      .catch(() => {});
    return () => {
      active = false;
    };
  }, [companyId]);

  const showAnomalies = anomalies.overall !== null || anomalies.categories.length > 0;

  // ai_insight_viewed (TELEMETRY.md client ingest) — fire per rendered insight
  // surface: the deterministic "Unusual spending" section (anomaly) and the AI
  // "What to watch" nudges (cashflow). trackEvent no-ops when opted out;
  // re-fires when the section re-renders on a company/period change, mirroring
  // web's dashboard and report_viewed's re-fire-on-focus behaviour.
  useEffect(() => {
    if (showAnomalies) trackEvent({ name: 'ai_insight_viewed', insight_type: 'anomaly' });
  }, [showAnomalies]);

  useEffect(() => {
    if (nudges.length > 0) trackEvent({ name: 'ai_insight_viewed', insight_type: 'cashflow' });
  }, [nudges]);

  async function onSignOut() {
    await signOut();
    router.replace('/sign-in');
  }

  // Answer the first-run consent prompt. Either choice stamps decided
  // server-side; dismiss locally on success so the card disappears at once.
  async function onAnswerConsent(enabled: boolean) {
    setConsentBusy(true);
    try {
      const res = await api.api.account.telemetry.$patch({ json: { enabled } });
      if (res.ok) setConsentNeeded(false);
    } catch {
      // Leave the prompt up; they can retry or use Settings → Privacy.
    } finally {
      setConsentBusy(false);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <View className="flex-row items-start justify-between">
          <View className="flex-1">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              {companyName ?? ' '}
            </Text>
            <Text className="mt-2 font-serif text-4xl font-light text-ink">Where you stand</Text>
          </View>
          <Pressable onPress={onSignOut} className="ml-3 mt-1 px-2 py-1">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Sign out
            </Text>
          </Pressable>
        </View>

        {/* Search (TMC-198). A pressable bar rather than a live input: tapping
          it opens the search screen with its own autofocused field, so this
          costs Home nothing but a row and there is no second debounce to keep
          in sync. */}
        <Pressable
          onPress={() => router.push('/search')}
          accessibilityRole="search"
          accessibilityLabel="Search"
          className="mt-6 flex-row items-center gap-2 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2.5 active:bg-gold-deep/10"
        >
          <Ionicons name="search-outline" size={16} className="text-ink-subtle" />
          <Text className="text-ink-subtle">Search invoices, contacts, expenses…</Text>
        </Pressable>

        {/* Pending workspace invitations → Workspace screen to accept/decline */}
        {pendingInvites > 0 ? (
          <Pressable
            onPress={() => router.push('/more/switch-account')}
            className="mt-6 flex-row items-center justify-between rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3 active:bg-gold-deep/10"
          >
            <Text className="flex-1 text-sm text-ink">
              You have {pendingInvites} pending workspace{' '}
              {pendingInvites === 1 ? 'invitation' : 'invitations'}.
            </Text>
            <Text className="ml-3 font-mono text-xs uppercase tracking-widest text-gold-deep">
              Review →
            </Text>
          </Pressable>
        ) : null}

        {/* First-run telemetry consent */}
        {consentNeeded ? (
          <View className="mt-6 rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-4">
            <Text className="font-serif text-base text-ink">Help us build a better product</Text>
            <Text className="mt-1 text-sm text-ink-muted">
              We'd like to collect anonymous usage data — which features you use and where errors
              occur. We never collect personal or financial information. You can change this any
              time in More → Privacy.
            </Text>
            <View className="mt-4 flex-row gap-3">
              <Pressable
                onPress={() => onAnswerConsent(true)}
                disabled={consentBusy}
                className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep disabled:opacity-50"
              >
                <Text className="text-sm font-medium text-cream">Yes, help</Text>
              </Pressable>
              <Pressable
                onPress={() => onAnswerConsent(false)}
                disabled={consentBusy}
                className="rounded-sm border border-ink/20 px-4 py-2 active:bg-cream disabled:opacity-50"
              >
                <Text className="text-sm font-medium text-ink">No thanks</Text>
              </Pressable>
            </View>
          </View>
        ) : null}

        {/* Period selector */}
        <View className="mt-6 flex-row flex-wrap gap-2">
          {PERIODS.map((p) => (
            <Pressable
              key={p.key}
              onPress={() => setPeriod(p.key)}
              className={`rounded-sm border px-3 py-1 ${
                period === p.key ? 'border-gold-deep' : 'border-ink/15'
              }`}
            >
              <Text
                className={`font-mono text-xs uppercase tracking-widest ${
                  period === p.key ? 'text-gold-deep' : 'text-ink-subtle'
                }`}
              >
                {p.label}
              </Text>
            </Pressable>
          ))}
        </View>

        {/* Position tiles */}
        {loading && !dashboard ? (
          <View className="mt-10 items-center">
            <ActivityIndicator className="text-ink" />
          </View>
        ) : dashboard ? (
          <View className="mt-8 gap-4">
            <Tile label="Money in" value={fmt(dashboard.moneyIn)} sub={flowLabel(period)} />
            <Tile label="Money out" value={fmt(dashboard.moneyOut)} sub={flowLabel(period)} />
            <Tile label="Owed to you" value={fmt(dashboard.owed)} sub="outstanding now" />
            <Tile label="Owed by you" value={fmt(dashboard.owing)} sub="bills outstanding" />
          </View>
        ) : (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load your position.</Text>
        )}

        {/* Right now — point-in-time counts (NOT period-bound). Counts only; the
            money tiles above own the dollars. Each tile deep-links to its
            filtered list. */}
        {counts ? (
          <View className="mt-8">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Right now
            </Text>
            <View className="mt-3">
              <MetricStrip
                tiles={[
                  {
                    label: 'Overdue',
                    value: counts.overdue,
                    onPress: () => router.push('/invoices?bucket=overdue'),
                    alert: counts.overdue > 0,
                  },
                  {
                    label: 'Awaiting',
                    value: counts.awaiting,
                    onPress: () => router.push('/invoices?bucket=awaiting'),
                  },
                  {
                    label: 'Drafts',
                    value: counts.drafts,
                    onPress: () => router.push('/invoices?status=draft'),
                  },
                  {
                    label: 'Open estimates',
                    value: counts.openEstimates,
                    onPress: () => router.push('/estimates?status=sent'),
                  },
                  // Flagged like an overdue invoice, because it is the same
                  // kind of fact: the customer has acted and the business has
                  // not (TMC-230).
                  {
                    label: 'Accepted',
                    value: counts.acceptedEstimates,
                    onPress: () => router.push('/estimates?status=accepted'),
                    alert: counts.acceptedEstimates > 0,
                  },
                  // Only shown when something is wrong. A permanent
                  // "0 undelivered" would be one more number to ignore; a tile
                  // that appears only when an email did not arrive is the whole
                  // point (TMC-226).
                  ...(counts.undelivered > 0
                    ? [
                        {
                          label: 'Not delivered',
                          value: counts.undelivered,
                          onPress: () => router.push('/invoices?bucket=undelivered'),
                          alert: true,
                        },
                      ]
                    : []),
                ]}
              />
            </View>
          </View>
        ) : null}

        {/* Unusual spending (deterministic) */}
        {showAnomalies ? (
          <View className="mt-8">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Unusual spending
            </Text>
            <View className="mt-3 gap-3">
              {anomalies.overall ? (
                <View className="rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
                  <Text className="text-sm text-ink/80">
                    Spending is {anomalies.overall.pctOver}% above your typical month —{' '}
                    {fmt(anomalies.overall.recent)} in the last 30 days vs about{' '}
                    {fmt(anomalies.overall.typical)}.
                  </Text>
                </View>
              ) : null}
              {anomalies.categories.map((cat) => (
                <View
                  key={cat.code}
                  className="rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3"
                >
                  <Text className="text-sm text-ink/80">
                    {cat.name}: {fmt(cat.recent)} vs about {fmt(cat.typical)} usual ({cat.pctOver}%
                    up).
                  </Text>
                </View>
              ))}
            </View>
          </View>
        ) : null}

        {/* What to watch (AI) */}
        {nudgesLoading ? (
          <View className="mt-8 flex-row items-center gap-2">
            <ActivityIndicator className="text-gold-deep" size="small" />
            <Text className="text-sm text-ink-subtle">Reading your cash flow…</Text>
          </View>
        ) : nudges.length > 0 ? (
          <View className="mt-8">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              What to watch
            </Text>
            {/*
              The tiles above follow the period toggle; the nudge signals are
              always month-to-date, so on "this year" a tile and the nudge under
              it quote different figures and read as a contradiction. Same label
              as web (TMC-229).
            */}
            <Text className="mt-1 text-xs text-ink-subtle">this month so far</Text>
            <View className="mt-3 gap-3">
              {nudges.map((n) => (
                <View key={n.text} className={`rounded-sm border px-4 py-3 ${toneClass(n.tone)}`}>
                  <Text className="text-sm text-ink/80">{n.text}</Text>
                </View>
              ))}
            </View>
          </View>
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
}

function Tile({ label, value, sub }: { label: string; value: string; sub: string }) {
  return (
    <View className="rounded-sm border border-ink/10 bg-cream-warm p-6">
      <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">{label}</Text>
      <Text className="mt-2 font-serif text-3xl font-light tabular-nums text-ink">{value}</Text>
      <Text className="mt-1 text-xs text-ink-subtle">{sub}</Text>
    </View>
  );
}

// apps/web/src/routes/(app)/+page.svelte
<script lang="ts">
  import { Sparkline } from '$lib/charts';
  import { may } from '$lib/perms';
  import { trackEvent } from '$lib/telemetry';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  const d = $derived(data.dashboard);

  // Server-side and keyed on existence, not on money: a contact, an invoice or
  // an estimate retires the getting-started panel, so a draft invoice counts and
  // a seasonal business in a quiet January does not regress to it (TMC-234).
  const isNew = $derived(d.isNewCompany);

  // Point-in-time count tiles (NOT period-bound — they sit under a "Right now"
  // label, outside the period toggle). Counts only: the money row above already
  // owns the dollar figures, so no $ here avoids a duplicate of "Owed to you".
  // Each tile deep-links to its filtered list. Overdue tints when non-zero —
  // the one metric worth an alert.
  const counts = $derived(data.counts);
  const countTiles = $derived([
    {
      label: 'Overdue',
      count: counts.overdue,
      hint: 'needs chasing',
      href: '/invoices?overdue=true',
      alert: counts.overdue > 0,
    },
    { label: 'Awaiting', count: counts.awaiting, hint: 'not yet due', href: '/invoices?awaiting=true' },
    { label: 'Drafts', count: counts.drafts, hint: 'to send', href: '/invoices?status=draft' },
    {
      label: 'Open estimates',
      count: counts.openEstimates,
      hint: 'awaiting reply',
      href: '/estimates?status=sent',
    },
    // Flagged like an overdue invoice, because it is the same kind of fact: the
    // customer has acted and the business has not. Before this the estimate
    // simply left the tile row when it was accepted (TMC-230).
    {
      label: 'Accepted',
      count: counts.acceptedEstimates,
      hint: 'ready to invoice',
      href: '/estimates?status=accepted',
      alert: counts.acceptedEstimates > 0,
    },
    // Only shown when something is wrong. A permanent "0 undelivered" tile
    // would be one more number to ignore; a tile that appears only when an
    // email did not arrive is the whole point (TMC-226).
    ...(counts.undelivered > 0
      ? [
          {
            label: 'Not delivered',
            count: counts.undelivered,
            hint: 'email did not arrive',
            href: '/invoices?undelivered=true',
            alert: true,
          },
        ]
      : []),
  ]);

  // Display formatting only — the authoritative value is the decimal string
  // from the API. Realistic position figures sit well within Number's safe
  // range, so toLocaleString is fine for the headline.
  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  const periods = [
    { key: 'month', label: 'This month' },
    { key: '30d', label: 'Last 30 days' },
    { key: 'ytd', label: 'Year to date' },
  ];
  const flowLabel = $derived(
    data.period === 'ytd' ? 'this year' : data.period === '30d' ? 'last 30 days' : 'this month',
  );

  // Border accent per nudge tone (gold = good, oxblood = warning, ink = info).
  const toneClass = (tone: string) =>
    tone === 'warning'
      ? 'border-danger/30 bg-danger/5'
      : tone === 'good'
        ? 'border-accent/30 bg-accent/5'
        : 'border-fg/15 bg-surface-2';

  // Anomaly flagging (deterministic): unusual spending vs the company's own
  // history. Shown only when something actually flags.
  const a = $derived(data.anomalies);
  const showAnomalies = $derived(a.overall !== null || a.categories.length > 0);

  // ai_insight_viewed (TELEMETRY.md client ingest). Fire per rendered insight
  // surface: the deterministic "Unusual spending" section (anomaly) and the AI
  // "What to watch" nudges (cashflow). trackEvent no-ops server-side / when
  // opted out; re-fires on period change (a fresh view of that period's
  // insights), matching report_viewed's re-fire-on-navigation behaviour.
  $effect(() => {
    if (showAnomalies) trackEvent({ name: 'ai_insight_viewed', insight_type: 'anomaly' });
  });

  $effect(() => {
    // Nudges stream in as a promise; guard against a stale resolution firing
    // after the period changed under it.
    let cancelled = false;
    data.nudges.then((result) => {
      if (!cancelled && result.nudges.length > 0) {
        trackEvent({ name: 'ai_insight_viewed', insight_type: 'cashflow' });
      }
    });
    return () => {
      cancelled = true;
    };
  });
</script>

<span class="eyebrow text-fg/60">{data.companyName}</span>
<h1 class="mt-2 font-serif text-4xl font-light leading-none tracking-tight text-fg">
  Where you stand<span class="text-accent">.</span>
</h1>

{#if !isNew}
<div class="mt-6 flex flex-wrap gap-2">
  {#each periods as p (p.key)}
    <a
      href="/?period={p.key}"
      class="rounded-sm border px-3 py-1 font-mono text-xs uppercase tracking-widest transition-colors {data.period ===
      p.key
        ? 'border-accent text-accent'
        : 'border-fg/15 text-fg/60 hover:border-fg/40 hover:text-fg'}"
    >
      {p.label}
    </a>
  {/each}
</div>
{/if}

{#if data.pendingInvites > 0}
  <a
    href="/select-company"
    class="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg transition-colors hover:bg-accent/10"
  >
    <span>
      You have {data.pendingInvites} pending workspace {data.pendingInvites === 1
        ? 'invitation'
        : 'invitations'}.
    </span>
    <span class="font-mono text-xs uppercase tracking-widest text-accent">Review →</span>
  </a>
{/if}

{#if data.needsBusinessDetails}
  <a
    href="/settings/business"
    class="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg transition-colors hover:bg-accent/10"
  >
    <span>Add your business address so it shows on the invoices your contacts see.</span>
    <span class="font-mono text-xs uppercase tracking-widest text-accent">Add details →</span>
  </a>
{/if}

{#if isNew}
  <!--
    A company with no contact, no invoice and no estimate has nothing this page
    can answer, and four $0.00 tiles over four 0 counts answered it anyway. The
    only call to action on the whole screen was the address nag, which points at
    Settings — so the first thing the product asked a new user to do was
    paperwork (TMC-234).

    The flag is server-side (dashboard.isNewCompany) and keyed on existence
    rather than on money, so a first invoice still sitting in draft is enough to
    retire this panel, and a seasonal business looking at a quiet January never
    sees it.
  -->
  <section class="mt-8 rounded-sm border border-fg/10 bg-surface-2 px-6 py-10">
    <span class="eyebrow text-accent">First steps</span>
    <h2 class="mt-3 font-serif text-3xl font-light leading-tight tracking-tight text-fg">
      Let's get you paid<span class="text-accent">.</span>
    </h2>
    <p class="mt-4 max-w-xl text-fg/70">
      Thalermark keeps the books in the background. Send an invoice, log what you spend, and the
      accounting takes care of itself.
    </p>
    {#if may(data.role, 'sales:write')}
      <a href="/invoices/new" class="btn mt-6 inline-block px-5 py-3">Send your first invoice</a>
    {/if}
    <p class="mt-5 text-sm text-fg/50">
      {#if may(data.role, 'contacts:write')}
        or <a href="/contacts/new" class="link">add a customer</a>
      {/if}
      {#if may(data.role, 'contacts:write') && may(data.role, 'expenses:write')}
        &middot;
      {/if}
      {#if may(data.role, 'expenses:write')}
        <a href="/expenses/new" class="link">record something you bought</a>
      {/if}
    </p>
  </section>
{:else}
<dl class="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
  <div class="rounded-sm border border-fg/10 bg-surface-2 p-6">
    <dt class="label">Money in</dt>
    <dd class="mt-2 font-serif text-3xl font-light tabular-nums text-fg">{fmt(d.moneyIn)}</dd>
    <p class="mt-1 text-xs text-fg/40">{flowLabel}</p>
  </div>
  <div class="rounded-sm border border-fg/10 bg-surface-2 p-6">
    <dt class="label">Money out</dt>
    <dd class="mt-2 font-serif text-3xl font-light tabular-nums text-fg">{fmt(d.moneyOut)}</dd>
    <p class="mt-1 text-xs text-fg/40">{flowLabel}</p>
  </div>
  <div class="rounded-sm border border-fg/10 bg-surface-2 p-6">
    <dt class="label">Owed to you</dt>
    <dd class="mt-2 font-serif text-3xl font-light tabular-nums text-fg">{fmt(d.owed)}</dd>
    <p class="mt-1 text-xs text-fg/40">outstanding now</p>
  </div>
  <a href="/bills" class="rounded-sm border border-fg/10 bg-surface-2 p-6 transition-colors hover:border-fg/25">
    <dt class="label">Owed by you</dt>
    <dd class="mt-2 font-serif text-3xl font-light tabular-nums text-fg">{fmt(d.owing)}</dd>
    <p class="mt-1 text-xs text-fg/40">unpaid bills</p>
  </a>
</dl>

<!--
  Its OWN row, with its own label, deliberately not inside the "Money in" tile.
  It was there first and it was misleading: "Money in" is CASH RECEIVED in the
  selected period (cashFlowNet), while this is REVENUE BILLED by the month it
  was issued. A trend line sitting under a number is read as that number's
  history, so a $200 cash month with a line peaking at a $6,000 billing month
  invited exactly the wrong conclusion — in an accounting product, of all
  places. Separated and labelled, it says only what it measures. It is also
  always twelve months, where the tiles follow the period toggle.
-->
{#if data.revenueTrend.length > 1}
  <a
    href="/reports/revenue-over-time"
    class="mt-6 flex items-end gap-6 rounded-sm border border-fg/10 bg-surface-2 p-5 transition-colors hover:border-fg/25"
  >
    <div class="shrink-0">
      <span class="label">Billed by month</span>
      <p class="mt-1 text-xs text-fg/40">last 12 months</p>
    </div>
    <div class="min-w-0 flex-1">
      <Sparkline values={data.revenueTrend} label="Revenue billed by month, last 12 months" />
    </div>
  </a>
{/if}

<h2 class="label mt-8 text-fg/60">Right now</h2>
<dl class="mt-3 grid grid-cols-2 gap-4 lg:grid-cols-4">
  {#each countTiles as t (t.label)}
    <a
      href={t.href}
      class="rounded-sm border p-4 transition-colors {t.alert
        ? 'border-danger/30 bg-danger/5 hover:border-danger/50'
        : 'border-fg/10 bg-surface-2 hover:border-fg/25'}"
    >
      <dt class="label">{t.label}</dt>
      <dd class="mt-1 font-serif text-2xl font-light tabular-nums text-fg">{t.count}</dd>
      <p class="mt-1 text-xs text-fg/40">{t.hint}</p>
    </a>
  {/each}
</dl>
{/if}

{#if showAnomalies}
  <section class="mt-8">
    <h2 class="label">Unusual spending</h2>
    <ul class="mt-3 space-y-3">
      {#if a.overall}
        <li class="rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-fg/80">
          Spending is {a.overall.pctOver}% above your typical month — {fmt(a.overall.recent)} in the
          last 30 days vs about {fmt(a.overall.typical)}.
        </li>
      {/if}
      {#each a.categories as cat (cat.code)}
        <li class="rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-fg/80">
          {cat.name}: {fmt(cat.recent)} vs about {fmt(cat.typical)} usual ({cat.pctOver}% up).
        </li>
      {/each}
    </ul>
  </section>
{/if}

{#await data.nudges}
  <div class="mt-8 flex items-center gap-2 text-sm text-fg/50">
    <span
      class="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-accent border-t-transparent"
    ></span>
    Reading your cash flow…
  </div>
{:then result}
  {#if result.nudges.length > 0}
    <!--
      Labelled with its own window, for the same reason the revenue sparkline
      above carries "last 12 months": the tiles follow the period toggle and this
      does not. The nudge signals are always month-to-date (reports.ts builds
      monthToDate plus three trailing months, and takes no period argument), so
      on the "this year" toggle a tile read $84,000 while the nudge under it said
      $6,200. Both figures are right and together they read as the product
      contradicting itself — on the one feature people pay for, whose whole
      architecture rests on the model quoting ledger figures rather than
      inventing them (TMC-229).

      Making the nudge follow the toggle is the fuller answer and is deliberately
      NOT done here: companies.cash_flow_nudges is a single cached value per
      company, so three toggle states sharing one slot would regenerate on every
      switch and triple the model spend for one page view. That belongs with the
      signals rework on TMC-229, which is already changing what the cache key is
      made of.
    -->
    <section class="mt-8">
      <h2 class="label">What to watch</h2>
      <p class="mt-1 text-xs text-fg/40">this month so far</p>
      <ul class="mt-3 space-y-3">
        {#each result.nudges as nudge (nudge.text)}
          <li class="rounded-sm border px-4 py-3 text-sm text-fg/80 {toneClass(nudge.tone)}">
            {nudge.text}
          </li>
        {/each}
      </ul>
    </section>
  {/if}
{/await}
