// apps/mobile/src/app/(app)/more/tax-policies/index.tsx
import { useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../../lib/api';
import { useMay } from '../../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../../lib/use-paginated-list';

// Mirror of apps/web's /settings/tax-policies. Account-scoped via x-account-id;
// keyset infinite scroll. Archived policies hide until "Show archived". Policies
// archive/restore instead of deleting. Writes are settings:manage.
type PolicyRow = {
  id: string;
  name: string;
  ratePct: string;
  isDefault: boolean;
  archivedAt: string | null;
};

const rate = (s: string) => `${Number(s)}%`;

export default function TaxPoliciesList() {
  const router = useRouter();
  const canManage = useMay('settings:manage');
  const [showArchived, setShowArchived] = useState(false);
  const [busyId, setBusyId] = useState<string | null>(null);

  const fetchPage = useCallback(
    async (cursor: string | null) => {
      const query = pageQuery(cursor);
      if (showArchived) query.includeArchived = 'true';
      const res = await api.api['tax-policies'].$get({ query });
      if (!res.ok) return null;
      const { taxPolicies, nextCursor } = await res.json();
      return {
        rows: taxPolicies.map(
          (p): PolicyRow => ({
            id: p.id,
            name: p.name,
            ratePct: p.ratePct,
            isDefault: p.isDefault,
            archivedAt: p.archivedAt ?? null,
          }),
        ),
        nextCursor,
      };
    },
    [showArchived],
  );

  const { list, loadingMore, loadMore, reload } = usePaginatedList(fetchPage);

  async function toggleArchive(policy: PolicyRow) {
    setBusyId(policy.id);
    try {
      const res = policy.archivedAt
        ? await api.api['tax-policies'][':id'].restore.$post({ param: { id: policy.id } })
        : await api.api['tax-policies'][':id'].archive.$post({ param: { id: policy.id } });
      if (res.ok) reload();
    } catch {
      // A focus refetch will reconcile.
    } finally {
      setBusyId(null);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="px-6 pt-6">
        <Pressable onPress={() => router.push('/more')}>
          <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
            ← More
          </Text>
        </Pressable>
        <View className="mt-3 flex-row items-end justify-between">
          <Text className="font-serif text-3xl font-light text-ink">Tax policies</Text>
          {canManage ? (
            <Pressable
              onPress={() => router.push('/more/tax-policies/new')}
              className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
            >
              <Text className="text-sm font-medium text-cream">+ New</Text>
            </Pressable>
          ) : null}
        </View>
        <Pressable onPress={() => setShowArchived((s) => !s)} className="mt-4 self-start">
          <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
            {showArchived ? '← Hide archived' : 'Show archived'}
          </Text>
        </Pressable>
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator className="text-ink" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load tax policies.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink-muted">
          {showArchived ? 'No tax policies yet.' : 'No active tax policies yet.'}
        </Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(p) => p.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator className="text-ink" />
              </View>
            ) : null
          }
          renderItem={({ item }) => (
            <View className="flex-row items-center gap-3 bg-cream-warm px-5 py-4">
              <Pressable
                onPress={() => router.push(`/more/tax-policies/${item.id}`)}
                className="flex-1 active:opacity-70"
              >
                <View className="flex-row items-center gap-2">
                  <Text className="font-serif text-lg text-ink">{item.name}</Text>
                  {item.isDefault ? (
                    <Text className="rounded-sm border border-gold-deep/40 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-gold-deep">
                      Default
                    </Text>
                  ) : null}
                  {item.archivedAt ? (
                    <Text className="rounded-sm border border-ink/15 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-ink-subtle">
                      Archived
                    </Text>
                  ) : null}
                </View>
                <Text className="mt-1 font-mono text-xs uppercase tracking-widest text-ink-subtle">
                  {rate(item.ratePct)}
                </Text>
              </Pressable>
              {canManage ? (
                <Pressable
                  onPress={() => toggleArchive(item)}
                  disabled={busyId === item.id}
                  className="rounded-sm border border-ink/15 px-2 py-1 active:border-gold-deep disabled:opacity-50"
                >
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                    {item.archivedAt ? 'Restore' : 'Archive'}
                  </Text>
                </Pressable>
              ) : null}
            </View>
          )}
        />
      )}
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/settings/tax-policies/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  const showArchived = $derived(data.showArchived);
  const canManage = $derived(may(data.role, 'settings:manage'));

  type Row = (typeof data.taxPolicies)[number];
  let rows = $state<Row[]>(untrack(() => data.taxPolicies));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.taxPolicies;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<Row>('/settings/tax-policies/more', cursor, {
        archived: showArchived ? '1' : '',
      });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }

  // numeric(7,4) reads as "8.2500"; show it as a tidy "8.25%".
  const ratePct = (s: string) => `${Number(s)}%`;
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Tax</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      Tax policies<span class="text-accent">.</span>
    </h1>
  </div>
  {#if canManage}
    <a href="/settings/tax-policies/new" class="btn"> + New policy </a>
  {/if}
</div>

<p class="mt-3 text-sm text-fg/60">
  Named sales-tax rates you can apply to catalog items and individual invoice lines.
</p>

<div class="mt-6">
  <a
    href={data.showArchived ? '/settings/tax-policies' : '/settings/tax-policies?archived=1'}
    class="label hover:text-accent"
  >
    {data.showArchived ? '← Hide archived' : 'Show archived'}
  </a>
</div>

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">
    {data.showArchived ? 'No tax policies yet.' : 'No active tax policies yet.'}
  </p>
{:else}
  <ul class="mt-6 divide-y divide-fg/10 rounded-sm border border-fg/10 bg-surface-2">
    {#each rows as policy (policy.id)}
      <li class="flex items-center justify-between gap-4 px-5 py-4">
        <a
          href="/settings/tax-policies/{policy.id}"
          class="min-w-0 flex-1 transition-colors hover:opacity-70"
        >
          <span class="font-serif text-lg text-fg">{policy.name}</span>
          {#if policy.isDefault}
            <span
              class="ml-2 rounded-sm border border-accent/40 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-accent"
            >
              Default
            </span>
          {/if}
          {#if policy.archivedAt}
            <span
              class="ml-2 rounded-sm border border-fg/15 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-fg/50"
            >
              Archived
            </span>
          {/if}
        </a>
        <span class="label">{ratePct(policy.ratePct)}</span>
        {#if canManage}
          <form method="post" action={policy.archivedAt ? '?/restore' : '?/archive'}>
            <input type="hidden" name="id" value={policy.id} />
            <button
              type="submit"
              class="rounded-sm border border-fg/15 px-2 py-1 font-mono text-xs uppercase tracking-widest text-fg/60 transition-colors hover:border-accent hover:text-accent"
            >
              {policy.archivedAt ? 'Restore' : 'Archive'}
            </button>
          </form>
        {/if}
      </li>
    {/each}
  </ul>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}
