// apps/web/src/routes/(app)/customers/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  const { filters } = $derived(data);
  const anyFilter = $derived(Boolean(filters.q || filters.openInvoices));

  // Seed local state from page 1; untrack() so Svelte doesn't fire the
  // state_referenced_locally warning — capturing the initial value is exactly
  // what we want, and the $effect below re-seeds when load() re-runs.
  type Row = (typeof data.customers)[number];
  let rows = $state<Row[]>(untrack(() => data.customers));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.customers;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<Row>('/customers/more', cursor, {
        q: filters.q,
        openInvoices: filters.openInvoices ? 'true' : '',
      });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Customers</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
      All customers<span class="text-gold-deep">.</span>
    </h1>
  </div>
  <a
    href="/customers/new"
    class="rounded-sm bg-ink px-4 py-2 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
  >
    + New customer
  </a>
</div>

<!-- Filters. Plain GET form so they live in the URL (shareable, back-button
     friendly) and re-run load() with a fresh page 1. -->
<form
  method="GET"
  class="mt-8 flex flex-wrap items-end gap-3 rounded-sm border border-ink/10 bg-cream-warm p-4"
>
  <label class="flex flex-1 flex-col gap-1 text-xs uppercase tracking-widest text-ink/50">
    Search
    <input
      type="search"
      name="q"
      value={filters.q}
      placeholder="Name or email"
      class="min-w-40 rounded-sm border border-ink/15 bg-cream px-2 py-1.5 text-sm normal-case tracking-normal text-ink"
    />
  </label>
  <label class="flex items-center gap-2 py-1.5 text-sm text-ink">
    <input
      type="checkbox"
      name="openInvoices"
      value="true"
      checked={filters.openInvoices}
      class="rounded-sm border-ink/30 text-gold-deep focus:ring-gold-deep"
    />
    Has open invoices
  </label>
  <button
    type="submit"
    class="rounded-sm bg-ink px-4 py-2 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
  >
    Filter
  </button>
  {#if anyFilter}
    <a href="/customers" class="text-sm text-ink/60 hover:text-ink">Clear</a>
  {/if}
</form>

{#if rows.length === 0}
  <p class="mt-8 text-ink/70">
    {anyFilter ? 'No customers match these filters.' : 'No customers yet.'}
  </p>
{:else}
  <ul class="mt-8 divide-y divide-ink/10 rounded-sm border border-ink/10 bg-cream-warm">
    {#each rows as c (c.id)}
      <li>
        <a
          href="/customers/{c.id}"
          class="flex items-center justify-between px-5 py-4 transition-colors hover:bg-cream"
        >
          <span class="font-serif text-lg text-ink">{c.name}</span>
          <span class="font-mono text-xs uppercase tracking-widest text-ink/50">
            {c.email ?? ''}
          </span>
        </a>
      </li>
    {/each}
  </ul>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}

// apps/mobile/src/app/(app)/customers/index.tsx
import { useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../lib/api';
import { pageQuery, usePaginatedList } from '../../../lib/use-paginated-list';

// Mirror of apps/web's /customers list. Account-scoped via x-account-id (the
// API filters by accountId); keyset-paginated with onEndReached infinite scroll.
// usePaginatedList refetches page 1 on focus so a customer created on
// /customers/new shows when we navigate back, and reloads whenever a filter
// flips (fetchPage identity changes). Filters: search (q, name OR email) and
// an "Open invoices" toggle (customers with an issued-but-unpaid invoice).
type CustomerRow = { id: string; name: string; email: string | null };

export default function CustomersList() {
  const router = useRouter();

  const [q, setQ] = useState('');
  const [appliedQ, setAppliedQ] = useState('');
  const [openInvoices, setOpenInvoices] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setAppliedQ(q.trim()), 300);
    return () => clearTimeout(t);
  }, [q]);

  const anyFilter = Boolean(appliedQ || openInvoices);

  const fetchPage = useCallback(
    async (cursor: string | null) => {
      const query: Record<string, string> = pageQuery(cursor);
      if (appliedQ) query.q = appliedQ;
      if (openInvoices) query.openInvoices = 'true';
      const res = await api.api.customers.$get({ query });
      if (!res.ok) return null;
      const { customers, nextCursor } = await res.json();
      return {
        rows: customers.map(
          (c): CustomerRow => ({ id: c.id, name: c.name, email: c.email ?? null }),
        ),
        nextCursor,
      };
    },
    [appliedQ, openInvoices],
  );

  const { list, loadingMore, loadMore } = usePaginatedList(fetchPage);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="flex-row items-end justify-between px-6 pt-6">
        <View>
          <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
            Customers
          </Text>
          <Text className="mt-2 font-serif text-3xl font-light text-ink">All customers</Text>
        </View>
        <Pressable
          onPress={() => router.push('/customers/new')}
          className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
        >
          <Text className="text-sm font-medium text-cream">+ New</Text>
        </Pressable>
      </View>

      <View className="mt-4 flex-row items-center gap-2 px-6">
        <TextInput
          value={q}
          onChangeText={setQ}
          placeholder="Search name or email"
          returnKeyType="search"
          className="flex-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2.5 text-ink"
        />
        <Pressable
          onPress={() => setOpenInvoices((v) => !v)}
          className={`rounded-sm border px-3 py-2.5 ${
            openInvoices ? 'border-ink bg-ink' : 'border-ink/20 bg-cream-warm'
          }`}
        >
          <Text
            className={`font-mono text-xs uppercase tracking-widest ${
              openInvoices ? 'text-cream' : 'text-ink/60'
            }`}
          >
            Open
          </Text>
        </Pressable>
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator color="#0f1626" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load customers.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink/70">
          {anyFilter ? 'No customers match these filters.' : 'No customers yet.'}
        </Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(c) => c.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          keyboardShouldPersistTaps="handled"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator color="#0f1626" />
              </View>
            ) : null
          }
          renderItem={({ item }) => (
            <Pressable
              onPress={() => router.push(`/customers/${item.id}`)}
              className="flex-row items-center justify-between bg-cream-warm px-5 py-4 active:bg-cream"
            >
              <Text className="font-serif text-lg text-ink">{item.name}</Text>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                {item.email ?? ''}
              </Text>
            </Pressable>
          )}
        />
      )}
    </SafeAreaView>
  );
}
