// apps/mobile/src/app/(app)/invoices/[id].tsx
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../lib/api';

// Invoice detail + status actions (mirror of apps/web's /invoices/[id]):
// mark-sent / mark-paid / void / send-by-email, gated by the same state
// machine the API enforces (INVOICE_TRANSITIONS). Edit / duplicate /
// edit-payment / Stripe pay link are deferred to later slices.
type LineItem = {
  position: number;
  description: string;
  quantity: string;
  unitPrice: string;
  amount: string;
};
type Invoice = {
  status: string;
  number: string;
  customerId: string;
  issueDate: string;
  dueDate: string;
  currency: string;
  subtotal: string;
  tax: string | null;
  total: string;
  notes: string | null;
  publicToken: string | null;
  paymentMethod: string | null;
  paymentReference: string | null;
  paidAt: string | null;
  lineItems: LineItem[];
};
type DetailState =
  | { state: 'loading' }
  | { state: 'ready'; invoice: Invoice; customerName: string | null; customerEmail: string | null }
  | { state: 'error' };

const PAYMENT_METHOD_LABELS: Record<string, string> = {
  cash: 'Cash',
  check: 'Check',
  venmo: 'Venmo',
  zelle: 'Zelle',
  stripe: 'Card (Stripe)',
  other: 'Other',
};
const PAID_METHODS = ['cash', 'check', 'venmo', 'zelle', 'other'] as const;

const TRANSITION_ERRORS: Record<string, string> = {
  invalid_transition: 'This invoice can no longer be changed.',
  invalid_recipient: 'Add a customer email or enter one to send.',
  email_not_configured: "Email isn't configured on this server.",
  customer_not_found: 'The customer for this invoice no longer exists.',
};

const apiOrigin = (process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000').replace(/\/$/, '');
const todayIso = () => new Date().toISOString().slice(0, 10);

export default function InvoiceDetail() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [detail, setDetail] = useState<DetailState>({ state: 'loading' });
  const [acting, setActing] = useState(false);
  const [transitionError, setTransitionError] = useState<string | null>(null);
  const [sentTo, setSentTo] = useState<string | null>(null);

  // Send override + mark-paid panel UI state.
  const [showOverride, setShowOverride] = useState(false);
  const [overrideEmail, setOverrideEmail] = useState('');
  const [showPaidPanel, setShowPaidPanel] = useState(false);
  const [paidMethod, setPaidMethod] = useState<(typeof PAID_METHODS)[number]>('cash');
  const [paidReference, setPaidReference] = useState('');
  const [paidOn, setPaidOn] = useState(todayIso());

  const load = useCallback(async () => {
    const res = await api.api.invoices[':id'].$get({ param: { id } });
    if (!res.ok) {
      setDetail({ state: 'error' });
      return;
    }
    const inv = await res.json();
    let customerName: string | null = null;
    let customerEmail: string | null = null;
    const custRes = await api.api.customers[':id'].$get({ param: { id: inv.customerId } });
    if (custRes.ok) {
      const c = await custRes.json();
      customerName = c.name;
      customerEmail = c.email ?? null;
    }
    setDetail({
      state: 'ready',
      customerName,
      customerEmail,
      invoice: {
        status: inv.status,
        number: inv.number,
        customerId: inv.customerId,
        issueDate: inv.issueDate,
        dueDate: inv.dueDate,
        currency: inv.currency,
        subtotal: inv.subtotal,
        tax: inv.tax ?? null,
        total: inv.total,
        notes: inv.notes ?? null,
        publicToken: inv.publicToken ?? null,
        paymentMethod: inv.paymentMethod ?? null,
        paymentReference: inv.paymentReference ?? null,
        paidAt: inv.paidAt ?? null,
        lineItems: inv.lineItems,
      },
    });
  }, [id]);

  useFocusEffect(
    useCallback(() => {
      let active = true;
      load().catch(() => {
        if (active) setDetail({ state: 'error' });
      });
      return () => {
        active = false;
      };
    }, [load]),
  );

  const inv = detail.state === 'ready' ? detail.invoice : null;
  const status = inv?.status;
  const canSend = status === 'draft' || status === 'sent';
  const canMarkSent = status === 'draft';
  const canMarkPaid = status === 'draft' || status === 'sent';
  const canVoid = status === 'draft' || status === 'sent';
  const hasActions = canSend || canMarkSent || canMarkPaid || canVoid;

  // Run a transition, then reload. `onOk` records any success side effect
  // (e.g. the "sent to" banner) before the refresh. The fn returns an hc
  // ClientResponse — typed structurally so RN's FormData/global mismatch on
  // the full Response type doesn't surface here.
  async function act(
    fn: () => Promise<{ ok: boolean; json: () => Promise<unknown> }>,
    onOk?: () => void,
  ) {
    setActing(true);
    setTransitionError(null);
    try {
      const res = await fn();
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        setTransitionError(TRANSITION_ERRORS[body?.error ?? ''] ?? body?.error ?? 'Action failed.');
        return;
      }
      onOk?.();
      await load();
    } catch {
      setTransitionError('Action failed.');
    } finally {
      setActing(false);
    }
  }

  function onSend() {
    const to = showOverride ? overrideEmail.trim() : '';
    const recipient = to || (detail.state === 'ready' ? detail.customerEmail : null);
    act(
      () => api.api.invoices[':id'].send.$post({ param: { id }, json: to ? { to } : {} }),
      () => {
        setSentTo(recipient);
        setShowOverride(false);
      },
    );
  }

  function onMarkPaid() {
    const reference = paidReference.trim();
    act(
      () =>
        api.api.invoices[':id']['mark-paid'].$post({
          param: { id },
          json: { method: paidMethod, reference: reference || undefined, paidOn },
        }),
      () => setShowPaidPanel(false),
    );
  }

  function onVoid() {
    Alert.alert('Void invoice?', 'This cannot be undone.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Void',
        style: 'destructive',
        onPress: () => act(() => api.api.invoices[':id'].void.$post({ param: { id } })),
      },
    ]);
  }

  const publicUrl = inv?.publicToken ? `${apiOrigin}/i/${inv.publicToken}` : null;
  const paidVia =
    inv?.status === 'paid' && inv.paymentMethod
      ? (PAYMENT_METHOD_LABELS[inv.paymentMethod] ?? inv.paymentMethod)
      : null;

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
        <Text
          onPress={() => router.push('/invoices')}
          className="font-mono text-xs uppercase tracking-widest text-ink/60"
        >
          ← Invoices
        </Text>

        {detail.state === 'loading' ? (
          <View className="mt-12 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        ) : detail.state === 'error' || !inv ? (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load this invoice.</Text>
        ) : (
          <>
            <View className="mt-3 flex-row items-center justify-between">
              <Text className="font-serif text-3xl font-light text-ink">{inv.number}</Text>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
                {inv.status}
              </Text>
            </View>

            {transitionError ? (
              <View className="mt-4 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
                <Text className="text-sm text-oxblood">{transitionError}</Text>
              </View>
            ) : null}
            {sentTo ? (
              <View className="mt-4 rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3">
                <Text className="text-sm text-ink">
                  Sent to <Text className="font-medium">{sentTo}</Text>.
                </Text>
              </View>
            ) : null}

            {/* Action toolbar */}
            {hasActions ? (
              <View className="mt-6 space-y-3">
                {canSend ? (
                  <View>
                    {showOverride ? (
                      <TextInput
                        value={overrideEmail}
                        onChangeText={setOverrideEmail}
                        placeholder={detail.customerEmail ?? 'recipient@example.com'}
                        keyboardType="email-address"
                        autoCapitalize="none"
                        className="mb-2 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
                      />
                    ) : null}
                    <View className="flex-row gap-2">
                      <Pressable
                        onPress={onSend}
                        disabled={acting}
                        className="flex-1 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                      >
                        <Text className="text-center text-sm font-medium text-cream">
                          {inv.status === 'sent' ? 'Resend invoice' : 'Send invoice'}
                        </Text>
                      </Pressable>
                      <Pressable
                        onPress={() => setShowOverride((v) => !v)}
                        className="rounded-sm border border-ink/20 px-3 py-3 active:bg-ink/5"
                      >
                        <Text className="font-mono text-xs uppercase tracking-widest text-ink/70">
                          {showOverride ? 'Cancel' : 'To…'}
                        </Text>
                      </Pressable>
                    </View>
                  </View>
                ) : null}

                <View className="flex-row gap-2">
                  {canMarkPaid ? (
                    <Pressable
                      onPress={() => setShowPaidPanel((v) => !v)}
                      disabled={acting}
                      className="flex-1 rounded-sm border border-ink/20 px-4 py-3 active:bg-ink/5 disabled:opacity-50"
                    >
                      <Text className="text-center text-sm font-medium text-ink">Mark paid</Text>
                    </Pressable>
                  ) : null}
                  {canVoid ? (
                    <Pressable
                      onPress={onVoid}
                      disabled={acting}
                      className="flex-1 rounded-sm border border-oxblood/30 px-4 py-3 active:bg-oxblood/5 disabled:opacity-50"
                    >
                      <Text className="text-center text-sm font-medium text-oxblood">Void</Text>
                    </Pressable>
                  ) : null}
                </View>

                {canMarkSent ? (
                  <Pressable
                    onPress={() =>
                      act(() => api.api.invoices[':id']['mark-sent'].$post({ param: { id } }))
                    }
                    disabled={acting}
                  >
                    <Text className="text-xs uppercase tracking-widest text-ink/50">
                      Mark sent without email
                    </Text>
                  </Pressable>
                ) : null}
              </View>
            ) : null}

            {/* Mark-paid panel */}
            {canMarkPaid && showPaidPanel ? (
              <View className="mt-4 rounded-sm border border-ink/15 bg-cream-warm p-4">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  How was it paid?
                </Text>
                <View className="mt-3 flex-row flex-wrap gap-2">
                  {PAID_METHODS.map((m) => (
                    <Pressable
                      key={m}
                      onPress={() => setPaidMethod(m)}
                      className={`rounded-sm border px-3 py-2 ${
                        paidMethod === m ? 'border-gold-deep bg-gold-deep/10' : 'border-ink/20'
                      }`}
                    >
                      <Text className={paidMethod === m ? 'text-ink' : 'text-ink/70'}>
                        {PAYMENT_METHOD_LABELS[m]}
                      </Text>
                    </Pressable>
                  ))}
                </View>
                {paidMethod === 'check' || paidMethod === 'other' ? (
                  <View className="mt-3">
                    <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                      {paidMethod === 'check' ? 'Check number' : 'Note'}
                    </Text>
                    <TextInput
                      value={paidReference}
                      onChangeText={setPaidReference}
                      className="mt-1 rounded-sm border border-ink/15 bg-cream px-3 py-2 text-ink"
                    />
                  </View>
                ) : null}
                <View className="mt-3">
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                    Payment date
                  </Text>
                  <TextInput
                    value={paidOn}
                    onChangeText={setPaidOn}
                    autoCapitalize="none"
                    className="mt-1 rounded-sm border border-ink/15 bg-cream px-3 py-2 text-ink"
                  />
                </View>
                <Pressable
                  onPress={onMarkPaid}
                  disabled={acting}
                  className="mt-4 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                >
                  <Text className="text-center text-sm font-medium text-cream">Confirm paid</Text>
                </Pressable>
              </View>
            ) : null}

            {/* Share link */}
            {publicUrl ? (
              <View className="mt-6 rounded-sm border border-ink/10 bg-cream-warm p-4">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Share link
                </Text>
                <Text className="mt-2 text-sm text-gold-deep">{publicUrl}</Text>
                <Text className="mt-2 text-xs text-ink/50">
                  Anyone with this link can view the invoice.
                </Text>
              </View>
            ) : null}

            {/* Meta */}
            <View className="mt-8 space-y-2">
              <Meta label="Customer" value={detail.customerName ?? '—'} />
              <Meta label="Issued" value={inv.issueDate} />
              <Meta label="Due" value={inv.dueDate} />
              {paidVia ? (
                <Meta
                  label="Paid via"
                  value={paidVia + (inv.paymentReference ? ` · ${inv.paymentReference}` : '')}
                />
              ) : null}
              {inv.status === 'paid' && inv.paidAt ? (
                <Meta label="Paid on" value={inv.paidAt.slice(0, 10)} />
              ) : null}
            </View>

            {/* Line items + totals */}
            <View className="mt-8 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
              {inv.lineItems.map((li) => (
                <View key={li.position} className="border-b border-ink/10 px-4 py-3">
                  <Text className="text-ink">{li.description}</Text>
                  <View className="mt-1 flex-row justify-between">
                    <Text className="font-mono text-xs text-ink/50">
                      {String(Number(li.quantity))} × {li.unitPrice}
                    </Text>
                    <Text className="font-mono tabular-nums text-ink">{li.amount}</Text>
                  </View>
                </View>
              ))}
              <View className="px-4 py-3">
                <Meta label="Subtotal" value={inv.subtotal} mono />
                <View className="mt-1">
                  <Meta label="Tax" value={inv.tax ?? '0.00'} mono />
                </View>
                <View className="mt-2 border-t border-ink/10 pt-2">
                  <Meta label="Total" value={`${inv.currency} ${inv.total}`} mono emphasize />
                </View>
              </View>
            </View>

            {inv.notes ? (
              <View className="mt-6">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Notes
                </Text>
                <Text className="mt-1 text-ink/80">{inv.notes}</Text>
              </View>
            ) : null}
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function Meta({
  label,
  value,
  mono,
  emphasize,
}: {
  label: string;
  value: string;
  mono?: boolean;
  emphasize?: boolean;
}) {
  return (
    <View className="flex-row justify-between">
      <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">{label}</Text>
      <Text
        className={`text-ink ${mono ? 'font-mono tabular-nums' : ''} ${emphasize ? 'text-lg' : ''}`}
      >
        {value}
      </Text>
    </View>
  );
}

// apps/web/src/routes/(app)/invoices/[id]/+page.svelte
<script lang="ts">
  import AuditHistory from '$lib/components/AuditHistory.svelte';
  import PaymentFields from '$lib/components/PaymentFields.svelte';
  import SplitButton from '$lib/components/SplitButton.svelte';
  import { may } from '$lib/perms';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
  const inv = $derived(data.invoice);
  const customer = $derived(data.customer);

  // Role gate (UX only — the API is authoritative). All invoice writes and
  // state actions are `sales:write`; the inline "add business address" shortcut
  // edits the company, so it needs `settings:manage`. Each status gate below is
  // ANDed with canWrite so a viewer/accountant sees no action buttons at all.
  const canWrite = $derived(may(data.role, 'sales:write'));
  const canManageSettings = $derived(may(data.role, 'settings:manage'));

  // Mirrors the API state machine: draft can be sent / paid / voided;
  // sent can be paid / voided; paid and voided are terminal. The buttons
  // disappear on terminal states so the UI doesn't tempt a 409 round-trip.
  // canSend covers both first-send (draft → sent + email) and resend
  // (sent → email only); the API handles the dispatch.
  const canSend = $derived(canWrite && (inv.status === 'draft' || inv.status === 'sent'));
  const canMarkSent = $derived(canWrite && inv.status === 'draft');
  const canMarkPaid = $derived(canWrite && (inv.status === 'draft' || inv.status === 'sent'));
  const canVoid = $derived(canWrite && (inv.status === 'draft' || inv.status === 'sent'));
  // Edit gate matches the API's draft-only rule — once sent/paid/voided the
  // invoice belongs to the audit trail, not the editor.
  const canEdit = $derived(canWrite && inv.status === 'draft');
  const hasActions = $derived(canSend || canMarkSent || canMarkPaid || canVoid);

  // Public share URL is available once mark-sent mints the token. Built
  // server-side off event.url.origin so it works behind any proxy. Shown
  // alongside the email send so the user can also share the link directly.
  const publicUrl = $derived(inv.publicToken ? `${data.origin}/i/${inv.publicToken}` : null);

  // Send-form state: collapsed `to` override field, opens on a click.
  // Default `to` mirrors the customer's email when available.
  let showOverride = $state(false);
  const sendLabel = $derived(inv.status === 'sent' ? 'Resend invoice' : 'Send invoice');

  // How a paid invoice was settled. 'stripe' is the webhook-stamped channel;
  // the rest come from the manual mark-paid picker. Falls back to the raw code
  // for forward-compat if a new method lands before this map is updated.
  const PAYMENT_METHOD_LABELS: Record<string, string> = {
    cash: 'Cash',
    check: 'Check',
    venmo: 'Venmo',
    zelle: 'Zelle',
    stripe: 'Card (Stripe)',
    other: 'Other',
  };
  const paidVia = $derived(
    inv.status === 'paid' && inv.paymentMethod
      ? (PAYMENT_METHOD_LABELS[inv.paymentMethod] ?? inv.paymentMethod)
      : null,
  );

  // Mark-paid disclosure: the toolbar shows a single Mark paid button that
  // reveals a panel, rather than crowding the action row with a select + field.
  // paidMethod drives the conditional check-number input inside the panel.
  const PAID_METHOD_CHOICES = [
    { value: 'cash', label: 'Cash' },
    { value: 'check', label: 'Check' },
    { value: 'venmo', label: 'Venmo' },
    { value: 'zelle', label: 'Zelle' },
    { value: 'other', label: 'Other' },
  ] as const;
  let showPaidPanel = $state(false);
  // Editing the recorded payment on an already-paid invoice — reuses the same
  // PaymentFields, pre-filled. Any date change is an append-only ledger
  // correction handled server-side.
  const canEditPayment = $derived(canWrite && inv.status === 'paid');
  let showEditPayment = $state(false);
</script>

<a href="/invoices" class="eyebrow text-fg/60 hover:text-fg">← Invoices</a>
<div class="mt-3 flex items-baseline justify-between gap-6">
  <h1 class="font-serif text-4xl font-light leading-none tracking-tight text-fg">
    Invoice {inv.number}<span class="text-accent">.</span>
  </h1>
  <div class="flex items-center gap-3">
    {#if canEdit}
      <a
        href="/invoices/{inv.id}/edit"
        class="rounded-sm border border-fg/20 px-3 py-1 font-mono text-xs uppercase tracking-widest text-fg/70 hover:border-accent hover:text-accent"
      >
        Edit
      </a>
    {/if}
    <!-- Duplicate-as-template: available for any status (a paid/sent invoice is
         a common template). Posts to ?/duplicate → new draft's edit page. -->
    {#if canWrite}
      <form method="post" action="?/duplicate">
        <button
          type="submit"
          class="rounded-sm border border-fg/20 px-3 py-1 font-mono text-xs uppercase tracking-widest text-fg/70 hover:border-accent hover:text-accent"
        >
          Duplicate
        </button>
      </form>
    {/if}
    <span class="font-mono text-xs uppercase tracking-widest text-fg/60">{inv.status}</span>
  </div>
</div>

{#if form?.transitionError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.transitionError}
  </div>
{/if}

{#if data.sentTo}
  <div class="mt-6 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg">
    Sent to <span class="font-medium">{data.sentTo}</span>.
  </div>
{/if}

{#if data.needsBusinessDetails && inv.status === 'draft' && data.businessCompanyId && canManageSettings}
  <details class="mt-6 rounded-sm border border-accent/30 bg-accent/5 px-4 py-3 text-sm text-fg">
    <summary class="cursor-pointer list-none font-medium">
      Your business address won't show on this invoice yet.
      <span class="font-mono text-xs uppercase tracking-widest text-accent">Add it →</span>
    </summary>
    <form method="post" action="?/addBusinessDetails" class="mt-4 space-y-4">
      <input type="hidden" name="companyId" value={data.businessCompanyId} />
      <p class="text-fg/70">
        Add it once and it appears on this invoice and every one after. You can skip and send
        without — set it later from Settings → Business.
      </p>
      <label class="block">
        <span class="label">Business address</span>
        <textarea
          name="businessAddress"
          rows="3"
          placeholder="123 Main St&#10;Springfield, IL 62704"
          class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
        ></textarea>
      </label>
      <label class="block">
        <span class="label">Phone (optional)</span>
        <input
          type="tel"
          name="businessPhone"
          placeholder="(555) 123-4567"
          class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
        />
      </label>
      <button
        type="submit"
        class="btn"
      >
        Save &amp; continue
      </button>
    </form>
  </details>
{/if}

{#if hasActions}
  <div class="mt-6 flex flex-wrap items-center gap-3">
    {#if canSend}
      <form method="post" action="?/send" class="flex flex-wrap items-center gap-2">
        {#if showOverride}
          <input
            type="email"
            name="to"
            placeholder={customer?.email ?? 'recipient@example.com'}
            class="rounded-sm border border-fg/20 bg-surface-2 px-3 py-2 text-sm text-fg placeholder:text-fg/40 focus:border-accent focus:outline-none"
          />
        {/if}
        <SplitButton label="Send options" caretClass="border-l border-surface/20 bg-inverse text-on-inverse hover:bg-accent">
          {#snippet primary()}
            <button
              type="submit"
              class="rounded-l-sm bg-inverse px-4 py-2 text-sm font-medium text-on-inverse transition-colors hover:bg-accent"
            >
              {sendLabel}
            </button>
          {/snippet}
          {#snippet menu(close)}
            <button
              type="button"
              role="menuitem"
              onclick={() => {
                showOverride = true;
                close();
              }}
              class="block w-full px-4 py-2 text-left text-sm text-fg/80 transition-colors hover:bg-surface-2 hover:text-fg"
            >
              Send to a different email…
            </button>
          {/snippet}
        </SplitButton>
      </form>
    {/if}
    {#if canMarkPaid}
      <SplitButton label="Payment method" caretClass="border border-fg/20 bg-surface-2 text-fg hover:border-accent hover:text-accent">
        {#snippet primary()}
          <button
            type="button"
            onclick={() => {
              showPaidPanel = !showPaidPanel;
            }}
            class="rounded-l-sm border border-r-0 border-fg/20 bg-surface-2 px-4 py-2 text-sm font-medium text-fg transition-colors hover:border-accent hover:text-accent"
          >
            Mark paid
          </button>
        {/snippet}
        {#snippet menu()}
          <p class="px-4 py-2 font-mono text-xs uppercase tracking-widest text-fg/40">
            Mark paid as…
          </p>
          <!-- Plain POST: the navigation itself dismisses the menu, so we must
               NOT close() on click — removing the form from the DOM first leaves
               it "not connected" and the browser cancels the submit. -->
          {#each PAID_METHOD_CHOICES as choice (choice.value)}
            <form method="post" action="?/markPaid">
              <input type="hidden" name="method" value={choice.value} />
              <button
                type="submit"
                role="menuitem"
                class="block w-full px-4 py-2 text-left text-sm text-fg/80 transition-colors hover:bg-surface-2 hover:text-fg"
              >
                {choice.label}
              </button>
            </form>
          {/each}
        {/snippet}
      </SplitButton>
    {/if}
    {#if canVoid}
      <form method="post" action="?/void">
        <button
          type="submit"
          class="rounded-sm border border-danger/30 px-4 py-2 text-sm font-medium text-danger transition-colors hover:bg-danger/5"
        >
          Void
        </button>
      </form>
    {/if}
  </div>
  {#if canMarkSent}
    <form method="post" action="?/markSent" class="mt-2">
      <button
        type="submit"
        class="text-xs uppercase tracking-widest text-fg/50 hover:text-accent"
      >
        Mark sent without email
      </button>
    </form>
  {/if}

  {#if canMarkPaid && showPaidPanel}
    <form
      method="post"
      action="?/markPaid"
      class="mt-4 max-w-md rounded-sm border border-fg/15 bg-surface-2 p-5"
    >
      <PaymentFields />
      <div class="mt-5 flex items-center gap-3">
        <button
          type="submit"
          class="btn"
        >
          Confirm paid
        </button>
        <button
          type="button"
          onclick={() => {
            showPaidPanel = false;
          }}
          class="text-xs uppercase tracking-widest text-fg/50 hover:text-accent"
        >
          Cancel
        </button>
      </div>
    </form>
  {/if}
{/if}

{#if canEditPayment}
  <div class="mt-6">
    {#if !showEditPayment}
      <button
        type="button"
        onclick={() => {
          showEditPayment = true;
        }}
        class="rounded-sm border border-fg/20 px-3 py-1 font-mono text-xs uppercase tracking-widest text-fg/70 hover:border-accent hover:text-accent"
      >
        Edit payment
      </button>
    {:else}
      <form
        method="post"
        action="?/editPayment"
        class="max-w-md rounded-sm border border-fg/15 bg-surface-2 p-5"
      >
        <PaymentFields
          method={inv.paymentMethod ?? 'cash'}
          reference={inv.paymentReference}
          date={inv.paidAt ? inv.paidAt.slice(0, 10) : undefined}
        />
        <div class="mt-5 flex items-center gap-3">
          <button
            type="submit"
            class="btn"
          >
            Update payment
          </button>
          <button
            type="button"
            onclick={() => {
              showEditPayment = false;
            }}
            class="text-xs uppercase tracking-widest text-fg/50 hover:text-accent"
          >
            Cancel
          </button>
        </div>
      </form>
    {/if}
  </div>
{/if}

{#if publicUrl}
  <div class="mt-6 rounded-sm border border-fg/10 bg-surface-2 p-4">
    <p class="label">Share link</p>
    <div class="mt-2 flex flex-wrap items-center gap-3 text-sm">
      <a href={publicUrl} target="_blank" rel="noopener" class="break-all text-accent hover:underline">
        {publicUrl}
      </a>
    </div>
    <p class="mt-2 text-xs text-fg/50">
      Anyone with this link can view the invoice.
    </p>
  </div>
{/if}

<dl class="mt-8 grid grid-cols-1 gap-x-12 gap-y-6 sm:grid-cols-3">
  <div>
    <dt class="label">Customer</dt>
    <dd class="mt-1 text-fg">
      {#if customer}
        <a href="/customers/{customer.id}" class="hover:text-accent">{customer.name}</a>
      {:else}
        —
      {/if}
    </dd>
  </div>
  <div>
    <dt class="label">Issued</dt>
    <dd class="mt-1 text-fg">{inv.issueDate}</dd>
  </div>
  <div>
    <dt class="label">Due</dt>
    <dd class="mt-1 text-fg">{inv.dueDate}</dd>
  </div>
  {#if paidVia}
    <div>
      <dt class="label">Paid via</dt>
      <dd class="mt-1 text-fg">
        {paidVia}{#if inv.paymentReference} · {inv.paymentReference}{/if}
      </dd>
    </div>
  {/if}
  {#if inv.status === 'paid' && inv.paidAt}
    <div>
      <dt class="label">Paid on</dt>
      <dd class="mt-1 text-fg">{inv.paidAt.slice(0, 10)}</dd>
    </div>
  {/if}
</dl>

<div class="mt-10 overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
  <table class="w-full text-left text-sm">
    <thead class="bg-surface">
      <tr class="label">
        <th class="px-5 py-3">Description</th>
        <th class="px-5 py-3 text-right">Qty</th>
        <th class="px-5 py-3 text-right">Unit price</th>
        <th class="px-5 py-3 text-right">Amount</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-fg/10">
      {#each inv.lineItems as li (li.id)}
        <tr>
          <td class="px-5 py-4 text-fg">{li.description}</td>
          <td class="px-5 py-4 text-right font-mono tabular-nums text-fg/80">{li.quantity}</td>
          <td class="px-5 py-4 text-right font-mono tabular-nums text-fg/80">{li.unitPrice}</td>
          <td class="px-5 py-4 text-right font-mono tabular-nums text-fg">{li.amount}</td>
        </tr>
      {/each}
    </tbody>
    <tfoot class="bg-surface">
      <tr>
        <td colspan="3" class="px-5 py-3 text-right label">
          Subtotal
        </td>
        <td class="px-5 py-3 text-right font-mono tabular-nums text-fg">{inv.subtotal}</td>
      </tr>
      <tr>
        <td colspan="3" class="px-5 py-3 text-right label">
          Tax
        </td>
        <td class="px-5 py-3 text-right font-mono tabular-nums text-fg">{inv.tax}</td>
      </tr>
      <tr>
        <td colspan="3" class="px-5 py-3 text-right label">
          Total ({inv.currency})
        </td>
        <td class="px-5 py-3 text-right font-mono tabular-nums text-lg text-fg">{inv.total}</td>
      </tr>
    </tfoot>
  </table>
</div>

{#if inv.notes}
  <div class="mt-8">
    <h2 class="label">Notes</h2>
    <p class="mt-2 whitespace-pre-wrap text-fg/80">{inv.notes}</p>
  </div>
{/if}

<AuditHistory events={data.auditEvents} />
