// apps/mobile/src/app/(auth)/sign-up.tsx
import { COPY } from '@thalermark/brand';
import { Link, router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Pressable, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { authClient } from '../../lib/auth-client';

export default function SignUp() {
  const { invite } = useLocalSearchParams<{ invite?: string }>();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  async function onSubmit() {
    setError(null);
    setSubmitting(true);
    const result = await authClient.signUp.email({ email, password, name });
    setSubmitting(false);
    if (result.error) {
      setError(result.error.message ?? 'Sign-up failed');
      return;
    }
    if (invite) {
      router.replace({ pathname: '/accept-invite', params: { token: invite } });
    } else {
      router.replace('/');
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream">
      <View className="flex-1 justify-center px-6">
        <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
          Get early access
        </Text>
        <Text className="mt-3 font-serif text-3xl font-light text-ink">{COPY.signUp.title}</Text>

        <View className="mt-8 space-y-5">
          <View>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">Name</Text>
            <TextInput
              value={name}
              onChangeText={setName}
              autoComplete="name"
              className="mt-2 border-b border-ink/30 py-2 text-ink"
            />
          </View>
          <View>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">Email</Text>
            <TextInput
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              autoComplete="email"
              inputMode="email"
              keyboardType="email-address"
              className="mt-2 border-b border-ink/30 py-2 text-ink"
            />
          </View>
          <View>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
              Password
            </Text>
            <TextInput
              value={password}
              onChangeText={setPassword}
              secureTextEntry
              autoComplete="new-password"
              className="mt-2 border-b border-ink/30 py-2 text-ink"
            />
          </View>
          {error ? (
            <Text className="font-mono text-xs uppercase tracking-widest text-oxblood">
              {error}
            </Text>
          ) : null}
          <Pressable
            onPress={onSubmit}
            disabled={submitting}
            className="mt-2 rounded-sm bg-ink px-3 py-3 active:bg-gold-deep disabled:opacity-50"
          >
            {submitting ? (
              <ActivityIndicator color="#f4ede0" />
            ) : (
              <Text className="text-center text-sm font-medium text-cream">
                {COPY.signUp.submit}
              </Text>
            )}
          </Pressable>
        </View>

        <View className="mt-8 flex-row justify-center">
          <Text className="text-sm text-ink/70">Already have an account? </Text>
          <Link
            href={invite ? { pathname: '/sign-in', params: { invite } } : '/sign-in'}
            className="text-sm text-gold-deep underline"
          >
            Sign in
          </Link>
        </View>

        <View className="mt-10 flex-row justify-center">
          <Link href="/server" className="font-mono text-xs uppercase tracking-widest text-ink/50">
            Advanced
          </Link>
        </View>
      </View>
    </SafeAreaView>
  );
}

// apps/web/src/routes/(auth)/sign-up/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { authClient } from '$lib/auth-client';
  import { COPY } from '@thalermark/brand';

  let name = $state('');
  let email = $state('');
  let password = $state('');
  let error = $state<string | null>(null);
  let submitting = $state(false);

  const inviteToken = $derived(page.url.searchParams.get('invite'));
  const postAuthPath = $derived(
    inviteToken ? `/accept-invite?token=${encodeURIComponent(inviteToken)}` : '/',
  );
  const signInHref = $derived(inviteToken ? `/sign-in?invite=${encodeURIComponent(inviteToken)}` : '/sign-in');

  async function onSubmit(event: SubmitEvent) {
    event.preventDefault();
    error = null;
    submitting = true;
    const result = await authClient.signUp.email({ email, password, name });
    submitting = false;
    if (result.error) {
      error = result.error.message ?? 'Sign-up failed';
      return;
    }
    // Hard nav: forces hooks.server.ts to re-run on a fresh request so the
    // new session + membership routing applies. See sign-in for context.
    window.location.assign(postAuthPath);
  }
</script>

<h2 class="mb-4 text-lg font-medium text-primary-900">{COPY.signUp.title}</h2>

<form onsubmit={onSubmit} class="space-y-4">
  <label class="block">
    <span class="block text-sm text-primary-700">Name</span>
    <input
      type="text"
      required
      bind:value={name}
      class="mt-1 w-full rounded border border-primary-300 px-3 py-2"
    />
  </label>
  <label class="block">
    <span class="block text-sm text-primary-700">Email</span>
    <input
      type="email"
      required
      bind:value={email}
      class="mt-1 w-full rounded border border-primary-300 px-3 py-2"
    />
  </label>
  <label class="block">
    <span class="block text-sm text-primary-700">Password</span>
    <input
      type="password"
      required
      minlength={8}
      bind:value={password}
      class="mt-1 w-full rounded border border-primary-300 px-3 py-2"
    />
  </label>
  {#if error}
    <p class="text-sm text-red-600">{error}</p>
  {/if}
  <button
    type="submit"
    disabled={submitting}
    class="w-full rounded bg-primary-900 px-3 py-2 text-white disabled:opacity-50"
  >
    {COPY.signUp.submit}
  </button>
</form>

<p class="mt-4 text-center text-sm text-primary-600">
  Already have an account? <a href={signInHref} class="underline">Sign in</a>
</p>
