// apps/mobile/src/app/(app)/jobs/index.tsx
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MetricStrip } from '../../../components/MetricStrip';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../lib/use-paginated-list';

// Mirror of apps/web's /jobs list. Open jobs by default — a closed job is filed
// away, and the point of closing one is that it stops cluttering the pickers.
type JobRow = {
  id: string;
  name: string;
  status: string;
  contactName: string | null;
  startedOn: string | null;
  endedOn: string | null;
  readyToBill: string;
  unratedMinutes: number;
};

type JobSummary = {
  open: number;
  closed: number;
  readyToBill: string;
  readyToBillOnClosed: string;
  jobsWithMoneyWaiting: number;
  unratedMinutes: number;
  unratedHours: string;
};

type StatusFilter = 'open' | 'closed' | 'all';

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

function dateRange(startedOn: string | null, endedOn: string | null): string {
  if (startedOn && endedOn) return `${startedOn} → ${endedOn}`;
  if (startedOn) return `Started ${startedOn}`;
  if (endedOn) return `Ended ${endedOn}`;
  return '';
}

export default function JobsList() {
  const router = useRouter();
  const canCreate = useMay('sales:write');

  const [status, setStatus] = useState<StatusFilter>('open');
  const [q, setQ] = useState('');
  const [appliedQ, setAppliedQ] = useState('');
  const [summary, setSummary] = useState<JobSummary | null>(null);

  useEffect(() => {
    const t = setTimeout(() => setAppliedQ(q.trim()), 300);
    return () => clearTimeout(t);
  }, [q]);

  // Refreshed on focus so billing a job on another screen is reflected when you
  // come back. Best-effort: a failure hides the strip rather than the list.
  useFocusEffect(
    useCallback(() => {
      let active = true;
      api.api.jobs.summary
        .$get({ query: {} })
        .then(async (res) => {
          if (active && res.ok) setSummary((await res.json()) as JobSummary);
        })
        .catch(() => {});
      return () => {
        active = false;
      };
    }, []),
  );

  const fetchPage = useCallback(
    async (cursor: string | null) => {
      const query: Record<string, string> = pageQuery(cursor);
      if (status !== 'all') query.status = status;
      if (appliedQ) query.q = appliedQ;
      const res = await api.api.jobs.$get({ query });
      if (!res.ok) return null;
      const { jobs, nextCursor } = await res.json();
      return {
        rows: jobs.map(
          (j): JobRow => ({
            id: j.id,
            name: j.name,
            status: j.status,
            contactName: j.contactName,
            startedOn: j.startedOn,
            endedOn: j.endedOn,
            readyToBill: j.readyToBill,
            unratedMinutes: j.unratedMinutes,
          }),
        ),
        nextCursor,
      };
    },
    [status, appliedQ],
  );

  const { list, loadingMore, loadMore } = usePaginatedList(fetchPage);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="flex-row items-end justify-between px-6 pt-6">
        <View>
          <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">Jobs</Text>
          <Text className="mt-2 font-serif text-3xl font-light text-ink">All jobs</Text>
        </View>
        {canCreate ? (
          <Pressable
            onPress={() => router.push('/jobs/new')}
            className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
          >
            <Text className="text-sm font-medium text-cream">+ New</Text>
          </Pressable>
        ) : null}
      </View>

      {summary ? (
        <View className="mt-4 px-6">
          {/*
            Same four questions as web. "Needs a rate" and money parked on closed
            jobs both carry `alert`: hours nobody priced cannot be billed, and a
            closed job takes its unbilled work out of the default list with it.
          */}
          <MetricStrip
            tiles={[
              {
                label: 'Open',
                value: summary.open,
                onPress: () => setStatus('open'),
                active: status === 'open',
              },
              {
                label: 'Closed',
                value: summary.closed,
                onPress: () => setStatus('closed'),
                active: status === 'closed',
              },
              {
                label: 'Ready to bill',
                value: fmt(summary.readyToBill),
                sub:
                  Number(summary.readyToBillOnClosed) > 0
                    ? `${fmt(summary.readyToBillOnClosed)} on closed`
                    : summary.jobsWithMoneyWaiting > 0
                      ? `across ${summary.jobsWithMoneyWaiting} ${summary.jobsWithMoneyWaiting === 1 ? 'job' : 'jobs'}`
                      : 'nothing waiting',
                // Shows every job, because money parked on a closed one is
                // otherwise invisible from the default view.
                onPress: () => setStatus('all'),
                alert: Number(summary.readyToBillOnClosed) > 0,
              },
              {
                label: 'Needs a rate',
                value: summary.unratedMinutes > 0 ? `${summary.unratedHours} h` : '—',
                sub: summary.unratedMinutes > 0 ? "can't be billed yet" : 'all hours priced',
                onPress: () => setStatus('all'),
                alert: summary.unratedMinutes > 0,
              },
            ]}
          />
        </View>
      ) : null}

      <View className="mt-4 px-6">
        <TextInput
          value={q}
          onChangeText={setQ}
          placeholder="Search job name"
          returnKeyType="search"
          className="rounded-sm border border-ink/15 bg-cream-warm px-3 py-2.5 text-ink"
        />
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator color="#0f1626" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load jobs.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink/70">
          {appliedQ
            ? 'No jobs match that search.'
            : status === 'closed'
              ? 'No closed jobs.'
              : 'No open jobs.'}
        </Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(j) => j.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          keyboardShouldPersistTaps="handled"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator color="#0f1626" />
              </View>
            ) : null
          }
          renderItem={({ item }) => (
            <Pressable
              onPress={() => router.push(`/jobs/${item.id}`)}
              className="flex-row items-center justify-between bg-cream-warm px-5 py-4 active:bg-cream"
            >
              <View className="flex-1 pr-3">
                <Text className="font-serif text-lg text-ink">{item.name}</Text>
                <Text className="mt-0.5 text-xs text-ink/50">
                  {item.contactName ?? ''}
                  {item.status === 'closed' ? ' · closed' : ''}
                </Text>
              </View>
              {/*
                Gold only when something is actually waiting, so the column reads
                as a prompt rather than a data dump. Unpriced work gets its own
                words — $0.00 there would read as "nothing to bill".
              */}
              {Number(item.readyToBill) > 0 ? (
                <Text className="font-mono text-sm text-gold-deep">
                  {fmt(item.readyToBill)} ready
                </Text>
              ) : item.unratedMinutes > 0 ? (
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  needs a rate
                </Text>
              ) : (
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  {dateRange(item.startedOn, item.endedOn)}
                </Text>
              )}
            </Pressable>
          )}
        />
      )}
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/jobs/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import MetricStrip from '$lib/components/MetricStrip.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  const filters = $derived(data.filters);
  const summary = $derived(data.summary);

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  // Same untrack() seed-and-re-seed pattern as /items and /contacts: load()
  // re-runs whenever a filter changes, and the $effect keeps the list in sync.
  type Row = (typeof data.jobs)[number];
  let rows = $state<Row[]>(untrack(() => data.jobs));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.jobs;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<Row>('/jobs/more', cursor, {
        status: filters.status,
        q: filters.q,
      });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }

  // The questions in the order they get asked: what is live, what is finished,
  // how much money is sitting there, and what is stopping the rest from being
  // billed.
  //
  // "Needs a rate" is the actionable one and the reason it earns a tile at all:
  // a job full of unpriced hours looks identical to a job with nothing to bill,
  // so it carries `alert` — the same treatment overdue invoices get.
  const strip = $derived(
    summary
      ? [
          {
            label: 'Open',
            value: summary.open,
            href: '/jobs?status=open',
            active: filters.status === 'open',
          },
          {
            label: 'Closed',
            value: summary.closed,
            href: '/jobs?status=closed',
            active: filters.status === 'closed',
          },
          {
            label: 'Ready to bill',
            value: fmt(summary.readyToBill),
            // Money sitting on CLOSED jobs is called out, because the default
            // list shows open ones: without this the headline can read $191
            // while everything visible adds to $60, and the difference looks
            // like a bug rather than money parked somewhere else. The tile links
            // to every job so the number is always reachable.
            sub:
              Number(summary.readyToBillOnClosed) > 0
                ? `${fmt(summary.readyToBillOnClosed)} on closed jobs`
                : summary.jobsWithMoneyWaiting > 0
                  ? `across ${summary.jobsWithMoneyWaiting} ${summary.jobsWithMoneyWaiting === 1 ? 'job' : 'jobs'}`
                  : 'nothing waiting',
            href: '/jobs?status=all',
            alert: Number(summary.readyToBillOnClosed) > 0,
          },
          {
            label: 'Needs a rate',
            value: summary.unratedMinutes > 0 ? `${summary.unratedHours} h` : '—',
            sub: summary.unratedMinutes > 0 ? "can't be billed yet" : 'all hours priced',
            href: '/jobs?status=all',
            alert: summary.unratedMinutes > 0,
          },
        ]
      : [],
  );

  function dateRange(startedOn: string | null, endedOn: string | null): string {
    if (startedOn && endedOn) return `${startedOn} → ${endedOn}`;
    if (startedOn) return `Started ${startedOn}`;
    if (endedOn) return `Ended ${endedOn}`;
    return '';
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Jobs</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      All jobs<span class="text-accent">.</span>
    </h1>
  </div>
  {#if may(data.role, 'sales:write')}
    <a href="/jobs/new" class="btn"> + New job </a>
  {/if}
</div>

<p class="mt-3 text-sm text-fg/60">
  A job is whatever you'd call it out loud — “the Smith job”, “Tuesdays at the Chens”. Log hours
  against it, tag what you bought for it, and bill it as many times as you need.
</p>

{#if strip.length > 0}
  <div class="mt-8">
    <MetricStrip tiles={strip} />
  </div>
{/if}

<!-- Filters. Plain GET form so they live in the URL (shareable, back-button
     friendly) and re-run load() with a fresh page 1 — mirrors /invoices. -->
<form
  method="GET"
  class="mt-8 flex flex-wrap items-end gap-3 rounded-sm border border-fg/10 bg-surface-2 p-4"
>
  <label class="flex flex-1 flex-col gap-1 text-xs uppercase tracking-widest text-fg/50">
    Search
    <input
      type="search"
      name="q"
      value={filters.q}
      placeholder="Job name"
      class="min-w-40 rounded-sm border border-fg/15 bg-surface px-2 py-1.5 text-sm normal-case tracking-normal text-fg"
    />
  </label>
  <label class="flex flex-col gap-1 text-xs uppercase tracking-widest text-fg/50">
    Status
    <select
      name="status"
      onchange={(e) => e.currentTarget.form?.requestSubmit()}
      class="rounded-sm border border-fg/15 bg-surface px-2 py-1.5 text-sm normal-case tracking-normal text-fg"
    >
      <option value="open" selected={filters.status === 'open'}>Open</option>
      <option value="closed" selected={filters.status === 'closed'}>Closed</option>
      <option value="all" selected={filters.status === 'all'}>All</option>
    </select>
  </label>
  <button type="submit" class="btn">Filter</button>
</form>

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">
    {filters.q
      ? 'No jobs match that search.'
      : filters.status === 'closed'
        ? 'No closed jobs.'
        : 'No open jobs.'}
  </p>
{:else}
  <ul class="mt-6 divide-y divide-fg/10 rounded-sm border border-fg/10 bg-surface-2">
    {#each rows as job (job.id)}
      <li>
        <a
          href="/jobs/{job.id}"
          class="flex items-center justify-between gap-4 px-5 py-4 transition-colors hover:opacity-70"
        >
          <span class="min-w-0 flex-1">
            <span class="font-serif text-lg text-fg">{job.name}</span>
            {#if job.contactName}
              <span class="ml-2 text-sm text-fg/50">{job.contactName}</span>
            {/if}
            {#if job.status === 'closed'}
              <span
                class="ml-2 rounded-sm border border-fg/15 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-fg/50"
              >
                Closed
              </span>
            {/if}
          </span>
          <!--
            What this job could invoice right now. Gold only when there is
            something, so the column reads as a prompt rather than a data dump.
            The unrated case gets its own words: $0.00 beside a day of unpriced
            work would read as "nothing to bill" when there is plenty.
          -->
          <span class="shrink-0 text-right">
            {#if Number(job.readyToBill) > 0}
              <span class="font-mono tabular-nums text-accent">{fmt(job.readyToBill)} ready</span>
            {:else if job.unratedMinutes > 0}
              <span class="label">needs a rate</span>
            {:else}
              <span class="label">{dateRange(job.startedOn, job.endedOn)}</span>
            {/if}
          </span>
        </a>
      </li>
    {/each}
  </ul>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}
