// apps/mobile/src/app/(app)/more/accounts.tsx
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';

// Mirror of apps/web's /settings/accounts (TMC-207) — the places this business's
// money sits.
//
// The user adds the bank account and card they actually have. That these become
// chart-of-accounts rows, and that a card is a liability while checking is an
// asset, is the system's business and appears nowhere on this screen.
//
// Not paginated: the endpoint returns the whole (small) set, because every
// picker in the app reads the same list and a cursor would buy nothing.

type MoneyAccount = {
  id: string;
  code: string;
  name: string;
  kind: string | null;
  isActive: boolean;
  balance: string;
};

type Kind = 'checking' | 'savings' | 'cash' | 'credit_card';

// The words the user picks between. Never "asset" or "liability" — those are
// what the system derives from this choice, not what anyone is asked.
const KINDS: { value: Kind; label: string; hint: string }[] = [
  { value: 'checking', label: 'Checking', hint: 'A business current account' },
  { value: 'savings', label: 'Savings', hint: 'Money set aside' },
  { value: 'cash', label: 'Cash', hint: 'A till, a cash box, an envelope in the truck' },
  { value: 'credit_card', label: 'Credit card', hint: 'Spend now, pay the statement later' },
];

const KIND_LABEL: Record<string, string> = {
  checking: 'Checking',
  savings: 'Savings',
  cash: 'Cash',
  credit_card: 'Credit card',
};

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

// A card's stored balance is credit-normal, so it comes back negative when money
// is owed. Owing $150 reads as "$150 owed", never "-$150".
function balanceLabel(kind: string | null, balance: string): string {
  const n = Number(balance);
  if (kind === 'credit_card') {
    return n === 0 ? 'Nothing owed' : `${fmt(Math.abs(n).toFixed(2))} owed`;
  }
  return fmt(balance);
}

export default function AccountsScreen() {
  const router = useRouter();
  const canManage = useMay('settings:manage');
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [accounts, setAccounts] = useState<MoneyAccount[] | null>(null);
  const [showArchived, setShowArchived] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [adding, setAdding] = useState(false);
  const [newName, setNewName] = useState('');
  const [newKind, setNewKind] = useState<Kind>('checking');
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState('');

  const load = useCallback(
    async (active: () => boolean) => {
      const compRes = await api.api.companies.$get().catch(() => null);
      if (!active() || !compRes?.ok) return;
      const { companies } = await compRes.json();
      const id = (await pickActiveCompany(companies))?.id ?? null;
      if (!active()) return;
      setCompanyId(id);
      if (!id) {
        setAccounts([]);
        return;
      }
      const query: Record<string, string> = { companyId: id };
      if (showArchived) query.includeArchived = 'true';
      const res = await api.api['money-accounts'].$get({ query }).catch(() => null);
      if (!active()) return;
      setAccounts(res?.ok ? ((await res.json()).moneyAccounts as MoneyAccount[]) : []);
    },
    [showArchived],
  );

  useFocusEffect(
    useCallback(() => {
      let alive = true;
      load(() => alive);
      return () => {
        alive = false;
      };
    }, [load]),
  );

  async function create() {
    if (!companyId || newName.trim().length === 0) return;
    setBusy(true);
    setError(null);
    try {
      const res = await api.api['money-accounts'].$post({
        json: { companyId, name: newName.trim(), kind: newKind },
      });
      if (res.ok) {
        setNewName('');
        setAdding(false);
        await load(() => true);
      } else {
        setError("That account couldn't be added. Try again.");
      }
    } catch {
      setError("That account couldn't be added. Try again.");
    } finally {
      setBusy(false);
    }
  }

  async function rename(id: string) {
    if (renameValue.trim().length === 0) return;
    setBusy(true);
    try {
      const res = await api.api['money-accounts'][':id'].$patch({
        param: { id },
        json: { name: renameValue.trim() },
      });
      if (res.ok) {
        setRenamingId(null);
        await load(() => true);
      }
    } catch {
      // A focus refetch will reconcile.
    } finally {
      setBusy(false);
    }
  }

  async function toggleArchive(a: MoneyAccount) {
    setBusy(true);
    setError(null);
    try {
      const res = a.isActive
        ? await api.api['money-accounts'][':id'].archive.$post({ param: { id: a.id } })
        : await api.api['money-accounts'][':id'].restore.$post({ param: { id: a.id } });
      if (res.ok) {
        await load(() => true);
      } else if (res.status === 409) {
        // The primary is the fallback every unset money column resolves to.
        setError("That's your main account — it can't be archived.");
      }
    } catch {
      // A focus refetch will reconcile.
    } finally {
      setBusy(false);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <Pressable onPress={() => router.push('/more')}>
          <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
            ← More
          </Text>
        </Pressable>

        <Text className="mt-3 font-serif text-3xl font-light text-ink">Accounts</Text>
        <Text className="mt-2 text-sm text-ink-subtle">
          Every place your money sits — the bank account you get paid into, the card you fill the
          truck with, the cash box.
        </Text>

        {error ? <Text className="mt-4 text-sm text-oxblood">{error}</Text> : null}

        {canManage && companyId ? (
          <Pressable
            onPress={() => setAdding((v) => !v)}
            className="mt-5 self-start rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
          >
            <Text className="text-sm font-medium text-cream">
              {adding ? 'Cancel' : '+ Add account'}
            </Text>
          </Pressable>
        ) : null}

        {adding ? (
          <View className="mt-4 rounded-sm border border-ink/15 bg-cream-warm p-4">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Name
            </Text>
            <TextInput
              value={newName}
              onChangeText={setNewName}
              placeholder="Chase Business Checking"
              className="mt-2 rounded-sm border border-field bg-cream px-3 py-2.5 text-ink"
            />
            <Text className="mt-4 font-mono text-xs uppercase tracking-widest text-ink-subtle">
              What kind of account is it?
            </Text>
            <View className="mt-2 gap-2">
              {KINDS.map((k) => (
                <Pressable
                  key={k.value}
                  onPress={() => setNewKind(k.value)}
                  className={`rounded-sm border px-3 py-2.5 ${
                    newKind === k.value
                      ? 'border-gold-deep bg-gold-deep/5'
                      : 'border-ink/15 bg-cream'
                  }`}
                >
                  <Text className="text-sm text-ink">{k.label}</Text>
                  <Text className="text-xs text-ink-subtle">{k.hint}</Text>
                </Pressable>
              ))}
            </View>
            <Pressable
              onPress={create}
              disabled={busy || newName.trim().length === 0}
              className="mt-4 self-start rounded-sm bg-ink px-4 py-2 active:bg-gold-deep disabled:opacity-50"
            >
              <Text className="text-sm font-medium text-cream">Add account</Text>
            </Pressable>
            {/*
              No starting-balance field, matching web: two ways to inject a
              starting figure would be two sources of truth for the same equity.
            */}
            <Text className="mt-3 text-xs text-ink-subtle">
              Already got money in this account? Add it afterwards under My Money.
            </Text>
          </View>
        ) : null}

        <Pressable onPress={() => setShowArchived((s) => !s)} className="mt-5 self-start">
          <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
            {showArchived ? '← Hide archived' : 'Show archived'}
          </Text>
        </Pressable>

        {accounts === null ? (
          <View className="mt-10 items-center">
            <ActivityIndicator className="text-ink" />
          </View>
        ) : accounts.length === 0 ? (
          <Text className="mt-8 text-ink-muted">No accounts yet.</Text>
        ) : (
          <View className="mt-5 overflow-hidden rounded-sm border border-ink/10">
            {accounts.map((a, i) => (
              <View
                key={a.id}
                className={`bg-cream-warm px-4 py-4 ${i > 0 ? 'border-t border-ink/10' : ''}`}
              >
                {renamingId === a.id ? (
                  <View>
                    <TextInput
                      value={renameValue}
                      onChangeText={setRenameValue}
                      className="rounded-sm border border-field bg-cream px-3 py-2 text-ink"
                    />
                    <View className="mt-3 flex-row gap-2">
                      <Pressable
                        onPress={() => rename(a.id)}
                        disabled={busy}
                        className="rounded-sm bg-ink px-3 py-1.5 active:bg-gold-deep disabled:opacity-50"
                      >
                        <Text className="text-sm font-medium text-cream">Save</Text>
                      </Pressable>
                      <Pressable
                        onPress={() => setRenamingId(null)}
                        className="rounded-sm border border-ink/20 px-3 py-1.5"
                      >
                        <Text className="text-sm text-ink-muted">Cancel</Text>
                      </Pressable>
                    </View>
                  </View>
                ) : (
                  <View>
                    <View className="flex-row flex-wrap items-center gap-2">
                      <Text className="font-serif text-lg text-ink">{a.name}</Text>
                      {!a.isActive ? (
                        <Text className="rounded-sm border border-ink/15 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-ink-subtle">
                          Archived
                        </Text>
                      ) : null}
                    </View>
                    <Text className="mt-0.5 text-xs text-ink-subtle">
                      {KIND_LABEL[a.kind ?? ''] ?? ''}
                    </Text>
                    <Text className="mt-1 font-mono text-sm text-ink/80">
                      {balanceLabel(a.kind, a.balance)}
                    </Text>
                    {canManage ? (
                      <View className="mt-3 flex-row gap-2">
                        <Pressable
                          onPress={() => {
                            setRenamingId(a.id);
                            setRenameValue(a.name);
                          }}
                          className="rounded-sm border border-ink/20 px-3 py-1.5 active:border-gold-deep"
                        >
                          <Text className="font-mono text-xs uppercase tracking-widest text-ink-muted">
                            Rename
                          </Text>
                        </Pressable>
                        <Pressable
                          onPress={() => toggleArchive(a)}
                          disabled={busy}
                          className="rounded-sm border border-ink/20 px-3 py-1.5 active:border-gold-deep disabled:opacity-50"
                        >
                          <Text className="font-mono text-xs uppercase tracking-widest text-ink-muted">
                            {a.isActive ? 'Archive' : 'Restore'}
                          </Text>
                        </Pressable>
                      </View>
                    ) : null}
                  </View>
                )}
              </View>
            ))}
          </View>
        )}

        {accounts && accounts.length > 0 ? (
          <Text className="mt-4 text-xs text-ink-subtle">
            Archiving takes an account out of the pickers. It stays on your books with whatever
            balance it holds — nothing you've already recorded changes.
          </Text>
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/settings/accounts/+page.svelte
<script lang="ts">
  import { may } from '$lib/perms';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  const canManage = $derived(may(data.role, 'settings:manage'));
  const accounts = $derived(data.moneyAccounts);

  // The words the user picks between. Never "asset" or "liability" — those are
  // what the system derives from this choice, not what anyone is asked.
  const KINDS: { value: string; label: string; hint: string }[] = [
    { value: 'checking', label: 'Checking', hint: 'A business current account' },
    { value: 'savings', label: 'Savings', hint: 'Money set aside' },
    { value: 'cash', label: 'Cash', hint: 'A till, a cash box, an envelope in the truck' },
    { value: 'credit_card', label: 'Credit card', hint: 'Spend now, pay the statement later' },
  ];

  const KIND_LABEL: Record<string, string> = {
    checking: 'Checking',
    savings: 'Savings',
    cash: 'Cash',
    credit_card: 'Credit card',
  };

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  // A card's stored balance is credit-normal, so it comes back negative when
  // money is owed. Owing $150 reads as "$150 owed", never "-$150".
  function balanceLabel(kind: string, balance: string): string {
    const n = Number(balance);
    if (kind === 'credit_card') {
      if (n === 0) return 'Nothing owed';
      return `${fmt(Math.abs(n).toFixed(2))} owed`;
    }
    return fmt(balance);
  }

  let renaming = $state<string | null>(null);
  let adding = $state(false);
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Settings</span>
    <h1 class="mt-2 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      Accounts<span class="text-accent">.</span>
    </h1>
  </div>
  {#if canManage && data.companyId}
    <button type="button" class="btn" onclick={() => (adding = !adding)}>
      {adding ? 'Cancel' : '+ Add account'}
    </button>
  {/if}
</div>

<p class="mt-3 max-w-2xl text-sm text-fg/60">
  Every place your money sits — the bank account you get paid into, the card you fill the truck
  with, the cash box. Once an account is here you can say which one a payment came from or landed
  in.
</p>

{#if form?.actionError}
  <p class="mt-4 text-sm text-danger">{form.actionError}</p>
{/if}

{#if adding && data.companyId}
  <form method="post" action="?/create" class="mt-6 rounded-sm border border-fg/15 bg-surface-2 p-5">
    <input type="hidden" name="companyId" value={data.companyId} />
    <label class="block">
      <span class="label">Name</span>
      <input
        name="name"
        required
        maxlength="200"
        placeholder="Chase Business Checking"
        class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
      />
      <span class="mt-1 block text-xs text-fg/50">
        Call it whatever you call it. This is the name you'll see when picking.
      </span>
    </label>

    <fieldset class="mt-5">
      <legend class="label">What kind of account is it?</legend>
      <div class="mt-2 grid gap-2 sm:grid-cols-2">
        {#each KINDS as k (k.value)}
          <label
            class="flex cursor-pointer items-start gap-3 rounded-sm border border-fg/15 bg-surface px-3 py-2.5 hover:border-accent"
          >
            <input
              type="radio"
              name="kind"
              value={k.value}
              required
              class="mt-1 border-fg/30 text-accent focus:ring-accent"
            />
            <span>
              <span class="block text-sm text-fg">{k.label}</span>
              <span class="block text-xs text-fg/50">{k.hint}</span>
            </span>
          </label>
        {/each}
      </div>
    </fieldset>

    <div class="mt-5 flex items-center gap-3">
      <button type="submit" class="btn">Add account</button>
      <button type="button" class="text-sm text-fg/60 hover:text-fg" onclick={() => (adding = false)}>
        Cancel
      </button>
    </div>

    <!--
      Deliberately no "starting balance" field. Two ways to inject a starting
      figure would be two sources of truth for the same equity; the two that
      already exist are the right ones.
    -->
    <p class="mt-4 max-w-xl text-xs text-fg/50">
      Already got money in this account? Add it afterwards under <a class="link" href="/owner-money"
        >My Money</a
      >, or — if you're moving over from another system mid-year — through the starting balances in
      <a class="link" href="/settings/business">Business</a>.
    </p>
  </form>
{/if}

<div class="mt-6">
  <a
    href={data.showArchived ? '/settings/accounts' : '/settings/accounts?archived=1'}
    class="label hover:text-accent"
  >
    {data.showArchived ? '← Hide archived' : 'Show archived'}
  </a>
</div>

{#if accounts.length === 0}
  <p class="mt-8 text-fg/70">No accounts yet.</p>
{:else}
  <ul class="mt-6 divide-y divide-fg/10 rounded-sm border border-fg/10 bg-surface-2">
    {#each accounts as a (a.id)}
      <li class="px-5 py-4">
        {#if renaming === a.id}
          <form method="post" action="?/rename" class="flex flex-wrap items-center gap-3">
            <input type="hidden" name="id" value={a.id} />
            <input
              name="name"
              value={a.name}
              required
              maxlength="200"
              class="min-w-60 flex-1 rounded-sm border border-fg/20 bg-surface px-3 py-1.5 text-sm text-fg focus:border-accent focus:outline-none"
            />
            <button type="submit" class="btn">Save</button>
            <button
              type="button"
              class="text-sm text-fg/60 hover:text-fg"
              onclick={() => (renaming = null)}
            >
              Cancel
            </button>
          </form>
        {:else}
          <div class="flex flex-wrap items-center justify-between gap-4">
            <div class="min-w-0">
              <span class="font-serif text-lg text-fg">{a.name}</span>
              {#if !a.isActive}
                <span
                  class="ml-2 rounded-sm border border-fg/15 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-fg/50"
                >
                  Archived
                </span>
              {/if}
              <span class="mt-0.5 block text-xs text-fg/50">{KIND_LABEL[a.kind ?? ''] ?? ''}</span>
            </div>
            <span class="font-mono text-sm tabular-nums text-fg/80">
              {balanceLabel(a.kind ?? '', a.balance)}
            </span>
            {#if canManage}
              <div class="flex items-center gap-2">
                <button
                  type="button"
                  class="rounded-sm border border-fg/15 px-2 py-1 font-mono text-xs uppercase tracking-widest text-fg/60 transition-colors hover:border-accent hover:text-accent"
                  onclick={() => (renaming = a.id)}
                >
                  Rename
                </button>
                <form method="post" action={a.isActive ? '?/archive' : '?/restore'}>
                  <input type="hidden" name="id" value={a.id} />
                  <button
                    type="submit"
                    class="rounded-sm border border-fg/15 px-2 py-1 font-mono text-xs uppercase tracking-widest text-fg/60 transition-colors hover:border-accent hover:text-accent"
                  >
                    {a.isActive ? 'Archive' : 'Restore'}
                  </button>
                </form>
              </div>
            {/if}
          </div>
        {/if}
      </li>
    {/each}
  </ul>
  <p class="mt-4 max-w-2xl text-xs text-fg/50">
    Archiving takes an account out of the pickers. It stays on your books with whatever balance it
    holds — nothing you've already recorded changes.
  </p>
{/if}
