// apps/mobile/src/app/(app)/bills/aging.tsx
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';

// AP aging — open bills bucketed by how far past due they are (the payable
// mirror of the A/R aging report). Mirror of apps/web's /bills/aging. The report
// is company-scoped (the API requires companyId), so it resolves the active
// company first.
type Bucket = 'current' | 'd1_30' | 'd31_60' | 'd61_90' | 'd90_plus';
type Aging = {
  asOf: string;
  buckets: Record<Bucket, string>;
  total: string;
  bills: {
    id: string;
    vendorName: string;
    reference: string | null;
    dueDate: string;
    amount: string;
    daysOverdue: number;
    bucket: string;
  }[];
};
type ViewState = { state: 'loading' } | { state: 'ready'; aging: Aging } | { state: 'error' };

const BUCKETS: { key: Bucket; label: string }[] = [
  { key: 'current', label: 'Current' },
  { key: 'd1_30', label: '1–30 days' },
  { key: 'd31_60', label: '31–60 days' },
  { key: 'd61_90', label: '61–90 days' },
  { key: 'd90_plus', label: '90+ days' },
];

const BUCKET_LABEL: Record<string, string> = {
  current: 'Current',
  d1_30: '1–30',
  d31_60: '31–60',
  d61_90: '61–90',
  d90_plus: '90+',
};

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

export default function BillsAging() {
  const router = useRouter();
  const [view, setView] = useState<ViewState>({ state: 'loading' });

  useFocusEffect(
    useCallback(() => {
      let active = true;
      (async () => {
        const compRes = await api.api.companies.$get();
        if (!active) return;
        if (!compRes.ok) {
          setView({ state: 'error' });
          return;
        }
        const { companies } = await compRes.json();
        const company = await pickActiveCompany(companies);
        if (!company) {
          setView({ state: 'error' });
          return;
        }
        const res = await api.api.bills.aging.$get({ query: { companyId: company.id } });
        if (!active) return;
        if (!res.ok) {
          setView({ state: 'error' });
          return;
        }
        setView({ state: 'ready', aging: (await res.json()) as Aging });
      })().catch(() => {
        if (active) setView({ state: 'error' });
      });
      return () => {
        active = false;
      };
    }, []),
  );

  const aging = view.state === 'ready' ? view.aging : null;

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <Pressable onPress={() => router.push('/bills')}>
          <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">← Bills</Text>
        </Pressable>

        <View className="mt-3 flex-row items-end justify-between">
          <Text className="font-serif text-3xl font-light text-ink">Who to pay first</Text>
          {aging ? (
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
              as of {aging.asOf}
            </Text>
          ) : null}
        </View>

        {view.state === 'loading' ? (
          <View className="mt-12 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        ) : view.state === 'error' || !aging ? (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load the aging report.</Text>
        ) : (
          <>
            <View className="mt-8 gap-3">
              {BUCKETS.map((b) => (
                <View
                  key={b.key}
                  className="flex-row items-center justify-between rounded-sm border border-ink/10 bg-cream-warm px-4 py-3"
                >
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                    {b.label}
                  </Text>
                  <Text className="font-serif text-lg font-light tabular-nums text-ink">
                    {fmt(aging.buckets[b.key])}
                  </Text>
                </View>
              ))}
              <View className="flex-row items-center justify-between rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
                  Total
                </Text>
                <Text className="font-serif text-lg font-light tabular-nums text-ink">
                  {fmt(aging.total)}
                </Text>
              </View>
            </View>

            {aging.bills.length === 0 ? (
              <Text className="mt-8 text-ink/70">No open bills — nothing outstanding.</Text>
            ) : (
              <View className="mt-8 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
                {aging.bills.map((b) => (
                  <Pressable
                    key={b.id}
                    onPress={() => router.push(`/bills/${b.id}`)}
                    className="border-b border-ink/10 px-4 py-3 active:bg-cream"
                  >
                    <View className="flex-row items-center justify-between">
                      <Text className="flex-1 pr-3 font-serif text-ink" numberOfLines={1}>
                        {b.vendorName}
                        {b.reference ? (
                          <Text className="font-mono text-xs text-ink/40"> #{b.reference}</Text>
                        ) : null}
                      </Text>
                      <Text className="font-mono tabular-nums text-ink">{fmt(b.amount)}</Text>
                    </View>
                    <Text className="mt-1 font-mono text-xs uppercase tracking-widest text-ink/50">
                      due {b.dueDate} · {BUCKET_LABEL[b.bucket] ?? b.bucket}
                      {b.daysOverdue > 0 ? ` · ${b.daysOverdue}d` : ''}
                    </Text>
                  </Pressable>
                ))}
              </View>
            )}
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/bills/aging/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  const aging = $derived(data.aging);

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  const BUCKETS = [
    { key: 'current', label: 'Current' },
    { key: 'd1_30', label: '1–30 days' },
    { key: 'd31_60', label: '31–60 days' },
    { key: 'd61_90', label: '61–90 days' },
    { key: 'd90_plus', label: '90+ days' },
  ] as const;

  const bucketLabel: Record<string, string> = {
    current: 'Current',
    d1_30: '1–30',
    d31_60: '31–60',
    d61_90: '61–90',
    d90_plus: '90+',
  };
</script>

<a href="/bills" class="eyebrow text-fg/60 hover:text-fg">← Bills</a>
<div class="mt-3 flex flex-wrap items-baseline justify-between gap-4">
  <h1 class="font-serif text-4xl font-light leading-none tracking-tight text-fg">
    AP aging<span class="text-accent">.</span>
  </h1>
  <span class="font-mono text-xs uppercase tracking-widest text-fg/50">as of {aging.asOf}</span>
</div>

<dl class="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
  {#each BUCKETS as b (b.key)}
    <div class="rounded-sm border border-fg/10 bg-surface-2 p-4">
      <dt class="label">{b.label}</dt>
      <dd class="mt-1 font-serif text-xl font-light tabular-nums text-fg">{fmt(aging.buckets[b.key])}</dd>
    </div>
  {/each}
  <div class="rounded-sm border border-accent/30 bg-accent/5 p-4">
    <dt class="label">Total</dt>
    <dd class="mt-1 font-serif text-xl font-light tabular-nums text-fg">{fmt(aging.total)}</dd>
  </div>
</dl>

{#if aging.bills.length === 0}
  <p class="mt-8 text-fg/70">No open bills — nothing outstanding.</p>
{:else}
  <div class="mt-8 overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
    <table class="w-full text-left text-sm">
      <thead class="bg-surface">
        <tr class="label">
          <th class="px-5 py-3">Vendor</th>
          <th class="px-5 py-3">Due</th>
          <th class="px-5 py-3">Age</th>
          <th class="px-5 py-3 text-right">Amount</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-fg/10">
        {#each aging.bills as b (b.id)}
          <tr class="hover:bg-surface">
            <td class="px-5 py-4">
              <a href="/bills/{b.id}" class="font-serif text-fg hover:text-accent">{b.vendorName}</a>
              {#if b.reference}
                <span class="ml-2 font-mono text-xs text-fg/40">#{b.reference}</span>
              {/if}
            </td>
            <td class="px-5 py-4 font-mono tabular-nums text-fg/80">{b.dueDate}</td>
            <td class="px-5 py-4 text-fg/70">
              {bucketLabel[b.bucket] ?? b.bucket}
              {#if b.daysOverdue > 0}
                <span class="text-fg/40">· {b.daysOverdue}d</span>
              {/if}
            </td>
            <td class="px-5 py-4 text-right font-mono tabular-nums text-fg">{fmt(b.amount)}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}
