// apps/web/src/routes/(app)/settings/business/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  // Show the just-saved value back after an action, else the stored value from
  // load. Empty string renders as a cleared field. `??` respects a returned
  // `false` flag (only null/undefined falls through to the stored default).
  const address = $derived(form?.businessAddress ?? data.company.businessAddress ?? '');
  const phone = $derived(form?.businessPhone ?? data.company.businessPhone ?? '');
  const email = $derived(form?.businessEmail ?? data.company.businessEmail ?? '');
  // Reply-to is saved by its own action (?/saveReplyTo) with distinct
  // replyToSaved/replyToError flags, so saving it doesn't trip the contact
  // form's "Saved." and vice-versa.
  const replyTo = $derived(form?.replyToEmail ?? data.company.replyToEmail ?? '');
  // Accounting method — stored as cash/accrual, offered in plain words. Cash is
  // the column default and what effectively every sole proprietor files.
  const accountingMethod = $derived(data.company.accountingMethod ?? 'cash');
  // First-year share of a "spread it out" purchase. Half-year is the IRS
  // default and the column default; full_year exists only as an accountant's
  // override for an asset already being depreciated that way elsewhere.
  const depreciationConvention = $derived(data.company.depreciationConvention ?? 'half_year');
  // Reporting timezone. Stored value wins; the browser's zone is only offered
  // as a one-click suggestion when the two disagree, so we never silently
  // change which period someone's figures land in.
  const timezone = $derived(data.company.timezone ?? 'UTC');
  // null = "no local pick yet", so the select follows the stored value —
  // including after a save reloads it. Any user choice takes over from there.
  let picked = $state<string | null>(null);
  const currentTimezone = $derived(picked ?? timezone);
  const detected =
    typeof Intl !== 'undefined' ? Intl.DateTimeFormat().resolvedOptions().timeZone : '';
  const suggestDetected = $derived(!!detected && detected !== currentTimezone);
  // Per-field show defaults, split by document type (invoice vs estimate).
  const showAddressInvoice = $derived(
    form?.showAddressOnInvoice ?? data.company.showAddressOnInvoice ?? true,
  );
  const showPhoneInvoice = $derived(
    form?.showPhoneOnInvoice ?? data.company.showPhoneOnInvoice ?? true,
  );
  const showEmailInvoice = $derived(
    form?.showEmailOnInvoice ?? data.company.showEmailOnInvoice ?? true,
  );
  const showAddressEstimate = $derived(
    form?.showAddressOnEstimate ?? data.company.showAddressOnEstimate ?? true,
  );
  const showPhoneEstimate = $derived(
    form?.showPhoneOnEstimate ?? data.company.showPhoneOnEstimate ?? true,
  );
  const showEmailEstimate = $derived(
    form?.showEmailOnEstimate ?? data.company.showEmailOnEstimate ?? true,
  );
</script>

<h1 class="font-serif text-4xl font-light leading-none tracking-tight text-fg">
  Business<span class="text-accent">.</span>
</h1>

<section class="mt-8 rounded-sm border border-fg/15 bg-surface-2">
  <header class="border-b border-fg/10 px-6 py-5">
    <span class="eyebrow">Address &amp; contact</span>
    <p class="mt-2 font-serif text-lg text-fg">{data.company.name}</p>
  </header>
  <form method="POST" action="?/save" class="px-6 py-7">
    <input type="hidden" name="companyId" value={data.company.id} />
    <p class="max-w-prose text-sm leading-relaxed text-fg/70">
      These show in the &ldquo;from&rdquo; block on the invoices and estimates your contacts see,
      under your business name. The checkboxes set the default for new documents &mdash; you can
      still change it on any individual invoice or estimate. Leave a field blank to omit it entirely.
    </p>

    <div class="mt-8 space-y-8">
      <div>
        <label for="businessAddress" class="label block">Business address</label>
        <textarea
          id="businessAddress"
          name="businessAddress"
          rows="3"
          placeholder="123 Main St&#10;Springfield, IL 62704"
          class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
          >{address}</textarea
        >
        <div class="mt-3 flex flex-wrap gap-x-6 gap-y-2">
          <label class="flex items-center gap-2 text-sm text-fg/70">
            <input
              type="checkbox"
              name="showAddressOnInvoice"
              checked={showAddressInvoice}
              class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
            />
            Show on invoices
          </label>
          <label class="flex items-center gap-2 text-sm text-fg/70">
            <input
              type="checkbox"
              name="showAddressOnEstimate"
              checked={showAddressEstimate}
              class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
            />
            Show on estimates
          </label>
        </div>
      </div>

      <div>
        <label for="businessPhone" class="label block">Phone</label>
        <input
          id="businessPhone"
          type="tel"
          name="businessPhone"
          value={phone}
          placeholder="(555) 123-4567"
          class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
        />
        <div class="mt-3 flex flex-wrap gap-x-6 gap-y-2">
          <label class="flex items-center gap-2 text-sm text-fg/70">
            <input
              type="checkbox"
              name="showPhoneOnInvoice"
              checked={showPhoneInvoice}
              class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
            />
            Show on invoices
          </label>
          <label class="flex items-center gap-2 text-sm text-fg/70">
            <input
              type="checkbox"
              name="showPhoneOnEstimate"
              checked={showPhoneEstimate}
              class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
            />
            Show on estimates
          </label>
        </div>
      </div>

      <div>
        <label for="businessEmail" class="label block">Email</label>
        <input
          id="businessEmail"
          type="email"
          name="businessEmail"
          value={email}
          placeholder="hello@yourbusiness.com"
          class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
        />
        <div class="mt-3 flex flex-wrap gap-x-6 gap-y-2">
          <label class="flex items-center gap-2 text-sm text-fg/70">
            <input
              type="checkbox"
              name="showEmailOnInvoice"
              checked={showEmailInvoice}
              class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
            />
            Show on invoices
          </label>
          <label class="flex items-center gap-2 text-sm text-fg/70">
            <input
              type="checkbox"
              name="showEmailOnEstimate"
              checked={showEmailEstimate}
              class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
            />
            Show on estimates
          </label>
        </div>
      </div>
    </div>

    <div class="mt-8 flex items-center gap-4">
      <button
        type="submit"
        class="btn"
      >
        Save
      </button>
      {#if form?.saved}
        <span class="text-sm text-fg/60">Saved.</span>
      {:else if form?.error}
        <span class="text-sm text-danger">Couldn't save: {form.error}</span>
      {/if}
    </div>
  </form>
</section>

<section class="mt-8 rounded-sm border border-fg/15 bg-surface-2">
  <header class="border-b border-fg/10 px-6 py-5">
    <span class="eyebrow">Your time zone</span>
    <p class="mt-2 font-serif text-lg text-fg">{data.company.name}</p>
  </header>
  <form method="POST" action="?/saveTimezone" class="px-6 py-6">
    <input type="hidden" name="companyId" value={data.company.id} />
    <p class="max-w-prose text-sm leading-relaxed text-fg/70">
      Reports count a day from midnight where you are. Get this wrong and a payment taken on the
      evening of 31 December can land in the wrong tax year.
    </p>
    <label class="mt-5 block">
      <span class="label">Time zone</span>
      <select
        name="timezone"
        value={currentTimezone}
        onchange={(e) => {
          picked = e.currentTarget.value;
        }}
        class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
      >
        {#each data.timezones as tz (tz)}
          <option value={tz}>{tz}</option>
        {/each}
      </select>
    </label>
    {#if suggestDetected}
      <p class="mt-3 text-sm text-fg/70">
        This browser looks like <strong>{detected}</strong>.
        <button
          type="button"
          class="link"
          onclick={() => {
            picked = detected;
          }}
        >
          Use that instead
        </button>
      </p>
    {/if}
    <div class="mt-5 flex items-center gap-4">
      <button type="submit" class="btn">Save</button>
      {#if form?.timezoneSaved}
        <span class="text-sm text-fg/60">Saved.</span>
      {:else if form?.timezoneError}
        <span class="text-sm text-danger">Couldn't save: {form.timezoneError}</span>
      {/if}
    </div>
  </form>
</section>

<section class="mt-8 rounded-sm border border-fg/15 bg-surface-2">
  <header class="border-b border-fg/10 px-6 py-5">
    <span class="eyebrow">When you count income</span>
    <p class="mt-2 font-serif text-lg text-fg">{data.company.name}</p>
  </header>
  <form method="POST" action="?/saveAccountingMethod" class="px-6 py-6">
    <input type="hidden" name="companyId" value={data.company.id} />
    <p class="max-w-prose text-sm leading-relaxed text-fg/70">
      This decides which year money lands in on your Schedule C worksheet. Most people count income
      when they get paid — that's the usual choice for freelancers and trades. Only change this if
      whoever files your taxes told you to; switching methods with the IRS isn't something you do
      casually.
    </p>
    <div class="mt-5 space-y-3">
      <label class="flex items-start gap-3">
        <input
          type="radio"
          name="accountingMethod"
          value="cash"
          checked={accountingMethod === 'cash'}
          class="mt-1"
        />
        <span>
          <span class="block text-sm text-fg">When you get paid</span>
          <span class="block text-xs text-fg/60">
            An invoice you sent in December but got paid for in January counts as January's income.
            Most common.
          </span>
        </span>
      </label>
      <label class="flex items-start gap-3">
        <input
          type="radio"
          name="accountingMethod"
          value="accrual"
          checked={accountingMethod === 'accrual'}
          class="mt-1"
        />
        <span>
          <span class="block text-sm text-fg">When you send the invoice</span>
          <span class="block text-xs text-fg/60">
            That same invoice counts as December's income, even though the money arrived later.
          </span>
        </span>
      </label>
    </div>
    <div class="mt-5 flex items-center gap-4">
      <button type="submit" class="btn">Save</button>
      {#if form?.accountingSaved}
        <span class="text-sm text-fg/60">Saved.</span>
      {:else if form?.accountingError}
        <span class="text-sm text-danger">Couldn't save: {form.accountingError}</span>
      {/if}
    </div>
  </form>
</section>

<section class="mt-8 rounded-sm border border-fg/15 bg-surface-2">
  <header class="border-b border-fg/10 px-6 py-5">
    <span class="eyebrow">Big purchases, first year</span>
    <p class="mt-2 font-serif text-lg text-fg">{data.company.name}</p>
  </header>
  <form method="POST" action="?/saveDepreciationConvention" class="px-6 py-6">
    <input type="hidden" name="companyId" value={data.company.id} />
    <p class="max-w-prose text-sm leading-relaxed text-fg/70">
      When you buy something big and choose to spread the cost out, this decides how much of it
      counts in the year you bought it. The standard answer is half — the IRS treats anything you
      buy as though you bought it mid-year, whether that was January or December. Only change this
      if whoever files your taxes told you to.
    </p>
    <div class="mt-5 space-y-3">
      <label class="flex items-start gap-3">
        <input
          type="radio"
          name="depreciationConvention"
          value="half_year"
          checked={depreciationConvention === 'half_year'}
          class="mt-1"
        />
        <span>
          <span class="block text-sm text-fg">Half the usual amount</span>
          <span class="block text-xs text-fg/60">
            A $3,600 mower over five years counts about $360 the year you buy it, then about $720 a
            year, with the last half landing in a sixth year. Standard.
          </span>
        </span>
      </label>
      <label class="flex items-start gap-3">
        <input
          type="radio"
          name="depreciationConvention"
          value="full_year"
          checked={depreciationConvention === 'full_year'}
          class="mt-1"
        />
        <span>
          <span class="block text-sm text-fg">The full amount</span>
          <span class="block text-xs text-fg/60">
            That same mower counts about $720 every year for five years, starting the year you buy
            it. Pick this only to match how an accountant is already handling it.
          </span>
        </span>
      </label>
    </div>
    <p class="mt-4 max-w-prose text-xs leading-relaxed text-fg/50">
      Changing this only affects years that haven't been counted yet — anything already on the books
      stays as it was recorded.
    </p>
    <div class="mt-5 flex items-center gap-4">
      <button type="submit" class="btn">Save</button>
      {#if form?.depreciationSaved}
        <span class="text-sm text-fg/60">Saved.</span>
      {:else if form?.depreciationError}
        <span class="text-sm text-danger">Couldn't save: {form.depreciationError}</span>
      {/if}
    </div>
  </form>
</section>

<section class="mt-8 rounded-sm border border-fg/15 bg-surface-2">
  <header class="border-b border-fg/10 px-6 py-5">
    <span class="eyebrow">Reply-to address</span>
    <p class="mt-2 font-serif text-lg text-fg">{data.company.name}</p>
  </header>
  <form method="POST" action="?/saveReplyTo" class="px-6 py-6">
    <input type="hidden" name="companyId" value={data.company.id} />
    <p class="max-w-prose text-sm leading-relaxed text-fg/70">
      Invoices and estimates go out under your business name, but from Thalermark's sending address.
      Set a reply-to so when a contact hits "reply," it reaches you. Leave it blank to send with no
      reply-to.
    </p>
    <label class="mt-5 block">
      <span class="label">Reply-to email</span>
      <input
        type="email"
        name="replyToEmail"
        value={replyTo}
        placeholder="you@yourbusiness.com"
        class="mt-2 w-full max-w-md rounded-sm border border-fg/20 bg-surface px-3 py-2 text-sm text-fg focus:border-accent focus:outline-none"
      />
    </label>
    <div class="mt-5 flex items-center gap-4">
      <button type="submit" class="btn">Save</button>
      {#if form?.replyToSaved}
        <span class="text-sm text-fg/60">Saved.</span>
      {:else if form?.replyToError}
        <span class="text-sm text-danger">Couldn't save: {form.replyToError}</span>
      {/if}
    </div>
  </form>
</section>

<section class="mt-8 rounded-sm border border-fg/15 bg-surface-2">
  <header class="border-b border-fg/10 px-6 py-5">
    <span class="eyebrow">Logo</span>
    <p class="mt-2 text-sm text-fg/70">
      Shown on the invoices and estimates your contacts see. PNG, JPEG, or WebP, up to 2&nbsp;MB.
    </p>
  </header>
  <div class="px-6 py-6">
    {#if data.logo}
      <img
        src={data.logo.url}
        alt="Current logo"
        class="max-h-24 max-w-[16rem] rounded-sm border border-fg/10 bg-surface object-contain p-2"
      />
      <form method="POST" action="?/removeLogo" class="mt-4">
        <input type="hidden" name="companyId" value={data.company.id} />
        <button
          type="submit"
          class="rounded-sm border border-fg/20 px-3 py-1.5 text-sm text-fg/70 transition-colors hover:border-danger/40 hover:text-danger"
        >
          Remove logo
        </button>
      </form>
    {:else}
      <p class="text-sm text-fg/50">No logo yet.</p>
    {/if}

    <form
      method="POST"
      action="?/uploadLogo"
      enctype="multipart/form-data"
      class="mt-5 flex flex-wrap items-center gap-3"
    >
      <input type="hidden" name="companyId" value={data.company.id} />
      <input
        type="file"
        name="logo"
        accept="image/png,image/jpeg,image/webp"
        class="text-sm text-fg/70 file:mr-3 file:rounded-sm file:border-0 file:bg-inverse file:px-3 file:py-1.5 file:text-sm file:font-medium file:text-on-inverse hover:file:bg-accent"
      />
      <button
        type="submit"
        class="btn"
      >
        {data.logo ? 'Replace' : 'Upload'}
      </button>
    </form>
    {#if form?.logoError}
      <p class="mt-3 text-sm text-danger">{form.logoError}</p>
    {/if}
  </div>
</section>

// apps/mobile/src/app/(app)/more/business.tsx
import * as ImagePicker from 'expo-image-picker';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  Image,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Checkbox } from '../../../components/Checkbox';
import { api } from '../../../lib/api';
import { getServerUrl } from '../../../lib/server-url';
import { uploadLogo } from '../../../lib/upload';

// Business identity settings — native mirror of apps/web's /settings/business.
// Address / phone / email (shown on invoices + estimates) via company PATCH,
// each with separate per-document-type "show on" defaults, plus the logo: a
// signed-URL preview with image-picker upload/replace and remove.
type Company = {
  id: string;
  name: string;
  businessAddress: string | null;
  businessPhone: string | null;
  businessEmail: string | null;
  replyToEmail: string | null;
  accountingMethod: string;
  depreciationConvention: string;
  timezone: string;
  showAddressOnInvoice: boolean;
  showPhoneOnInvoice: boolean;
  showEmailOnInvoice: boolean;
  showAddressOnEstimate: boolean;
  showPhoneOnEstimate: boolean;
  showEmailOnEstimate: boolean;
};
type Logo = { url: string; contentType: string };
type LoadState =
  | { state: 'loading' }
  | { state: 'ready'; company: Company; logo: Logo | null }
  | { state: 'error' };

const LOGO_ERRORS: Record<string, string> = {
  unsupported_media_type: 'Logo must be a PNG, JPEG, or WebP.',
  file_too_large: 'Logo must be under 2 MB.',
  storage_not_configured: 'Logo storage is not configured on this server.',
};

const absolutize = (url: string) => (url.startsWith('http') ? url : `${getServerUrl()}${url}`);

// The device's own IANA zone, used only as a one-tap suggestion — never applied
// silently, since it would change which period a user's figures land in. Guarded
// because Hermes' Intl surface has varied across Expo SDKs.
function deviceZone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone ?? '';
  } catch {
    return '';
  }
}

export default function BusinessSettings() {
  const router = useRouter();
  const [load, setLoad] = useState<LoadState>({ state: 'loading' });
  const [address, setAddress] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  // Reply-to has its own card + save (separate concern from the invoice "from"
  // block above it), so it carries its own saving/status state.
  const [replyTo, setReplyTo] = useState('');
  const [replySaving, setReplySaving] = useState(false);
  const [replyStatus, setReplyStatus] = useState<'idle' | 'saved' | 'error'>('idle');
  // Accounting method + timezone each get their own card and save. Both quietly
  // change which period figures land in, so neither should ride along with an
  // address edit.
  const [method, setMethod] = useState<'cash' | 'accrual'>('cash');
  const [methodSaving, setMethodSaving] = useState(false);
  const [methodStatus, setMethodStatus] = useState<'idle' | 'saved' | 'error'>('idle');
  const [convention, setConvention] = useState<'half_year' | 'full_year'>('half_year');
  const [conventionSaving, setConventionSaving] = useState(false);
  const [conventionStatus, setConventionStatus] = useState<'idle' | 'saved' | 'error'>('idle');
  const [timezone, setTimezone] = useState('UTC');
  const deviceTimezone = deviceZone();
  const [tzSaving, setTzSaving] = useState(false);
  const [tzStatus, setTzStatus] = useState<'idle' | 'saved' | 'error'>('idle');
  // Per-field "show on" defaults, split by document type (invoice vs estimate).
  const [showAddrInv, setShowAddrInv] = useState(true);
  const [showPhoneInv, setShowPhoneInv] = useState(true);
  const [showEmailInv, setShowEmailInv] = useState(true);
  const [showAddrEst, setShowAddrEst] = useState(true);
  const [showPhoneEst, setShowPhoneEst] = useState(true);
  const [showEmailEst, setShowEmailEst] = useState(true);
  const [saving, setSaving] = useState(false);
  const [status, setStatus] = useState<'idle' | 'saved' | 'error'>('idle');
  const [logoBusy, setLogoBusy] = useState(false);
  const [logoError, setLogoError] = useState<string | null>(null);

  const fetchCompany = useCallback(async (active: () => boolean) => {
    const res = await api.api.companies.$get();
    if (!active()) return;
    if (!res.ok) {
      setLoad({ state: 'error' });
      return;
    }
    const company = (await res.json()).companies[0];
    if (!company) {
      setLoad({ state: 'error' });
      return;
    }
    // Signed logo URL — best-effort; a 404 (no logo) renders the empty state.
    let logo: Logo | null = null;
    const logoRes = await api.api.companies[':id'].logo.$get({ param: { id: company.id } });
    if (active() && logoRes.ok) logo = (await logoRes.json()) as Logo;
    if (!active()) return;
    setLoad({
      state: 'ready',
      company: {
        id: company.id,
        name: company.name,
        businessAddress: company.businessAddress,
        businessPhone: company.businessPhone,
        businessEmail: company.businessEmail,
        replyToEmail: company.replyToEmail,
        accountingMethod: company.accountingMethod,
        depreciationConvention: company.depreciationConvention,
        timezone: company.timezone,
        showAddressOnInvoice: company.showAddressOnInvoice,
        showPhoneOnInvoice: company.showPhoneOnInvoice,
        showEmailOnInvoice: company.showEmailOnInvoice,
        showAddressOnEstimate: company.showAddressOnEstimate,
        showPhoneOnEstimate: company.showPhoneOnEstimate,
        showEmailOnEstimate: company.showEmailOnEstimate,
      },
      logo,
    });
    setAddress(company.businessAddress ?? '');
    setPhone(company.businessPhone ?? '');
    setEmail(company.businessEmail ?? '');
    setReplyTo(company.replyToEmail ?? '');
    setMethod(company.accountingMethod === 'accrual' ? 'accrual' : 'cash');
    setConvention(company.depreciationConvention === 'full_year' ? 'full_year' : 'half_year');
    setTimezone(company.timezone ?? 'UTC');
    setShowAddrInv(company.showAddressOnInvoice);
    setShowPhoneInv(company.showPhoneOnInvoice);
    setShowEmailInv(company.showEmailOnInvoice);
    setShowAddrEst(company.showAddressOnEstimate);
    setShowPhoneEst(company.showPhoneOnEstimate);
    setShowEmailEst(company.showEmailOnEstimate);
  }, []);

  useFocusEffect(
    useCallback(() => {
      let alive = true;
      fetchCompany(() => alive).catch(() => {
        if (alive) setLoad({ state: 'error' });
      });
      return () => {
        alive = false;
      };
    }, [fetchCompany]),
  );

  const company = load.state === 'ready' ? load.company : null;
  const logo = load.state === 'ready' ? load.logo : null;

  async function onSave() {
    if (!company) return;
    setSaving(true);
    setStatus('idle');
    try {
      const res = await api.api.companies[':id'].$patch({
        param: { id: company.id },
        json: {
          businessAddress: address.trim(),
          businessPhone: phone.trim(),
          businessEmail: email.trim(),
          showAddressOnInvoice: showAddrInv,
          showPhoneOnInvoice: showPhoneInv,
          showEmailOnInvoice: showEmailInv,
          showAddressOnEstimate: showAddrEst,
          showPhoneOnEstimate: showPhoneEst,
          showEmailOnEstimate: showEmailEst,
        },
      });
      setStatus(res.ok ? 'saved' : 'error');
    } catch {
      setStatus('error');
    } finally {
      setSaving(false);
    }
  }

  async function onSaveReplyTo() {
    if (!company) return;
    setReplySaving(true);
    setReplyStatus('idle');
    try {
      const res = await api.api.companies[':id'].$patch({
        param: { id: company.id },
        json: { replyToEmail: replyTo.trim() },
      });
      setReplyStatus(res.ok ? 'saved' : 'error');
    } catch {
      setReplyStatus('error');
    } finally {
      setReplySaving(false);
    }
  }

  async function onSaveMethod(next: 'cash' | 'accrual') {
    if (!company) return;
    setMethod(next);
    setMethodSaving(true);
    setMethodStatus('idle');
    try {
      const res = await api.api.companies[':id'].$patch({
        param: { id: company.id },
        json: { accountingMethod: next },
      });
      setMethodStatus(res.ok ? 'saved' : 'error');
    } catch {
      setMethodStatus('error');
    } finally {
      setMethodSaving(false);
    }
  }

  async function onSaveConvention(next: 'half_year' | 'full_year') {
    if (!company) return;
    setConvention(next);
    setConventionSaving(true);
    setConventionStatus('idle');
    try {
      const res = await api.api.companies[':id'].$patch({
        param: { id: company.id },
        json: { depreciationConvention: next },
      });
      setConventionStatus(res.ok ? 'saved' : 'error');
    } catch {
      setConventionStatus('error');
    } finally {
      setConventionSaving(false);
    }
  }

  async function onSaveTimezone(next: string) {
    if (!company) return;
    setTzSaving(true);
    setTzStatus('idle');
    try {
      const res = await api.api.companies[':id'].$patch({
        param: { id: company.id },
        json: { timezone: next },
      });
      if (res.ok) {
        setTimezone(next);
        setTzStatus('saved');
      } else {
        setTzStatus('error');
      }
    } catch {
      setTzStatus('error');
    } finally {
      setTzSaving(false);
    }
  }

  async function onPickLogo() {
    if (!company) return;
    setLogoError(null);
    const perm = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!perm.granted) {
      setLogoError('Photo access denied.');
      return;
    }
    const result = await ImagePicker.launchImageLibraryAsync({
      quality: 0.9,
      mediaTypes: ['images'],
    });
    if (result.canceled || !result.assets[0]) return;

    setLogoBusy(true);
    try {
      const up = await uploadLogo(company.id, result.assets[0]);
      if (!up.ok) {
        setLogoError(LOGO_ERRORS[up.error] ?? 'Upload failed. Try again.');
        return;
      }
      await fetchCompany(() => true);
    } finally {
      setLogoBusy(false);
    }
  }

  async function onRemoveLogo() {
    if (!company) return;
    setLogoError(null);
    setLogoBusy(true);
    try {
      const res = await api.api.companies[':id'].logo.$delete({ param: { id: company.id } });
      if (!res.ok) {
        setLogoError('Could not remove the logo.');
        return;
      }
      await fetchCompany(() => true);
    } finally {
      setLogoBusy(false);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
        <Text
          onPress={() => router.push('/more')}
          className="font-mono text-xs uppercase tracking-widest text-ink/60"
        >
          ← More
        </Text>
        <Text className="mt-3 font-serif text-3xl font-light text-ink">Business</Text>

        {load.state === 'loading' ? (
          <View className="mt-12 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        ) : load.state === 'error' || !company ? (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load these settings.</Text>
        ) : (
          <>
            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Address & contact
              </Text>
              <Text className="mt-2 font-serif text-lg text-ink">{company.name}</Text>
              <Text className="mt-3 text-sm text-ink/70">
                These show in the "from" block on the invoices and estimates your contacts see,
                under your business name. The checkboxes set the default for new documents — you can
                still change it on any individual invoice or estimate. Leave a field blank to omit
                it entirely.
              </Text>

              <Text className="mt-5 font-mono text-xs uppercase tracking-widest text-ink/50">
                Business address
              </Text>
              <TextInput
                value={address}
                onChangeText={(t) => {
                  setAddress(t);
                  setStatus('idle');
                }}
                placeholder={'123 Main St\nSpringfield, IL 62704'}
                multiline
                className="mt-2 min-h-[72px] rounded-sm border border-ink/20 bg-cream px-3 py-2 text-ink"
              />
              <View className="mt-2 flex-row flex-wrap gap-x-6 gap-y-2">
                <Checkbox
                  label="Show on invoices"
                  value={showAddrInv}
                  onToggle={() => {
                    setShowAddrInv((v) => !v);
                    setStatus('idle');
                  }}
                />
                <Checkbox
                  label="Show on estimates"
                  value={showAddrEst}
                  onToggle={() => {
                    setShowAddrEst((v) => !v);
                    setStatus('idle');
                  }}
                />
              </View>

              <Text className="mt-5 font-mono text-xs uppercase tracking-widest text-ink/50">
                Phone
              </Text>
              <TextInput
                value={phone}
                onChangeText={(t) => {
                  setPhone(t);
                  setStatus('idle');
                }}
                placeholder="(555) 123-4567"
                keyboardType="phone-pad"
                className="mt-2 rounded-sm border border-ink/20 bg-cream px-3 py-2 text-ink"
              />
              <View className="mt-2 flex-row flex-wrap gap-x-6 gap-y-2">
                <Checkbox
                  label="Show on invoices"
                  value={showPhoneInv}
                  onToggle={() => {
                    setShowPhoneInv((v) => !v);
                    setStatus('idle');
                  }}
                />
                <Checkbox
                  label="Show on estimates"
                  value={showPhoneEst}
                  onToggle={() => {
                    setShowPhoneEst((v) => !v);
                    setStatus('idle');
                  }}
                />
              </View>

              <Text className="mt-5 font-mono text-xs uppercase tracking-widest text-ink/50">
                Email
              </Text>
              <TextInput
                value={email}
                onChangeText={(t) => {
                  setEmail(t);
                  setStatus('idle');
                }}
                placeholder="hello@yourbusiness.com"
                keyboardType="email-address"
                autoCapitalize="none"
                className="mt-2 rounded-sm border border-ink/20 bg-cream px-3 py-2 text-ink"
              />
              <View className="mt-2 flex-row flex-wrap gap-x-6 gap-y-2">
                <Checkbox
                  label="Show on invoices"
                  value={showEmailInv}
                  onToggle={() => {
                    setShowEmailInv((v) => !v);
                    setStatus('idle');
                  }}
                />
                <Checkbox
                  label="Show on estimates"
                  value={showEmailEst}
                  onToggle={() => {
                    setShowEmailEst((v) => !v);
                    setStatus('idle');
                  }}
                />
              </View>

              <View className="mt-5 flex-row items-center gap-4">
                <Pressable
                  onPress={onSave}
                  disabled={saving}
                  className="rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                >
                  <Text className="text-sm font-medium text-cream">Save</Text>
                </Pressable>
                {status === 'saved' ? (
                  <Text className="text-sm text-ink/60">Saved.</Text>
                ) : status === 'error' ? (
                  <Text className="text-sm text-oxblood">Couldn't save.</Text>
                ) : null}
              </View>
            </View>

            {/* Timezone. Deliberately not a 400-entry picker on a phone: the
                device's own zone is the answer in virtually every case, so we
                show what's stored and offer a one-tap correction. */}
            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Your time zone
              </Text>
              <Text className="mt-2 font-serif text-lg text-ink">{timezone}</Text>
              <Text className="mt-3 text-sm text-ink/70">
                Reports count a day from midnight where you are. Get this wrong and a payment taken
                on the evening of 31 December can land in the wrong tax year.
              </Text>
              {deviceTimezone && deviceTimezone !== timezone ? (
                <View className="mt-5 flex-row items-center gap-4">
                  <Pressable
                    onPress={() => onSaveTimezone(deviceTimezone)}
                    disabled={tzSaving}
                    className="rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                  >
                    <Text className="text-sm font-medium text-cream">Use {deviceTimezone}</Text>
                  </Pressable>
                  {tzStatus === 'error' ? (
                    <Text className="text-sm text-oxblood">Couldn't save.</Text>
                  ) : null}
                </View>
              ) : (
                <Text className="mt-4 text-sm text-ink/60">
                  {tzStatus === 'saved'
                    ? 'Saved.'
                    : tzStatus === 'error'
                      ? "Couldn't save."
                      : 'Matches this device.'}
                </Text>
              )}
            </View>

            {/* Accounting method, in plain words — the user never sees
                "cash"/"accrual" as a label, only what it means. Saves on tap
                since it's a two-option choice. */}
            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                When you count income
              </Text>
              <Text className="mt-2 font-serif text-lg text-ink">{company.name}</Text>
              <Text className="mt-3 text-sm text-ink/70">
                This decides which tax year money lands in. Most people count income when they get
                paid — the usual choice for freelancers and trades. Only change it if whoever files
                your taxes told you to.
              </Text>
              <View className="mt-5 gap-3">
                {(
                  [
                    ['cash', 'When you get paid', 'Most common.'],
                    ['accrual', 'When you send the invoice', 'Even if the money arrives later.'],
                  ] as const
                ).map(([value, label, hint]) => (
                  <Pressable
                    key={value}
                    onPress={() => onSaveMethod(value)}
                    disabled={methodSaving}
                    className={`rounded-sm border px-4 py-3 ${
                      method === value ? 'border-gold-deep bg-gold-deep/10' : 'border-ink/15'
                    }`}
                  >
                    <Text className="text-ink">{label}</Text>
                    <Text className="mt-0.5 text-xs text-ink/60">{hint}</Text>
                  </Pressable>
                ))}
              </View>
              {methodStatus === 'saved' ? (
                <Text className="mt-4 text-sm text-ink/60">Saved.</Text>
              ) : methodStatus === 'error' ? (
                <Text className="mt-4 text-sm text-oxblood">Couldn't save.</Text>
              ) : null}
            </View>

            {/* First-year share of a big purchase spread over years (TMC-123).
                Half-year is the IRS standard; full-year exists only so an
                accountant can match how an asset is already being handled. The
                person who bought the thing never comes here — they chose
                "deduct it all" vs "spread it out" at the point of purchase. */}
            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Big purchases, first year
              </Text>
              <Text className="mt-2 font-serif text-lg text-ink">{company.name}</Text>
              <Text className="mt-3 text-sm text-ink/70">
                When you buy something big and spread the cost out, this decides how much counts in
                the year you bought it. The standard answer is half — the IRS treats anything you
                buy as though you bought it mid-year. Only change it if whoever files your taxes
                told you to.
              </Text>
              <View className="mt-5 gap-3">
                {(
                  [
                    [
                      'half_year',
                      'Half the usual amount',
                      'A $3,600 mower counts about $360 the first year, then about $720 a year. Standard.',
                    ],
                    [
                      'full_year',
                      'The full amount',
                      'That mower counts about $720 every year for five years, starting the year you buy it.',
                    ],
                  ] as const
                ).map(([value, label, hint]) => (
                  <Pressable
                    key={value}
                    onPress={() => onSaveConvention(value)}
                    disabled={conventionSaving}
                    className={`rounded-sm border px-4 py-3 ${
                      convention === value ? 'border-gold-deep bg-gold-deep/10' : 'border-ink/15'
                    }`}
                  >
                    <Text className="text-ink">{label}</Text>
                    <Text className="mt-0.5 text-xs text-ink/60">{hint}</Text>
                  </Pressable>
                ))}
              </View>
              <Text className="mt-4 text-xs text-ink/50">
                Changing this only affects years that haven't been counted yet.
              </Text>
              {conventionStatus === 'saved' ? (
                <Text className="mt-4 text-sm text-ink/60">Saved.</Text>
              ) : conventionStatus === 'error' ? (
                <Text className="mt-4 text-sm text-oxblood">Couldn't save.</Text>
              ) : null}
            </View>

            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Reply-to address
              </Text>
              <Text className="mt-2 font-serif text-lg text-ink">{company.name}</Text>
              <Text className="mt-3 text-sm text-ink/70">
                Invoices and estimates go out under your business name, but from Thalermark's
                sending address. Set a reply-to so when a contact hits "reply," it reaches you.
                Leave it blank to send with no reply-to.
              </Text>

              <Text className="mt-5 font-mono text-xs uppercase tracking-widest text-ink/50">
                Reply-to email
              </Text>
              <TextInput
                value={replyTo}
                onChangeText={(t) => {
                  setReplyTo(t);
                  setReplyStatus('idle');
                }}
                placeholder="you@yourbusiness.com"
                keyboardType="email-address"
                autoCapitalize="none"
                autoCorrect={false}
                className="mt-2 rounded-sm border border-ink/20 bg-cream px-3 py-2 text-ink"
              />

              <View className="mt-5 flex-row items-center gap-4">
                <Pressable
                  onPress={onSaveReplyTo}
                  disabled={replySaving}
                  className="rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                >
                  <Text className="text-sm font-medium text-cream">Save</Text>
                </Pressable>
                {replyStatus === 'saved' ? (
                  <Text className="text-sm text-ink/60">Saved.</Text>
                ) : replyStatus === 'error' ? (
                  <Text className="text-sm text-oxblood">Couldn't save.</Text>
                ) : null}
              </View>
            </View>

            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">Logo</Text>
              <Text className="mt-2 text-sm text-ink/70">
                Shown on the invoices and estimates your contacts see. PNG, JPEG, or WebP, up to 2
                MB.
              </Text>

              {logo ? (
                <Image
                  source={{ uri: absolutize(logo.url) }}
                  resizeMode="contain"
                  className="mt-4 h-24 w-48 self-start rounded-sm border border-ink/10 bg-cream"
                />
              ) : (
                <Text className="mt-4 text-sm text-ink/50">No logo yet.</Text>
              )}

              <View className="mt-4 flex-row gap-2">
                <Pressable
                  onPress={onPickLogo}
                  disabled={logoBusy}
                  className="rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                >
                  <Text className="text-sm font-medium text-cream">
                    {logoBusy ? '…' : logo ? 'Replace' : 'Upload'}
                  </Text>
                </Pressable>
                {logo ? (
                  <Pressable
                    onPress={onRemoveLogo}
                    disabled={logoBusy}
                    className="rounded-sm border border-ink/20 px-4 py-3 active:bg-ink/5 disabled:opacity-50"
                  >
                    <Text className="text-sm font-medium text-ink">Remove</Text>
                  </Pressable>
                ) : null}
              </View>
              {logoError ? <Text className="mt-3 text-sm text-oxblood">{logoError}</Text> : null}
            </View>
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}
