// apps/web/src/routes/(app)/settings/profile/+page.svelte
<script lang="ts">
  import { onMount, untrack } from 'svelte';
  import { invalidateAll } from '$app/navigation';
  import { authClient } from '$lib/auth-client';
  import PasswordStrength from '$lib/components/PasswordStrength.svelte';
  import { checkPassword } from '@thalermark/validation';

  let { data } = $props();

  // --- Display name ---
  // Seed the editable field from the load once; untrack so it isn't re-captured
  // reactively (matches the edit-page convention).
  let name = $state(untrack(() => data.profile.name));
  let savingName = $state(false);
  let nameError = $state<string | null>(null);
  let nameSaved = $state(false);

  async function onSaveName(event: SubmitEvent) {
    event.preventDefault();
    nameError = null;
    nameSaved = false;
    const trimmed = name.trim();
    if (!trimmed) {
      nameError = 'Name cannot be empty.';
      return;
    }
    savingName = true;
    const result = await authClient.updateUser({ name: trimmed });
    savingName = false;
    if (result.error) {
      nameError = result.error.message ?? 'Could not update your name.';
      return;
    }
    nameSaved = true;
    // Refresh the session-derived name elsewhere in the app (nav avatar/menu).
    await invalidateAll();
  }

  // --- Password ---
  let currentPassword = $state('');
  let newPassword = $state('');
  let confirmPassword = $state('');
  let changingPw = $state(false);
  let pwError = $state<string | null>(null);
  let pwDone = $state(false);

  // Does this user actually have a password? A social-only (trusted-provider)
  // sign-in has no `credential` account, so the change form doesn't apply — show
  // a "set a password" path instead. Resolved client-side after mount.
  let hasPassword = $state<boolean | null>(null);
  let sendingReset = $state(false);
  let resetSent = $state(false);

  onMount(async () => {
    const res = await authClient.listAccounts();
    hasPassword = (res.data ?? []).some((a) => a.providerId === 'credential');
  });

  async function onChangePassword(event: SubmitEvent) {
    event.preventDefault();
    pwError = null;
    pwDone = false;
    // Same policy as signup (length + not-weak/common); the server re-checks on
    // /change-password, this is just the instant client-side message.
    const check = checkPassword(newPassword);
    if (!check.ok) {
      pwError = check.message;
      return;
    }
    if (newPassword !== confirmPassword) {
      pwError = 'New passwords do not match.';
      return;
    }
    changingPw = true;
    const result = await authClient.changePassword({
      currentPassword,
      newPassword,
      revokeOtherSessions: true,
    });
    changingPw = false;
    if (result.error) {
      pwError =
        result.error.code === 'INVALID_PASSWORD'
          ? 'Your current password is incorrect.'
          : (result.error.message ?? 'Could not change your password.');
      return;
    }
    currentPassword = '';
    newPassword = '';
    confirmPassword = '';
    pwDone = true;
  }

  // Email a reset/set link to the user's own address (same flow as the
  // forgot-password page). Serves both "I forgot my current password" and the
  // social-only "set a first password" case — the server creates the credential
  // when the link is completed.
  async function onSendResetLink() {
    sendingReset = true;
    await authClient.requestPasswordReset({ email: data.profile.email });
    sendingReset = false;
    resetSent = true;
  }
</script>

<span class="eyebrow">Profile</span>
<h1 class="mt-3 font-serif text-3xl font-light tracking-tight text-fg">Your profile</h1>
<p class="mt-2 text-sm text-fg/60">Your personal details and sign-in password.</p>

<section class="mt-8 max-w-lg">
  <h2 class="label">Your details</h2>
  <form onsubmit={onSaveName} class="mt-4 space-y-4">
    <label class="block">
      <span class="label block">Display name</span>
      <input
        type="text"
        required
        bind:value={name}
        oninput={() => (nameSaved = false)}
        class="field-line mt-2"
      />
    </label>
    <label class="block">
      <span class="label block">Email</span>
      <input
        type="email"
        value={data.profile.email}
        readonly
        class="field-line mt-2 cursor-not-allowed text-fg/60"
      />
      <span class="mt-1 block text-xs text-fg/50">Email can't be changed.</span>
    </label>
    {#if nameError}
      <p class="label text-danger">{nameError}</p>
    {/if}
    <div class="flex items-center gap-4">
      <button type="submit" disabled={savingName} class="btn">
        {savingName ? 'Saving…' : 'Save'}
      </button>
      {#if nameSaved}
        <span class="label text-success">Saved</span>
      {/if}
    </div>
  </form>
</section>

<section class="mt-12 max-w-lg">
  <h2 class="label">Password</h2>

  {#if hasPassword === null}
    <p class="mt-4 text-sm text-fg/50">Loading…</p>
  {:else if hasPassword}
    {#if pwDone}
      <div class="callout mt-4 px-5 py-4">
        <p class="font-serif text-lg text-fg">Password updated.</p>
        <p class="mt-2 text-sm text-fg/75">Other devices have been signed out.</p>
      </div>
    {/if}
    <form onsubmit={onChangePassword} class="mt-4 space-y-4">
      <label class="block">
        <span class="label block">Current password</span>
        <input
          type="password"
          required
          autocomplete="current-password"
          bind:value={currentPassword}
          class="field-line mt-2"
        />
      </label>
      <label class="block">
        <span class="label block">New password</span>
        <input
          type="password"
          required
          minlength={10}
          autocomplete="new-password"
          bind:value={newPassword}
          oninput={() => (pwDone = false)}
          class="field-line mt-2"
        />
        <PasswordStrength password={newPassword} />
      </label>
      <label class="block">
        <span class="label block">Confirm new password</span>
        <input
          type="password"
          required
          minlength={10}
          autocomplete="new-password"
          bind:value={confirmPassword}
          class="field-line mt-2"
        />
      </label>
      {#if pwError}
        <p class="label text-danger">{pwError}</p>
      {/if}
      <button type="submit" disabled={changingPw} class="btn">
        {changingPw ? 'Updating…' : 'Change password'}
      </button>
    </form>
    {#if resetSent}
      <p class="mt-4 text-sm text-fg/70">
        We've emailed a reset link to <span class="font-medium text-fg">{data.profile.email}</span>.
        It expires in one hour.
      </p>
    {:else}
      <button
        type="button"
        onclick={onSendResetLink}
        disabled={sendingReset}
        class="link mt-4 text-sm"
      >
        {sendingReset ? 'Sending…' : 'Forgot your current password?'}
      </button>
    {/if}
  {:else}
    <p class="callout mt-4">
      You sign in with a connected account, so there's no password on this account to change.
    </p>
  {/if}
</section>

// apps/mobile/src/app/(app)/more/profile.tsx
import { checkPassword } from '@thalermark/validation';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PasswordStrength } from '../../../components/PasswordStrength';
import { authClient } from '../../../lib/auth-client';

// Personal profile — native mirror of apps/web's /settings/profile. Display name
// + change password for the signed-in user (no email change — that needs
// re-verification, out of scope). Uses the Better Auth client directly
// (updateUser / changePassword); the /change-password endpoint enforces the same
// password policy as signup server-side, this screen just gives instant feedback.
//
// Social-only logins (a trusted provider, no `credential` account) have no
// password to change, so they get an explanatory banner instead of the form.
export default function Profile() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [savedName, setSavedName] = useState('');
  const [hasPassword, setHasPassword] = useState(false);

  const [savingName, setSavingName] = useState(false);
  const [nameError, setNameError] = useState<string | null>(null);
  const [nameSaved, setNameSaved] = useState(false);

  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [changingPw, setChangingPw] = useState(false);
  const [pwError, setPwError] = useState<string | null>(null);
  const [pwDone, setPwDone] = useState(false);

  const [sendingReset, setSendingReset] = useState(false);
  const [resetSent, setResetSent] = useState(false);

  useFocusEffect(
    useCallback(() => {
      let alive = true;
      Promise.all([authClient.getSession(), authClient.listAccounts()])
        .then(([sessionRes, accountsRes]) => {
          if (!alive) return;
          const user = sessionRes.data?.user;
          if (user) {
            setName(user.name ?? '');
            setSavedName(user.name ?? '');
            setEmail(user.email ?? '');
          }
          setHasPassword((accountsRes.data ?? []).some((a) => a.providerId === 'credential'));
          setLoading(false);
        })
        .catch(() => {
          if (alive) setLoading(false);
        });
      return () => {
        alive = false;
      };
    }, []),
  );

  async function onSaveName() {
    setNameError(null);
    setNameSaved(false);
    const trimmed = name.trim();
    if (!trimmed) {
      setNameError('Name cannot be empty.');
      return;
    }
    setSavingName(true);
    const result = await authClient.updateUser({ name: trimmed });
    setSavingName(false);
    if (result.error) {
      setNameError(result.error.message ?? 'Could not update your name.');
      return;
    }
    setSavedName(trimmed);
    setNameSaved(true);
  }

  async function onChangePassword() {
    setPwError(null);
    setPwDone(false);
    const check = checkPassword(newPassword);
    if (!check.ok) {
      setPwError(check.message);
      return;
    }
    if (newPassword !== confirmPassword) {
      setPwError('New passwords do not match.');
      return;
    }
    setChangingPw(true);
    const result = await authClient.changePassword({
      currentPassword,
      newPassword,
      revokeOtherSessions: true,
    });
    setChangingPw(false);
    if (result.error) {
      setPwError(
        result.error.code === 'INVALID_PASSWORD'
          ? 'Your current password is incorrect.'
          : (result.error.message ?? 'Could not change your password.'),
      );
      return;
    }
    setCurrentPassword('');
    setNewPassword('');
    setConfirmPassword('');
    setPwDone(true);
  }

  // Email a reset link to the user's own address (same flow as forgot-password)
  // for the "I forgot my current password" escape hatch.
  async function onSendResetLink() {
    setSendingReset(true);
    await authClient.requestPasswordReset({ email });
    setSendingReset(false);
    setResetSent(true);
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <Text
          onPress={() => router.push('/more')}
          className="font-mono text-xs uppercase tracking-widest text-ink-subtle"
        >
          ← More
        </Text>
        <Text className="mt-3 font-serif text-3xl font-light text-ink">Profile</Text>

        {loading ? (
          <View className="mt-12 items-center">
            <ActivityIndicator className="text-ink" />
          </View>
        ) : (
          <>
            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                Your details
              </Text>

              <Text className="mt-4 font-mono text-xs uppercase tracking-widest text-ink-subtle">
                Display name
              </Text>
              <TextInput
                value={name}
                onChangeText={(v) => {
                  setName(v);
                  setNameSaved(false);
                }}
                autoComplete="name"
                className="mt-2 border-b border-field py-2 text-ink"
              />

              <Text className="mt-5 font-mono text-xs uppercase tracking-widest text-ink-subtle">
                Email
              </Text>
              <Text className="mt-2 py-2 text-ink-subtle">{email}</Text>
              <Text className="text-xs text-ink-subtle">Email can't be changed.</Text>

              {nameError ? (
                <Text className="mt-3 font-mono text-xs uppercase tracking-widest text-oxblood">
                  {nameError}
                </Text>
              ) : null}
              <View className="mt-5 flex-row items-center gap-4">
                <Pressable
                  onPress={onSaveName}
                  disabled={savingName || name.trim() === savedName}
                  className="rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                >
                  <Text className="text-sm font-medium text-cream">Save</Text>
                </Pressable>
                {nameSaved ? <Text className="text-sm text-ink-subtle">Saved.</Text> : null}
              </View>
            </View>

            <View className="mt-6 rounded-sm border border-ink/15 bg-cream-warm p-6">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                Password
              </Text>

              {hasPassword ? (
                <>
                  {pwDone ? (
                    <Text className="mt-3 text-sm text-ink-muted">
                      Password updated. Other devices have been signed out.
                    </Text>
                  ) : null}

                  <Text className="mt-4 font-mono text-xs uppercase tracking-widest text-ink-subtle">
                    Current password
                  </Text>
                  <TextInput
                    value={currentPassword}
                    onChangeText={setCurrentPassword}
                    secureTextEntry
                    autoComplete="current-password"
                    className="mt-2 border-b border-field py-2 text-ink"
                  />

                  <Text className="mt-4 font-mono text-xs uppercase tracking-widest text-ink-subtle">
                    New password
                  </Text>
                  <TextInput
                    value={newPassword}
                    onChangeText={(v) => {
                      setNewPassword(v);
                      setPwDone(false);
                    }}
                    secureTextEntry
                    autoComplete="new-password"
                    className="mt-2 border-b border-field py-2 text-ink"
                  />
                  <PasswordStrength password={newPassword} />

                  <Text className="mt-4 font-mono text-xs uppercase tracking-widest text-ink-subtle">
                    Confirm new password
                  </Text>
                  <TextInput
                    value={confirmPassword}
                    onChangeText={setConfirmPassword}
                    secureTextEntry
                    autoComplete="new-password"
                    className="mt-2 border-b border-field py-2 text-ink"
                  />

                  {pwError ? (
                    <Text className="mt-3 font-mono text-xs uppercase tracking-widest text-oxblood">
                      {pwError}
                    </Text>
                  ) : null}
                  <Pressable
                    onPress={onChangePassword}
                    disabled={changingPw}
                    className="mt-5 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
                  >
                    <Text className="text-center text-sm font-medium text-cream">
                      {changingPw ? 'Updating…' : 'Change password'}
                    </Text>
                  </Pressable>

                  {resetSent ? (
                    <Text className="mt-5 text-sm text-ink-muted">
                      We've emailed a reset link to {email}. It expires in one hour.
                    </Text>
                  ) : (
                    <Pressable onPress={onSendResetLink} disabled={sendingReset} className="mt-5">
                      <Text className="text-sm text-gold-deep underline">
                        {sendingReset ? 'Sending…' : 'Forgot your current password?'}
                      </Text>
                    </Pressable>
                  )}
                </>
              ) : (
                <Text className="mt-3 text-sm text-ink-muted">
                  You sign in with a connected account, so there's no password on this account to
                  change.
                </Text>
              )}
            </View>
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}
