// apps/web/src/routes/(app)/reports/top-products/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  const total = $derived(
    data.products.reduce((sum, p) => sum + Number(p.revenue), 0).toLocaleString('en-US', {
      style: 'currency',
      currency: 'USD',
    }),
  );

  const basisNote = $derived(
    data.basis === 'sent'
      ? 'Pre-tax revenue from invoices that have been sent or paid.'
      : 'Pre-tax revenue from paid invoices only (cash basis).',
  );
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Reports</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
      Top products<span class="text-gold-deep">.</span>
    </h1>
  </div>
  <div class="flex items-center gap-1 rounded-sm border border-ink/15 bg-cream-warm p-1 font-mono text-xs uppercase tracking-widest">
    <a
      href="/reports/top-products"
      class="rounded-sm px-3 py-1 transition-colors {data.basis === 'paid'
        ? 'bg-ink text-cream'
        : 'text-ink/60 hover:text-ink'}"
    >
      Paid
    </a>
    <a
      href="/reports/top-products?basis=sent"
      class="rounded-sm px-3 py-1 transition-colors {data.basis === 'sent'
        ? 'bg-ink text-cream'
        : 'text-ink/60 hover:text-ink'}"
    >
      Sent
    </a>
  </div>
</div>

<p class="mt-3 text-sm text-ink/60">
  {basisNote} A sales lens, not a tax figure — the “Uncatalogued / other” row collects hand-typed
  lines so the rows tie back to revenue.
</p>

{#if data.products.length === 0}
  <p class="mt-8 text-ink/70">No sales yet on this basis.</p>
{:else}
  <div class="mt-8 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
    <table class="w-full text-left text-sm">
      <thead class="bg-cream">
        <tr class="font-mono text-xs uppercase tracking-widest text-ink/50">
          <th class="px-5 py-3">Product</th>
          <th class="w-24 px-5 py-3 text-right">Lines</th>
          <th class="w-36 px-5 py-3 text-right">Revenue</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-ink/10">
        {#each data.products as p (p.sourceItemId ?? 'uncatalogued')}
          <tr>
            <td class="px-5 py-3">
              {#if p.name}
                <a href="/settings/items/{p.sourceItemId}" class="text-ink hover:text-gold-deep">
                  {p.name}
                </a>
              {:else}
                <span class="text-ink/50 italic">Uncatalogued / other</span>
              {/if}
            </td>
            <td class="px-5 py-3 text-right font-mono tabular-nums text-ink/70">{p.lineCount}</td>
            <td class="px-5 py-3 text-right font-mono tabular-nums text-ink">{fmt(p.revenue)}</td>
          </tr>
        {/each}
      </tbody>
      <tfoot class="border-t border-ink/10 bg-cream">
        <tr class="font-mono text-xs uppercase tracking-widest">
          <td class="px-5 py-3 text-ink/70">Total</td>
          <td></td>
          <td class="px-5 py-3 text-right text-base tabular-nums text-ink">{total}</td>
        </tr>
      </tfoot>
    </table>
  </div>
{/if}

// apps/mobile/src/app/(app)/more/top-products.tsx
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../lib/api';

// Mirror of apps/web's /reports/top-products. A sales lens, not a tax figure:
// pre-tax revenue grouped by source_item_id, with a single "Uncatalogued /
// other" bucket for hand-typed lines so the rows tie back to revenue. `basis`
// flips cash (paid-only) vs accrual-ish (sent or paid); the API validates it.
type Basis = 'paid' | 'sent';
type Product = {
  sourceItemId: string | null;
  name: string | null;
  revenue: string;
  lineCount: number;
};

const BASES: { key: Basis; label: string }[] = [
  { key: 'paid', label: 'Paid' },
  { key: 'sent', label: 'Sent' },
];

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

const basisNote = (b: Basis) =>
  b === 'sent'
    ? 'Pre-tax revenue from invoices that have been sent or paid.'
    : 'Pre-tax revenue from paid invoices only (cash basis).';

export default function TopProducts() {
  const router = useRouter();
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [basis, setBasis] = useState<Basis>('paid');
  const [products, setProducts] = useState<Product[] | null>(null);
  const [error, setError] = useState(false);

  // Resolve the active company once (single-company MVP auto-picks the first).
  useFocusEffect(
    useCallback(() => {
      let active = true;
      api.api.companies
        .$get()
        .then(async (res) => {
          if (!active || !res.ok) return;
          const { companies } = await res.json();
          setCompanyId(companies[0]?.id ?? null);
        })
        .catch(() => {});
      return () => {
        active = false;
      };
    }, []),
  );

  // Refetch when the company or basis changes.
  useEffect(() => {
    if (!companyId) return;
    let active = true;
    setProducts(null);
    setError(false);
    api.api.companies[':id']['top-products']
      .$get({ param: { id: companyId }, query: { basis } })
      .then(async (res) => {
        if (!active) return;
        if (!res.ok) {
          setError(true);
          return;
        }
        const data = await res.json();
        setProducts(data.products);
      })
      .catch(() => {
        if (active) setError(true);
      });
    return () => {
      active = false;
    };
  }, [companyId, basis]);

  const total =
    products
      ?.reduce((sum, p) => sum + Number(p.revenue), 0)
      .toLocaleString('en-US', {
        style: 'currency',
        currency: 'USD',
      }) ?? '';

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <Pressable onPress={() => router.push('/more')}>
          <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">← More</Text>
        </Pressable>

        <View className="mt-3 flex-row items-end justify-between gap-4">
          <Text className="font-serif text-3xl font-light text-ink">Top products</Text>
          <View className="flex-row gap-1 rounded-sm border border-ink/15 bg-cream-warm p-1">
            {BASES.map((b) => (
              <Pressable
                key={b.key}
                onPress={() => setBasis(b.key)}
                className={`rounded-sm px-3 py-1 ${basis === b.key ? 'bg-ink' : ''}`}
              >
                <Text
                  className={`font-mono text-xs uppercase tracking-widest ${
                    basis === b.key ? 'text-cream' : 'text-ink/60'
                  }`}
                >
                  {b.label}
                </Text>
              </Pressable>
            ))}
          </View>
        </View>

        <Text className="mt-3 text-sm text-ink/60">
          {basisNote(basis)} A sales lens, not a tax figure — the “Uncatalogued / other” row
          collects hand-typed lines so the rows tie back to revenue.
        </Text>

        {error ? (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load the report.</Text>
        ) : products === null ? (
          <View className="mt-12 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        ) : products.length === 0 ? (
          <Text className="mt-8 text-ink/70">No sales yet on this basis.</Text>
        ) : (
          <View className="mt-8 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
            <View className="flex-row bg-cream px-4 py-3">
              <Text className="flex-1 font-mono text-xs uppercase tracking-widest text-ink/50">
                Product
              </Text>
              <Text className="w-12 text-right font-mono text-xs uppercase tracking-widest text-ink/50">
                Lines
              </Text>
              <Text className="w-24 text-right font-mono text-xs uppercase tracking-widest text-ink/50">
                Revenue
              </Text>
            </View>

            {products.map((p) => (
              // Catalogued rows link to the item; the uncatalogued bucket (null
              // source) is inert. A disabled Pressable keeps the markup uniform.
              <Pressable
                key={p.sourceItemId ?? 'uncatalogued'}
                disabled={!p.sourceItemId}
                onPress={() => router.push(`/more/items/${p.sourceItemId}`)}
                className="flex-row items-center border-t border-ink/10 px-4 py-3 active:bg-cream"
              >
                {p.name ? (
                  <Text className="flex-1 text-ink">{p.name}</Text>
                ) : (
                  <Text className="flex-1 italic text-ink/50">Uncatalogued / other</Text>
                )}
                <Text className="w-12 text-right font-mono text-sm tabular-nums text-ink/70">
                  {p.lineCount}
                </Text>
                <Text className="w-24 text-right font-mono text-sm tabular-nums text-ink">
                  {fmt(p.revenue)}
                </Text>
              </Pressable>
            ))}

            <View className="flex-row items-center border-t border-ink/10 bg-cream px-4 py-3">
              <Text className="flex-1 font-mono text-xs uppercase tracking-widest text-ink/70">
                Total
              </Text>
              <Text className="w-24 text-right font-mono text-base tabular-nums text-ink">
                {total}
              </Text>
            </View>
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}
