// apps/mobile/src/app/(app)/contacts/index.tsx
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MetricStrip } from '../../../components/MetricStrip';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../lib/use-paginated-list';

// Roster summary powering the metric strip (mirror of web). A contact can be
// both a customer and a vendor, so those slices overlap and don't sum to total.
type ContactSummary = {
  total: number;
  customers: number;
  vendors: number;
  withOpenInvoices: number;
};
type ContactRoleFilter = '' | 'customer' | 'vendor';

// Mirror of apps/web's /contacts list. Account-scoped via x-account-id (the
// API filters by accountId); keyset-paginated with onEndReached infinite scroll.
// usePaginatedList refetches page 1 on focus so a contact created on
// /contacts/new shows when we navigate back, and reloads whenever a filter
// flips (fetchPage identity changes). Filters: search (q, name OR email) and
// an "Open invoices" toggle (contacts with an issued-but-unpaid invoice).
type ContactRow = { id: string; name: string; email: string | null };

export default function ContactsList() {
  const router = useRouter();
  const canCreate = useMay('contacts:write');

  const [q, setQ] = useState('');
  const [appliedQ, setAppliedQ] = useState('');
  const [openInvoices, setOpenInvoices] = useState(false);
  const [role, setRole] = useState<ContactRoleFilter>('');
  const [summary, setSummary] = useState<ContactSummary | null>(null);

  useEffect(() => {
    const t = setTimeout(() => setAppliedQ(q.trim()), 300);
    return () => clearTimeout(t);
  }, [q]);

  // Point-in-time roster summary for the strip; refreshed on focus. Best-effort.
  useFocusEffect(
    useCallback(() => {
      let active = true;
      api.api.contacts.summary
        .$get({ query: {} })
        .then(async (res) => {
          if (active && res.ok) setSummary(await res.json());
        })
        .catch(() => {});
      return () => {
        active = false;
      };
    }, []),
  );

  const anyFilter = Boolean(appliedQ || openInvoices || role);

  const fetchPage = useCallback(
    async (cursor: string | null) => {
      const query: Record<string, string> = pageQuery(cursor);
      if (appliedQ) query.q = appliedQ;
      if (openInvoices) query.openInvoices = 'true';
      if (role) query.role = role;
      const res = await api.api.contacts.$get({ query });
      if (!res.ok) return null;
      const { contacts, nextCursor } = await res.json();
      return {
        rows: contacts.map((c): ContactRow => ({ id: c.id, name: c.name, email: c.email ?? null })),
        nextCursor,
      };
    },
    [appliedQ, openInvoices, role],
  );

  const { list, loadingMore, loadMore } = usePaginatedList(fetchPage);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="flex-row items-end justify-between px-6 pt-6">
        <View>
          <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
            Contacts
          </Text>
          <Text className="mt-2 font-serif text-3xl font-light text-ink">All contacts</Text>
        </View>
        {canCreate ? (
          <Pressable
            onPress={() => router.push('/contacts/new')}
            className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
          >
            <Text className="text-sm font-medium text-cream">+ New</Text>
          </Pressable>
        ) : null}
      </View>

      {summary ? (
        <View className="mt-4 px-6">
          <MetricStrip
            tiles={[
              {
                label: 'Total',
                value: summary.total,
                onPress: () => {
                  setRole('');
                  setOpenInvoices(false);
                },
                active: !role && !openInvoices,
              },
              {
                label: 'Customers',
                value: summary.customers,
                onPress: () => {
                  setRole('customer');
                  setOpenInvoices(false);
                },
                active: role === 'customer',
              },
              {
                label: 'Vendors',
                value: summary.vendors,
                onPress: () => {
                  setRole('vendor');
                  setOpenInvoices(false);
                },
                active: role === 'vendor',
              },
              {
                label: 'With open invoices',
                value: summary.withOpenInvoices,
                onPress: () => {
                  setOpenInvoices(true);
                  setRole('');
                },
                active: openInvoices,
              },
            ]}
          />
        </View>
      ) : null}

      <View className="mt-4 flex-row items-center gap-2 px-6">
        <TextInput
          value={q}
          onChangeText={setQ}
          placeholder="Search name or email"
          returnKeyType="search"
          className="flex-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2.5 text-ink"
        />
        <Pressable
          onPress={() =>
            setOpenInvoices((v) => {
              if (!v) setRole('');
              return !v;
            })
          }
          className={`rounded-sm border px-3 py-2.5 ${
            openInvoices ? 'border-ink bg-ink' : 'border-ink/20 bg-cream-warm'
          }`}
        >
          <Text
            className={`font-mono text-xs uppercase tracking-widest ${
              openInvoices ? 'text-cream' : 'text-ink/60'
            }`}
          >
            Open
          </Text>
        </Pressable>
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator color="#0f1626" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load contacts.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink/70">
          {anyFilter ? 'No contacts match these filters.' : 'No contacts yet.'}
        </Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(c) => c.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          keyboardShouldPersistTaps="handled"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator color="#0f1626" />
              </View>
            ) : null
          }
          renderItem={({ item }) => (
            <Pressable
              onPress={() => router.push(`/contacts/${item.id}`)}
              className="flex-row items-center justify-between bg-cream-warm px-5 py-4 active:bg-cream"
            >
              <Text className="font-serif text-lg text-ink">{item.name}</Text>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                {item.email ?? ''}
              </Text>
            </Pressable>
          )}
        />
      )}
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/contacts/+page.svelte
<script lang="ts">
  import ImportExportActions from '$lib/components/ImportExportActions.svelte';
  import LoadMore from '$lib/components/LoadMore.svelte';
  import MetricStrip from '$lib/components/MetricStrip.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  const { filters, summary } = $derived(data);
  const anyFilter = $derived(Boolean(filters.q || filters.openInvoices || filters.role));

  // Point-in-time roster strip (counts only — no money on the contacts page).
  // A contact can be both a customer and a vendor, so those slices overlap by
  // design and don't sum to Total. Tiles deep-link to the matching filter.
  const strip = $derived([
    { label: 'Total', value: summary?.total ?? 0, href: '/contacts', active: !anyFilter },
    {
      label: 'Customers',
      value: summary?.customers ?? 0,
      href: '/contacts?role=customer',
      active: filters.role === 'customer',
    },
    {
      label: 'Vendors',
      value: summary?.vendors ?? 0,
      href: '/contacts?role=vendor',
      active: filters.role === 'vendor',
    },
    {
      label: 'With open invoices',
      value: summary?.withOpenInvoices ?? 0,
      href: '/contacts?openInvoices=true',
      active: filters.openInvoices,
    },
  ]);

  // Seed local state from page 1; untrack() so Svelte doesn't fire the
  // state_referenced_locally warning — capturing the initial value is exactly
  // what we want, and the $effect below re-seeds when load() re-runs.
  type Row = (typeof data.contacts)[number];
  let rows = $state<Row[]>(untrack(() => data.contacts));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.contacts;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<Row>('/contacts/more', cursor, {
        q: filters.q,
        openInvoices: filters.openInvoices ? 'true' : '',
        role: filters.role,
      });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Contacts</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      All contacts<span class="text-accent">.</span>
    </h1>
  </div>
  <div class="flex items-center gap-2">
    <ImportExportActions entity="contacts" role={data.role} />
    {#if may(data.role, 'contacts:write')}
      <a href="/contacts/new" class="btn"> + New contact </a>
    {/if}
  </div>
</div>

<div class="mt-8">
  <MetricStrip tiles={strip} />
</div>

<!-- Filters. Plain GET form so they live in the URL (shareable, back-button
     friendly) and re-run load() with a fresh page 1. -->
<form
  method="GET"
  class="mt-8 flex flex-wrap items-end gap-3 rounded-sm border border-fg/10 bg-surface-2 p-4"
>
  <label class="flex flex-1 flex-col gap-1 text-xs uppercase tracking-widest text-fg/50">
    Search
    <input
      type="search"
      name="q"
      value={filters.q}
      placeholder="Name or email"
      class="min-w-40 rounded-sm border border-fg/15 bg-surface px-2 py-1.5 text-sm normal-case tracking-normal text-fg"
    />
  </label>
  <label class="flex items-center gap-2 py-1.5 text-sm text-fg">
    <input
      type="checkbox"
      name="openInvoices"
      value="true"
      checked={filters.openInvoices}
      onchange={(e) => e.currentTarget.form?.requestSubmit()}
      class="rounded-sm border-fg/30 text-accent focus:ring-accent"
    />
    Has open invoices
  </label>
  <button
    type="submit"
    class="btn"
  >
    Filter
  </button>
  {#if anyFilter}
    <a href="/contacts" class="text-sm text-fg/60 hover:text-fg">Clear</a>
  {/if}
</form>

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">
    {anyFilter ? 'No contacts match these filters.' : 'No contacts yet.'}
  </p>
{:else}
  <ul class="mt-8 divide-y divide-fg/10 rounded-sm border border-fg/10 bg-surface-2">
    {#each rows as c (c.id)}
      <li>
        <a
          href="/contacts/{c.id}"
          class="flex items-center justify-between px-5 py-4 transition-colors hover:bg-surface"
        >
          <span class="font-serif text-lg text-fg">{c.name}</span>
          <span class="label">
            {c.email ?? ''}
          </span>
        </a>
      </li>
    {/each}
  </ul>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}
