// apps/mobile/src/app/(app)/estimates/new.tsx
import {
  type EstimateLineItemInput,
  type LineItemType,
  addMoney,
  contactCreateSchema,
  estimateCreateSchema,
  formatUnitPrice,
  localToday,
  multiplyMoney,
  sumMoney,
  unitPriceFromTotal,
} from '@thalermark/validation';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Checkbox } from '../../../components/Checkbox';
import { ContactField } from '../../../components/ContactField';
import { DateField } from '../../../components/DateField';
import { type ItemPatch, ItemPickerField } from '../../../components/ItemPickerField';
import { TaxRow } from '../../../components/TaxRow';
import { TypeRow } from '../../../components/TypeRow';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { apiErrorMessage } from '../../../lib/api-errors';
import { NEW_CONTACT, findEmailDupe } from '../../../lib/contact-dupes';
import { type TaxPolicyLite, lineTax, policyRate, resolvePolicyId } from '../../../lib/line-tax';

// Mirror of apps/web's /estimates/new — the invoice create form minus dueDate,
// plus an optional expiresOn (quote validity). Contact via the ContactField
// type-ahead; two-step create with inline contact; decimal-string money;
// sourceItemId via ItemPickerField.

type Row = {
  description: string;
  quantity: string;
  unitLabel: string;
  unitPrice: string;
  amount: string;
  sourceItemId: string | null;
  type: LineItemType;
  taxable: boolean;
  taxPolicyId: string;
};
const blankRow = (): Row => ({
  description: '',
  quantity: '',
  unitLabel: '',
  unitPrice: '',
  amount: '',
  sourceItemId: null,
  type: 'service',
  taxable: false,
  taxPolicyId: '',
});

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

const FRIENDLY: Record<string, string> = {
  estimate_number_taken: 'Estimate number already used for this company. Try another.',
  customer_company_mismatch: 'Selected contact does not belong to this company.',
  contact_not_found: 'Selected contact no longer exists.',
};

export default function NewEstimate() {
  const router = useRouter();

  const [companyId, setCompanyId] = useState<string | null>(null);
  const [bootstrapped, setBootstrapped] = useState(false);

  const [contactId, setContactId] = useState('');
  const [contactName, setContactName] = useState('');
  const [newName, setNewName] = useState('');
  const [newEmail, setNewEmail] = useState('');

  const [number, setNumber] = useState('');
  const [issueDate, setIssueDate] = useState(todayIso());
  const [expiresOn, setExpiresOn] = useState('');
  const [taxPolicies, setTaxPolicies] = useState<TaxPolicyLite[]>([]);
  const [notes, setNotes] = useState('');
  // From-block "show on this estimate" toggles, seeded from the company's
  // estimate-side defaults at bootstrap. Default true so a load failure still
  // submits a sensible (always-show) estimate.
  const [showAddress, setShowAddress] = useState(true);
  const [showPhone, setShowPhone] = useState(true);
  const [showEmail, setShowEmail] = useState(true);
  const [rows, setRows] = useState<Row[]>([blankRow()]);

  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Bootstrap once — ref gate (not a state dep), so a state flip can't tear
  // down `active` mid-flight and drop the next-number prefill (M3 footgun).
  const didBootstrap = useRef(false);
  useFocusEffect(
    useCallback(() => {
      if (didBootstrap.current) return;
      didBootstrap.current = true;
      let active = true;
      (async () => {
        const compRes = await api.api.companies.$get();
        if (!active) return;
        if (compRes.ok) {
          const { companies } = await compRes.json();
          const company = await pickActiveCompany(companies);
          if (company) {
            setCompanyId(company.id);
            // Re-date through the company's timezone (TMC-258) — the useState
            // seed above can only use the device clock in UTC, which dates an
            // evening document tomorrow. One-shot bootstrap, so no user edit
            // is at risk.
            setIssueDate(localToday(company.timezone));
            setShowAddress(company.showAddressOnEstimate);
            setShowPhone(company.showPhoneOnEstimate);
            setShowEmail(company.showEmailOnEstimate);
            const numRes = await api.api.estimates['next-number'].$get({
              query: { companyId: company.id },
            });
            if (active && numRes.ok) setNumber((await numRes.json()).suggestion);
            const polRes = await api.api['tax-policies'].$get({
              query: { companyId: company.id },
            });
            if (active && polRes.ok) {
              const { taxPolicies: pols } = await polRes.json();
              setTaxPolicies(
                pols.map((p) => ({
                  id: p.id,
                  name: p.name,
                  ratePct: p.ratePct,
                  isDefault: p.isDefault,
                })),
              );
            }
          }
        }
        if (active) setBootstrapped(true);
      })().catch(() => {
        if (active) setBootstrapped(true);
      });
      return () => {
        active = false;
      };
    }, []),
  );

  const inlineMode = contactId === NEW_CONTACT;

  const computedRows = useMemo(
    () =>
      rows.map((r) => {
        const rate = r.taxable ? policyRate(taxPolicies, r.taxPolicyId) : '0';
        return { ...r, tax: lineTax(r.taxable, rate, r.amount) };
      }),
    [rows, taxPolicies],
  );
  const subtotal = useMemo(() => sumMoney(computedRows.map((r) => r.amount)), [computedRows]);
  const taxTotal = useMemo(() => sumMoney(computedRows.map((r) => r.tax)), [computedRows]);
  const total = useMemo(() => addMoney(subtotal, taxTotal), [subtotal, taxTotal]);

  const patchRow = (i: number, patch: Partial<Row>) =>
    setRows((rs) => rs.map((r, j) => (j === i ? { ...r, ...patch } : r)));
  // Keep unit price and line total in step (mirror of web). Editing quantity or
  // unit price re-derives the amount (unit price sticky); editing the amount
  // back-computes a 4dp unit price so an agreed total that doesn't divide evenly
  // (e.g. $650 over 7 → $92.8571 → $650.00) is representable.
  const setRowQuantity = (i: number, quantity: string) =>
    setRows((rs) =>
      rs.map((r, j) =>
        j === i ? { ...r, quantity, amount: multiplyMoney(quantity, r.unitPrice) } : r,
      ),
    );
  const setRowUnitPrice = (i: number, unitPrice: string) =>
    setRows((rs) =>
      rs.map((r, j) =>
        j === i ? { ...r, unitPrice, amount: multiplyMoney(r.quantity, unitPrice) } : r,
      ),
    );
  const setRowAmount = (i: number, amount: string) =>
    setRows((rs) =>
      rs.map((r, j) =>
        j === i ? { ...r, amount, unitPrice: unitPriceFromTotal(amount, r.quantity) } : r,
      ),
    );
  const addRow = () => setRows((rs) => [...rs, blankRow()]);
  const removeRow = (i: number) =>
    setRows((rs) => (rs.length <= 1 ? rs : rs.filter((_, j) => j !== i)));
  const toggleRowTaxable = (i: number) =>
    setRows((rs) =>
      rs.map((r, j) => {
        if (j !== i) return r;
        const turningOn = !r.taxable;
        return {
          ...r,
          taxable: turningOn,
          taxPolicyId:
            turningOn && !r.taxPolicyId ? resolvePolicyId(taxPolicies, '') : r.taxPolicyId,
        };
      }),
    );
  const applyPick = (i: number, patch: ItemPatch) => {
    const { taxable, taxPolicyId, unitLabel, ...rest } = patch;
    setRows((rs) =>
      rs.map((r, j) => {
        if (j !== i) return r;
        const merged: Row = { ...r, ...rest };
        // A pick carries the item's unit ('' when it has none); hand-typing the
        // description leaves unitLabel out of the patch, so the row keeps its own.
        if (unitLabel !== undefined) merged.unitLabel = unitLabel ?? '';
        if (taxable !== undefined) {
          merged.taxable = taxable;
          merged.taxPolicyId = taxable ? resolvePolicyId(taxPolicies, taxPolicyId ?? '') : '';
        }
        // A pick sets unit price + quantity; keep the amount in step.
        merged.amount = multiplyMoney(merged.quantity, merged.unitPrice);
        return merged;
      }),
    );
  };

  const noCompany = bootstrapped && companyId === null;
  const hasContact = inlineMode ? newName.trim().length > 0 : contactId !== '';
  const canSubmit = !submitting && !noCompany && hasContact;

  async function onSubmit() {
    if (!companyId) {
      setFormError('No company in this workspace.');
      return;
    }
    setFormError(null);
    setFieldErrors({});

    let resolvedContactId = contactId;
    if (inlineMode) {
      const custInput = {
        companyId,
        name: newName.trim(),
        email: newEmail.trim() === '' ? undefined : newEmail.trim(),
      };
      const parsedCust = contactCreateSchema.safeParse(custInput);
      if (!parsedCust.success) {
        const errs: Record<string, string> = {};
        for (const issue of parsedCust.error.issues) {
          const key = `contact_${String(issue.path[0] ?? '_')}`;
          if (!errs[key]) errs[key] = issue.message;
        }
        setFieldErrors(errs);
        return;
      }
      setSubmitting(true);
      try {
        // HARD BLOCK on email exact match (the API doesn't dedupe). Search by
        // the email so the check is correct at any contact count.
        if (parsedCust.data.email) {
          const dres = await api.api.contacts.$get({
            query: { q: parsedCust.data.email, companyId },
          });
          if (dres.ok) {
            const { contacts: list } = await dres.json();
            const dupe = findEmailDupe(
              parsedCust.data.email,
              list.map((c) => ({ id: c.id, name: c.name, email: c.email ?? null })),
            );
            if (dupe) {
              setFieldErrors({ contact_email: `${dupe.name} already uses this email.` });
              setSubmitting(false);
              return;
            }
          }
        }
        const custRes = await api.api.contacts.$post({ json: parsedCust.data });
        if (!custRes.ok) {
          const body = (await custRes.json().catch(() => null)) as { error?: string } | null;
          setFormError(
            apiErrorMessage(body?.error, 'That customer could not be created. Try again.'),
          );
          return;
        }
        const created = await custRes.json();
        resolvedContactId = created.id;
        setContactName(created.name);
        setContactId(created.id);
        setNewName('');
        setNewEmail('');
      } catch {
        setFormError('That customer could not be created. Try again.');
        setSubmitting(false);
        return;
      }
    }

    const lineItems: EstimateLineItemInput[] = rows.map((r, i) => {
      const amount = multiplyMoney(r.quantity, r.unitPrice);
      const rate = r.taxable ? policyRate(taxPolicies, r.taxPolicyId) : '0';
      return {
        position: i + 1,
        description: r.description.trim(),
        quantity: r.quantity.trim(),
        unitLabel: r.unitLabel.trim() || undefined,
        unitPrice: r.unitPrice.trim(),
        amount,
        type: r.type,
        taxable: r.taxable,
        taxRatePct: rate,
        taxAmount: lineTax(r.taxable, rate, amount),
        taxPolicyId: r.taxable ? r.taxPolicyId || undefined : undefined,
        sourceItemId: r.sourceItemId ?? undefined,
      };
    });
    const sub = sumMoney(lineItems.map((li) => li.amount));
    const taxVal = sumMoney(lineItems.map((li) => li.taxAmount ?? '0'));
    const payload = {
      companyId,
      contactId: resolvedContactId,
      number: number.trim(),
      issueDate: issueDate.trim(),
      expiresOn: expiresOn.trim() === '' ? undefined : expiresOn.trim(),
      subtotal: sub,
      tax: taxVal,
      total: addMoney(sub, taxVal),
      notes: notes.trim() === '' ? undefined : notes.trim(),
      showAddress,
      showPhone,
      showEmail,
      lineItems,
    };

    const parsed = estimateCreateSchema.safeParse(payload);
    if (!parsed.success) {
      const errs: Record<string, string> = {};
      for (const issue of parsed.error.issues) {
        const top = String(issue.path[0] ?? '_');
        const key = top === 'lineItems' ? 'lineItems' : top;
        if (!errs[key]) errs[key] = issue.message;
      }
      setFieldErrors(errs);
      setSubmitting(false);
      return;
    }

    setSubmitting(true);
    try {
      const res = await api.api.estimates.$post({ json: parsed.data });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        const code = apiErrorMessage(body?.error, 'That could not be created. Try again.');
        setFormError(
          FRIENDLY[code] ?? apiErrorMessage(code, 'That could not be saved. Try again.'),
        );
        return;
      }
      const created = await res.json();
      router.replace(`/estimates/${created.id}`);
    } catch {
      setFormError('That could not be created. Try again.');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              ← Estimates
            </Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">New estimate</Text>

          {formError ? (
            <View className="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
              <Text className="text-sm text-oxblood">{formError}</Text>
            </View>
          ) : null}

          <View className="mt-8 gap-5">
            <ContactField
              label="Contact *"
              companyId={companyId}
              contactName={contactName}
              setContactName={setContactName}
              contactId={contactId}
              setContactId={setContactId}
              error={fieldErrors.contactId}
              newName={newName}
              setNewName={setNewName}
              newEmail={newEmail}
              setNewEmail={setNewEmail}
              nameError={fieldErrors.contact_name}
              emailError={fieldErrors.contact_email}
            />

            <LabeledInput
              label="Number *"
              value={number}
              onChangeText={setNumber}
              error={fieldErrors.number}
            />
            <DateField
              label="Issued *"
              value={issueDate}
              onChange={setIssueDate}
              error={fieldErrors.issueDate}
            />
            <DateField
              label="Valid until"
              value={expiresOn}
              onChange={setExpiresOn}
              error={fieldErrors.expiresOn}
              optional
            />

            {/* Line items */}
            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                Line items
              </Text>
              {fieldErrors.lineItems ? (
                <Text className="mt-1 text-xs text-oxblood">{fieldErrors.lineItems}</Text>
              ) : null}
              <View className="mt-2 gap-4">
                {rows.map((row, i) => (
                  // biome-ignore lint/suspicious/noArrayIndexKey: rows are positional and reorder-free
                  <View key={i} className="rounded-sm border border-ink/10 bg-cream-warm p-3">
                    <ItemPickerField
                      description={row.description}
                      onChange={(patch) => applyPick(i, patch)}
                    />
                    <TypeRow value={row.type} onSelect={(t) => patchRow(i, { type: t })} />
                    <View className="mt-2 flex-row gap-2">
                      <View className="flex-1">
                        <Text className="font-mono text-[10px] uppercase tracking-widest text-ink-subtle">
                          Qty
                        </Text>
                        <TextInput
                          value={row.quantity}
                          onChangeText={(t) => setRowQuantity(i, t)}
                          inputMode="decimal"
                          className="mt-1 rounded-sm border border-field bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                        />
                      </View>
                      <View className="flex-1">
                        <Text className="font-mono text-[10px] uppercase tracking-widest text-ink-subtle">
                          Unit price
                        </Text>
                        <TextInput
                          value={row.unitPrice}
                          onChangeText={(t) => setRowUnitPrice(i, t)}
                          inputMode="decimal"
                          className="mt-1 rounded-sm border border-field bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                        />
                      </View>
                      <View className="flex-1">
                        <Text className="font-mono text-[10px] uppercase tracking-widest text-ink-subtle">
                          Amount
                        </Text>
                        <TextInput
                          value={row.amount}
                          onChangeText={(t) => setRowAmount(i, t)}
                          inputMode="decimal"
                          className="mt-1 rounded-sm border border-field bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                        />
                      </View>
                    </View>
                    <View className="mt-2">
                      <Text className="font-mono text-[10px] uppercase tracking-widest text-ink-subtle">
                        Unit
                      </Text>
                      <TextInput
                        value={row.unitLabel}
                        onChangeText={(t) => patchRow(i, { unitLabel: t })}
                        placeholder="hr, day, sq ft"
                        maxLength={50}
                        className="mt-1 rounded-sm border border-field bg-cream px-2 py-2 text-ink"
                      />
                    </View>
                    <TaxRow
                      taxPolicies={taxPolicies}
                      taxable={row.taxable}
                      taxPolicyId={row.taxPolicyId}
                      lineTaxAmount={computedRows[i]?.tax ?? '0.00'}
                      onToggle={() => toggleRowTaxable(i)}
                      onSelectPolicy={(pid) => patchRow(i, { taxPolicyId: pid })}
                    />
                    {rows.length > 1 ? (
                      <Pressable onPress={() => removeRow(i)} className="mt-2 self-end">
                        <Text className="font-mono text-xs uppercase tracking-wider text-oxblood">
                          Remove
                        </Text>
                      </Pressable>
                    ) : null}
                  </View>
                ))}
              </View>
              <Pressable onPress={addRow} className="mt-3">
                <Text className="text-sm font-medium text-gold-deep">+ Add row</Text>
              </Pressable>
            </View>

            <View className="rounded-sm border border-ink/10 bg-cream-warm p-4">
              <TotalRow label="Subtotal" value={subtotal} />
              <TotalRow label="Tax" value={taxTotal} />
              <View className="mt-3 border-t border-ink/10 pt-3">
                <TotalRow label="Total" value={total} emphasize />
              </View>
            </View>

            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                Notes
              </Text>
              <TextInput
                value={notes}
                onChangeText={setNotes}
                multiline
                className="mt-1 rounded-sm border border-field bg-cream-warm px-3 py-2 text-ink"
              />
            </View>

            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                Your details on this estimate
              </Text>
              <Text className="mt-1 text-xs text-ink-subtle">
                Only details you've added in Business settings will show.
              </Text>
              <Checkbox
                label="Show my address"
                value={showAddress}
                onToggle={() => setShowAddress((v) => !v)}
                className="mt-3"
              />
              <Checkbox
                label="Show my phone"
                value={showPhone}
                onToggle={() => setShowPhone((v) => !v)}
                className="mt-3"
              />
              <Checkbox
                label="Show my email"
                value={showEmail}
                onToggle={() => setShowEmail((v) => !v)}
                className="mt-3"
              />
            </View>

            {noCompany ? (
              <Text className="text-xs text-oxblood">No company in this workspace.</Text>
            ) : null}

            <Pressable
              onPress={onSubmit}
              disabled={!canSubmit}
              className="mt-2 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
            >
              {submitting ? (
                <ActivityIndicator className="text-cream" />
              ) : (
                <Text className="text-center text-sm font-medium text-cream">Create estimate</Text>
              )}
            </Pressable>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

function LabeledInput({
  label,
  value,
  onChangeText,
  error,
  autoCapitalize,
}: {
  label: string;
  value: string;
  onChangeText: (t: string) => void;
  error?: string;
  autoCapitalize?: 'none';
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">{label}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        autoCapitalize={autoCapitalize}
        className="mt-1 rounded-sm border border-field bg-cream-warm px-3 py-2 text-ink"
      />
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}

function TotalRow({
  label,
  value,
  emphasize,
}: {
  label: string;
  value: string;
  emphasize?: boolean;
}) {
  return (
    <View className="flex-row justify-between">
      <Text
        className={`font-mono text-xs uppercase tracking-widest ${emphasize ? 'text-ink-muted' : 'text-ink-subtle'}`}
      >
        {label}
      </Text>
      <Text className={`font-mono tabular-nums text-ink ${emphasize ? 'text-lg' : ''}`}>
        {value}
      </Text>
    </View>
  );
}

// apps/web/src/routes/(app)/estimates/new/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { enhanceForm } from '$lib/form-enhance';
    import { untrack } from 'svelte';
  import ContactPicker from '$lib/components/ContactPicker.svelte';
  import ItemPicker from '$lib/components/ItemPicker.svelte';
  import { defaultPolicyId, lineTax, policyRate } from '$lib/line-tax';
  import {
    type LineItemType,
    addMoney,
    formatUnitPrice,
    multiplyMoney,
    sumMoney,
    unitPriceFromTotal,
  } from '@thalermark/validation';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  type Row = {
    description: string;
    quantity: string;
    unitLabel: string;
    unitPrice: string;
    amount: string;
    sourceItemId: string | null;
    type: LineItemType;
    taxable: boolean;
    taxPolicyId: string;
  };

  function blankRow(): Row {
    return { description: '', quantity: '', unitLabel: '', unitPrice: '', amount: '', sourceItemId: null, type: 'service', taxable: false, taxPolicyId: '' };
  }

  // Editing quantity/unit price re-derives the amount (unit price sticky);
  // editing the amount back-computes a 4dp unit price so an agreed total that
  // doesn't divide evenly is representable (e.g. $650 over 7 → $92.8571 →
  // $650.00). The form submits quantity + unit price; the server recomputes the
  // amount, so the (unnamed) amount input is preview sugar steering the price.
  function recalcAmount(row: Row) {
    row.amount = multiplyMoney(row.quantity, row.unitPrice);
  }
  function recalcPrice(row: Row) {
    row.unitPrice = unitPriceFromTotal(row.amount, row.quantity);
  }

  function resolvePolicyId(pref: string): string {
    if (pref && data.taxPolicies.some((p) => p.id === pref)) return pref;
    return defaultPolicyId(data.taxPolicies) || data.taxPolicies[0]?.id || '';
  }
  function onTaxableChange(row: Row) {
    if (row.taxable && !row.taxPolicyId) row.taxPolicyId = resolvePolicyId('');
  }
  function applyItemTax(row: Row, taxable: boolean, taxPolicyId: string | null) {
    row.taxable = taxable;
    row.taxPolicyId = taxable ? resolvePolicyId(taxPolicyId ?? '') : '';
  }

  // Dates come from the server, resolved through the company's timezone
  // (TMC-258). The browser clock in UTC dated an evening document tomorrow.


  // Seeding strategy mirrors /invoices/new (8.4c). Static inputs render via
  // value={form?.values?.X ?? default}; live-preview inputs (tax + rows)
  // use $state with untrack() initializers so SSR re-render after a fail()
  // captures the right initial values without firing the
  // state_referenced_locally warning.
  const values = $derived(form?.values);

  let rows = $state<Row[]>(
    untrack(() => {
      const seeded = form?.values?.lineItems;
      return seeded && seeded.length > 0
        ? seeded.map((li) => ({
            description: li.description,
            quantity: li.quantity,
            unitLabel: li.unitLabel ?? '',
            unitPrice: formatUnitPrice(li.unitPrice),
            amount: multiplyMoney(li.quantity, li.unitPrice),
            sourceItemId: li.sourceItemId ?? null,
            type: li.type ?? 'service',
            taxable: li.taxable ?? false,
            taxPolicyId: li.taxPolicyId ?? '',
          }))
        : [blankRow()];
    }),
  );

  const computedRows = $derived(
    rows.map((r) => {
      const rate = r.taxable ? policyRate(data.taxPolicies, r.taxPolicyId) : '0';
      return { ...r, tax: lineTax(r.taxable, rate, r.amount) };
    }),
  );
  const subtotal = $derived(sumMoney(computedRows.map((r) => r.amount)));
  const taxTotal = $derived(sumMoney(computedRows.map((r) => r.tax)));
  const total = $derived(addMoney(subtotal, taxTotal));

  // From-block "show on this estimate" toggles. Seed from the prior submit on a
  // fail re-render, else the company-level estimate default. `??` respects a
  // returned `false` (only null/undefined falls through).
  const showAddress = $derived(form?.values?.showAddress ?? data.showDefaults.showAddress);
  const showPhone = $derived(form?.values?.showPhone ?? data.showDefaults.showPhone);
  const showEmail = $derived(form?.values?.showEmail ?? data.showDefaults.showEmail);

  const fieldErrors = $derived(form?.fieldErrors ?? {});
  function err(key: string): string | undefined {
    return (fieldErrors as Record<string, string>)[key];
  }

  function addRow() {
    rows.push(blankRow());
  }

  function removeRow(index: number) {
    if (rows.length <= 1) return;
    rows.splice(index, 1);
  }
</script>

<a href="/estimates" class="eyebrow text-fg/60 hover:text-fg">← Estimates</a>
<h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
  New estimate<span class="text-accent">.</span>
</h1>

{#if form?.formError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger" data-form-error role="alert" tabindex="-1">
    {form.formError}
  </div>
{/if}

  <form method="post" class="mt-8 space-y-8" use:enhance={enhanceForm}>
    <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
      <div>
        <label for="contactName" class="label">
          Contact<span class="text-accent">*</span>
        </label>
        <ContactPicker
          initialContactId={values?.contactId ?? ''}
          initialContactName={values?.contactName ?? ''}
          initialNewName={values?.newContactName ?? ''}
          initialNewEmail={values?.newContactEmail ?? ''}
          fieldError={err('contactId')}
          contactErrors={form?.contactErrors}
          dupeContact={form?.dupeContact}
        />
      </div>

      <div>
        <label for="number" class="label">
          Number<span class="text-accent">*</span>
        </label>
        <input
          id="number"
          name="number"
          type="text"
          required
          maxlength="50"
          value={values?.number ?? data.suggestedNumber}
          class="field mt-1"
        />
        {#if err('number')}
          <p class="mt-1 text-xs text-danger">{err('number')}</p>
        {/if}
      </div>

      <div>
        <label for="issueDate" class="label">
          Issued<span class="text-accent">*</span>
        </label>
        <input
          id="issueDate"
          name="issueDate"
          type="date"
          required
          value={values?.issueDate ?? data.today}
          class="field mt-1"
        />
        {#if err('issueDate')}
          <p class="mt-1 text-xs text-danger">{err('issueDate')}</p>
        {/if}
      </div>

      <div>
        <label for="expiresOn" class="label">
          Expires
        </label>
        <input
          id="expiresOn"
          name="expiresOn"
          type="date"
          value={values?.expiresOn ?? data.expiresDefault}
          class="field mt-1"
        />
        {#if err('expiresOn')}
          <p class="mt-1 text-xs text-danger">{err('expiresOn')}</p>
        {/if}
        <p class="mt-1 text-xs text-fg/50">
          Optional. Leave blank for an open-ended quote.
        </p>
      </div>
    </div>

    <fieldset class="space-y-3">
      <legend class="label">Line items</legend>
      {#if err('lineItems')}
        <p class="text-xs text-danger">{err('lineItems')}</p>
      {/if}
      <div class="overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
        <table class="w-full text-left text-sm">
          <thead class="bg-surface">
            <tr class="label">
              <th class="px-3 py-2">Description</th>
              <th class="w-28 px-3 py-2 text-right">Qty</th>
              <th class="w-32 px-3 py-2 text-right">Unit price</th>
              <th class="w-36 px-3 py-2">Tax</th>
              <th class="w-32 px-3 py-2 text-right">Amount</th>
              <th class="w-10 px-3 py-2"></th>
            </tr>
          </thead>
          <tbody class="divide-y divide-fg/10">
            {#each rows as row, i (i)}
              <tr>
                <td class="px-3 py-2 align-top">
                  <ItemPicker
                    bind:description={row.description}
                    bind:quantity={row.quantity}
                    bind:unitPrice={row.unitPrice}
                    bind:sourceItemId={row.sourceItemId}
                    onpick={(s) => {
                      row.type = s.type;
                      row.unitLabel = s.unitLabel ?? '';
                      applyItemTax(row, s.taxable, s.taxPolicyId);
                      recalcAmount(row);
                    }}
                  />
                  <select
                    bind:value={row.type}
                    name="li_type"
                    aria-label="Type"
                    class="mt-1 rounded-sm border border-fg/15 bg-surface px-1.5 py-1 text-xs text-fg/70 focus:border-accent focus:outline-none"
                  >
                    <option value="service">Service</option>
                    <option value="product">Product</option>
                  </select>
                </td>
                <td class="px-3 py-2 align-top">
                  <input
                    type="text"
                    name="li_quantity"
                    inputmode="decimal"
                    required
                    bind:value={row.quantity}
                    oninput={() => recalcAmount(row)}
                    class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                  />
                  <input
                    type="text"
                    name="li_unitLabel"
                    maxlength="50"
                    placeholder="unit"
                    aria-label="Unit"
                    bind:value={row.unitLabel}
                    class="mt-1 w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right text-xs text-fg/70 focus:border-accent focus:outline-none"
                  />
                </td>
                <td class="px-3 py-2 align-top">
                  <input
                    type="text"
                    name="li_unitPrice"
                    inputmode="decimal"
                    required
                    bind:value={row.unitPrice}
                    oninput={() => recalcAmount(row)}
                    class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                  />
                </td>
                <td class="px-3 py-2 align-top">
                  <label class="flex items-center gap-1.5 text-xs text-fg/70">
                    <input
                      type="checkbox"
                      bind:checked={row.taxable}
                      onchange={() => onTaxableChange(row)}
                      class="size-4 accent-accent"
                    />
                    Taxable
                  </label>
                  {#if row.taxable}
                    {#if data.taxPolicies.length > 0}
                      <select
                        bind:value={row.taxPolicyId}
                        aria-label="Tax policy"
                        class="mt-1 w-full rounded-sm border border-fg/15 bg-surface px-1.5 py-1 text-xs text-fg focus:border-accent focus:outline-none"
                      >
                        {#each data.taxPolicies as p (p.id)}
                          <option value={p.id}>{p.name} ({Number(p.ratePct)}%)</option>
                        {/each}
                      </select>
                    {:else}
                      <a
                        href="/settings/tax-policies/new"
                        class="mt-1 block text-[0.65rem] text-accent hover:underline"
                      >
                        + Add a rate
                      </a>
                    {/if}
                  {/if}
                  <input type="hidden" name="li_taxable" value={row.taxable ? '1' : '0'} />
                  <input
                    type="hidden"
                    name="li_taxPolicyId"
                    value={row.taxable ? row.taxPolicyId : ''}
                  />
                </td>
                <td class="px-3 py-2 align-top">
                  <input
                    type="text"
                    inputmode="decimal"
                    aria-label="Amount"
                    bind:value={row.amount}
                    oninput={() => recalcPrice(row)}
                    class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                  />
                  {#if row.taxable}
                    <span class="mt-1 block text-right text-[0.65rem] font-normal text-fg/50">
                      +{computedRows[i]?.tax ?? '0.00'} tax
                    </span>
                  {/if}
                </td>
                <td class="px-3 py-2 text-right align-top">
                  <button
                    type="button"
                    onclick={() => removeRow(i)}
                    disabled={rows.length <= 1}
                    aria-label="Remove row"
                    class="text-fg/50 transition-colors hover:text-danger disabled:cursor-not-allowed disabled:opacity-30"
                  >
                    ×
                  </button>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
      <button
        type="button"
        onclick={addRow}
        class="text-sm font-medium text-accent hover:text-fg"
      >
        + Add row
      </button>
    </fieldset>

    <div class="flex justify-end">
      <dl class="w-full max-w-xs rounded-sm border border-fg/10 bg-surface-2 p-4 text-sm">
        <div class="flex justify-between">
          <dt class="label">Subtotal</dt>
          <dd class="font-mono tabular-nums text-fg">{subtotal}</dd>
        </div>
        <div class="mt-2 flex justify-between">
          <dt class="label">Tax</dt>
          <dd class="font-mono tabular-nums text-fg">{taxTotal}</dd>
        </div>
        <div class="mt-3 flex justify-between border-t border-fg/10 pt-3">
          <dt class="font-mono text-xs uppercase tracking-widest text-fg/70">Total</dt>
          <dd class="font-mono tabular-nums text-lg text-fg">{total}</dd>
        </div>
      </dl>
    </div>

    <div>
      <label for="notes" class="label">Notes</label
      >
      <textarea
        id="notes"
        name="notes"
        rows="4"
        maxlength="5000"
        class="field mt-1"
        >{values?.notes ?? ''}</textarea
      >
    </div>

    <fieldset class="space-y-2">
      <legend class="label">Your details on this estimate</legend>
      <p class="text-xs text-fg/50">
        Choose which of your business details appear under your name. Only details you've added in
        <a href="/settings/business" class="link">Settings → Business</a> will show.
      </p>
      <label class="flex items-center gap-3 text-sm text-fg">
        <input
          type="checkbox"
          name="showAddress"
          checked={showAddress}
          class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
        />
        Show my address
      </label>
      <label class="flex items-center gap-3 text-sm text-fg">
        <input
          type="checkbox"
          name="showPhone"
          checked={showPhone}
          class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
        />
        Show my phone
      </label>
      <label class="flex items-center gap-3 text-sm text-fg">
        <input
          type="checkbox"
          name="showEmail"
          checked={showEmail}
          class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
        />
        Show my email
      </label>
    </fieldset>

    <div class="flex items-center gap-4">
      <button
        type="submit"
        class="btn"
      >
        Create estimate
      </button>
      <a href="/estimates" class="text-sm text-fg/60 hover:text-fg">Cancel</a>
    </div>
  </form>
