// apps/web/src/routes/(app)/jobs/[id]/+page.svelte
<script lang="ts">
  import { may } from '$lib/perms';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
  const job = $derived(data.job);
  const margin = $derived(data.job.margin);
  const time = $derived(data.time);
  const canWrite = $derived(may(data.role, 'sales:write'));

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  const today = new Date().toISOString().slice(0, 10);

  function hours(minutes: number): string {
    return (Math.round((minutes / 60) * 100) / 100).toFixed(2);
  }
</script>

<a href="/jobs" class="eyebrow text-fg/60 hover:text-fg">← Jobs</a>
<div class="mt-3 flex flex-wrap items-baseline justify-between gap-4">
  <div>
    <h1 class="font-serif text-4xl font-light leading-none tracking-tight text-fg">
      {job.name}<span class="text-accent">.</span>
    </h1>
    <!--
      The customer is asked for at create, so it has to show back here — not
      showing it reads as "that field did nothing".
    -->
    {#if job.contactName}
      <p class="mt-2 text-sm text-fg/60">for {job.contactName}</p>
    {/if}
  </div>
  {#if canWrite}
    <div class="flex items-center gap-2">
      <!--
        The entry point for billing. You decide to bill a job while looking at
        the job, not while staring at an empty invoice — so this is what carries
        the job and its unbilled hours into the form.
      -->
      <a href="/invoices/new?jobId={job.id}" class="btn">Bill this job</a>
      <form method="post" action="?/setStatus">
        <input type="hidden" name="status" value={job.status === 'open' ? 'closed' : 'open'} />
        <button
          type="submit"
          class="rounded-sm border border-fg/15 px-3 py-1.5 font-mono text-xs uppercase tracking-widest text-fg/60 transition-colors hover:border-accent hover:text-accent"
        >
          {job.status === 'open' ? 'Close job' : 'Reopen'}
        </button>
      </form>
    </div>
  {/if}
</div>

{#if form?.actionError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.actionError}
  </div>
{/if}

<!--
  The margin block. "Made" is billed minus what you bought for it; the hours are
  never subtracted into it, because a sole proprietor's own labour is not a
  deductible expense. They divide it instead — which is the number that answers
  "was this job worth my time".
-->
<div class="mt-8 grid gap-px overflow-hidden rounded-sm border border-fg/10 bg-fg/10 sm:grid-cols-4">
  <div class="bg-surface-2 px-5 py-4">
    <span class="label">Billed</span>
    <p class="mt-1 font-mono text-xl tabular-nums text-fg/80">{fmt(margin.billed)}</p>
  </div>
  <div class="bg-surface-2 px-5 py-4">
    <span class="label">What it cost</span>
    <p class="mt-1 font-mono text-xl tabular-nums text-fg/80">{fmt(margin.costs)}</p>
  </div>
  <div class="bg-surface-2 px-5 py-4">
    <span class="label">Made</span>
    <p class="mt-1 font-mono text-xl tabular-nums text-fg">{fmt(margin.made)}</p>
  </div>
  <div class="bg-surface-2 px-5 py-4">
    <span class="label">Per hour</span>
    <!--
      A dash, not $0.00, when nothing is logged. Zero would read as "this job
      paid you nothing an hour" rather than "you haven't told me the hours".
    -->
    <p class="mt-1 font-mono text-xl tabular-nums text-fg">
      {margin.effectiveHourly ? `${fmt(margin.effectiveHourly)}` : '—'}
    </p>
    <p class="mt-1 text-xs text-fg/50">
      {margin.minutes > 0 ? `over ${margin.hours} h` : 'no hours logged'}
    </p>
  </div>
</div>

<h2 class="mt-10 font-serif text-2xl font-light text-fg">Invoices</h2>
{#if job.invoices.length === 0}
  <p class="mt-3 text-sm text-fg/60">
    Nothing billed yet. A job can carry as many invoices as it needs — a deposit and a final, or one
    every fortnight.
  </p>
{:else}
  <ul class="mt-4 divide-y divide-fg/10 rounded-sm border border-fg/10 bg-surface-2">
    {#each job.invoices as inv (inv.id)}
      <li>
        <a
          href="/invoices/{inv.id}"
          class="flex items-center justify-between gap-4 px-5 py-3 text-sm transition-colors hover:opacity-70"
        >
          <span class="font-mono text-xs text-fg/50">{inv.number}</span>
          <span class="text-fg/60">{inv.issueDate}</span>
          <span class="label">{inv.status}</span>
          <span class="font-mono tabular-nums text-fg/80">{fmt(inv.total)}</span>
        </a>
      </li>
    {/each}
  </ul>
{/if}

<h2 class="mt-10 font-serif text-2xl font-light text-fg">Hours</h2>

{#if canWrite}
  <!--
    A plain duration field, not only a timer. Reconstructing "3 hours yesterday"
    after the fact has to be as easy as running a stopwatch live, because the
    start of a job is the moment nobody is thinking about software.
  -->
  <form method="post" action="?/logTime" class="mt-4 grid gap-4 sm:grid-cols-[10rem_8rem_1fr_auto]">
    <div>
      <label for="entryDate" class="label">Date</label>
      <input id="entryDate" name="entryDate" type="date" value={today} required class="field mt-1" />
    </div>
    <div>
      <label for="duration" class="label">Hours</label>
      <input
        id="duration"
        name="duration"
        type="text"
        inputmode="decimal"
        placeholder="3.25"
        required
        class="field mt-1"
      />
    </div>
    <div>
      <label for="note" class="label">What you did</label>
      <input id="note" name="note" type="text" maxlength="1000" class="field mt-1" />
    </div>
    <div class="flex items-end">
      <button type="submit" class="btn">Log</button>
    </div>
    <div class="sm:col-span-4">
      <label for="rate" class="label">Rate per hour</label>
      <input
        id="rate"
        name="rate"
        type="text"
        inputmode="decimal"
        placeholder="Optional — leave blank if these hours aren't billable"
        class="field mt-1 max-w-sm"
      />
    </div>
  </form>
  {#if form?.timeError}
    <p class="mt-2 text-xs text-danger">{form.timeError}</p>
  {/if}
{/if}

{#if time.timeEntries.length === 0}
  <p class="mt-4 text-sm text-fg/60">No hours logged against this job yet.</p>
{:else}
  <ul class="mt-4 divide-y divide-fg/10 rounded-sm border border-fg/10 bg-surface-2">
    {#each time.timeEntries as entry (entry.id)}
      <li class="flex items-center justify-between gap-4 px-5 py-3 text-sm">
        <span class="w-28 shrink-0 text-fg/60">{entry.entryDate}</span>
        <span class="w-16 shrink-0 font-mono tabular-nums text-fg/80">{hours(entry.minutes)} h</span>
        <span class="min-w-0 flex-1 truncate text-fg/70">{entry.note ?? ''}</span>
        {#if entry.billedInvoiceId}
          <span class="label text-fg/40">Billed</span>
        {:else if canWrite}
          <form method="post" action="?/deleteTime">
            <input type="hidden" name="id" value={entry.id} />
            <button type="submit" class="link text-xs">Remove</button>
          </form>
        {/if}
      </li>
    {/each}
  </ul>
  <p class="mt-3 text-sm text-fg/60">{time.totalHours} hours in total.</p>
{/if}

{#if canWrite && job.invoices.length === 0 && time.timeEntries.length === 0}
  <form method="post" action="?/delete" class="mt-10">
    <button type="submit" class="link text-xs text-danger">Delete this job</button>
    <p class="mt-1 text-xs text-fg/50">
      Only while it's empty. Once it has hours or invoices, close it instead.
    </p>
  </form>
{/if}

// apps/mobile/src/app/(app)/jobs/[id]/index.tsx
import { formatUnitPrice, minutesFromDuration } from '@thalermark/validation';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../../lib/api';
import { useMay } from '../../../../lib/role';

// Mirror of apps/web's /jobs/[id]. The margin block leads, and the number it
// exists for is PER HOUR, not made.
//
// Hours are never subtracted into margin — a sole proprietor cannot deduct their
// own labour, so there is no wage expense and no journal entry. They divide it
// instead, which is what answers "was this job worth my time".
//
// INTERNAL ONLY. Nothing on this screen reaches the customer.
type JobDetail = {
  id: string;
  name: string;
  status: string;
  contactName: string | null;
  invoices: { id: string; number: string; issueDate: string; status: string; total: string }[];
  margin: {
    billed: string;
    costs: string;
    made: string;
    minutes: number;
    hours: string;
    effectiveHourly: string | null;
  };
};

type TimeEntry = {
  id: string;
  entryDate: string;
  minutes: number;
  note: string | null;
  rate: string | null;
  billedInvoiceId: string | null;
};

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

const hours = (minutes: number) => (Math.round((minutes / 60) * 100) / 100).toFixed(2);

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

export default function JobDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const canWrite = useMay('sales:write');

  const [job, setJob] = useState<JobDetail | null>(null);
  const [entries, setEntries] = useState<TimeEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);

  const [duration, setDuration] = useState('');
  const [note, setNote] = useState('');
  const [rate, setRate] = useState('');
  // Prefilled from the last rate used on this job — most work is billed at one
  // rate, and retyping it every entry is the friction that stops people logging.
  const [ratePrefilled, setRatePrefilled] = useState(false);
  const [timeError, setTimeError] = useState<string | null>(null);
  const [logging, setLogging] = useState(false);

  const load = useCallback(async () => {
    const [jobRes, timeRes] = await Promise.all([
      api.api.jobs[':id'].$get({ param: { id } }),
      api.api.jobs[':id'].time.$get({ param: { id }, query: { unbilled: undefined } }),
    ]);
    if (!jobRes.ok) {
      setFailed(true);
      setLoading(false);
      return;
    }
    setJob((await jobRes.json()) as JobDetail);
    if (timeRes.ok) {
      const rows = ((await timeRes.json()).timeEntries ?? []) as TimeEntry[];
      setEntries(rows);
      // Newest-first, so the first row carrying a rate is the last one used.
      // Only seeds once, so it never overwrites what the user is typing.
      const last = rows.find((r) => r.rate)?.rate;
      if (last) {
        setRatePrefilled((already) => {
          if (!already) setRate(formatUnitPrice(last));
          return true;
        });
      }
    }
    setLoading(false);
  }, [id]);

  useFocusEffect(
    useCallback(() => {
      let active = true;
      load().catch(() => {
        if (active) {
          setFailed(true);
          setLoading(false);
        }
      });
      return () => {
        active = false;
      };
    }, [load]),
  );

  async function logTime() {
    setTimeError(null);
    // Shared with web (@thalermark/validation) so the same typed string cannot
    // become two different durations.
    const minutes = minutesFromDuration(duration);
    if (minutes === null) {
      setTimeError('Enter hours like 3.25 or 3:15.');
      return;
    }
    setLogging(true);
    try {
      const res = await api.api.jobs[':id'].time.$post({
        param: { id },
        json: {
          entryDate: todayIso(),
          minutes,
          note: note.trim() || undefined,
          rate: rate.trim() || undefined,
        },
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        setTimeError(body?.error ?? 'Could not log those hours.');
        return;
      }
      setDuration('');
      setNote('');
      await load();
    } catch {
      setTimeError('Could not log those hours.');
    } finally {
      setLogging(false);
    }
  }

  async function removeEntry(entryId: string) {
    const res = await api.api['time-entries'][':id'].$delete({ param: { id: entryId } });
    if (!res.ok) {
      const body = (await res.json().catch(() => null)) as { error?: string } | null;
      setTimeError(
        body?.error === 'time_entry_billed'
          ? 'Those hours are already on an invoice. Take them off it first.'
          : 'Could not remove those hours.',
      );
      return;
    }
    await load();
  }

  async function toggleStatus() {
    if (!job) return;
    const res = await api.api.jobs[':id'].$patch({
      param: { id },
      json: { status: job.status === 'open' ? 'closed' : 'open' },
    });
    if (res.ok) await load();
  }

  if (loading) {
    return (
      <SafeAreaView className="flex-1 items-center justify-center bg-cream" edges={['top']}>
        <ActivityIndicator color="#0f1626" />
      </SafeAreaView>
    );
  }

  if (failed || !job) {
    return (
      <SafeAreaView className="flex-1 bg-cream px-6 pt-6" edges={['top']}>
        <Pressable onPress={() => router.back()}>
          <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">← Jobs</Text>
        </Pressable>
        <Text className="mt-8 text-sm text-oxblood">Couldn't load this job.</Text>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        className="flex-1"
      >
        <ScrollView contentContainerClassName="px-6 pb-12 pt-6" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">← Jobs</Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">{job.name}</Text>
          {/*
            The customer is asked for at create, so it has to show back here —
            not showing it reads as "that field did nothing".
          */}
          {job.contactName ? (
            <Text className="mt-1 text-sm text-ink/60">for {job.contactName}</Text>
          ) : null}

          <View className="mt-6 rounded-sm border border-ink/10 bg-cream-warm p-5">
            <View className="flex-row justify-between">
              <View>
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Billed
                </Text>
                <Text className="mt-1 font-mono text-lg text-ink/80">{fmt(job.margin.billed)}</Text>
              </View>
              <View>
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Cost
                </Text>
                <Text className="mt-1 font-mono text-lg text-ink/80">{fmt(job.margin.costs)}</Text>
              </View>
              <View>
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Made
                </Text>
                <Text className="mt-1 font-mono text-lg text-ink">{fmt(job.margin.made)}</Text>
              </View>
            </View>
            <View className="mt-5 border-t border-ink/10 pt-4">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Per hour
              </Text>
              {/*
                A dash, not $0.00, when nothing is logged. Zero would read as
                "this job paid you nothing an hour" rather than "you haven't told
                me the hours".
              */}
              <Text className="mt-1 font-serif text-3xl font-light text-ink">
                {job.margin.effectiveHourly ? fmt(job.margin.effectiveHourly) : '—'}
              </Text>
              <Text className="mt-1 text-xs text-ink/50">
                {job.margin.minutes > 0 ? `over ${job.margin.hours} h` : 'no hours logged'}
              </Text>
            </View>
          </View>

          {canWrite ? (
            <View className="mt-4 flex-row gap-2">
              <Pressable
                onPress={() => router.push(`/invoices/new?jobId=${job.id}`)}
                className="flex-1 items-center rounded-sm bg-ink px-4 py-3 active:bg-gold-deep"
              >
                <Text className="text-sm font-medium text-cream">Bill this job</Text>
              </Pressable>
              <Pressable
                onPress={toggleStatus}
                className="items-center rounded-sm border border-ink/20 px-4 py-3"
              >
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
                  {job.status === 'open' ? 'Close' : 'Reopen'}
                </Text>
              </Pressable>
            </View>
          ) : null}

          <Text className="mt-10 font-serif text-2xl font-light text-ink">Invoices</Text>
          {job.invoices.length === 0 ? (
            <Text className="mt-2 text-sm text-ink/60">
              Nothing billed yet. A job can carry as many invoices as it needs.
            </Text>
          ) : (
            <View className="mt-3 rounded-sm border border-ink/10 bg-cream-warm">
              {job.invoices.map((inv, i) => (
                <Pressable
                  key={inv.id}
                  onPress={() => router.push(`/invoices/${inv.id}`)}
                  className={`flex-row items-center justify-between px-5 py-3 ${
                    i > 0 ? 'border-t border-ink/10' : ''
                  }`}
                >
                  <Text className="font-mono text-xs text-ink/50">{inv.number}</Text>
                  <Text className="text-sm text-ink/60">{inv.issueDate}</Text>
                  <Text className="font-mono text-sm text-ink/80">{fmt(inv.total)}</Text>
                </Pressable>
              ))}
            </View>
          )}

          <Text className="mt-10 font-serif text-2xl font-light text-ink">Hours</Text>

          {canWrite ? (
            <View className="mt-3">
              {/*
                A plain duration field, not a timer. Reconstructing "3 hours
                yesterday" has to be as easy as running a stopwatch live, because
                the start of a job is exactly when nobody is thinking about an app.
              */}
              <View className="flex-row gap-2">
                <TextInput
                  value={duration}
                  onChangeText={setDuration}
                  placeholder="3.25"
                  keyboardType="decimal-pad"
                  className="w-24 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2.5 text-ink"
                />
                <TextInput
                  value={note}
                  onChangeText={setNote}
                  placeholder="What you did"
                  maxLength={1000}
                  className="flex-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2.5 text-ink"
                />
              </View>
              <TextInput
                value={rate}
                onChangeText={setRate}
                placeholder="Rate per hour — optional"
                keyboardType="decimal-pad"
                className="mt-2 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2.5 text-ink"
              />
              <Pressable
                onPress={logTime}
                disabled={logging}
                className="mt-2 items-center rounded-sm border border-ink/20 px-4 py-2.5 active:bg-cream-warm disabled:opacity-50"
              >
                {logging ? (
                  <ActivityIndicator color="#0f1626" />
                ) : (
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink/70">
                    Log hours
                  </Text>
                )}
              </Pressable>
              {timeError ? <Text className="mt-2 text-xs text-oxblood">{timeError}</Text> : null}
            </View>
          ) : null}

          {entries.length === 0 ? (
            <Text className="mt-4 text-sm text-ink/60">No hours logged against this job yet.</Text>
          ) : (
            <View className="mt-4 rounded-sm border border-ink/10 bg-cream-warm">
              {entries.map((entry, i) => (
                <View
                  key={entry.id}
                  className={`flex-row items-center justify-between px-5 py-3 ${
                    i > 0 ? 'border-t border-ink/10' : ''
                  }`}
                >
                  <Text className="w-24 text-sm text-ink/60">{entry.entryDate}</Text>
                  <Text className="w-16 font-mono text-sm text-ink/80">
                    {hours(entry.minutes)} h
                  </Text>
                  <Text className="flex-1 pr-2 text-sm text-ink/70" numberOfLines={1}>
                    {entry.note ?? ''}
                  </Text>
                  {/*
                    Silent when no rate was set — those hours still count toward
                    the job's time, and "$0.00/h" would look like a mistake.
                  */}
                  {entry.rate ? (
                    <Text className="pr-2 font-mono text-xs text-ink/60">
                      ${formatUnitPrice(entry.rate)}/h
                    </Text>
                  ) : null}
                  {entry.billedInvoiceId ? (
                    <Text className="font-mono text-[0.6rem] uppercase tracking-widest text-ink/40">
                      Billed
                    </Text>
                  ) : canWrite ? (
                    <Pressable onPress={() => removeEntry(entry.id)}>
                      <Text className="font-mono text-[0.6rem] uppercase tracking-widest text-oxblood">
                        Remove
                      </Text>
                    </Pressable>
                  ) : null}
                </View>
              ))}
            </View>
          )}
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
