// apps/web/src/routes/(app)/owner-money/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';
  import type { OwnerMoneyRow } from './owner-money-rows';

  let { data }: PageProps = $props();

  const { filters } = $derived(data);
  const companyId = $derived(data.companyId);
  const hasFilters = $derived(!!filters.kind);
  const openingBalance = $derived(data.openingBalance);
  const canWrite = $derived(may(data.role, 'expenses:write'));

  const money = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  // See /contacts for the untrack() seed-and-re-seed pattern. The filter is a
  // GET, so changing it navigates here, re-runs load(), and the $effect re-seeds
  // with the new filter set's page 1.
  let rows = $state<OwnerMoneyRow[]>(untrack(() => data.rows));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.rows;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<OwnerMoneyRow>('/owner-money/more', cursor, {
        companyId,
        kind: filters.kind,
      });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Investments &amp; withdrawals</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      You and the business<span class="text-accent">.</span>
    </h1>
  </div>
  {#if may(data.role, 'expenses:write')}
    <a href="/owner-money/new" class="btn">+ Record</a>
  {/if}
</div>

<p class="mt-4 max-w-2xl text-sm text-fg/60">
  Money you put into the business from your own pocket, and money you take out to pay yourself.
</p>

<!-- Starting balances — what the business already had when it started. A
     one-time setup; shows a summary once set. -->
{#if canWrite}
  <a
    href="/owner-money/opening-balance"
    class="mt-6 flex items-center justify-between gap-4 rounded-sm border border-fg/10 bg-surface-2 px-5 py-4 hover:border-accent"
  >
    {#if openingBalance}
      <div>
        <span class="label">Starting balances</span>
        <p class="mt-1 font-mono text-sm tabular-nums text-fg/80">
          {money(openingBalance.cash)} in the bank
          {#if Number(openingBalance.receivables) > 0}
            · {money(openingBalance.receivables)} owed to you{/if}
          {#if Number(openingBalance.payables) > 0}
            · {money(openingBalance.payables)} owed{/if}
        </p>
      </div>
      <span class="font-mono text-xs uppercase tracking-widest text-accent">Edit</span>
    {:else}
      <div>
        <span class="label">Starting balances</span>
        <p class="mt-1 text-sm text-fg/60">Tell us what your business started with.</p>
      </div>
      <span class="font-mono text-xs uppercase tracking-widest text-accent">Set →</span>
    {/if}
  </a>
{/if}

<!-- Filter bar. Plain GET form so the filter lives in the URL (shareable, back-
     button friendly) and the page works without JS. -->
<form method="GET" class="mt-8 flex flex-wrap items-end gap-3 rounded-sm border border-fg/10 bg-surface-2 p-4">
  <label class="flex flex-col gap-1 text-xs uppercase tracking-widest text-fg/50">
    Show
    <select
      name="kind"
      onchange={(e) => e.currentTarget.form?.requestSubmit()}
      class="rounded-sm border border-fg/15 bg-surface px-2 py-1.5 text-sm normal-case tracking-normal text-fg"
    >
      <option value="" selected={filters.kind === ''}>All</option>
      <option value="contribution" selected={filters.kind === 'contribution'}>Investments</option>
      <option value="draw" selected={filters.kind === 'draw'}>Withdrawals</option>
    </select>
  </label>
  {#if hasFilters}
    <a href="/owner-money" class="pb-1.5 text-sm text-fg/60 hover:text-fg">Clear</a>
  {/if}
</form>

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">
    {hasFilters ? 'Nothing matches this filter.' : 'Nothing recorded yet.'}
  </p>
{:else}
  <div class="mt-6 overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
    <table class="w-full text-left text-sm">
      <thead class="bg-surface">
        <tr class="label">
          <th class="px-5 py-3">Date</th>
          <th class="px-5 py-3">Type</th>
          <th class="px-5 py-3">Note</th>
          <th class="px-5 py-3 text-right">Amount</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-fg/10">
        {#each rows as ev (ev.id)}
          <tr class="hover:bg-surface">
            <td class="px-5 py-4 font-mono tabular-nums text-fg/80">{ev.occurredOn}</td>
            <td class="px-5 py-4">
              <a href="/owner-money/{ev.id}" class="font-serif text-fg hover:text-accent">
                {ev.kindLabel}
              </a>
            </td>
            <td class="px-5 py-4 text-fg/70">{ev.memo ?? '—'}</td>
            <td
              class="px-5 py-4 text-right font-mono tabular-nums {ev.direction === 'in'
                ? 'text-success'
                : 'text-fg'}"
            >
              {ev.direction === 'in' ? '+' : '−'}{ev.amount}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}

// apps/mobile/src/app/(app)/owner-money/index.tsx
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FilterChips } from '../../../components/FilterChips';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../lib/use-paginated-list';

// Mirror of apps/web's /owner-money list — money the owner puts into the
// business or takes out for themselves. The double-entry is hidden: a
// 'contribution' reads as an "Investment", a 'draw' as a "Withdrawal" — NOT
// "Money in / Money out", which the dashboard already uses for all business
// income and expenses. Keyset infinite
// scroll via usePaginatedList; the kind chip flips fetchPage's identity, which
// reloads page 1. Unscoped by company like the expenses/bills lists.
type EventRow = {
  id: string;
  kind: string;
  amount: string;
  occurredOn: string;
  memo: string | null;
};

const KIND_OPTIONS = [
  { label: 'All', value: '' },
  { label: 'Investments', value: 'contribution' },
  { label: 'Withdrawals', value: 'draw' },
];

type OpeningBalance = { cash: string; receivables: string; payables: string } | null;

const money = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

export default function OwnerMoneyList() {
  const router = useRouter();
  const canCreate = useMay('expenses:write');
  const [kind, setKind] = useState('');
  const [openingBalance, setOpeningBalance] = useState<OpeningBalance>(null);

  // The company's starting balances for the summary card (best-effort). Reloads
  // on focus so it refreshes after the user sets/edits them.
  useFocusEffect(
    useCallback(() => {
      let active = true;
      (async () => {
        const compRes = await api.api.companies.$get();
        if (!active || !compRes.ok) return;
        const { companies } = await compRes.json();
        const company = await pickActiveCompany(companies);
        if (!company) return;
        const obRes = await api.api['owner-money']['opening-balance'].$get({
          query: { companyId: company.id },
        });
        if (active && obRes.ok) setOpeningBalance((await obRes.json()).openingBalance);
      })().catch(() => {});
      return () => {
        active = false;
      };
    }, []),
  );

  const fetchPage = useCallback(
    async (cursor: string | null) => {
      const query = pageQuery(cursor);
      if (kind) query.kind = kind;
      const res = await api.api['owner-money'].$get({ query });
      if (!res.ok) return null;
      const { events, nextCursor } = await res.json();
      return {
        rows: events.map(
          (e): EventRow => ({
            id: e.id,
            kind: e.kind,
            amount: e.amount,
            occurredOn: e.occurredOn,
            memo: e.memo,
          }),
        ),
        nextCursor,
      };
    },
    [kind],
  );

  const { list, loadingMore, loadMore } = usePaginatedList(fetchPage);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="flex-row items-end justify-between px-6 pt-6">
        <View>
          <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
            Investments &amp; withdrawals
          </Text>
          <Text className="mt-2 font-serif text-3xl font-light text-ink">You and the business</Text>
        </View>
        {canCreate ? (
          <Pressable
            onPress={() => router.push('/owner-money/new')}
            className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
          >
            <Text className="text-sm font-medium text-cream">+ Record</Text>
          </Pressable>
        ) : null}
      </View>

      {canCreate ? (
        <Pressable
          onPress={() => router.push('/owner-money/opening-balance')}
          className="mx-6 mt-5 flex-row items-center justify-between gap-3 rounded-sm border border-ink/10 bg-cream-warm px-5 py-4 active:bg-cream"
        >
          <View className="flex-1">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Starting balances
            </Text>
            {openingBalance ? (
              <Text className="mt-1 font-mono text-sm tabular-nums text-ink/80">
                {money(openingBalance.cash)} in the bank
              </Text>
            ) : (
              <Text className="mt-1 text-sm text-ink-subtle">
                Tell us what your business started with.
              </Text>
            )}
          </View>
          <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
            {openingBalance ? 'Edit' : 'Set'}
          </Text>
        </Pressable>
      ) : null}

      <View className="mt-4">
        <FilterChips options={KIND_OPTIONS} value={kind} onChange={setKind} />
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator className="text-ink" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load this.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink-muted">
          {kind ? 'Nothing matches this filter.' : 'Nothing recorded yet.'}
        </Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(e) => e.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator className="text-ink" />
              </View>
            ) : null
          }
          renderItem={({ item }) => {
            const isIn = item.kind === 'contribution';
            return (
              <Pressable
                onPress={() => router.push(`/owner-money/${item.id}`)}
                className="bg-cream-warm px-5 py-4 active:bg-cream"
              >
                <View className="flex-row items-center justify-between">
                  <Text className="flex-1 pr-3 font-serif text-lg text-ink">
                    {isIn ? 'Investment' : 'Withdrawal'}
                  </Text>
                  <Text
                    className={`font-mono tabular-nums ${isIn ? 'text-gold-deep' : 'text-ink'}`}
                  >
                    {isIn ? '+' : '−'}
                    {item.amount}
                  </Text>
                </View>
                <View className="mt-1 flex-row items-center justify-between">
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                    {item.occurredOn}
                  </Text>
                  {item.memo ? (
                    <Text
                      className="flex-1 pl-3 text-right text-xs text-ink-subtle"
                      numberOfLines={1}
                    >
                      {item.memo}
                    </Text>
                  ) : null}
                </View>
              </Pressable>
            );
          }}
        />
      )}
    </SafeAreaView>
  );
}
