// apps/web/src/routes/(app)/owner-money/opening-balance/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
  const current = $derived(data.current);
  const fieldErrors = $derived(form?.fieldErrors ?? {});

  function err(key: string): string | undefined {
    return (fieldErrors as Record<string, string>)[key];
  }
  // Seed each field from a failed submit, else the saved balance, else blank.
  function v(key: 'asOfDate' | 'cash' | 'receivables' | 'payables'): string {
    const submitted = (form?.values as Record<string, unknown> | undefined)?.[key];
    if (typeof submitted === 'string') return submitted;
    const saved = current as Record<string, unknown> | null;
    const val = saved?.[key];
    return typeof val === 'string' ? val : '';
  }
  const dateValue = $derived(v('asOfDate') || current?.asOfDate || data.today);
</script>

<a href="/owner-money" class="eyebrow text-fg/60 hover:text-fg">← My Money</a>
<h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
  Starting balances<span class="text-accent">.</span>
</h1>
<p class="mt-4 max-w-2xl text-sm text-fg/60">
  What your business already had when you started using Thalermark — so your numbers are right from
  day one. Fill in what applies; leave the rest blank.
</p>

{#if form?.formError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.formError}
  </div>
{/if}

<form method="post" action="?/save" class="mt-8 space-y-6" use:enhance>
  <div>
    <label for="asOfDate" class="label">When did you start?<span class="text-accent">*</span></label>
    <input id="asOfDate" name="asOfDate" type="date" required value={dateValue} class="field mt-1" />
    {#if err('asOfDate')}
      <p class="mt-1 text-xs text-danger">{err('asOfDate')}</p>
    {/if}
  </div>

  <div>
    <label for="cash" class="label">Money in the bank</label>
    <p class="text-xs text-fg/50">How much was in the business account when you started.</p>
    <input
      id="cash"
      name="cash"
      type="text"
      inputmode="decimal"
      placeholder="0.00"
      value={v('cash')}
      class="mt-1 w-full rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
    />
    {#if err('cash')}
      <p class="mt-1 text-xs text-danger">{err('cash')}</p>
    {/if}
  </div>

  <div>
    <label for="receivables" class="label">Money customers already owed you</label>
    <p class="text-xs text-fg/50">Unpaid work from before you started here.</p>
    <input
      id="receivables"
      name="receivables"
      type="text"
      inputmode="decimal"
      placeholder="0.00"
      value={v('receivables')}
      class="mt-1 w-full rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
    />
  </div>

  <div>
    <label for="payables" class="label">Money you already owed</label>
    <p class="text-xs text-fg/50">Bills or suppliers you hadn't paid yet.</p>
    <input
      id="payables"
      name="payables"
      type="text"
      inputmode="decimal"
      placeholder="0.00"
      value={v('payables')}
      class="mt-1 w-full rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
    />
  </div>

  <div class="flex items-center gap-4">
    <button type="submit" class="btn">Save</button>
    <a href="/owner-money" class="text-sm text-fg/60 hover:text-fg">Cancel</a>
  </div>
</form>

{#if current}
  <form method="post" action="?/clear" class="mt-8 border-t border-fg/10 pt-6" use:enhance>
    <p class="text-sm text-fg/60">
      Clear your starting balances if you entered them by mistake. This removes them from your books.
    </p>
    <button
      type="submit"
      class="mt-3 rounded-sm border border-danger/30 px-3 py-1 font-mono text-xs uppercase tracking-widest text-danger/80 hover:border-danger hover:text-danger"
    >
      Clear starting balances
    </button>
  </form>
{/if}

// apps/mobile/src/app/(app)/owner-money/opening-balance.tsx
import { openingBalanceUpsertSchema } from '@thalermark/validation';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DateField } from '../../../components/DateField';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { apiErrorMessage } from '../../../lib/api-errors';

// Mirror of apps/web's /owner-money/opening-balance. "Starting balances" — what
// the business already had when it started. One per company (upsert); the
// double-entry is hidden behind plain language.
const todayIso = () => new Date().toISOString().slice(0, 10);

export default function OpeningBalanceScreen() {
  const router = useRouter();
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [bootstrapped, setBootstrapped] = useState(false);
  const [hasExisting, setHasExisting] = useState(false);

  const [asOfDate, setAsOfDate] = useState(todayIso());
  const [cash, setCash] = useState('');
  const [receivables, setReceivables] = useState('');
  const [payables, setPayables] = useState('');

  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const didBootstrap = useRef(false);
  useFocusEffect(
    useCallback(() => {
      if (didBootstrap.current) return;
      didBootstrap.current = true;
      let active = true;
      (async () => {
        const compRes = await api.api.companies.$get();
        if (!active || !compRes.ok) return;
        const { companies } = await compRes.json();
        const company = await pickActiveCompany(companies);
        if (!company) return;
        setCompanyId(company.id);
        const obRes = await api.api['owner-money']['opening-balance'].$get({
          query: { companyId: company.id },
        });
        if (active && obRes.ok) {
          const { openingBalance } = await obRes.json();
          if (openingBalance) {
            setHasExisting(true);
            setAsOfDate(openingBalance.asOfDate);
            setCash(openingBalance.cash);
            setReceivables(openingBalance.receivables);
            setPayables(openingBalance.payables);
          }
        }
      })()
        .catch(() => {})
        .finally(() => {
          if (active) setBootstrapped(true);
        });
      return () => {
        active = false;
      };
    }, []),
  );

  const noCompany = bootstrapped && companyId === null;
  const canSubmit =
    !submitting &&
    !noCompany &&
    (Number(cash) > 0 || Number(receivables) > 0 || Number(payables) > 0);

  async function onSubmit() {
    if (!companyId) return;
    setFormError(null);
    setFieldErrors({});
    const parsed = openingBalanceUpsertSchema.safeParse({
      companyId,
      asOfDate: asOfDate.trim(),
      cash: cash.trim() === '' ? undefined : cash.trim(),
      receivables: receivables.trim() === '' ? undefined : receivables.trim(),
      payables: payables.trim() === '' ? undefined : payables.trim(),
    });
    if (!parsed.success) {
      const errs: Record<string, string> = {};
      for (const issue of parsed.error.issues) {
        const k = String(issue.path[0] ?? '_');
        if (!errs[k]) errs[k] = issue.message;
      }
      setFieldErrors(errs);
      return;
    }
    setSubmitting(true);
    try {
      const res = await api.api['owner-money']['opening-balance'].$put({ json: parsed.data });
      if (!res.ok) {
        const b = (await res.json().catch(() => null)) as { error?: string } | null;
        setFormError(apiErrorMessage(b?.error, 'That could not be saved. Try again.'));
        return;
      }
      router.replace('/owner-money');
    } catch {
      setFormError('That could not be saved. Try again.');
    } finally {
      setSubmitting(false);
    }
  }

  function onClear() {
    if (!companyId) return;
    Alert.alert('Clear starting balances?', 'This removes them from your books.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Clear',
        style: 'destructive',
        onPress: async () => {
          setSubmitting(true);
          try {
            const res = await api.api['owner-money']['opening-balance'].$delete({
              query: { companyId },
            });
            if (res.ok || res.status === 404) router.replace('/owner-money');
          } finally {
            setSubmitting(false);
          }
        },
      },
    ]);
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              ← Investments
            </Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">Starting balances</Text>
          <Text className="mt-2 text-sm text-ink-subtle">
            What your business already had when you started. Fill in what applies; leave the rest
            blank.
          </Text>

          {formError ? (
            <View className="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
              <Text className="text-sm text-oxblood">{formError}</Text>
            </View>
          ) : null}

          <View className="mt-8 gap-5">
            <DateField
              label="When did you start? *"
              value={asOfDate}
              onChange={setAsOfDate}
              error={fieldErrors.asOfDate}
            />
            <MoneyField
              label="Money in the bank"
              hint="How much was in the business account when you started."
              value={cash}
              onChangeText={setCash}
              error={fieldErrors.cash}
            />
            <MoneyField
              label="Money customers already owed you"
              hint="Unpaid work from before you started here."
              value={receivables}
              onChangeText={setReceivables}
            />
            <MoneyField
              label="Money you already owed"
              hint="Bills or suppliers you hadn't paid yet."
              value={payables}
              onChangeText={setPayables}
            />

            {noCompany ? (
              <Text className="text-xs text-oxblood">No company in this workspace.</Text>
            ) : null}

            <Pressable
              onPress={onSubmit}
              disabled={!canSubmit}
              className="mt-2 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
            >
              {submitting ? (
                <ActivityIndicator className="text-cream" />
              ) : (
                <Text className="text-center text-sm font-medium text-cream">Save</Text>
              )}
            </Pressable>

            {hasExisting ? (
              <Pressable
                onPress={onClear}
                disabled={submitting}
                className="mt-2 self-start rounded-sm border border-oxblood/30 px-4 py-3 active:bg-oxblood/5 disabled:opacity-50"
              >
                <Text className="font-mono text-xs uppercase tracking-widest text-oxblood">
                  Clear starting balances
                </Text>
              </Pressable>
            ) : null}
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

function MoneyField({
  label,
  hint,
  value,
  onChangeText,
  error,
}: {
  label: string;
  hint: string;
  value: string;
  onChangeText: (t: string) => void;
  error?: string;
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">{label}</Text>
      <Text className="mt-0.5 text-xs text-ink/45">{hint}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        keyboardType="decimal-pad"
        placeholder="0.00"
        className="mt-1 rounded-sm border border-field bg-cream-warm px-3 py-2 text-right font-mono text-ink"
      />
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}
