// apps/mobile/src/app/(app)/bills/index.tsx
import { useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FilterChips } from '../../../components/FilterChips';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../lib/use-paginated-list';

// Mirror of apps/web's /bills list — accounts payable, the money you owe
// vendors. The API LEFT JOINs the vendor name onto each row, so the list shows
// vendor / due date / status / amount without resolving contacts. Keyset
// infinite scroll via usePaginatedList; the status chip flips fetchPage's
// identity, which reloads page 1. Unscoped by company like the invoices/expenses
// lists (the active-company tile on the dashboard is the company-scoped view).
type BillRow = {
  id: string;
  vendorName: string;
  dueDate: string;
  amount: string;
  status: string;
  reference: string | null;
};

const STATUS_OPTIONS = [
  { label: 'All', value: '' },
  { label: 'Open', value: 'open' },
  { label: 'Paid', value: 'paid' },
  { label: 'Voided', value: 'voided' },
];

const todayIso = () => new Date().toISOString().slice(0, 10);

export default function BillsList() {
  const router = useRouter();
  const canCreate = useMay('expenses:write');
  const [status, setStatus] = useState('');
  const today = todayIso();

  const fetchPage = useCallback(
    async (cursor: string | null) => {
      const query = pageQuery(cursor);
      if (status) query.status = status;
      const res = await api.api.bills.$get({ query });
      if (!res.ok) return null;
      const { bills, nextCursor } = await res.json();
      return {
        rows: bills.map(
          (b): BillRow => ({
            id: b.id,
            vendorName: b.vendorName,
            dueDate: b.dueDate,
            amount: b.amount,
            status: b.status,
            reference: b.reference,
          }),
        ),
        nextCursor,
      };
    },
    [status],
  );

  const { list, loadingMore, loadMore } = usePaginatedList(fetchPage);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="flex-row items-end justify-between px-6 pt-6">
        <View>
          <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">Bills</Text>
          <Text className="mt-2 font-serif text-3xl font-light text-ink">What you owe</Text>
        </View>
        {canCreate ? (
          <Pressable
            onPress={() => router.push('/bills/new')}
            className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
          >
            <Text className="text-sm font-medium text-cream">+ New</Text>
          </Pressable>
        ) : null}
      </View>

      <Pressable
        onPress={() => router.push('/bills/aging')}
        className="mt-4 flex-row items-center justify-between px-6 py-1"
      >
        <Text className="text-sm font-medium text-gold-deep">Aging report</Text>
        <Text className="text-gold-deep">→</Text>
      </Pressable>

      <View className="mt-3">
        <FilterChips options={STATUS_OPTIONS} value={status} onChange={setStatus} />
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator color="#0f1626" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load bills.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink/70">
          {status ? 'No bills with this status.' : 'No bills yet.'}
        </Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(b) => b.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator color="#0f1626" />
              </View>
            ) : null
          }
          renderItem={({ item }) => {
            const overdue = item.status === 'open' && item.dueDate < today;
            return (
              <Pressable
                onPress={() => router.push(`/bills/${item.id}`)}
                className="bg-cream-warm px-5 py-4 active:bg-cream"
              >
                <View className="flex-row items-center justify-between">
                  <Text className="flex-1 pr-3 font-serif text-lg text-ink" numberOfLines={1}>
                    {item.vendorName}
                    {item.reference ? (
                      <Text className="font-mono text-xs text-ink/40"> #{item.reference}</Text>
                    ) : null}
                  </Text>
                  <Text className="font-mono tabular-nums text-ink">{item.amount}</Text>
                </View>
                <View className="mt-1 flex-row items-center justify-between">
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                    {item.status} · due {item.dueDate}
                  </Text>
                  {overdue ? (
                    <Text className="font-mono text-xs uppercase tracking-widest text-oxblood">
                      Overdue
                    </Text>
                  ) : null}
                </View>
              </Pressable>
            );
          }}
        />
      )}
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/bills/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';
  import type { BillRow } from './bill-rows';

  let { data }: PageProps = $props();

  const { filters } = $derived(data);
  const companyId = $derived(data.companyId);

  const STATUSES = [
    { key: '', label: 'All' },
    { key: 'open', label: 'Open' },
    { key: 'paid', label: 'Paid' },
    { key: 'voided', label: 'Voided' },
  ];

  // Seed-and-re-seed via untrack(), the list pattern across the app. The status
  // filter is a link, so changing it navigates here and re-runs load().
  let rows = $state<BillRow[]>(untrack(() => data.rows));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.rows;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  // Open + past its due date = overdue; surfaced with a subtle marker.
  const today = new Date().toISOString().slice(0, 10);

  function statusClass(status: string): string {
    return status === 'paid'
      ? 'bg-accent/15 text-accent'
      : status === 'voided'
        ? 'bg-fg/10 text-fg/50'
        : 'bg-warning/15 text-warning';
  }

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<BillRow>('/bills/more', cursor, {
        companyId,
        status: filters.status,
      });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Bills</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      What you owe<span class="text-accent">.</span>
    </h1>
  </div>
  <div class="flex items-center gap-4">
    <a href="/bills/aging" class="text-sm text-fg/60 hover:text-fg">Aging report →</a>
    {#if may(data.role, 'expenses:write')}
      <a href="/bills/new" class="btn">+ New bill</a>
    {/if}
  </div>
</div>

<!-- Status filter. Plain links so the filter lives in the URL. -->
<div class="mt-8 flex flex-wrap gap-2">
  {#each STATUSES as s (s.key)}
    <a
      href={s.key ? `/bills?status=${s.key}` : '/bills'}
      class="rounded-sm border px-3 py-1 font-mono text-xs uppercase tracking-widest transition-colors {filters.status ===
      s.key
        ? 'border-accent text-accent'
        : 'border-fg/15 text-fg/60 hover:border-fg/40 hover:text-fg'}"
    >
      {s.label}
    </a>
  {/each}
</div>

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">
    {filters.status ? 'No bills with this status.' : 'No bills yet.'}
  </p>
{:else}
  <div class="mt-6 overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
    <table class="w-full text-left text-sm">
      <thead class="bg-surface">
        <tr class="label">
          <th class="px-5 py-3">Vendor</th>
          <th class="px-5 py-3">Due</th>
          <th class="px-5 py-3">Status</th>
          <th class="px-5 py-3 text-right">Amount</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-fg/10">
        {#each rows as bill (bill.id)}
          {@const overdue = bill.status === 'open' && bill.dueDate < today}
          <tr class="hover:bg-surface">
            <td class="px-5 py-4">
              <a href="/bills/{bill.id}" class="font-serif text-fg hover:text-accent">
                {bill.vendorName}
              </a>
              {#if bill.reference}
                <span class="ml-2 align-middle font-mono text-xs text-fg/40">#{bill.reference}</span>
              {/if}
            </td>
            <td class="px-5 py-4 font-mono tabular-nums text-fg/80">
              {bill.dueDate}
              {#if overdue}
                <span class="ml-1 text-xs font-medium uppercase tracking-wide text-danger">overdue</span>
              {/if}
            </td>
            <td class="px-5 py-4">
              <span
                class="rounded-sm px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide {statusClass(
                  bill.status,
                )}"
              >
                {bill.status}
              </span>
            </td>
            <td class="px-5 py-4 text-right font-mono tabular-nums text-fg">{fmt(bill.amount)}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}
