// apps/mobile/src/app/(app)/invoices/recurring/new.tsx
import {
  type LineItemType,
  type RecurringInvoiceLineItemInput,
  addMoney,
  contactCreateSchema,
  formatUnitPrice,
  multiplyMoney,
  recurringInvoiceCreateSchema,
  sumMoney,
  unitPriceFromTotal,
} from '@thalermark/validation';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ContactField } from '../../../../components/ContactField';
import { DateField } from '../../../../components/DateField';
import { type ItemPatch, ItemPickerField } from '../../../../components/ItemPickerField';
import { TaxRow } from '../../../../components/TaxRow';
import { TypeRow } from '../../../../components/TypeRow';
import { pickActiveCompany } from '../../../../lib/active-company';
import { api } from '../../../../lib/api';
import { NEW_CONTACT, findEmailDupe } from '../../../../lib/contact-dupes';
import { type TaxPolicyLite, lineTax, policyRate, resolvePolicyId } from '../../../../lib/line-tax';

// Mirror of apps/web's /recurring/new — the invoice create form minus
// number/issue/due, plus cadence (frequency, every-N, start/end, max
// occurrences, net terms). Counters are JSON numbers; money/qty decimal
// strings. Contact via the ContactField type-ahead; two-step create with
// inline contact.
const FREQUENCIES = ['weekly', 'monthly', 'yearly'] as const;
const FREQ_LABELS: Record<string, string> = {
  weekly: 'Weekly',
  monthly: 'Monthly',
  yearly: 'Yearly',
};

type Row = {
  description: string;
  quantity: string;
  unitPrice: string;
  amount: string;
  sourceItemId: string | null;
  type: LineItemType;
  taxable: boolean;
  taxPolicyId: string;
};
const blankRow = (): Row => ({
  description: '',
  quantity: '',
  unitPrice: '',
  amount: '',
  sourceItemId: null,
  type: 'service',
  taxable: false,
  taxPolicyId: '',
});
const todayIso = () => new Date().toISOString().slice(0, 10);

const FRIENDLY: Record<string, string> = {
  customer_company_mismatch: 'Selected contact does not belong to this company.',
  contact_not_found: 'Selected contact no longer exists.',
};

export default function NewRecurring() {
  const router = useRouter();

  const [companyId, setCompanyId] = useState<string | null>(null);
  const [bootstrapped, setBootstrapped] = useState(false);

  const [contactId, setContactId] = useState('');
  const [contactName, setContactName] = useState('');
  const [newName, setNewName] = useState('');
  const [newEmail, setNewEmail] = useState('');

  const [frequency, setFrequency] = useState<(typeof FREQUENCIES)[number]>('monthly');
  const [intervalCount, setIntervalCount] = useState('1');
  const [startDate, setStartDate] = useState(todayIso());
  const [endDate, setEndDate] = useState('');
  const [maxOccurrences, setMaxOccurrences] = useState('');
  const [netTermsDays, setNetTermsDays] = useState('');
  const [taxPolicies, setTaxPolicies] = useState<TaxPolicyLite[]>([]);
  const [notes, setNotes] = useState('');
  const [rows, setRows] = useState<Row[]>([blankRow()]);

  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const didBootstrap = useRef(false);
  useFocusEffect(
    useCallback(() => {
      if (didBootstrap.current) return;
      didBootstrap.current = true;
      let active = true;
      (async () => {
        const compRes = await api.api.companies.$get();
        if (!active) return;
        if (compRes.ok) {
          const { companies } = await compRes.json();
          const company = await pickActiveCompany(companies);
          if (company) {
            setCompanyId(company.id);
            const polRes = await api.api['tax-policies'].$get({
              query: { companyId: company.id },
            });
            if (active && polRes.ok) {
              const { taxPolicies: pols } = await polRes.json();
              setTaxPolicies(
                pols.map((p) => ({
                  id: p.id,
                  name: p.name,
                  ratePct: p.ratePct,
                  isDefault: p.isDefault,
                })),
              );
            }
          }
        }
        if (active) setBootstrapped(true);
      })().catch(() => {
        if (active) setBootstrapped(true);
      });
      return () => {
        active = false;
      };
    }, []),
  );

  const inlineMode = contactId === NEW_CONTACT;

  const computedRows = useMemo(
    () =>
      rows.map((r) => {
        const rate = r.taxable ? policyRate(taxPolicies, r.taxPolicyId) : '0';
        return { ...r, tax: lineTax(r.taxable, rate, r.amount) };
      }),
    [rows, taxPolicies],
  );
  const subtotal = useMemo(() => sumMoney(computedRows.map((r) => r.amount)), [computedRows]);
  const taxTotal = useMemo(() => sumMoney(computedRows.map((r) => r.tax)), [computedRows]);
  const total = useMemo(() => addMoney(subtotal, taxTotal), [subtotal, taxTotal]);

  const patchRow = (i: number, patch: Partial<Row>) =>
    setRows((rs) => rs.map((r, j) => (j === i ? { ...r, ...patch } : r)));
  // Keep unit price and line total in step (mirror of web). Editing quantity or
  // unit price re-derives the amount (unit price sticky); editing the amount
  // back-computes a 4dp unit price so an agreed total that doesn't divide evenly
  // (e.g. $650 over 7 → $92.8571 → $650.00) is representable.
  const setRowQuantity = (i: number, quantity: string) =>
    setRows((rs) =>
      rs.map((r, j) =>
        j === i ? { ...r, quantity, amount: multiplyMoney(quantity, r.unitPrice) } : r,
      ),
    );
  const setRowUnitPrice = (i: number, unitPrice: string) =>
    setRows((rs) =>
      rs.map((r, j) =>
        j === i ? { ...r, unitPrice, amount: multiplyMoney(r.quantity, unitPrice) } : r,
      ),
    );
  const setRowAmount = (i: number, amount: string) =>
    setRows((rs) =>
      rs.map((r, j) =>
        j === i ? { ...r, amount, unitPrice: unitPriceFromTotal(amount, r.quantity) } : r,
      ),
    );
  const addRow = () => setRows((rs) => [...rs, blankRow()]);
  const removeRow = (i: number) =>
    setRows((rs) => (rs.length <= 1 ? rs : rs.filter((_, j) => j !== i)));
  const toggleRowTaxable = (i: number) =>
    setRows((rs) =>
      rs.map((r, j) => {
        if (j !== i) return r;
        const turningOn = !r.taxable;
        return {
          ...r,
          taxable: turningOn,
          taxPolicyId:
            turningOn && !r.taxPolicyId ? resolvePolicyId(taxPolicies, '') : r.taxPolicyId,
        };
      }),
    );
  const applyPick = (i: number, patch: ItemPatch) => {
    const { taxable, taxPolicyId, ...rest } = patch;
    setRows((rs) =>
      rs.map((r, j) => {
        if (j !== i) return r;
        const merged: Row = { ...r, ...rest };
        if (taxable !== undefined) {
          merged.taxable = taxable;
          merged.taxPolicyId = taxable ? resolvePolicyId(taxPolicies, taxPolicyId ?? '') : '';
        }
        // A pick sets unit price + quantity; keep the amount in step.
        merged.amount = multiplyMoney(merged.quantity, merged.unitPrice);
        return merged;
      }),
    );
  };

  const noCompany = bootstrapped && companyId === null;
  const hasContact = inlineMode ? newName.trim().length > 0 : contactId !== '';
  const canSubmit = !submitting && !noCompany && hasContact;

  // Parse a counter TextInput → a positive integer, or undefined when blank/bad.
  const toInt = (s: string): number | undefined => {
    const n = Number(s.trim());
    return s.trim() !== '' && Number.isInteger(n) && n >= 0 ? n : undefined;
  };

  async function onSubmit() {
    if (!companyId) {
      setFormError('No company in this workspace.');
      return;
    }
    setFormError(null);
    setFieldErrors({});

    let resolvedContactId = contactId;
    if (inlineMode) {
      const parsedCust = contactCreateSchema.safeParse({
        companyId,
        name: newName.trim(),
        email: newEmail.trim() === '' ? undefined : newEmail.trim(),
      });
      if (!parsedCust.success) {
        const errs: Record<string, string> = {};
        for (const issue of parsedCust.error.issues) {
          const key = `contact_${String(issue.path[0] ?? '_')}`;
          if (!errs[key]) errs[key] = issue.message;
        }
        setFieldErrors(errs);
        return;
      }
      setSubmitting(true);
      try {
        // HARD BLOCK on email exact match (the API doesn't dedupe). Search by
        // the email so the check is correct at any contact count.
        if (parsedCust.data.email) {
          const dres = await api.api.contacts.$get({
            query: { q: parsedCust.data.email, companyId },
          });
          if (dres.ok) {
            const { contacts: list } = await dres.json();
            const dupe = findEmailDupe(
              parsedCust.data.email,
              list.map((c) => ({ id: c.id, name: c.name, email: c.email ?? null })),
            );
            if (dupe) {
              setFieldErrors({ contact_email: `${dupe.name} already uses this email.` });
              setSubmitting(false);
              return;
            }
          }
        }
        const custRes = await api.api.contacts.$post({ json: parsedCust.data });
        if (!custRes.ok) {
          const body = (await custRes.json().catch(() => null)) as { error?: string } | null;
          setFormError(body?.error ?? 'contact_create_failed');
          return;
        }
        const created = await custRes.json();
        resolvedContactId = created.id;
        setContactName(created.name);
        setContactId(created.id);
        setNewName('');
        setNewEmail('');
      } catch {
        setFormError('contact_create_failed');
        setSubmitting(false);
        return;
      }
    }

    const lineItems: RecurringInvoiceLineItemInput[] = rows.map((r, i) => {
      const amount = multiplyMoney(r.quantity, r.unitPrice);
      const rate = r.taxable ? policyRate(taxPolicies, r.taxPolicyId) : '0';
      return {
        position: i + 1,
        description: r.description.trim(),
        quantity: r.quantity.trim(),
        unitPrice: r.unitPrice.trim(),
        amount,
        type: r.type,
        taxable: r.taxable,
        taxRatePct: rate,
        taxAmount: lineTax(r.taxable, rate, amount),
        taxPolicyId: r.taxable ? r.taxPolicyId || undefined : undefined,
        sourceItemId: r.sourceItemId ?? undefined,
      };
    });
    const sub = sumMoney(lineItems.map((li) => li.amount));
    const taxVal = sumMoney(lineItems.map((li) => li.taxAmount ?? '0'));
    const payload = {
      companyId,
      contactId: resolvedContactId,
      frequency,
      intervalCount: toInt(intervalCount) ?? 1,
      startDate: startDate.trim(),
      endDate: endDate.trim() === '' ? undefined : endDate.trim(),
      maxOccurrences: toInt(maxOccurrences),
      netTermsDays: toInt(netTermsDays),
      subtotal: sub,
      tax: taxVal,
      total: addMoney(sub, taxVal),
      notes: notes.trim() === '' ? undefined : notes.trim(),
      lineItems,
    };

    const parsed = recurringInvoiceCreateSchema.safeParse(payload);
    if (!parsed.success) {
      const errs: Record<string, string> = {};
      for (const issue of parsed.error.issues) {
        const top = String(issue.path[0] ?? '_');
        const key = top === 'lineItems' ? 'lineItems' : top;
        if (!errs[key]) errs[key] = issue.message;
      }
      setFieldErrors(errs);
      setSubmitting(false);
      return;
    }

    setSubmitting(true);
    try {
      const res = await api.api['recurring-invoices'].$post({ json: parsed.data });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        const code = body?.error ?? 'create_failed';
        setFormError(FRIENDLY[code] ?? code);
        return;
      }
      const created = await res.json();
      router.replace(`/invoices/recurring/${created.id}`);
    } catch {
      setFormError('create_failed');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
              ← Recurring
            </Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">New schedule</Text>

          {formError ? (
            <View className="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
              <Text className="text-sm text-oxblood">{formError}</Text>
            </View>
          ) : null}

          <View className="mt-8 space-y-5">
            <ContactField
              label="Contact *"
              companyId={companyId}
              contactName={contactName}
              setContactName={setContactName}
              contactId={contactId}
              setContactId={setContactId}
              error={fieldErrors.contactId}
              newName={newName}
              setNewName={setNewName}
              newEmail={newEmail}
              setNewEmail={setNewEmail}
              nameError={fieldErrors.contact_name}
              emailError={fieldErrors.contact_email}
            />

            {/* Cadence */}
            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Frequency
              </Text>
              <View className="mt-2 flex-row gap-2">
                {FREQUENCIES.map((f) => (
                  <Pressable
                    key={f}
                    onPress={() => setFrequency(f)}
                    className={`flex-1 rounded-sm border px-3 py-2 ${
                      frequency === f ? 'border-gold-deep bg-gold-deep/10' : 'border-ink/20'
                    }`}
                  >
                    <Text className={`text-center ${frequency === f ? 'text-ink' : 'text-ink/70'}`}>
                      {FREQ_LABELS[f]}
                    </Text>
                  </Pressable>
                ))}
              </View>
            </View>
            <LabeledInput
              label="Every (count)"
              value={intervalCount}
              onChangeText={setIntervalCount}
              error={fieldErrors.intervalCount}
              keyboardType="number-pad"
            />
            <DateField
              label="Start date *"
              value={startDate}
              onChange={setStartDate}
              error={fieldErrors.startDate}
            />
            <DateField
              label="End date (optional)"
              value={endDate}
              onChange={setEndDate}
              error={fieldErrors.endDate}
              optional
            />
            <LabeledInput
              label="Max occurrences (optional)"
              value={maxOccurrences}
              onChangeText={setMaxOccurrences}
              error={fieldErrors.maxOccurrences}
              keyboardType="number-pad"
            />
            <LabeledInput
              label="Net terms days (default 30)"
              value={netTermsDays}
              onChangeText={setNetTermsDays}
              error={fieldErrors.netTermsDays}
              keyboardType="number-pad"
            />

            {/* Line items */}
            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Line items
              </Text>
              {fieldErrors.lineItems ? (
                <Text className="mt-1 text-xs text-oxblood">{fieldErrors.lineItems}</Text>
              ) : null}
              <View className="mt-2 space-y-4">
                {rows.map((row, i) => (
                  // biome-ignore lint/suspicious/noArrayIndexKey: rows are positional and reorder-free
                  <View key={i} className="rounded-sm border border-ink/10 bg-cream-warm p-3">
                    <ItemPickerField
                      description={row.description}
                      onChange={(patch) => applyPick(i, patch)}
                    />
                    <TypeRow value={row.type} onSelect={(t) => patchRow(i, { type: t })} />
                    <View className="mt-2 flex-row gap-2">
                      <View className="flex-1">
                        <Text className="font-mono text-[10px] uppercase tracking-widest text-ink/50">
                          Qty
                        </Text>
                        <TextInput
                          value={row.quantity}
                          onChangeText={(t) => setRowQuantity(i, t)}
                          inputMode="decimal"
                          className="mt-1 rounded-sm border border-ink/15 bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                        />
                      </View>
                      <View className="flex-1">
                        <Text className="font-mono text-[10px] uppercase tracking-widest text-ink/50">
                          Unit price
                        </Text>
                        <TextInput
                          value={row.unitPrice}
                          onChangeText={(t) => setRowUnitPrice(i, t)}
                          inputMode="decimal"
                          className="mt-1 rounded-sm border border-ink/15 bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                        />
                      </View>
                      <View className="flex-1">
                        <Text className="font-mono text-[10px] uppercase tracking-widest text-ink/50">
                          Amount
                        </Text>
                        <TextInput
                          value={row.amount}
                          onChangeText={(t) => setRowAmount(i, t)}
                          inputMode="decimal"
                          className="mt-1 rounded-sm border border-ink/15 bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                        />
                      </View>
                    </View>
                    <TaxRow
                      taxPolicies={taxPolicies}
                      taxable={row.taxable}
                      taxPolicyId={row.taxPolicyId}
                      lineTaxAmount={computedRows[i]?.tax ?? '0.00'}
                      onToggle={() => toggleRowTaxable(i)}
                      onSelectPolicy={(pid) => patchRow(i, { taxPolicyId: pid })}
                    />
                    {rows.length > 1 ? (
                      <Pressable onPress={() => removeRow(i)} className="mt-2 self-end">
                        <Text className="font-mono text-xs uppercase tracking-wider text-oxblood">
                          Remove
                        </Text>
                      </Pressable>
                    ) : null}
                  </View>
                ))}
              </View>
              <Pressable onPress={addRow} className="mt-3">
                <Text className="text-sm font-medium text-gold-deep">+ Add row</Text>
              </Pressable>
            </View>

            <View className="rounded-sm border border-ink/10 bg-cream-warm p-4">
              <TotalRow label="Subtotal" value={subtotal} />
              <TotalRow label="Tax" value={taxTotal} />
              <View className="mt-3 border-t border-ink/10 pt-3">
                <TotalRow label="Total per invoice" value={total} emphasize />
              </View>
            </View>

            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">Notes</Text>
              <TextInput
                value={notes}
                onChangeText={setNotes}
                multiline
                className="mt-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
              />
            </View>

            {noCompany ? (
              <Text className="text-xs text-oxblood">No company in this workspace.</Text>
            ) : null}

            <Pressable
              onPress={onSubmit}
              disabled={!canSubmit}
              className="mt-2 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
            >
              {submitting ? (
                <ActivityIndicator color="#f4ede0" />
              ) : (
                <Text className="text-center text-sm font-medium text-cream">Create schedule</Text>
              )}
            </Pressable>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

function LabeledInput({
  label,
  value,
  onChangeText,
  error,
  autoCapitalize,
  keyboardType,
}: {
  label: string;
  value: string;
  onChangeText: (t: string) => void;
  error?: string;
  autoCapitalize?: 'none';
  keyboardType?: 'number-pad';
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">{label}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        autoCapitalize={autoCapitalize}
        keyboardType={keyboardType}
        className="mt-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
      />
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}

function TotalRow({
  label,
  value,
  emphasize,
}: {
  label: string;
  value: string;
  emphasize?: boolean;
}) {
  return (
    <View className="flex-row justify-between">
      <Text
        className={`font-mono text-xs uppercase tracking-widest ${emphasize ? 'text-ink/70' : 'text-ink/50'}`}
      >
        {label}
      </Text>
      <Text className={`font-mono tabular-nums text-ink ${emphasize ? 'text-lg' : ''}`}>
        {value}
      </Text>
    </View>
  );
}

// apps/web/src/routes/(app)/recurring/new/+page.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import ContactPicker from '$lib/components/ContactPicker.svelte';
  import ItemPicker from '$lib/components/ItemPicker.svelte';
  import { defaultPolicyId, lineTax, policyRate } from '$lib/line-tax';
  import {
    type LineItemType,
    addMoney,
    formatUnitPrice,
    multiplyMoney,
    sumMoney,
    unitPriceFromTotal,
  } from '@thalermark/validation';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  type Row = {
    description: string;
    quantity: string;
    unitPrice: string;
    amount: string;
    sourceItemId: string | null;
    type: LineItemType;
    taxable: boolean;
    taxPolicyId: string;
  };

  function blankRow(): Row {
    return { description: '', quantity: '', unitPrice: '', amount: '', sourceItemId: null, type: 'service', taxable: false, taxPolicyId: '' };
  }

  // Editing quantity/unit price re-derives the amount (unit price sticky);
  // editing the amount back-computes a 4dp unit price so an agreed total that
  // doesn't divide evenly is representable (e.g. $650 over 7 → $92.8571 →
  // $650.00). The form submits quantity + unit price; the server recomputes the
  // amount, so the (unnamed) amount input is preview sugar steering the price.
  function recalcAmount(row: Row) {
    row.amount = multiplyMoney(row.quantity, row.unitPrice);
  }
  function recalcPrice(row: Row) {
    row.unitPrice = unitPriceFromTotal(row.amount, row.quantity);
  }

  function resolvePolicyId(pref: string): string {
    if (pref && data.taxPolicies.some((p) => p.id === pref)) return pref;
    return defaultPolicyId(data.taxPolicies) || data.taxPolicies[0]?.id || '';
  }
  function onTaxableChange(row: Row) {
    if (row.taxable && !row.taxPolicyId) row.taxPolicyId = resolvePolicyId('');
  }
  function applyItemTax(row: Row, taxable: boolean, taxPolicyId: string | null) {
    row.taxable = taxable;
    row.taxPolicyId = taxable ? resolvePolicyId(taxPolicyId ?? '') : '';
  }

  function todayIso(): string {
    return new Date().toISOString().slice(0, 10);
  }

  // Seeding mirrors /estimates/new: static inputs render value={values?.X ??
  // default}; the live-preview line rows use $state with untrack() initializers.
  // Tax is derived from the lines.
  const values = $derived(form?.values);

  let rows = $state<Row[]>(
    untrack(() => {
      const seeded = form?.values?.lineItems;
      return seeded && seeded.length > 0
        ? seeded.map((li) => ({
            description: li.description,
            quantity: li.quantity,
            unitPrice: formatUnitPrice(li.unitPrice),
            amount: multiplyMoney(li.quantity, li.unitPrice),
            sourceItemId: li.sourceItemId ?? null,
            type: li.type ?? 'service',
            taxable: li.taxable ?? false,
            taxPolicyId: li.taxPolicyId ?? '',
          }))
        : [blankRow()];
    }),
  );

  const computedRows = $derived(
    rows.map((r) => {
      const rate = r.taxable ? policyRate(data.taxPolicies, r.taxPolicyId) : '0';
      return { ...r, tax: lineTax(r.taxable, rate, r.amount) };
    }),
  );
  const subtotal = $derived(sumMoney(computedRows.map((r) => r.amount)));
  const taxTotal = $derived(sumMoney(computedRows.map((r) => r.tax)));
  const total = $derived(addMoney(subtotal, taxTotal));

  const fieldErrors = $derived(form?.fieldErrors ?? {});
  function err(key: string): string | undefined {
    return (fieldErrors as Record<string, string>)[key];
  }

  function addRow() {
    rows.push(blankRow());
  }

  function removeRow(index: number) {
    if (rows.length <= 1) return;
    rows.splice(index, 1);
  }
</script>

<a href="/recurring" class="eyebrow text-fg/60 hover:text-fg">← Recurring</a>
<h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
  New schedule<span class="text-accent">.</span>
</h1>

{#if form?.formError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.formError}
  </div>
{/if}

  <form method="post" class="mt-8 space-y-8">
    <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
      <div>
        <label for="contactName" class="label">
          Contact<span class="text-accent">*</span>
        </label>
        <ContactPicker
          initialContactId={values?.contactId ?? ''}
          initialContactName={values?.contactName ?? ''}
          initialNewName={values?.newContactName ?? ''}
          initialNewEmail={values?.newContactEmail ?? ''}
          fieldError={err('contactId')}
          contactErrors={form?.contactErrors}
          dupeContact={form?.dupeContact}
        />
      </div>

      <div>
        <label for="startDate" class="label">
          First invoice on<span class="text-accent">*</span>
        </label>
        <input
          id="startDate"
          name="startDate"
          type="date"
          required
          value={values?.startDate ?? todayIso()}
          class="field mt-1"
        />
        {#if err('startDate')}
          <p class="mt-1 text-xs text-danger">{err('startDate')}</p>
        {/if}
      </div>

      <div>
        <label for="frequency" class="label">
          Frequency<span class="text-accent">*</span>
        </label>
        <select
          id="frequency"
          name="frequency"
          required
          class="field mt-1"
        >
          {#each ['weekly', 'monthly', 'yearly'] as f (f)}
            <option value={f} selected={(values?.frequency ?? 'monthly') === f}>
              {f[0].toUpperCase() + f.slice(1)}
            </option>
          {/each}
        </select>
        {#if err('frequency')}
          <p class="mt-1 text-xs text-danger">{err('frequency')}</p>
        {/if}
      </div>

      <div>
        <label for="intervalCount" class="label">
          Repeat every<span class="text-accent">*</span>
        </label>
        <input
          id="intervalCount"
          name="intervalCount"
          type="number"
          min="1"
          required
          value={values?.intervalCount ?? '1'}
          class="field mt-1"
        />
        <p class="mt-1 text-xs text-fg/50">e.g. 2 = every other period.</p>
        {#if err('intervalCount')}
          <p class="mt-1 text-xs text-danger">{err('intervalCount')}</p>
        {/if}
      </div>

      <div>
        <label for="netTermsDays" class="label">
          Payment terms (days)
        </label>
        <input
          id="netTermsDays"
          name="netTermsDays"
          type="number"
          min="0"
          value={values?.netTermsDays ?? '30'}
          class="field mt-1"
        />
        <p class="mt-1 text-xs text-fg/50">Due date = issue date + this many days.</p>
        {#if err('netTermsDays')}
          <p class="mt-1 text-xs text-danger">{err('netTermsDays')}</p>
        {/if}
      </div>

      <div>
        <label for="endDate" class="label">
          End date
        </label>
        <input
          id="endDate"
          name="endDate"
          type="date"
          value={values?.endDate ?? ''}
          class="field mt-1"
        />
        {#if err('endDate')}
          <p class="mt-1 text-xs text-danger">{err('endDate')}</p>
        {/if}
      </div>

      <div>
        <label for="maxOccurrences" class="label">
          Stop after N invoices
        </label>
        <input
          id="maxOccurrences"
          name="maxOccurrences"
          type="number"
          min="1"
          value={values?.maxOccurrences ?? ''}
          class="field mt-1"
        />
        {#if err('maxOccurrences')}
          <p class="mt-1 text-xs text-danger">{err('maxOccurrences')}</p>
        {/if}
      </div>
    </div>
    <p class="text-xs text-fg/50">
      End date and stop-after are both optional — leave blank to run until you pause or end it.
    </p>

    <fieldset class="space-y-3">
      <legend class="label">Line items</legend>
      {#if err('lineItems')}
        <p class="text-xs text-danger">{err('lineItems')}</p>
      {/if}
      <div class="overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
        <table class="w-full text-left text-sm">
          <thead class="bg-surface">
            <tr class="label">
              <th class="px-3 py-2">Description</th>
              <th class="w-28 px-3 py-2 text-right">Qty</th>
              <th class="w-32 px-3 py-2 text-right">Unit price</th>
              <th class="w-36 px-3 py-2">Tax</th>
              <th class="w-32 px-3 py-2 text-right">Amount</th>
              <th class="w-10 px-3 py-2"></th>
            </tr>
          </thead>
          <tbody class="divide-y divide-fg/10">
            {#each rows as row, i (i)}
              <tr>
                <td class="px-3 py-2 align-top">
                  <ItemPicker
                    bind:description={row.description}
                    bind:quantity={row.quantity}
                    bind:unitPrice={row.unitPrice}
                    bind:sourceItemId={row.sourceItemId}
                    onpick={(s) => {
                      row.type = s.type;
                      applyItemTax(row, s.taxable, s.taxPolicyId);
                      recalcAmount(row);
                    }}
                  />
                  <select
                    bind:value={row.type}
                    name="li_type"
                    aria-label="Type"
                    class="mt-1 rounded-sm border border-fg/15 bg-surface px-1.5 py-1 text-xs text-fg/70 focus:border-accent focus:outline-none"
                  >
                    <option value="service">Service</option>
                    <option value="product">Product</option>
                  </select>
                </td>
                <td class="px-3 py-2 align-top">
                  <input
                    type="text"
                    name="li_quantity"
                    inputmode="decimal"
                    required
                    bind:value={row.quantity}
                    oninput={() => recalcAmount(row)}
                    class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                  />
                </td>
                <td class="px-3 py-2 align-top">
                  <input
                    type="text"
                    name="li_unitPrice"
                    inputmode="decimal"
                    required
                    bind:value={row.unitPrice}
                    oninput={() => recalcAmount(row)}
                    class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                  />
                </td>
                <td class="px-3 py-2 align-top">
                  <label class="flex items-center gap-1.5 text-xs text-fg/70">
                    <input
                      type="checkbox"
                      bind:checked={row.taxable}
                      onchange={() => onTaxableChange(row)}
                      class="size-4 accent-accent"
                    />
                    Taxable
                  </label>
                  {#if row.taxable}
                    {#if data.taxPolicies.length > 0}
                      <select
                        bind:value={row.taxPolicyId}
                        aria-label="Tax policy"
                        class="mt-1 w-full rounded-sm border border-fg/15 bg-surface px-1.5 py-1 text-xs text-fg focus:border-accent focus:outline-none"
                      >
                        {#each data.taxPolicies as p (p.id)}
                          <option value={p.id}>{p.name} ({Number(p.ratePct)}%)</option>
                        {/each}
                      </select>
                    {:else}
                      <a
                        href="/settings/tax-policies/new"
                        class="mt-1 block text-[0.65rem] text-accent hover:underline"
                      >
                        + Add a rate
                      </a>
                    {/if}
                  {/if}
                  <input type="hidden" name="li_taxable" value={row.taxable ? '1' : '0'} />
                  <input
                    type="hidden"
                    name="li_taxPolicyId"
                    value={row.taxable ? row.taxPolicyId : ''}
                  />
                </td>
                <td class="px-3 py-2 align-top">
                  <input
                    type="text"
                    inputmode="decimal"
                    aria-label="Amount"
                    bind:value={row.amount}
                    oninput={() => recalcPrice(row)}
                    class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                  />
                  {#if row.taxable}
                    <span class="mt-1 block text-right text-[0.65rem] font-normal text-fg/50">
                      +{computedRows[i]?.tax ?? '0.00'} tax
                    </span>
                  {/if}
                </td>
                <td class="px-3 py-2 text-right align-top">
                  <button
                    type="button"
                    onclick={() => removeRow(i)}
                    disabled={rows.length <= 1}
                    aria-label="Remove row"
                    class="text-fg/50 transition-colors hover:text-danger disabled:cursor-not-allowed disabled:opacity-30"
                  >
                    ×
                  </button>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
      <button type="button" onclick={addRow} class="text-sm font-medium text-accent hover:text-fg">
        + Add row
      </button>
    </fieldset>

    <div class="flex justify-end">
      <dl class="w-full max-w-xs rounded-sm border border-fg/10 bg-surface-2 p-4 text-sm">
        <div class="flex justify-between">
          <dt class="label">Subtotal</dt>
          <dd class="font-mono tabular-nums text-fg">{subtotal}</dd>
        </div>
        <div class="mt-2 flex justify-between">
          <dt class="label">Tax</dt>
          <dd class="font-mono tabular-nums text-fg">{taxTotal}</dd>
        </div>
        <div class="mt-3 flex justify-between border-t border-fg/10 pt-3">
          <dt class="font-mono text-xs uppercase tracking-widest text-fg/70">Total per invoice</dt>
          <dd class="font-mono tabular-nums text-lg text-fg">{total}</dd>
        </div>
      </dl>
    </div>

    <div>
      <label for="notes" class="label">Notes</label>
      <textarea
        id="notes"
        name="notes"
        rows="4"
        maxlength="5000"
        class="field mt-1"
        >{values?.notes ?? ''}</textarea
      >
    </div>

    <div class="flex items-center gap-4">
      <button
        type="submit"
        class="btn"
      >
        Create schedule
      </button>
      <a href="/recurring" class="text-sm text-fg/60 hover:text-fg">Cancel</a>
    </div>
  </form>
