// apps/web/src/routes/(app)/search/+page.svelte
<script lang="ts">
  import { formatMoney, groupByType, hrefFor } from '$lib/global-search';

  let { data } = $props();

  const groups = $derived(groupByType(data.results));
  const total = $derived(data.results.length);

  // Links rather than buttons so paging works with JS off, consistent with the
  // list pages' plain-GET filter forms.
  function pageHref(page: number): string {
    const sp = new URLSearchParams({ q: data.q });
    if (data.scope === 'all') sp.set('scope', 'all');
    if (page > 1) sp.set('page', String(page));
    return `/search?${sp}`;
  }

  function scopeHref(scope: 'company' | 'all'): string {
    const sp = new URLSearchParams({ q: data.q });
    if (scope === 'all') sp.set('scope', 'all');
    return `/search?${sp}`;
  }
</script>

<svelte:head><title>Search · Thalermark</title></svelte:head>

<h1 class="font-serif text-4xl font-light text-fg">Search</h1>

<!-- Plain GET form: works with JS disabled, and keeps the query in the URL so a
     result set is linkable. -->
<form method="GET" action="/search" class="mt-6 flex items-center gap-3">
  <input
    type="text"
    name="q"
    value={data.q}
    maxlength="200"
    autocomplete="off"
    placeholder="Search invoices, estimates, contacts, expenses, bills, jobs, items…"
    class="field flex-1"
    aria-label="Search"
  />
  {#if data.scope === 'all'}
    <input type="hidden" name="scope" value="all" />
  {/if}
  <button type="submit" class="btn">Search</button>
</form>

{#if data.q !== ''}
  <div class="mt-4 flex items-center gap-4 font-mono text-xs uppercase tracking-widest">
    <a
      href={scopeHref('company')}
      class="hover:text-fg {data.scope === 'company' ? 'text-fg' : 'text-fg/50'}"
    >
      This business
    </a>
    <a
      href={scopeHref('all')}
      class="hover:text-fg {data.scope === 'all' ? 'text-fg' : 'text-fg/50'}"
    >
      All businesses
    </a>
  </div>
{/if}

{#if data.q === ''}
  <p class="mt-10 text-sm text-fg/60">
    Type anything — a customer's name, an invoice number, an amount, a note on a receipt.
  </p>
{:else if total === 0}
  <div class="callout mt-10">
    <p class="text-sm text-fg/80">
      <span class="text-fg">Nothing matched “{data.q}”.</span>
      Search covers invoices, estimates, contacts, expenses, bills, jobs and items — names,
      numbers, amounts and notes. Try a shorter word, or check you're looking in the right
      business.
    </p>
  </div>
{:else}
  <p class="mt-8 font-mono text-xs uppercase tracking-widest text-fg/50" role="status">
    {total} result{total === 1 ? '' : 's'}{data.page > 1 ? ` · page ${data.page}` : ''}
  </p>

  {#each groups as group (group.type)}
    <section class="mt-8">
      <h2 class="label">{group.label}</h2>
      <ul class="mt-2 divide-y divide-fg/10 border-y border-fg/10">
        {#each group.items as hit (hit.entityId)}
          <li>
            <a
              href={hrefFor(hit.entityType, hit.entityId)}
              class="flex items-baseline justify-between gap-4 px-1 py-3 hover:bg-accent/5"
            >
              <span class="min-w-0">
                <span class="text-fg">{hit.title}</span>
                {#if hit.subtitle}
                  <span class="text-fg/50"> · {hit.subtitle}</span>
                {/if}
                {#if hit.status}
                  <span class="ml-2 font-mono text-xs uppercase tracking-widest text-fg/40">
                    {hit.status}
                  </span>
                {/if}
              </span>
              <span class="shrink-0 text-right">
                {#if hit.amount}
                  <span class="font-mono text-sm text-fg/80">{formatMoney(hit.amount)}</span>
                {/if}
                {#if hit.occurredOn}
                  <span class="ml-3 font-mono text-xs text-fg/40">{hit.occurredOn}</span>
                {/if}
              </span>
            </a>
          </li>
        {/each}
      </ul>
    </section>
  {/each}

  <nav class="mt-10 flex items-center justify-between" aria-label="Search result pages">
    {#if data.page > 1}
      <a href={pageHref(data.page - 1)} class="btn-ghost btn">Previous</a>
    {:else}
      <span></span>
    {/if}
    {#if data.hasMore && !data.atDepthLimit}
      <a href={pageHref(data.page + 1)} class="btn-ghost btn">Next</a>
    {/if}
  </nav>

  {#if data.atDepthLimit}
    <!-- Ranked results are a top-N, not a browsable list. Rather than paging
         forever through a fading tail, point at the tools built for it. -->
    <div class="callout mt-6">
      <p class="text-sm text-fg/80">
        <span class="text-fg">That's as far as search goes.</span>
        If what you're after is further down, the Invoices, Expenses and Contacts pages have
        filters and date ranges built for working through a long list.
      </p>
    </div>
  {/if}
{/if}

// apps/mobile/src/app/(app)/search.tsx
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { pickActiveCompany } from '../../lib/active-company';
import { api } from '../../lib/api';
import { formatMoney, groupByType, hrefFor, useGlobalSearch } from '../../lib/global-search';

// Global search on mobile (TMC-198).
//
// A hidden route rather than a sixth tab: the bar was deliberately consolidated
// to five (M11f), and search is something you reach for rather than somewhere
// you live. Two doors in — the bar at the top of Home, and a row in the More
// hub — so it is discoverable without spending a tab.
//
// There is no shared mobile header (every screen renders its own under
// headerShown: false), which is why this is a screen with its own input rather
// than the web's expand-in-place header box.
export default function SearchScreen() {
  const router = useRouter();
  const [companyId, setCompanyId] = useState<string | null>(null);
  const { text, onChangeText, results, loading, searching } = useGlobalSearch(companyId);

  // Resolve the active company once, so results are scoped to the business the
  // rest of the app is scoped to. Falls back to the whole workspace if it can't
  // be resolved — a wider search beats a broken one.
  const didBootstrap = useRef(false);
  useFocusEffect(
    useCallback(() => {
      if (didBootstrap.current) return;
      didBootstrap.current = true;
      let active = true;
      (async () => {
        const res = await api.api.companies.$get();
        if (!active || !res.ok) return;
        const { companies } = await res.json();
        const company = await pickActiveCompany(companies);
        if (company) setCompanyId(company.id);
      })().catch(() => {});
      return () => {
        active = false;
      };
    }, []),
  );

  const groups = groupByType(results);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="flex-row items-center gap-3 px-6 pt-6">
        <Pressable onPress={() => router.back()} className="-ml-2 p-2" accessibilityLabel="Back">
          <Ionicons name="chevron-back" size={22} className="text-ink" />
        </Pressable>
        <TextInput
          value={text}
          onChangeText={onChangeText}
          placeholder="Search invoices, contacts, expenses…"
          placeholderClassName="text-ink-subtle"
          autoFocus
          autoCorrect={false}
          autoCapitalize="none"
          returnKeyType="search"
          maxLength={200}
          className="flex-1 rounded-sm border border-field bg-cream-warm px-3 py-2.5 text-ink"
        />
      </View>

      <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
        {!searching ? (
          <Text className="text-sm text-ink-subtle">
            Type anything — a customer's name, an invoice number, an amount, a note on a receipt.
          </Text>
        ) : loading ? (
          <ActivityIndicator className="text-gold-deep" />
        ) : results.length === 0 ? (
          <Text className="text-sm text-ink-subtle">
            Nothing matched “{text.trim()}”. Search covers invoices, estimates, contacts, expenses,
            bills and jobs — names, numbers, amounts and notes.
          </Text>
        ) : (
          groups.map((group) => (
            <View key={group.type} className="mb-8">
              <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
                {group.label}
              </Text>
              <View className="mt-2 overflow-hidden rounded-sm border border-ink/15">
                {group.items.map((hit) => {
                  const href = hrefFor(hit.entityType, hit.entityId);
                  return (
                    <Pressable
                      key={`${hit.entityType}:${hit.entityId}`}
                      disabled={href === null}
                      onPress={() => {
                        if (href) router.push(href as never);
                      }}
                      className="border-b border-ink/10 px-3 py-3 active:bg-gold-deep/10"
                    >
                      <View className="flex-row items-baseline justify-between gap-3">
                        <Text className="flex-1 text-ink" numberOfLines={1}>
                          {hit.title}
                          {hit.subtitle ? (
                            <Text className="text-ink-subtle"> · {hit.subtitle}</Text>
                          ) : null}
                        </Text>
                        {hit.amount ? (
                          <Text className="font-mono text-xs text-ink-muted">
                            {formatMoney(hit.amount)}
                          </Text>
                        ) : null}
                      </View>
                      {hit.status || hit.occurredOn ? (
                        <View className="mt-1 flex-row items-center gap-3">
                          {hit.status ? (
                            <Text className="font-mono text-[10px] uppercase tracking-widest text-ink-subtle">
                              {hit.status}
                            </Text>
                          ) : null}
                          {hit.occurredOn ? (
                            <Text className="font-mono text-[10px] text-ink-subtle">
                              {hit.occurredOn}
                            </Text>
                          ) : null}
                        </View>
                      ) : null}
                    </Pressable>
                  );
                })}
              </View>
            </View>
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
}
