// apps/web/src/routes/(app)/recurring/+page.svelte
<script lang="ts">
  import { cadenceLabel } from '$lib/recurring';
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  // See /customers for the untrack() seed-and-re-seed pattern.
  type Row = (typeof data.schedules)[number];
  let rows = $state<Row[]>(untrack(() => data.schedules));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.schedules;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<Row>('/recurring/more', cursor);
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Recurring</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
      Recurring invoices<span class="text-gold-deep">.</span>
    </h1>
  </div>
  {#if may(data.role, 'sales:write')}
    <a
      href="/recurring/new"
      class="rounded-sm bg-ink px-4 py-2 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
    >
      + New schedule
    </a>
  {/if}
</div>

{#if rows.length === 0}
  <p class="mt-8 text-ink/70">
    No recurring schedules yet. Set one up to auto-generate and email invoices on a cadence.
  </p>
{:else}
  <div class="mt-8 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
    <table class="w-full text-left text-sm">
      <thead class="bg-cream">
        <tr class="font-mono text-xs uppercase tracking-widest text-ink/50">
          <th class="px-5 py-3">Customer</th>
          <th class="px-5 py-3">Cadence</th>
          <th class="px-5 py-3">Next run</th>
          <th class="px-5 py-3">Status</th>
          <th class="px-5 py-3 text-right">Total</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-ink/10">
        {#each rows as s (s.id)}
          <tr class="hover:bg-cream">
            <td class="px-5 py-4">
              <a href="/recurring/{s.id}" class="font-serif text-ink hover:text-gold-deep">
                {s.customerName ?? '—'}
              </a>
            </td>
            <td class="px-5 py-4 text-ink/80">{cadenceLabel(s.frequency, s.intervalCount)}</td>
            <td class="px-5 py-4 font-mono tabular-nums text-ink/80">
              {s.status === 'ended' ? '—' : s.nextRunDate}
            </td>
            <td class="px-5 py-4">
              <span class="font-mono text-xs uppercase tracking-widest text-ink/60">
                {s.status}
              </span>
            </td>
            <td class="px-5 py-4 text-right font-mono tabular-nums text-ink">
              {s.currency} {s.total}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}

// apps/mobile/src/app/(app)/invoices/recurring/index.tsx
import { useRouter } from 'expo-router';
import { useCallback } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../../lib/api';
import { useMay } from '../../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../../lib/use-paginated-list';

// Recurring schedules list. Lives in the invoices Stack (reached via the
// "Recurring schedules →" link on the invoices list), not its own tab. Mirror
// of apps/web's /recurring. customerName is LEFT JOINed by the API (#195);
// keyset infinite scroll via usePaginatedList.
type RecurringRow = {
  id: string;
  customerName: string | null;
  status: string;
  frequency: string;
  intervalCount: number;
  nextRunDate: string;
  currency: string;
  total: string;
};

function cadenceLabel(frequency: string, interval: number): string {
  const unit = frequency === 'weekly' ? 'week' : frequency === 'monthly' ? 'month' : 'year';
  return interval === 1 ? `Every ${unit}` : `Every ${interval} ${unit}s`;
}

export default function RecurringList() {
  const router = useRouter();
  const canCreate = useMay('sales:write');

  const fetchPage = useCallback(async (cursor: string | null) => {
    const res = await api.api['recurring-invoices'].$get({ query: pageQuery(cursor) });
    if (!res.ok) return null;
    const { recurringInvoices, nextCursor } = await res.json();
    return {
      rows: recurringInvoices.map(
        (r): RecurringRow => ({
          id: r.id,
          customerName: r.customerName ?? null,
          status: r.status,
          frequency: r.frequency,
          intervalCount: r.intervalCount,
          nextRunDate: r.nextRunDate,
          currency: r.currency,
          total: r.total,
        }),
      ),
      nextCursor,
    };
  }, []);

  const { list, loadingMore, loadMore } = usePaginatedList(fetchPage);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="px-6 pt-6">
        <Text
          onPress={() => router.push('/invoices')}
          className="font-mono text-xs uppercase tracking-widest text-ink/60"
        >
          ← Invoices
        </Text>
        <View className="mt-2 flex-row items-end justify-between">
          <Text className="font-serif text-3xl font-light text-ink">Recurring</Text>
          {canCreate ? (
            <Pressable
              onPress={() => router.push('/invoices/recurring/new')}
              className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
            >
              <Text className="text-sm font-medium text-cream">+ New</Text>
            </Pressable>
          ) : null}
        </View>
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator color="#0f1626" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load schedules.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink/70">No recurring schedules yet.</Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(r) => r.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator color="#0f1626" />
              </View>
            ) : null
          }
          renderItem={({ item }) => (
            <Pressable
              onPress={() => router.push(`/invoices/recurring/${item.id}`)}
              className="bg-cream-warm px-5 py-4 active:bg-cream"
            >
              <View className="flex-row items-center justify-between">
                <Text className="font-serif text-lg text-ink">{item.customerName ?? '—'}</Text>
                <Text className="font-mono tabular-nums text-ink">
                  {item.currency} {item.total}
                </Text>
              </View>
              <View className="mt-1 flex-row items-center justify-between">
                <Text className="text-sm text-ink/70">
                  {cadenceLabel(item.frequency, item.intervalCount)}
                </Text>
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  {item.status}
                  {item.status !== 'ended' ? ` · next ${item.nextRunDate}` : ''}
                </Text>
              </View>
            </Pressable>
          )}
        />
      )}
    </SafeAreaView>
  );
}
