// apps/mobile/src/app/(app)/purchases/index.tsx
import { useRouter } from 'expo-router';
import { useCallback } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../lib/use-paginated-list';

// Mirror of apps/web's /purchases — "big purchases": durable gear bought and
// used for years. The API LEFT JOINs the vendor name and derives the per-row
// loan balance, so the list shows what / cost / still-owed without extra
// lookups. Keyset infinite scroll. Reached from the Expenses-new branch.
type PurchaseRow = {
  id: string;
  description: string;
  amount: string;
  purchaseDate: string;
  funding: string;
  owing: string;
  vendorName: string | null;
};

const money = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

export default function PurchasesList() {
  const router = useRouter();
  const canCreate = useMay('expenses:write');

  const fetchPage = useCallback(async (cursor: string | null) => {
    const res = await api.api.purchases.$get({ query: pageQuery(cursor) });
    if (!res.ok) return null;
    const { purchases, nextCursor } = await res.json();
    return {
      rows: purchases.map(
        (p): PurchaseRow => ({
          id: p.id,
          description: p.description,
          amount: p.amount,
          purchaseDate: p.purchaseDate,
          funding: p.funding,
          owing: p.owing,
          vendorName: p.vendorName,
        }),
      ),
      nextCursor,
    };
  }, []);

  const { list, loadingMore, loadMore } = usePaginatedList(fetchPage);

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="flex-row items-end justify-between px-6 pt-6">
        <View>
          <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
            Big purchases
          </Text>
          <Text className="mt-2 font-serif text-3xl font-light text-ink">Things you bought</Text>
        </View>
        {canCreate ? (
          <Pressable
            onPress={() => router.push('/purchases/new')}
            className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
          >
            <Text className="text-sm font-medium text-cream">+ Log</Text>
          </Pressable>
        ) : null}
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator color="#0f1626" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load this.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink/70">Nothing logged yet.</Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(p) => p.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator color="#0f1626" />
              </View>
            ) : null
          }
          renderItem={({ item }) => {
            const stillOwes = Number(item.owing) > 0;
            return (
              <Pressable
                onPress={() => router.push(`/purchases/${item.id}`)}
                className="bg-cream-warm px-5 py-4 active:bg-cream"
              >
                <View className="flex-row items-center justify-between">
                  <Text className="flex-1 pr-3 font-serif text-lg text-ink" numberOfLines={1}>
                    {item.description}
                  </Text>
                  <Text className="font-mono tabular-nums text-ink">{money(item.amount)}</Text>
                </View>
                <View className="mt-1 flex-row items-center justify-between">
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                    {item.purchaseDate}
                    {item.vendorName ? ` · ${item.vendorName}` : ''}
                  </Text>
                  {stillOwes ? (
                    <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
                      owe {money(item.owing)}
                    </Text>
                  ) : (
                    <Text className="font-mono text-xs uppercase tracking-widest text-ink/40">
                      Paid off
                    </Text>
                  )}
                </View>
              </Pressable>
            );
          }}
        />
      )}
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/purchases/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';
  import type { PurchaseRow } from './purchase-rows';

  let { data }: PageProps = $props();

  const companyId = $derived(data.companyId);
  const canWrite = $derived(may(data.role, 'expenses:write'));
  const money = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  let rows = $state<PurchaseRow[]>(untrack(() => data.rows));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.rows;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<PurchaseRow>('/purchases/more', cursor, { companyId });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Big purchases</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      Things you bought<span class="text-accent">.</span>
    </h1>
  </div>
  {#if canWrite}
    <a href="/purchases/new" class="btn">+ Log a purchase</a>
  {/if}
</div>

<p class="mt-4 max-w-2xl text-sm text-fg/60">
  Big things you'll use for years — a mower, trailer, truck. We track what you paid, what you still
  owe, and how it helps at tax time.
</p>

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">Nothing logged yet.</p>
{:else}
  <div class="mt-6 overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
    <table class="w-full text-left text-sm">
      <thead class="bg-surface">
        <tr class="label">
          <th class="px-5 py-3">Date</th>
          <th class="px-5 py-3">What</th>
          <th class="px-5 py-3 text-right">Cost</th>
          <th class="px-5 py-3 text-right">Still owed</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-fg/10">
        {#each rows as p (p.id)}
          <tr class="hover:bg-surface">
            <td class="px-5 py-4 font-mono tabular-nums text-fg/80">{p.purchaseDate}</td>
            <td class="px-5 py-4">
              <a href="/purchases/{p.id}" class="font-serif text-fg hover:text-accent">
                {p.description}
              </a>
              {#if p.vendorName}
                <span class="block text-xs text-fg/50">from {p.vendorName}</span>
              {/if}
            </td>
            <td class="px-5 py-4 text-right font-mono tabular-nums text-fg">{money(p.amount)}</td>
            <td class="px-5 py-4 text-right font-mono tabular-nums">
              {#if p.stillOwes}
                <span class="text-fg">{money(p.owing)}</span>
              {:else}
                <span class="text-fg/40">Paid off</span>
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}
