// apps/web/src/routes/(app)/contacts/new/+page.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import AddressLookup from '$lib/components/AddressLookup.svelte';
  import { findEmailDupe, findNameDupes } from '$lib/contact-dupes';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
  const values = $derived(form?.values ?? {});
  const fieldErrors = $derived(form?.fieldErrors ?? {});

  type FieldKey =
    | 'name'
    | 'email'
    | 'phone'
    | 'addressLine1'
    | 'addressLine2'
    | 'city'
    | 'region'
    | 'postalCode'
    | 'country'
    | 'notes';

  function v(key: FieldKey): string {
    const raw = (values as Record<string, unknown>)[key];
    return typeof raw === 'string' ? raw : '';
  }
  function err(key: FieldKey): string | undefined {
    return (fieldErrors as Record<string, string>)[key];
  }

  // Live dupe-hints (mirrors the inline-create path on /invoices/new).
  // Name match is advisory — shown as a suggestion list with a link to the
  // existing contact; user can ignore and create anyway. Email match is
  // also enforced server-side as a hard block.
  let nameInput = $state<string>(untrack(() => v('name')));
  let emailInput = $state<string>(untrack(() => v('email')));
  const liveEmailDupe = $derived(findEmailDupe(emailInput, data.contacts));
  const liveNameDupes = $derived(findNameDupes(nameInput, data.contacts));

  // Address fields move from uncontrolled value={...} to bind:value so the
  // AddressLookup component can write a picked suggestion across all five.
  // Initial values seed from form?.values via untrack() so a fail()-re-render
  // restores typed-but-not-submitted input — same pattern as 8.4c's
  // line-item rows.
  let addressLine1 = $state<string>(untrack(() => v('addressLine1')));
  let addressLine2 = $state<string>(untrack(() => v('addressLine2')));
  let city = $state<string>(untrack(() => v('city')));
  let region = $state<string>(untrack(() => v('region')));
  let postalCode = $state<string>(untrack(() => v('postalCode')));
  let country = $state<string>(untrack(() => v('country')));
</script>

<a href="/contacts" class="eyebrow text-fg/60 hover:text-fg">← Contacts</a>
<h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
  New contact<span class="text-accent">.</span>
</h1>

{#if form?.formError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger">
    {form.formError}
  </div>
{/if}

<form method="post" class="mt-8 space-y-6">
  <div>
    <label for="name" class="label">
      Name<span class="text-accent">*</span>
    </label>
    <input
      id="name"
      name="name"
      type="text"
      required
      maxlength="200"
      bind:value={nameInput}
      class="field mt-1"
    />
    {#if err('name')}
      <p class="mt-1 text-xs text-danger">{err('name')}</p>
    {/if}
    {#if liveNameDupes.length > 0}
      <div class="mt-2 rounded-sm border border-fg/10 bg-surface-2/60 p-2 text-xs">
        <p class="text-fg/60">
          Looks like {liveNameDupes.length === 1 ? 'an existing contact' : 'existing contacts'}:
        </p>
        <ul class="mt-1 space-y-1">
          {#each liveNameDupes as dupe (dupe.id)}
            <li class="flex items-center justify-between gap-2">
              <span class="text-fg">{dupe.name}{#if dupe.email}<span class="text-fg/50"> · {dupe.email}</span>{/if}</span>
              <a
                href="/contacts/{dupe.id}"
                class="rounded-sm border border-fg/15 bg-surface-2 px-2 py-1 text-xs uppercase tracking-wider text-fg/70 hover:border-accent hover:text-accent"
              >
                Open
              </a>
            </li>
          {/each}
        </ul>
      </div>
    {/if}
  </div>

  <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
    <div>
      <label for="email" class="label">Email</label>
      <input
        id="email"
        name="email"
        type="email"
        maxlength="320"
        bind:value={emailInput}
        class="field mt-1"
      />
      {#if err('email') && err('email') !== 'email_dupe'}
        <p class="mt-1 text-xs text-danger">{err('email')}</p>
      {/if}
      {#if form?.dupeContact}
        <div class="mt-2 rounded-sm border border-danger/30 bg-danger/5 p-3 text-sm">
          <p class="text-fg">
            <span class="font-medium">{form.dupeContact.name}</span> already uses this email.
          </p>
          <div class="mt-2 flex flex-wrap items-center gap-3">
            <a
              href="/contacts/{form.dupeContact.id}"
              class="rounded-sm bg-inverse px-3 py-1 text-xs uppercase tracking-wider text-on-inverse hover:bg-accent"
            >
              Open {form.dupeContact.name}
            </a>
            <span class="text-xs text-fg/50">or change the email to create a different contact.</span>
          </div>
        </div>
      {:else if liveEmailDupe}
        <div class="mt-2 rounded-sm border border-accent/30 bg-accent/5 p-3 text-sm">
          <p class="text-fg">
            <span class="font-medium">{liveEmailDupe.name}</span> already uses this email.
          </p>
          <a
            href="/contacts/{liveEmailDupe.id}"
            class="mt-2 inline-block rounded-sm border border-fg/20 bg-surface-2 px-3 py-1 text-xs uppercase tracking-wider text-fg/70 hover:border-accent hover:text-accent"
          >
            Open {liveEmailDupe.name}
          </a>
        </div>
      {/if}
    </div>
    <div>
      <label for="phone" class="label">Phone</label>
      <input
        id="phone"
        name="phone"
        type="tel"
        maxlength="50"
        value={v('phone')}
        class="field mt-1"
      />
      {#if err('phone')}
        <p class="mt-1 text-xs text-danger">{err('phone')}</p>
      {/if}
    </div>
  </div>

  <fieldset class="space-y-4">
    <legend class="label">Address</legend>
    <AddressLookup
      bind:addressLine1
      bind:city
      bind:region
      bind:postalCode
      bind:country
    />
    <input
      name="addressLine2"
      type="text"
      maxlength="200"
      placeholder="Suite, unit, etc."
      bind:value={addressLine2}
      class="field"
    />
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-3">
      <input
        name="city"
        type="text"
        maxlength="100"
        placeholder="City"
        bind:value={city}
        class="rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 text-fg focus:border-accent focus:outline-none"
      />
      <input
        name="region"
        type="text"
        maxlength="100"
        placeholder="State / Region"
        bind:value={region}
        class="rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 text-fg focus:border-accent focus:outline-none"
      />
      <input
        name="postalCode"
        type="text"
        maxlength="20"
        placeholder="Postal code"
        bind:value={postalCode}
        class="rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 text-fg focus:border-accent focus:outline-none"
      />
    </div>
    <input
      name="country"
      type="text"
      maxlength="2"
      placeholder="Country (ISO, e.g. US)"
      bind:value={country}
      class="w-32 rounded-sm border border-fg/15 bg-surface-2 px-3 py-2 uppercase text-fg focus:border-accent focus:outline-none"
    />
  </fieldset>

  <div>
    <label for="notes" class="label">Notes</label>
    <textarea
      id="notes"
      name="notes"
      rows="4"
      maxlength="5000"
      class="field mt-1"
      >{v('notes')}</textarea
    >
  </div>

  <div class="flex items-center gap-4">
    <button
      type="submit"
      class="btn"
    >
      Create contact
    </button>
    <a href="/contacts" class="text-sm text-fg/60 hover:text-fg">Cancel</a>
  </div>
</form>

// apps/mobile/src/app/(app)/contacts/new.tsx
import { contactCreateSchema } from '@thalermark/validation';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AddressField, type AddressSuggestion } from '../../../components/AddressField';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { type DupeCandidate, findEmailDupe, findNameDupes } from '../../../lib/contact-dupes';

// Mirror of apps/web's /contacts/new (+page.svelte + its server action),
// client-side. The API has no dupe endpoint and doesn't auto-pick a company,
// so this screen does both: load the contact list for live dupe hints, grab
// companies[0] for the required companyId, hard-block on an exact email dupe.
type OptionalKey =
  | 'email'
  | 'phone'
  | 'addressLine1'
  | 'addressLine2'
  | 'city'
  | 'region'
  | 'postalCode'
  | 'country'
  | 'notes';

const OPTIONAL_FIELDS: OptionalKey[] = [
  'email',
  'phone',
  'addressLine1',
  'addressLine2',
  'city',
  'region',
  'postalCode',
  'country',
  'notes',
];

type FieldKey = 'name' | OptionalKey;

export default function NewContact() {
  const router = useRouter();

  const [values, setValues] = useState<Record<FieldKey, string>>({
    name: '',
    email: '',
    phone: '',
    addressLine1: '',
    addressLine2: '',
    city: '',
    region: '',
    postalCode: '',
    country: '',
    notes: '',
  });
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [bootstrapped, setBootstrapped] = useState(false);
  const [contacts, setContacts] = useState<DupeCandidate[]>([]);
  const [fieldErrors, setFieldErrors] = useState<Partial<Record<FieldKey, string>>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Load companies (for companyId) + the contact list (for dupe hints) once.
  useFocusEffect(
    useCallback(() => {
      if (bootstrapped) return;
      let active = true;
      Promise.all([api.api.companies.$get(), api.api.contacts.$get()])
        .then(async ([companiesRes, contactsRes]) => {
          if (!active) return;
          if (companiesRes.ok) {
            const { companies } = await companiesRes.json();
            const company = await pickActiveCompany(companies);
            setCompanyId(company?.id ?? null);
          }
          if (contactsRes.ok) {
            const { contacts: rows } = await contactsRes.json();
            setContacts(rows.map((c) => ({ id: c.id, name: c.name, email: c.email ?? null })));
          }
          setBootstrapped(true);
        })
        .catch(() => {
          if (active) setBootstrapped(true);
        });
      return () => {
        active = false;
      };
    }, [bootstrapped]),
  );

  const set = (key: FieldKey, val: string) => setValues((v) => ({ ...v, [key]: val }));

  // Picking an address suggestion rewrites Street + fans the rest into the
  // sibling city / region / postalCode / country fields (a programmatic write,
  // so it doesn't re-trigger the type-ahead).
  const applyAddress = (s: AddressSuggestion) =>
    setValues((v) => ({
      ...v,
      addressLine1: s.addressLine1,
      city: s.city,
      region: s.region,
      postalCode: s.postalCode,
      country: s.country,
    }));

  const emailDupe = useMemo(
    () => findEmailDupe(values.email, contacts),
    [values.email, contacts],
  );
  const nameDupes = useMemo(() => findNameDupes(values.name, contacts), [values.name, contacts]);

  const noCompany = bootstrapped && companyId === null;
  const canSubmit = !submitting && !emailDupe && !noCompany && values.name.trim().length > 0;

  async function onSubmit() {
    if (!companyId) {
      setFormError('No company in this workspace.');
      return;
    }
    setFormError(null);
    setFieldErrors({});

    // Trim; omit empty optionals so undefined (not '') reaches the schema —
    // '' would fail .email()/.max(). Matches web's readForm().
    const body: Record<string, string> = { companyId, name: values.name.trim() };
    for (const k of OPTIONAL_FIELDS) {
      const trimmed = values[k].trim();
      if (trimmed !== '') body[k] = trimmed;
    }

    const parsed = contactCreateSchema.safeParse(body);
    if (!parsed.success) {
      const errs: Partial<Record<FieldKey, string>> = {};
      for (const issue of parsed.error.issues) {
        const key = String(issue.path[0] ?? '') as FieldKey;
        if (key && !errs[key]) errs[key] = issue.message;
      }
      setFieldErrors(errs);
      return;
    }

    setSubmitting(true);
    try {
      const res = await api.api.contacts.$post({ json: parsed.data });
      if (!res.ok) {
        const errBody = (await res.json().catch(() => null)) as { error?: string } | null;
        setFormError(errBody?.error ?? 'create_failed');
        return;
      }
      const created = await res.json();
      router.replace(`/contacts/${created.id}`);
    } catch {
      setFormError('create_failed');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
              ← Contacts
            </Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">New contact</Text>

          {formError ? (
            <View className="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
              <Text className="text-sm text-oxblood">{formError}</Text>
            </View>
          ) : null}

          <View className="mt-8 space-y-5">
            <Field
              label="Name *"
              value={values.name}
              onChangeText={(t) => set('name', t)}
              error={fieldErrors.name}
            />
            {nameDupes.length > 0 ? (
              <View className="rounded-sm border border-ink/10 bg-cream-warm/60 p-3">
                <Text className="text-xs text-ink/60">
                  Looks like{' '}
                  {nameDupes.length === 1 ? 'an existing contact' : 'existing contacts'}:
                </Text>
                {nameDupes.map((d) => (
                  <Pressable
                    key={d.id}
                    onPress={() => router.push(`/contacts/${d.id}`)}
                    className="mt-1 flex-row items-center justify-between"
                  >
                    <Text className="text-sm text-ink">
                      {d.name}
                      {d.email ? <Text className="text-ink/50"> · {d.email}</Text> : null}
                    </Text>
                    <Text className="font-mono text-xs uppercase tracking-wider text-gold-deep">
                      Open
                    </Text>
                  </Pressable>
                ))}
              </View>
            ) : null}

            <Field
              label="Email"
              value={values.email}
              onChangeText={(t) => set('email', t)}
              error={fieldErrors.email}
              keyboardType="email-address"
              autoCapitalize="none"
            />
            {emailDupe ? (
              <View className="rounded-sm border border-oxblood/30 bg-oxblood/5 p-3">
                <Text className="text-sm text-ink">
                  <Text className="font-medium">{emailDupe.name}</Text> already uses this email.
                </Text>
                <Pressable
                  onPress={() => router.push(`/contacts/${emailDupe.id}`)}
                  className="mt-2"
                >
                  <Text className="font-mono text-xs uppercase tracking-wider text-gold-deep">
                    Open {emailDupe.name}
                  </Text>
                </Pressable>
                <Text className="mt-1 text-xs text-ink/50">
                  or change the email to create a different contact.
                </Text>
              </View>
            ) : null}

            <Field
              label="Phone"
              value={values.phone}
              onChangeText={(t) => set('phone', t)}
              keyboardType="phone-pad"
            />
            <AddressField
              value={values.addressLine1}
              onChangeText={(t) => set('addressLine1', t)}
              onPick={applyAddress}
              country={values.country}
            />
            <Field
              label="Suite, unit, etc."
              value={values.addressLine2}
              onChangeText={(t) => set('addressLine2', t)}
            />
            <Field label="City" value={values.city} onChangeText={(t) => set('city', t)} />
            <Field
              label="State / Region"
              value={values.region}
              onChangeText={(t) => set('region', t)}
            />
            <Field
              label="Postal code"
              value={values.postalCode}
              onChangeText={(t) => set('postalCode', t)}
            />
            <Field
              label="Country (ISO, e.g. US)"
              value={values.country}
              onChangeText={(t) => set('country', t)}
              autoCapitalize="characters"
              error={fieldErrors.country}
            />
            <Field
              label="Notes"
              value={values.notes}
              onChangeText={(t) => set('notes', t)}
              multiline
            />

            {noCompany ? (
              <Text className="text-xs text-oxblood">No company in this workspace.</Text>
            ) : null}

            <Pressable
              onPress={onSubmit}
              disabled={!canSubmit}
              className="mt-2 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
            >
              {submitting ? (
                <ActivityIndicator color="#f4ede0" />
              ) : (
                <Text className="text-center text-sm font-medium text-cream">Create contact</Text>
              )}
            </Pressable>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

// Small labelled TextInput matching the (auth) screens' field idiom.
function Field({
  label,
  value,
  onChangeText,
  error,
  keyboardType,
  autoCapitalize,
  multiline,
}: {
  label: string;
  value: string;
  onChangeText: (t: string) => void;
  error?: string;
  keyboardType?: 'email-address' | 'phone-pad';
  autoCapitalize?: 'none' | 'characters';
  multiline?: boolean;
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">{label}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        keyboardType={keyboardType}
        autoCapitalize={autoCapitalize}
        multiline={multiline}
        className="mt-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
      />
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}
