// apps/web/src/routes/(auth)/sign-in/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { authClient } from '$lib/auth-client';
  import SocialSignIn from '$lib/components/SocialSignIn.svelte';
  import { COPY } from '@thalermark/brand';

  let email = $state('');
  let password = $state('');
  let error = $state<string | null>(null);
  let submitting = $state(false);
  let needsVerification = $state(false);
  let resending = $state(false);
  let resent = $state(false);
  let resendError = $state<string | null>(null);

  const inviteToken = $derived(page.url.searchParams.get('invite'));
  const postAuthPath = $derived(
    inviteToken ? `/accept-invite?token=${encodeURIComponent(inviteToken)}` : '/',
  );
  const signUpHref = $derived(inviteToken ? `/sign-up?invite=${encodeURIComponent(inviteToken)}` : '/sign-up');

  // Social providers the api advertises (already public via the rendered
  // buttons) + this device's last-used method (a local, leak-free cookie read
  // server-side in the (auth) load).
  const socialProviders = $derived((page.data.socialProviders ?? []) as string[]);
  const lastAuthMethod = $derived((page.data.lastAuthMethod ?? null) as string | null);

  const PROVIDER_LABELS: Record<string, string> = {
    google: 'Google',
    facebook: 'Facebook',
    twitter: 'X',
  };

  // Option B wrong-method rescue: on ANY failed login, nudge users who signed up
  // with a social provider toward the buttons below. Deliberately UNCONDITIONAL
  // w.r.t. the entered email (no email→provider lookup) so it can't leak whether
  // an account exists or which provider it uses. Hidden when no social providers
  // are configured, and suppressed when this device last signed in with a
  // password (a device-local signal that leaks nothing remotely).
  const showMethodHint = $derived(
    !!error && socialProviders.length > 0 && lastAuthMethod !== 'password',
  );
  const methodHintText = $derived(joinOr(socialProviders.map((p) => PROVIDER_LABELS[p] ?? p)));

  // Oxford-style "A, B, or C".
  function joinOr(names: string[]): string {
    if (names.length <= 1) return names[0] ?? '';
    if (names.length === 2) return `${names[0]} or ${names[1]}`;
    return `${names.slice(0, -1).join(', ')}, or ${names.at(-1)}`;
  }

  // Remember this device's last sign-in method (provider id or 'password') so the
  // next visit can badge the right button and suppress the wrong-method hint.
  // Only the method string is stored — nothing identifying. Read back
  // server-side in the (auth) layout load.
  function rememberMethod(method: string) {
    document.cookie = `last_auth_method=${method}; path=/; max-age=31536000; samesite=lax`;
  }

  async function onSubmit(event: SubmitEvent) {
    event.preventDefault();
    error = null;
    submitting = true;
    needsVerification = false;
    try {
      const result = await authClient.signIn.email({ email, password });
      if (result.error) {
        const msg = result.error.message ?? 'Sign-in failed';
        // Unverified email/password account → offer to resend the link instead of
        // a dead-end error. BA returns EMAIL_NOT_VERIFIED; match the message too
        // in case the code shape shifts.
        if (result.error.code === 'EMAIL_NOT_VERIFIED' || /verif/i.test(msg)) {
          needsVerification = true;
          return;
        }
        error = msg;
        return;
      }
      rememberMethod('password');
      // Hard nav: forces hooks.server.ts to re-run membership routing on a
      // fresh request. goto() + invalidateAll() leaves stale layout data.
      window.location.assign(postAuthPath);
    } catch {
      // A thrown request (network down, API unreachable, CSP-blocked) never
      // reaches the result-error branch, so surface it instead of a stuck button.
      error = 'Could not reach the server. Check your connection and try again.';
    } finally {
      submitting = false;
    }
  }

  async function onResend() {
    resending = true;
    resent = false;
    resendError = null;
    try {
      await authClient.sendVerificationEmail({
        email,
        callbackURL: `${window.location.origin}${postAuthPath}`,
      });
      resent = true;
    } catch {
      resendError = 'Could not send the email. Please try again.';
    } finally {
      resending = false;
    }
  }
</script>

<span class="eyebrow">Welcome back</span>
<h1 class="mt-3 font-serif text-3xl font-light leading-tight tracking-tight text-fg">
  {COPY.signIn.title}
</h1>

<form onsubmit={onSubmit} class="mt-8 space-y-5">
  <label class="block">
    <span class="label block">Email</span>
    <input type="email" required bind:value={email} class="field-line mt-2" />
  </label>
  <label class="block">
    <span class="label block">Password</span>
    <input type="password" required bind:value={password} class="field-line mt-2" />
  </label>
  {#if error}
    <p class="label text-danger">{error}</p>
    {#if showMethodHint}
      <p class="text-sm text-fg/60">
        Signed up with {methodHintText}? Use the button{socialProviders.length > 1 ? 's' : ''} below.
      </p>
    {/if}
  {/if}
  {#if needsVerification}
    <div class="callout">
      <p>
        Verify your email to sign in — we sent a link to
        <span class="font-medium text-fg">{email}</span>.
      </p>
      <div class="mt-3 flex items-center gap-4">
        <button type="button" onclick={onResend} disabled={resending} class="btn-ghost btn-sm">
          {resending ? 'Sending…' : 'Resend verification'}
        </button>
        {#if resent}
          <span class="label text-success">Sent</span>
        {/if}
        {#if resendError}
          <span class="label text-danger">{resendError}</span>
        {/if}
      </div>
    </div>
  {/if}
  <button type="submit" disabled={submitting} class="btn w-full py-3">
    {COPY.signIn.submit}
  </button>
  <div class="flex justify-end">
    <a href="/forgot-password" class="link text-sm">Forgot password?</a>
  </div>
</form>

<!-- Hidden during an invite flow: invites are email-anchored, so a mismatched
     social account would create a stray account instead of joining. -->
<SocialSignIn
  providers={inviteToken ? [] : (page.data.socialProviders ?? [])}
  callbackPath={postAuthPath}
  lastUsed={inviteToken ? null : lastAuthMethod}
/>

<p class="mt-8 text-center text-sm text-fg/70">
  No account?
  <a
    href={signUpHref}
    class="link"
    >Sign up</a
  >
</p>

// apps/mobile/src/app/(auth)/sign-in.tsx
import { COPY } from '@thalermark/brand';
import { Link, router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { SocialSignIn } from '../../components/SocialSignIn';
import { authClient } from '../../lib/auth-client';
import { getLastAuthMethod, setLastAuthMethod } from '../../lib/secure-store';
import { useSocialProviders } from '../../lib/social-providers';

// Short provider names for the wrong-method hint (the buttons use longer labels).
const PROVIDER_NAMES: Record<string, string> = {
  google: 'Google',
  facebook: 'Facebook',
  twitter: 'X',
};

// Oxford-style "A, B, or C".
function joinOr(names: string[]): string {
  if (names.length <= 1) return names[0] ?? '';
  if (names.length === 2) return `${names[0]} or ${names[1]}`;
  return `${names.slice(0, -1).join(', ')}, or ${names.at(-1)}`;
}

export default function SignIn() {
  const { invite } = useLocalSearchParams<{ invite?: string }>();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  // An unverified email/password account can't sign in (the server requires
  // verification). Offer a resend rather than a dead-end error.
  const [needsVerification, setNeedsVerification] = useState(false);
  const [resending, setResending] = useState(false);
  const [resent, setResent] = useState(false);

  const providers = useSocialProviders();
  // This device's last sign-in method — suppresses the wrong-method hint when it
  // was a password (a device-local signal that leaks nothing remotely).
  const [lastMethod, setLastMethod] = useState<string | null>(null);
  useEffect(() => {
    let active = true;
    getLastAuthMethod().then((m) => {
      if (active) setLastMethod(m);
    });
    return () => {
      active = false;
    };
  }, []);

  // Option B wrong-method rescue: on any failed sign-in, nudge users who signed
  // up with a social provider toward the buttons below. Unconditional w.r.t. the
  // entered email (no email→provider lookup) so it can't leak account existence;
  // hidden when no providers are configured or this device last used a password.
  const showMethodHint = !!error && providers.length > 0 && lastMethod !== 'password';
  const methodHintText = joinOr(providers.map((p) => PROVIDER_NAMES[p] ?? p));

  async function onSubmit() {
    setError(null);
    setNeedsVerification(false);
    setSubmitting(true);
    // An unreachable server REJECTS rather than returning an error result, and
    // this used to have no catch, so the button span forever with nothing said
    // (TMC-272). That is not an exotic case on a phone: no signal, a server
    // that is down, or a self-host address typed wrong in Advanced all land
    // here. `finally` owns the pending flag so no path can leave it stuck.
    try {
      const result = await authClient.signIn.email({ email, password });
      if (result.error) {
        const msg = result.error.message ?? 'Sign-in failed';
        // BA returns EMAIL_NOT_VERIFIED for an unverified account; match the
        // message too in case the code shape shifts.
        if (result.error.code === 'EMAIL_NOT_VERIFIED' || /verif/i.test(msg)) {
          setNeedsVerification(true);
          return;
        }
        setError(msg);
        return;
      }
      await setLastAuthMethod('password');
      if (invite) {
        router.replace({ pathname: '/accept-invite', params: { token: invite } });
      } else {
        router.replace('/');
      }
    } catch {
      setError("Couldn't reach the server. Check your connection, or the address under Advanced.");
    } finally {
      setSubmitting(false);
    }
  }

  // Re-send the verification link. No callbackURL: the link verifies server-side,
  // then the user signs in again here (a bearer client can't adopt the cookie
  // session autoSignInAfterVerification would create).
  async function onResend() {
    setResending(true);
    setResent(false);
    try {
      await authClient.sendVerificationEmail({ email });
      setResent(true);
    } finally {
      setResending(false);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream">
      <View className="flex-1 justify-center px-6">
        <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
          Welcome back
        </Text>
        <Text className="mt-3 font-serif text-3xl font-light text-ink">{COPY.signIn.title}</Text>

        <View className="mt-8 gap-5">
          <View>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Email
            </Text>
            <TextInput
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              autoComplete="email"
              inputMode="email"
              keyboardType="email-address"
              className="mt-2 border-b border-field py-2 text-ink"
            />
          </View>
          <View>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Password
            </Text>
            <TextInput
              value={password}
              onChangeText={setPassword}
              secureTextEntry
              autoComplete="current-password"
              className="mt-2 border-b border-field py-2 text-ink"
            />
          </View>
          <View className="items-end">
            <Link href="/forgot-password">
              <Text className="text-sm text-gold-deep underline">Forgot password?</Text>
            </Link>
          </View>
          {error ? (
            <Text className="font-mono text-xs uppercase tracking-widest text-oxblood">
              {error}
            </Text>
          ) : null}
          {showMethodHint ? (
            <Text className="text-sm text-ink-subtle">
              Signed up with {methodHintText}? Use the button
              {providers.length > 1 ? 's' : ''} below.
            </Text>
          ) : null}
          {needsVerification ? (
            <View className="rounded-sm border border-gold-deep/30 bg-gold-deep/5 px-4 py-3">
              <Text className="text-sm text-ink/80">
                Verify your email to sign in — we sent a link to{' '}
                <Text className="font-medium text-ink">{email}</Text>.
              </Text>
              <View className="mt-3 flex-row items-center gap-4">
                <Pressable
                  onPress={onResend}
                  disabled={resending}
                  className="rounded-sm border border-ink/25 px-3 py-1.5 active:bg-ink/5 disabled:opacity-50"
                >
                  <Text className="text-sm font-medium text-ink">
                    {resending ? 'Sending…' : 'Resend verification'}
                  </Text>
                </Pressable>
                {resent ? (
                  <Text className="font-mono text-xs uppercase tracking-widest text-sage">
                    Sent
                  </Text>
                ) : null}
              </View>
            </View>
          ) : null}
          <Pressable
            onPress={onSubmit}
            disabled={submitting}
            className="mt-2 rounded-sm bg-ink px-3 py-3 active:bg-gold-deep disabled:opacity-50"
          >
            {submitting ? (
              <ActivityIndicator className="text-cream" />
            ) : (
              <Text className="text-center text-sm font-medium text-cream">
                {COPY.signIn.submit}
              </Text>
            )}
          </Pressable>
        </View>

        {invite ? null : <SocialSignIn />}

        <View className="mt-8 flex-row justify-center">
          <Text className="text-sm text-ink-muted">No account? </Text>
          <Link href={invite ? { pathname: '/sign-up', params: { invite } } : '/sign-up'}>
            <Text className="text-sm text-gold-deep underline">Sign up</Text>
          </Link>
        </View>

        <View className="mt-10 flex-row justify-center">
          <Link href="/server">
            <Text className="font-mono text-xs uppercase tracking-widest text-ink-subtle">
              Advanced
            </Text>
          </Link>
        </View>
      </View>
    </SafeAreaView>
  );
}
