// apps/web/src/routes/(app)/ledger/close/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { may } from '$lib/perms';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  const canAdjust = $derived(may(data.role, 'ledger:adjust'));

  const money = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  // Which year's confirm panel is open. Closing a year is irreversible-ish
  // (re-opening is possible but deliberate), so it never happens on one click.
  let confirming = $state<number | null>(null);
  let submitting = $state(false);
</script>

<div>
  <span class="eyebrow text-accent">The Ledger</span>
  <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
    Close out a year<span class="text-accent">.</span>
  </h1>
</div>

<p class="mt-4 max-w-2xl text-sm text-fg/60">
  Closing a year moves its profit into your business's equity and locks the year, so nothing can
  change it afterwards. Most people do this once their accountant has finished the tax return.
</p>

<!--
  A LINK, not a copy of the form. The vehicle answers are deliberately NOT
  period-locked, so they can be given before or after a close — which means this
  page has no reason to own them, and a second copy of the form would be a second
  thing to keep correct. Pointing at the worksheet also lands the user where the
  rest of the return is.
-->
{#if data.vehiclesNeedingAnswers > 0}
  <p class="callout mt-6 text-sm text-fg/70">
    Before you close: {data.vehiclesNeedingAnswers === 1
      ? 'one of your vehicles is'
      : `${data.vehiclesNeedingAnswers} of your vehicles are`} missing details the return needs.
    <a href="/reports/tax-worksheet" class="link">Finish that first</a> — you can still answer it
    after closing, but it's easier while the year is in front of you.
  </p>
{/if}

{#if form?.formError}
  <div class="callout mt-6 border-danger/40 text-danger" data-form-error role="alert" tabindex="-1">{form.formError}</div>
{/if}
{#if form?.closedYear}
  <div class="callout mt-6">{form.closedYear} is closed.</div>
{/if}
{#if form?.reopenedYear}
  <div class="callout mt-6">{form.reopenedYear} is open again.</div>
{/if}

<h2 class="mt-10 font-serif text-2xl font-light text-fg">Ready to close</h2>

{#if data.closable.length === 0}
  <p class="mt-4 text-sm text-fg/70">
    Nothing to close right now. A year can be closed once it's over.
  </p>
{:else}
  <div class="mt-4 space-y-4">
    {#each data.closable as year (year.fiscalYear)}
      <div class="rounded-sm border border-fg/10 bg-surface-2 p-6">
        <div class="flex flex-wrap items-baseline justify-between gap-4">
          <div>
            <h3 class="font-serif text-xl text-fg">{year.fiscalYear}</h3>
            <p class="mt-1 text-sm text-fg/70">
              {Number(year.netIncome) < 0 ? 'Loss' : 'Profit'} of
              <span class="font-mono tabular-nums text-fg"
                >{money(String(Math.abs(Number(year.netIncome))))}</span
              >
              {#if Number(year.withdrawals) > 0}
                · <span class="font-mono tabular-nums text-fg">{money(year.withdrawals)}</span> taken
                out
              {/if}
            </p>
          </div>
          {#if canAdjust}
            <button
              type="button"
              class="btn"
              onclick={() => (confirming = confirming === year.fiscalYear ? null : year.fiscalYear)}
            >
              {confirming === year.fiscalYear ? 'Cancel' : `Close ${year.fiscalYear}`}
            </button>
          {/if}
        </div>

        {#if confirming === year.fiscalYear}
          <div class="mt-5 border-t border-fg/10 pt-5">
            <p class="text-sm leading-relaxed text-fg/80">
              This locks {year.fiscalYear} so nothing can change it, and moves the year's
              {Number(year.netIncome) < 0 ? 'loss' : 'profit'} into
              <strong class="font-medium text-fg">{year.equityLabel.toLowerCase()}</strong>. If you
              need to add or fix something in {year.fiscalYear} later, you can re-open it here.
            </p>
            <form
              method="POST"
              action="?/close"
              class="mt-5"
              use:enhance={() => {
                submitting = true;
                return async ({ update }) => {
                  await update();
                  submitting = false;
                  confirming = null;
                };
              }}
            >
              <input type="hidden" name="fiscalYear" value={year.fiscalYear} />
              <button type="submit" class="btn" disabled={submitting}>
                {submitting ? 'Closing…' : `Yes, close ${year.fiscalYear}`}
              </button>
            </form>
          </div>
        {/if}
      </div>
    {/each}
  </div>
{/if}

<!-- Years with no activity aren't given a card of their own — there's nothing to
     close and no button to press. Naming them in one line answers "why isn't 2023
     listed?" without turning the page into a stack of empty boxes. -->
{#if data.emptyYears.length > 0}
  <p class="mt-4 text-sm text-fg/50">
    Nothing on the books for {new Intl.ListFormat('en', { style: 'long', type: 'conjunction' }).format(
      data.emptyYears.map(String),
    )}.
  </p>
{/if}

{#if data.closes.length > 0}
  <h2 class="mt-12 font-serif text-2xl font-light text-fg">Closed years</h2>
  <div class="mt-4 overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
    <table class="w-full text-left text-sm">
      <thead class="bg-surface">
        <tr class="label">
          <th class="px-5 py-3">Year</th>
          <!-- "Profit or loss": a closed year can be either, and the column
               happily shows a negative. -->
          <th class="px-5 py-3 text-right">Profit or loss</th>
          <th class="px-5 py-3">Closed on</th>
          <th class="px-5 py-3"></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-fg/10">
        {#each data.closes as row (row.id)}
          <tr>
            <td class="px-5 py-4 font-mono tabular-nums text-fg">{row.fiscalYear}</td>
            <td class="px-5 py-4 text-right font-mono tabular-nums text-fg/80">
              {money(row.netIncome)}
            </td>
            <td class="px-5 py-4 font-mono tabular-nums text-fg/60">{row.closedAt}</td>
            <td class="px-5 py-4 text-right">
              <!-- Only the most recent close can be re-opened: an earlier year
                   would stay locked by the later one anyway. -->
              {#if canAdjust && row.id === data.reopenableId}
                <form method="POST" action="?/reopen" use:enhance>
                  <input type="hidden" name="id" value={row.id} />
                  <button type="submit" class="link text-sm">Re-open</button>
                </form>
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}

// apps/mobile/src/app/(app)/ledger/close.tsx
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { pickActiveCompany } from '../../../lib/active-company';
import { api } from '../../../lib/api';
import { useMay } from '../../../lib/role';

// Mirror of apps/web's /ledger/close — the year-end close (TMC-159). Reached
// from inside The Ledger, so it sits behind the same airlock the portal already
// puts in front of accounting vocabulary. The copy stays plain regardless: the
// user reads "close out 2025", never "closing entries".

// How many finished years back to offer, matching web.
const YEARS_OFFERED = 4;

type Closable = {
  fiscalYear: number;
  netIncome: string;
  withdrawals: string;
  equityLabel: string;
  empty: boolean;
};

type ClosedRow = {
  id: string;
  fiscalYear: number;
  netIncome: string;
  closedAt: string;
};

const money = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

export default function LedgerClose() {
  const router = useRouter();
  const canAdjust = useMay('ledger:adjust');

  const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading');
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [closable, setClosable] = useState<Closable[]>([]);
  const [emptyYears, setEmptyYears] = useState<number[]>([]);
  const [closes, setCloses] = useState<ClosedRow[]>([]);
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    try {
      const compRes = await api.api.companies.$get();
      if (!compRes.ok) return setState('error');
      const company = await pickActiveCompany((await compRes.json()).companies);
      if (!company) return setState('error');
      setCompanyId(company.id);

      const closesRes = await api.api.ledger['period-closes'].$get({
        query: { companyId: company.id },
      });
      if (!closesRes.ok) return setState('error');
      const { closes: rows } = await closesRes.json();
      setCloses(
        rows.map((c) => ({
          id: c.id,
          fiscalYear: c.fiscalYear,
          netIncome: c.netIncome,
          closedAt: c.closedAt.slice(0, 10),
        })),
      );

      // Only years that are over and not already covered by a close are worth
      // previewing — a later closed year locks the earlier ones.
      const closedYears = new Set(rows.map((c) => c.fiscalYear));
      const newestClosed = rows.length > 0 ? Math.max(...rows.map((c) => c.fiscalYear)) : null;
      const lastFinished = new Date().getFullYear() - 1;

      const candidates: number[] = [];
      for (let y = lastFinished; y > lastFinished - YEARS_OFFERED; y--) {
        if (closedYears.has(y)) continue;
        if (newestClosed !== null && y < newestClosed) continue;
        candidates.push(y);
      }

      const previews = await Promise.all(
        candidates.map(async (fiscalYear): Promise<Closable | null> => {
          const res = await api.api.ledger['period-closes'].preview.$get({
            query: { companyId: company.id, fiscalYear: String(fiscalYear) },
          });
          if (!res.ok) return null;
          const p = await res.json();
          return {
            fiscalYear,
            netIncome: p.netIncome,
            withdrawals: p.withdrawals,
            equityLabel: p.equityLabel,
            empty: p.empty,
          };
        }),
      );
      const offered = previews.filter((p): p is Closable => p !== null);
      // Only years with something on them get a card — an empty year has nothing
      // to close and no button to press. The rest are named in one line so it's
      // still clear why they aren't listed.
      setClosable(offered.filter((p) => !p.empty));
      setEmptyYears(offered.filter((p) => p.empty).map((p) => p.fiscalYear));
      setState('ready');
    } catch {
      setState('error');
    }
  }, []);

  useFocusEffect(
    useCallback(() => {
      load();
    }, [load]),
  );

  // Closing is a deliberate act, so it goes through a confirm — the same beat
  // the web page gets from its expand-then-confirm panel.
  function confirmClose(year: Closable) {
    Alert.alert(
      `Close out ${year.fiscalYear}?`,
      `This locks ${year.fiscalYear} so nothing can change it, and moves the year's ${
        Number(year.netIncome) < 0 ? 'loss' : 'profit'
      } into ${year.equityLabel.toLowerCase()}. You can re-open it here later if you need to.`,
      [
        { text: 'Cancel', style: 'cancel' },
        { text: `Close ${year.fiscalYear}`, onPress: () => doClose(year.fiscalYear) },
      ],
    );
  }

  async function doClose(fiscalYear: number) {
    if (!companyId || busy) return;
    setBusy(true);
    try {
      const res = await api.api.ledger['period-closes'].$post({
        json: { companyId, fiscalYear },
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        Alert.alert('Could not close', closeErrorMessage(body?.error, fiscalYear));
        return;
      }
      await load();
    } finally {
      setBusy(false);
    }
  }

  function confirmReopen(row: ClosedRow) {
    Alert.alert(
      `Re-open ${row.fiscalYear}?`,
      `${row.fiscalYear} will accept changes again, and its profit moves back out of equity.`,
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Re-open', onPress: () => doReopen(row.id) },
      ],
    );
  }

  async function doReopen(id: string) {
    if (busy) return;
    setBusy(true);
    try {
      const res = await api.api.ledger['period-closes'][':id'].reopen.$post({ param: { id } });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        Alert.alert(
          'Could not re-open',
          body?.error === 'later_year_still_closed'
            ? 'Re-open the most recent year first.'
            : 'Could not re-open that year.',
        );
        return;
      }
      await load();
    } finally {
      setBusy(false);
    }
  }

  if (state === 'loading') {
    return (
      <SafeAreaView className="flex-1 items-center justify-center bg-cream" edges={['top']}>
        <ActivityIndicator className="text-ink" />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <Pressable onPress={() => router.back()} className="pb-2">
          <Text className="text-sm text-ink-subtle">← Ledger</Text>
        </Pressable>
        <Text className="font-mono text-xs uppercase tracking-widest text-gold-deep">
          The Ledger
        </Text>
        <Text className="mt-2 font-serif text-3xl font-light text-ink">Close out a year</Text>
        <Text className="mt-4 text-sm leading-relaxed text-ink-subtle">
          Closing a year moves its profit into your business's equity and locks the year, so nothing
          can change it afterwards. Most people do this once their accountant has finished the tax
          return.
        </Text>

        {state === 'error' ? (
          <Text className="mt-8 text-sm text-oxblood">Couldn't load this.</Text>
        ) : null}

        <Text className="mt-10 font-serif text-2xl font-light text-ink">Ready to close</Text>
        {closable.length === 0 ? (
          <Text className="mt-3 text-sm text-ink-muted">
            Nothing to close right now. A year can be closed once it's over.
          </Text>
        ) : (
          closable.map((year) => (
            <View
              key={year.fiscalYear}
              className="mt-4 rounded-sm border border-ink/10 bg-cream-warm p-5"
            >
              <Text className="font-serif text-xl text-ink">{year.fiscalYear}</Text>
              <Text className="mt-1 text-sm text-ink-muted">
                {Number(year.netIncome) < 0 ? 'Loss' : 'Profit'} of{' '}
                <Text className="font-mono tabular-nums text-ink">
                  {money(String(Math.abs(Number(year.netIncome))))}
                </Text>
                {Number(year.withdrawals) > 0 ? (
                  <Text className="text-ink-muted">
                    {' · '}
                    <Text className="font-mono tabular-nums text-ink">
                      {money(year.withdrawals)}
                    </Text>
                    {' taken out'}
                  </Text>
                ) : null}
              </Text>
              {canAdjust ? (
                <Pressable
                  onPress={() => confirmClose(year)}
                  disabled={busy}
                  className="mt-4 self-start rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
                >
                  <Text className="text-sm font-medium text-cream">Close {year.fiscalYear}</Text>
                </Pressable>
              ) : null}
            </View>
          ))
        )}

        {/* Years with no activity get one line rather than a card each — there's
            nothing to close, but naming them answers "why isn't 2023 listed?". */}
        {emptyYears.length > 0 ? (
          <Text className="mt-4 text-sm text-ink-subtle">
            Nothing on the books for{' '}
            {new Intl.ListFormat('en', { style: 'long', type: 'conjunction' }).format(
              emptyYears.map(String),
            )}
            .
          </Text>
        ) : null}

        {closes.length > 0 ? (
          <>
            <Text className="mt-12 font-serif text-2xl font-light text-ink">Closed years</Text>
            {closes.map((row, i) => (
              <View key={row.id} className="mt-4 rounded-sm border border-ink/10 bg-cream-warm p-5">
                <View className="flex-row items-center justify-between">
                  <Text className="font-mono tabular-nums text-lg text-ink">{row.fiscalYear}</Text>
                  <Text className="font-mono tabular-nums text-ink/80">{money(row.netIncome)}</Text>
                </View>
                <Text className="mt-1 font-mono text-xs uppercase tracking-widest text-ink-subtle">
                  Closed {row.closedAt}
                </Text>
                {/* Only the most recent close can be re-opened: an earlier year
                    would stay locked by the later one anyway. */}
                {canAdjust && i === 0 ? (
                  <Pressable
                    onPress={() => confirmReopen(row)}
                    disabled={busy}
                    className="mt-3 self-start py-1"
                  >
                    <Text className="text-sm text-gold-deep">Re-open</Text>
                  </Pressable>
                ) : null}
              </View>
            ))}
          </>
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
}

// Server error codes are accounting-shaped; the user reads plain sentences.
function closeErrorMessage(code: string | undefined, fiscalYear: number): string {
  switch (code) {
    case 'year_not_finished':
      return `${fiscalYear} isn't over yet.`;
    case 'already_closed':
      return `${fiscalYear} is already closed.`;
    case 'later_year_closed':
      return 'A more recent year is already closed. Re-open it first.';
    case 'nothing_to_close':
      return `There's nothing on the books for ${fiscalYear}.`;
    case 'equity_account_missing':
      return 'This business is missing an equity account. Contact support.';
    default:
      return 'Could not close that year.';
  }
}
