// apps/web/src/routes/(app)/customers/[id]/edit/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  // On first render, seed values from the loaded customer. On a fail()
  // re-render the user's just-submitted values win so they don't lose
  // their typing — same shape as the create form, just with a different
  // initial source.
  const seed = $derived(form?.values ?? data.customer);
  const fieldErrors = $derived(form?.fieldErrors ?? {});

  type FieldKey =
    | 'name'
    | 'email'
    | 'phone'
    | 'addressLine1'
    | 'addressLine2'
    | 'city'
    | 'region'
    | 'postalCode'
    | 'country'
    | 'notes';

  function v(key: FieldKey): string {
    const raw = (seed as Record<string, unknown>)[key];
    return typeof raw === 'string' ? raw : '';
  }
  function err(key: FieldKey): string | undefined {
    return (fieldErrors as Record<string, string>)[key];
  }
</script>

<a href="/customers/{data.customer.id}" class="eyebrow text-ink/60 hover:text-ink">← {data.customer.name}</a>
<h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
  Edit customer<span class="text-gold-deep">.</span>
</h1>

{#if form?.formError}
  <div class="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3 text-sm text-oxblood">
    {form.formError}
  </div>
{/if}

<form method="post" class="mt-8 space-y-6">
  <div>
    <label for="name" class="font-mono text-xs uppercase tracking-widest text-ink/50">
      Name<span class="text-gold-deep">*</span>
    </label>
    <input
      id="name"
      name="name"
      type="text"
      required
      maxlength="200"
      value={v('name')}
      class="mt-1 w-full rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
    />
    {#if err('name')}
      <p class="mt-1 text-xs text-oxblood">{err('name')}</p>
    {/if}
  </div>

  <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
    <div>
      <label for="email" class="font-mono text-xs uppercase tracking-widest text-ink/50">Email</label>
      <input
        id="email"
        name="email"
        type="email"
        maxlength="320"
        value={v('email')}
        class="mt-1 w-full rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
      />
      {#if err('email')}
        <p class="mt-1 text-xs text-oxblood">{err('email')}</p>
      {/if}
    </div>
    <div>
      <label for="phone" class="font-mono text-xs uppercase tracking-widest text-ink/50">Phone</label>
      <input
        id="phone"
        name="phone"
        type="tel"
        maxlength="50"
        value={v('phone')}
        class="mt-1 w-full rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
      />
      {#if err('phone')}
        <p class="mt-1 text-xs text-oxblood">{err('phone')}</p>
      {/if}
    </div>
  </div>

  <fieldset class="space-y-4">
    <legend class="font-mono text-xs uppercase tracking-widest text-ink/50">Address</legend>
    <input
      name="addressLine1"
      type="text"
      maxlength="200"
      placeholder="Street"
      value={v('addressLine1')}
      class="w-full rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
    />
    <input
      name="addressLine2"
      type="text"
      maxlength="200"
      placeholder="Suite, unit, etc."
      value={v('addressLine2')}
      class="w-full rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
    />
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-3">
      <input
        name="city"
        type="text"
        maxlength="100"
        placeholder="City"
        value={v('city')}
        class="rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
      />
      <input
        name="region"
        type="text"
        maxlength="100"
        placeholder="State / Region"
        value={v('region')}
        class="rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
      />
      <input
        name="postalCode"
        type="text"
        maxlength="20"
        placeholder="Postal code"
        value={v('postalCode')}
        class="rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
      />
    </div>
    <input
      name="country"
      type="text"
      maxlength="2"
      placeholder="Country (ISO, e.g. US)"
      value={v('country')}
      class="w-32 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 uppercase text-ink focus:border-gold-deep focus:outline-none"
    />
  </fieldset>

  <div>
    <label for="notes" class="font-mono text-xs uppercase tracking-widest text-ink/50">Notes</label>
    <textarea
      id="notes"
      name="notes"
      rows="4"
      maxlength="5000"
      class="mt-1 w-full rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink focus:border-gold-deep focus:outline-none"
      >{v('notes')}</textarea
    >
  </div>

  <div class="flex items-center gap-4">
    <button
      type="submit"
      class="rounded-sm bg-ink px-5 py-2 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
    >
      Save changes
    </button>
    <a href="/customers/{data.customer.id}" class="text-sm text-ink/60 hover:text-ink">Cancel</a>
  </div>
</form>

// apps/mobile/src/app/(app)/customers/[id]/edit.tsx
import { customerUpdateSchema } from '@thalermark/validation';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../../lib/api';

// Edit half of apps/web's /customers/[id]/edit. Seeds from the loaded customer,
// then PATCHes with full-replacement semantics — undefined optionals clear the
// column (mirror of customers/new minus the dupe detection, which only matters
// when creating). companyId is immutable, so it's not in the schema.
type OptionalKey =
  | 'email'
  | 'phone'
  | 'addressLine1'
  | 'addressLine2'
  | 'city'
  | 'region'
  | 'postalCode'
  | 'country'
  | 'notes';

const OPTIONAL_FIELDS: OptionalKey[] = [
  'email',
  'phone',
  'addressLine1',
  'addressLine2',
  'city',
  'region',
  'postalCode',
  'country',
  'notes',
];

type FieldKey = 'name' | OptionalKey;
type Values = Record<FieldKey, string>;

export default function EditCustomer() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [values, setValues] = useState<Values | null>(null);
  const [fieldErrors, setFieldErrors] = useState<Partial<Record<FieldKey, string>>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Seed once from the loaded customer; don't clobber edits on a focus regain.
  useFocusEffect(
    useCallback(() => {
      if (values) return;
      let active = true;
      api.api.customers[':id']
        .$get({ param: { id } })
        .then(async (res) => {
          if (!active) return;
          if (!res.ok) {
            setFormError('load_failed');
            return;
          }
          const c = await res.json();
          setValues({
            name: c.name,
            email: c.email ?? '',
            phone: c.phone ?? '',
            addressLine1: c.addressLine1 ?? '',
            addressLine2: c.addressLine2 ?? '',
            city: c.city ?? '',
            region: c.region ?? '',
            postalCode: c.postalCode ?? '',
            country: c.country ?? '',
            notes: c.notes ?? '',
          });
        })
        .catch(() => {
          if (active) setFormError('load_failed');
        });
      return () => {
        active = false;
      };
    }, [id, values]),
  );

  const set = (key: FieldKey, val: string) => setValues((v) => (v ? { ...v, [key]: val } : v));

  async function onSubmit() {
    if (!values) return;
    setFormError(null);
    setFieldErrors({});

    // Trim; omit empty optionals so undefined (not '') reaches the schema —
    // full-replacement on the API clears the column. Matches customers/new.
    const body: Record<string, string> = { name: values.name.trim() };
    for (const k of OPTIONAL_FIELDS) {
      const trimmed = values[k].trim();
      if (trimmed !== '') body[k] = trimmed;
    }

    const parsed = customerUpdateSchema.safeParse(body);
    if (!parsed.success) {
      const errs: Partial<Record<FieldKey, string>> = {};
      for (const issue of parsed.error.issues) {
        const key = String(issue.path[0] ?? '') as FieldKey;
        if (key && !errs[key]) errs[key] = issue.message;
      }
      setFieldErrors(errs);
      return;
    }

    setSubmitting(true);
    try {
      const res = await api.api.customers[':id'].$patch({ param: { id }, json: parsed.data });
      if (!res.ok) {
        const errBody = (await res.json().catch(() => null)) as { error?: string } | null;
        setFormError(errBody?.error ?? 'save_failed');
        return;
      }
      router.replace(`/customers/${id}`);
    } catch {
      setFormError('save_failed');
    } finally {
      setSubmitting(false);
    }
  }

  if (!values) {
    return (
      <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
        {formError ? (
          <Text className="mt-12 px-6 text-sm text-oxblood">Couldn't load this customer.</Text>
        ) : (
          <View className="mt-12 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        )}
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
              ← {values.name || 'Customer'}
            </Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">Edit customer</Text>

          {formError ? (
            <View className="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
              <Text className="text-sm text-oxblood">{formError}</Text>
            </View>
          ) : null}

          <View className="mt-8 space-y-5">
            <Field
              label="Name *"
              value={values.name}
              onChangeText={(t) => set('name', t)}
              error={fieldErrors.name}
            />
            <Field
              label="Email"
              value={values.email}
              onChangeText={(t) => set('email', t)}
              error={fieldErrors.email}
              keyboardType="email-address"
              autoCapitalize="none"
            />
            <Field
              label="Phone"
              value={values.phone}
              onChangeText={(t) => set('phone', t)}
              keyboardType="phone-pad"
            />
            <Field
              label="Street"
              value={values.addressLine1}
              onChangeText={(t) => set('addressLine1', t)}
            />
            <Field
              label="Suite, unit, etc."
              value={values.addressLine2}
              onChangeText={(t) => set('addressLine2', t)}
            />
            <Field label="City" value={values.city} onChangeText={(t) => set('city', t)} />
            <Field
              label="State / Region"
              value={values.region}
              onChangeText={(t) => set('region', t)}
            />
            <Field
              label="Postal code"
              value={values.postalCode}
              onChangeText={(t) => set('postalCode', t)}
            />
            <Field
              label="Country (ISO, e.g. US)"
              value={values.country}
              onChangeText={(t) => set('country', t)}
              autoCapitalize="characters"
              error={fieldErrors.country}
            />
            <Field
              label="Notes"
              value={values.notes}
              onChangeText={(t) => set('notes', t)}
              multiline
            />

            <Pressable
              onPress={onSubmit}
              disabled={submitting || values.name.trim().length === 0}
              className="mt-2 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
            >
              {submitting ? (
                <ActivityIndicator color="#f4ede0" />
              ) : (
                <Text className="text-center text-sm font-medium text-cream">Save changes</Text>
              )}
            </Pressable>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

// Matches the field idiom in customers/new.
function Field({
  label,
  value,
  onChangeText,
  error,
  keyboardType,
  autoCapitalize,
  multiline,
}: {
  label: string;
  value: string;
  onChangeText: (t: string) => void;
  error?: string;
  keyboardType?: 'email-address' | 'phone-pad';
  autoCapitalize?: 'none' | 'characters';
  multiline?: boolean;
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">{label}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        keyboardType={keyboardType}
        autoCapitalize={autoCapitalize}
        multiline={multiline}
        className="mt-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
      />
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}
