// apps/web/src/routes/(app)/invoices/[id]/edit/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { enhanceForm } from '$lib/form-enhance';
    import { untrack } from 'svelte';
  import ContactPicker from '$lib/components/ContactPicker.svelte';
  import ItemPicker from '$lib/components/ItemPicker.svelte';
  import { defaultPolicyId, lineTax, policyRate } from '$lib/line-tax';
  import {
    type LineItemType,
    addMoney,
    formatUnitPrice,
    billingUnitLabel,
    entryUnit,
    formatQuantity,
    multiplyMoney,
    sumMoney,
    timeEntryLineDescription,
    unitPriceFromTotal,
  } from '@thalermark/validation';
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();

  type Row = {
    description: string;
    quantity: string;
    unitLabel: string;
    unitPrice: string;
    amount: string;
    sourceItemId: string | null;
    type: LineItemType;
    taxable: boolean;
    taxPolicyId: string;
    // Set on a row added from tracked time in THIS edit. Pre-existing hour lines
    // have no back-link to their entry — those ids ride the hidden
    // alreadyBilledTimeEntryId fields instead.
    timeEntryId: string | null;
  };

  // Seed strategy mirrors /invoices/new but the "no prior submit" source is
  // the loaded invoice instead of empty defaults / today's date. Static
  // inputs render via `value={form?.values?.X ?? data.invoice.X}`; live-
  // preview inputs (line item rows) use $state with an untrack() initializer so
  // the SSR re-render after a fail() captures the right initial values without
  // firing the state_referenced_locally warning. Tax is derived from the lines.
  const values = $derived(form?.values);

  let rows = $state<Row[]>(
    untrack(() => {
      const seeded = form?.values?.lineItems;
      if (seeded && seeded.length > 0) {
        return seeded.map((li) => ({
          description: li.description,
          quantity: li.quantity,
          unitLabel: li.unitLabel ?? '',
          unitPrice: formatUnitPrice(li.unitPrice),
          amount: multiplyMoney(li.quantity, li.unitPrice),
          sourceItemId: li.sourceItemId ?? null,
          type: li.type === 'product' ? 'product' : 'service',
          taxable: li.taxable ?? false,
          taxPolicyId: li.taxPolicyId ?? '',
          timeEntryId: li.timeEntryId ?? null,
        }));
      }
      return data.invoice.lineItems.map((li) => ({
        description: li.description,
        quantity: li.quantity,
        unitLabel: li.unitLabel ?? '',
        unitPrice: formatUnitPrice(li.unitPrice),
        amount: multiplyMoney(li.quantity, li.unitPrice),
        sourceItemId: li.sourceItemId ?? null,
        type: li.type === 'product' ? 'product' : 'service',
        // Since 0027 the saved line carries its own link, so an hour line
        // rebuilds itself on load — and deleting it releases the entry.
        timeEntryId: li.timeEntryId ?? null,
        taxable: li.taxable ?? false,
        taxPolicyId: li.taxPolicyId ?? '',
      }));
    }),
  );

  // Hours on this job that no invoice has claimed. Local state because pressing
  // Add moves them into the line table — they should leave this list at the same
  // moment, or the user cannot tell whether the press worked.
  let pendingTime = $state(untrack(() => data.unbilledTime));

  function addTrackedTime() {
    const added: Row[] = pendingTime.map((t) => {
      const unitPrice = t.rate ?? '0';
      // Non-null by construction: the loader drops entries with nothing billable
      // in their job's unit.
      const quantity = t.quantity as string;
      return {
        description: timeEntryLineDescription({
          entryDate: t.entryDate,
          note: t.note,
          jobName: data.jobName,
          // A time-card entry names its clock span on the line (TMC-265).
          startTime: t.startTime,
          endTime: t.endTime,
        }),
        quantity,
        unitLabel: billingUnitLabel(data.billingUnit, quantity),
        unitPrice: formatUnitPrice(unitPrice),
        // Priced through the same multiplyMoney every typed row uses, so a
        // billed hour and a hand-typed hour cannot round differently.
        amount: multiplyMoney(quantity, unitPrice),
        sourceItemId: null,
        // Labour is a service — routes revenue to 4000 in the hidden ledger.
        type: 'service' as LineItemType,
        // Taxability of labour varies by state and trade; a tick beats a guess.
        taxable: false,
        taxPolicyId: '',
        timeEntryId: t.id,
      };
    });
    // Drop a trailing blank row rather than stranding it between real lines.
    const keep = rows.filter((r) => r.description || r.quantity || r.unitPrice);
    rows = [...keep, ...added];
    pendingTime = [];
  }

  const computedRows = $derived(
    rows.map((r) => {
      const rate = r.taxable ? policyRate(data.taxPolicies, r.taxPolicyId) : '0';
      return { ...r, tax: lineTax(r.taxable, rate, r.amount) };
    }),
  );
  const subtotal = $derived(sumMoney(computedRows.map((r) => r.amount)));
  const taxTotal = $derived(sumMoney(computedRows.map((r) => r.tax)));
  const total = $derived(addMoney(subtotal, taxTotal));

  // Editing quantity/unit price re-derives the amount (unit price sticky);
  // editing the amount back-computes a 4dp unit price so an agreed total that
  // doesn't divide evenly is representable (e.g. $650 over 7 → $92.8571 →
  // $650.00). The form submits quantity + unit price; the server recomputes the
  // amount, so the (unnamed) amount input is preview sugar steering the price.
  function recalcAmount(row: Row) {
    row.amount = multiplyMoney(row.quantity, row.unitPrice);
  }
  function recalcPrice(row: Row) {
    row.unitPrice = unitPriceFromTotal(row.amount, row.quantity);
  }

  function resolvePolicyId(pref: string): string {
    if (pref && data.taxPolicies.some((p) => p.id === pref)) return pref;
    return defaultPolicyId(data.taxPolicies) || data.taxPolicies[0]?.id || '';
  }
  function onTaxableChange(row: Row) {
    if (row.taxable && !row.taxPolicyId) row.taxPolicyId = resolvePolicyId('');
  }
  function applyItemTax(row: Row, taxable: boolean, taxPolicyId: string | null) {
    row.taxable = taxable;
    row.taxPolicyId = taxable ? resolvePolicyId(taxPolicyId ?? '') : '';
  }

  // From-block "show on this invoice" toggles. Seed from the prior submit on a
  // fail re-render, else the invoice's stored flags. `??` respects a returned
  // `false` (only null/undefined falls through).
  const showAddress = $derived(form?.values?.showAddress ?? data.invoice.showAddress);
  const showPhone = $derived(form?.values?.showPhone ?? data.invoice.showPhone);
  const showEmail = $derived(form?.values?.showEmail ?? data.invoice.showEmail);

  const fieldErrors = $derived(form?.fieldErrors ?? {});
  function err(key: string): string | undefined {
    return (fieldErrors as Record<string, string>)[key];
  }

  function addRow() {
    rows.push(blankRow());
  }

  function removeRow(index: number) {
    if (rows.length <= 1) return;
    rows.splice(index, 1);
  }

  function blankRow(): Row {
    return { description: '', quantity: '', unitLabel: '', unitPrice: '', amount: '', sourceItemId: null, type: 'service', taxable: false, taxPolicyId: '', timeEntryId: null };
  }
</script>

<a href="/invoices/{data.invoice.id}" class="eyebrow text-fg/60 hover:text-fg">← Invoice {data.invoice.number}</a>
<h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
  Edit invoice<span class="text-accent">.</span>
</h1>

{#if form?.formError}
  <div class="mt-6 rounded-sm border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger" data-form-error role="alert" tabindex="-1">
    {form.formError}
  </div>
{/if}

<form method="post" class="mt-8 space-y-8" use:enhance={enhanceForm}>
  <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
    <div>
      <label for="contactName" class="label">
        Contact<span class="text-accent">*</span>
      </label>
      <ContactPicker
        allowCreate={false}
        initialContactId={values?.contactId ?? data.invoice.contactId}
        initialContactName={values?.contactName ?? data.initialContact?.name ?? ''}
        fieldError={err('contactId')}
      />
    </div>

    <div>
      <label for="number" class="label">
        Number<span class="text-accent">*</span>
      </label>
      <input
        id="number"
        name="number"
        type="text"
        required
        maxlength="50"
        value={values?.number ?? data.invoice.number}
        class="field mt-1"
      />
      {#if err('number')}
        <p class="mt-1 text-xs text-danger">{err('number')}</p>
      {/if}
    </div>

    <div>
      <label for="issueDate" class="label">
        Issued<span class="text-accent">*</span>
      </label>
      <input
        id="issueDate"
        name="issueDate"
        type="date"
        required
        value={values?.issueDate ?? data.invoice.issueDate}
        class="field mt-1"
      />
      {#if err('issueDate')}
        <p class="mt-1 text-xs text-danger">{err('issueDate')}</p>
      {/if}
    </div>

    <div>
      <label for="dueDate" class="label">
        Due<span class="text-accent">*</span>
      </label>
      <input
        id="dueDate"
        name="dueDate"
        type="date"
        required
        value={values?.dueDate ?? data.invoice.dueDate}
        class="field mt-1"
      />
      {#if err('dueDate')}
        <p class="mt-1 text-xs text-danger">{err('dueDate')}</p>
      {/if}
    </div>
  </div>

  <fieldset class="space-y-3">
    <legend class="label">Line items</legend>
    <!--
      Hours logged AFTER this draft was started. Not seeded automatically the way
      /invoices/new seeds them: there, nothing exists to disturb. Here the lines
      are already curated, so adding is an explicit press.
    -->
    {#if pendingTime.length > 0}
      <div class="rounded-sm border border-accent/30 bg-accent/5 p-4">
        <p class="label">Unbilled work on this job</p>
        <ul class="mt-2 divide-y divide-fg/10">
          {#each pendingTime as t (t.id)}
            <li class="flex items-center gap-3 py-1.5 text-sm">
              <span class="w-24 shrink-0 text-fg/60">{t.entryDate}</span>
              <!--
                Reads in the job's own unit (TMC-264): "3 visits", not "1.5 h".
                The picker has to name the same thing the seeded line will, or
                the user ticks hours and gets visits.
              -->
              <span class="w-20 shrink-0 font-mono tabular-nums text-fg/80">
                {formatQuantity(t.quantity ?? '0')}
                {billingUnitLabel(entryUnit(t, data.billingUnit), t.quantity ?? '0')}
              </span>
              <span class="min-w-0 flex-1 truncate text-fg/70">{t.note ?? ''}</span>
              <span class="shrink-0 font-mono tabular-nums text-fg/60">
                {t.rate
                  ? `$${formatUnitPrice(t.rate)}/${billingUnitLabel(entryUnit(t, data.billingUnit), '1')}`
                  : 'no rate'}
              </span>
            </li>
          {/each}
        </ul>
        <button type="button" class="btn mt-3" onclick={addTrackedTime}>
          Add to this invoice
        </button>
      </div>
    {/if}
    {#if err('lineItems')}
      <p class="text-xs text-danger">{err('lineItems')}</p>
    {/if}
    <div class="overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
      <table class="w-full text-left text-sm">
        <thead class="bg-surface">
          <tr class="label">
            <th class="px-3 py-2">Description</th>
            <th class="w-28 px-3 py-2 text-right">Qty</th>
            <th class="w-32 px-3 py-2 text-right">Unit price</th>
            <th class="w-36 px-3 py-2">Tax</th>
            <th class="w-32 px-3 py-2 text-right">Amount</th>
            <th class="w-10 px-3 py-2"></th>
          </tr>
        </thead>
        <tbody class="divide-y divide-fg/10">
          {#each rows as row, i (i)}
            <tr>
              <td class="px-3 py-2 align-top">
                <ItemPicker
                  bind:description={row.description}
                  bind:quantity={row.quantity}
                  bind:unitPrice={row.unitPrice}
                  bind:sourceItemId={row.sourceItemId}
                  onpick={(s) => {
                    row.type = s.type;
                    row.unitLabel = s.unitLabel ?? '';
                    applyItemTax(row, s.taxable, s.taxPolicyId);
                    recalcAmount(row);
                  }}
                />
                <select
                  bind:value={row.type}
                  name="li_type"
                  aria-label="Type"
                  class="mt-1 rounded-sm border border-fg/15 bg-surface px-1.5 py-1 text-xs text-fg/70 focus:border-accent focus:outline-none"
                >
                  <option value="service">Service</option>
                  <option value="product">Product</option>
                </select>
              </td>
              <td class="px-3 py-2 align-top">
                <input
                  type="text"
                  name="li_quantity"
                  inputmode="decimal"
                  required
                  bind:value={row.quantity}
                  oninput={() => recalcAmount(row)}
                  class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                />
                <input
                  type="text"
                  name="li_unitLabel"
                  maxlength="50"
                  placeholder="unit"
                  aria-label="Unit"
                  bind:value={row.unitLabel}
                  class="mt-1 w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right text-xs text-fg/70 focus:border-accent focus:outline-none"
                />
              </td>
              <td class="px-3 py-2 align-top">
                <input
                  type="text"
                  name="li_unitPrice"
                  inputmode="decimal"
                  required
                  bind:value={row.unitPrice}
                  oninput={() => recalcAmount(row)}
                  class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                />
              </td>
              <td class="px-3 py-2 align-top">
                <label class="flex items-center gap-1.5 text-xs text-fg/70">
                  <input
                    type="checkbox"
                    bind:checked={row.taxable}
                    onchange={() => onTaxableChange(row)}
                    class="size-4 accent-accent"
                  />
                  Taxable
                </label>
                {#if row.taxable}
                  {#if data.taxPolicies.length > 0}
                    <select
                      bind:value={row.taxPolicyId}
                      aria-label="Tax policy"
                      class="mt-1 w-full rounded-sm border border-fg/15 bg-surface px-1.5 py-1 text-xs text-fg focus:border-accent focus:outline-none"
                    >
                      {#each data.taxPolicies as p (p.id)}
                        <option value={p.id}>{p.name} ({Number(p.ratePct)}%)</option>
                      {/each}
                    </select>
                  {:else}
                    <a
                      href="/settings/tax-policies/new"
                      class="mt-1 block text-[0.65rem] text-accent hover:underline"
                    >
                      + Add a rate
                    </a>
                  {/if}
                {/if}
                <input type="hidden" name="li_taxable" value={row.taxable ? '1' : '0'} />
                <input type="hidden" name="li_timeEntryId" value={row.timeEntryId ?? ''} />
                <input
                  type="hidden"
                  name="li_taxPolicyId"
                  value={row.taxable ? row.taxPolicyId : ''}
                />
              </td>
              <td class="px-3 py-2 align-top">
                <input
                  type="text"
                  inputmode="decimal"
                  aria-label="Amount"
                  bind:value={row.amount}
                  oninput={() => recalcPrice(row)}
                  class="w-full rounded-sm border border-fg/15 bg-surface px-2 py-1 text-right font-mono tabular-nums text-fg focus:border-accent focus:outline-none"
                />
                {#if row.taxable}
                  <span class="mt-1 block text-right text-[0.65rem] font-normal text-fg/50">
                    +{computedRows[i]?.tax ?? '0.00'} tax
                  </span>
                {/if}
              </td>
              <td class="px-3 py-2 text-right align-top">
                <button
                  type="button"
                  onclick={() => removeRow(i)}
                  disabled={rows.length <= 1}
                  aria-label="Remove row"
                  class="text-fg/50 transition-colors hover:text-danger disabled:cursor-not-allowed disabled:opacity-30"
                >
                  ×
                </button>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
    <button
      type="button"
      onclick={addRow}
      class="text-sm font-medium text-accent hover:text-fg"
    >
      + Add row
    </button>
  </fieldset>

  <div class="flex justify-end">
    <dl class="w-full max-w-xs rounded-sm border border-fg/10 bg-surface-2 p-4 text-sm">
      <div class="flex justify-between">
        <dt class="label">Subtotal</dt>
        <dd class="font-mono tabular-nums text-fg">{subtotal}</dd>
      </div>
      <div class="mt-2 flex justify-between">
        <dt class="label">Tax</dt>
        <dd class="font-mono tabular-nums text-fg">{taxTotal}</dd>
      </div>
      <div class="mt-3 flex justify-between border-t border-fg/10 pt-3">
        <dt class="font-mono text-xs uppercase tracking-widest text-fg/70">Total</dt>
        <dd class="font-mono tabular-nums text-lg text-fg">{total}</dd>
      </div>
    </dl>
  </div>

  <div>
    <label for="notes" class="label">Notes</label
    >
    <textarea
      id="notes"
      name="notes"
      rows="4"
      maxlength="5000"
      class="field mt-1"
      >{values?.notes ?? data.invoice.notes ?? ''}</textarea
    >
  </div>

  <fieldset class="space-y-2">
    <legend class="label">Your details on this invoice</legend>
    <p class="text-xs text-fg/50">
      Choose which of your business details appear under your name. Only details you've added in
      <a href="/settings/business" class="link">Settings → Business</a> will show.
    </p>
    <label class="flex items-center gap-3 text-sm text-fg">
      <input
        type="checkbox"
        name="showAddress"
        checked={showAddress}
        class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
      />
      Show my address
    </label>
    <label class="flex items-center gap-3 text-sm text-fg">
      <input
        type="checkbox"
        name="showPhone"
        checked={showPhone}
        class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
      />
      Show my phone
    </label>
    <label class="flex items-center gap-3 text-sm text-fg">
      <input
        type="checkbox"
        name="showEmail"
        checked={showEmail}
        class="size-4 rounded-sm border-fg/30 text-accent focus:ring-accent"
      />
      Show my email
    </label>
  </fieldset>

  <div class="flex items-center gap-4">
    <button
      type="submit"
      class="btn"
    >
      Save changes
    </button>
    <a href="/invoices/{data.invoice.id}" class="text-sm text-fg/60 hover:text-fg">Cancel</a>
  </div>
</form>

// apps/mobile/src/app/(app)/invoices/[id]/edit.tsx
import {
  type InvoiceLineItemInput,
  type LineItemType,
  addMoney,
  formatUnitPrice,
  hoursFromMinutes,
  hoursUnitLabel,
  invoiceUpdateSchema,
  multiplyMoney,
  sumMoney,
  timeEntryLineDescription,
  unitPriceFromTotal,
} from '@thalermark/validation';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Checkbox } from '../../../../components/Checkbox';
import { ContactField } from '../../../../components/ContactField';
import { DateField } from '../../../../components/DateField';
import { type ItemPatch, ItemPickerField } from '../../../../components/ItemPickerField';
import { TaxRow } from '../../../../components/TaxRow';
import { TypeRow } from '../../../../components/TypeRow';
import { api } from '../../../../lib/api';
import { apiErrorMessage } from '../../../../lib/api-errors';
import { type TaxPolicyLite, lineTax, policyRate, resolvePolicyId } from '../../../../lib/line-tax';

// Edit half of apps/web's /invoices/[id]/edit — draft-only on the API (the
// detail screen only surfaces the Edit button for drafts). PATCHes the whole
// invoice (invoiceUpdateSchema = create minus companyId), so the form re-sends
// every field + line. Leaner than invoices/new: the ContactField re-picks an
// existing contact only (allowCreate=false — a draft already names one).
// CRITICAL: each line carries its sourceItemId through unchanged, or editing a
// draft would null the top-products breadcrumb (see apps/mobile/CLAUDE.md).
type Row = {
  description: string;
  quantity: string;
  unitLabel: string;
  unitPrice: string;
  amount: string;
  sourceItemId: string | null;
  type: LineItemType;
  taxable: boolean;
  taxPolicyId: string;
  // The tracked time entry this line bills (TMC-180). Since 0027 the saved line
  // carries its own link, so an hour line rebuilds itself on load and deleting
  // the row releases the entry.
  timeEntryId: string | null;
};
const blankRow = (): Row => ({
  description: '',
  quantity: '',
  unitLabel: '',
  unitPrice: '',
  amount: '',
  sourceItemId: null,
  timeEntryId: null,
  type: 'service',
  taxable: false,
  taxPolicyId: '',
});
type Seed = {
  contactId: string;
  number: string;
  issueDate: string;
  dueDate: string;
  notes: string;
  showAddress: boolean;
  showPhone: boolean;
  showEmail: boolean;
  rows: Row[];
};

const FRIENDLY: Record<string, string> = {
  invoice_number_taken: 'Invoice number already used for this company. Try another.',
  customer_company_mismatch: 'Selected contact does not belong to this company.',
  contact_not_found: 'Selected contact no longer exists.',
  invalid_transition: 'This invoice can no longer be edited.',
};

export default function EditInvoice() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [seed, setSeed] = useState<Seed | null>(null);
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [contactName, setContactName] = useState('');
  const [taxPolicies, setTaxPolicies] = useState<TaxPolicyLite[]>([]);
  // Names the job on a seeded line when the entry carries no note of its own.
  const [jobName, setJobName] = useState('');
  const [pendingTime, setPendingTime] = useState<
    {
      id: string;
      entryDate: string;
      minutes: number;
      hours: string;
      note: string | null;
      rate: string | null;
    }[]
  >([]);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Seed once from the invoice + contact list; don't clobber edits on refocus.
  useFocusEffect(
    useCallback(() => {
      if (seed) return;
      let active = true;
      (async () => {
        const invRes = await api.api.invoices[':id'].$get({ param: { id } });
        if (!active) return;
        if (!invRes.ok) {
          setFormError('That could not be loaded. Try again.');
          return;
        }
        const inv = await invRes.json();
        setCompanyId(inv.companyId);
        // The ContactField type-ahead searches on demand; we only need the
        // currently linked contact's name to seed its display text.
        const cRes = await api.api.contacts[':id'].$get({ param: { id: inv.contactId } });
        if (active && cRes.ok) setContactName((await cRes.json()).name);
        setSeed({
          contactId: inv.contactId,
          number: inv.number,
          issueDate: inv.issueDate,
          dueDate: inv.dueDate,
          notes: inv.notes ?? '',
          showAddress: inv.showAddress,
          showPhone: inv.showPhone,
          showEmail: inv.showEmail,
          rows: inv.lineItems.map((li) => ({
            description: li.description,
            quantity: li.quantity,
            unitLabel: li.unitLabel ?? '',
            unitPrice: formatUnitPrice(li.unitPrice),
            amount: multiplyMoney(li.quantity, li.unitPrice),
            sourceItemId: li.sourceItemId ?? null,
            timeEntryId: li.timeEntryId ?? null,
            type: li.type === 'product' ? 'product' : 'service',
            taxable: li.taxable ?? false,
            taxPolicyId: li.taxPolicyId ?? '',
          })),
        });

        // Hours logged on this invoice's job that no invoice has claimed, so a
        // draft can absorb time logged AFTER it was started. Adding is an
        // explicit press, unlike the create screen which seeds automatically:
        // there nothing exists to disturb, here the lines are already curated.
        if (inv.jobId) {
          const timeRes = await api.api.jobs[':id'].time.$get({
            param: { id: inv.jobId },
            query: { unbilled: 'true' },
          });
          if (active && timeRes.ok) {
            const { timeEntries, jobName } = await timeRes.json();
            setJobName(jobName);
            setPendingTime(
              timeEntries.map((t) => ({
                id: t.id,
                entryDate: t.entryDate,
                minutes: t.minutes,
                hours: hoursFromMinutes(t.minutes),
                note: t.note,
                rate: t.rate,
              })),
            );
          }
        }
        const polRes = await api.api['tax-policies'].$get({ query: { companyId: inv.companyId } });
        if (active && polRes.ok) {
          const { taxPolicies: pols } = await polRes.json();
          setTaxPolicies(
            pols.map((p) => ({
              id: p.id,
              name: p.name,
              ratePct: p.ratePct,
              isDefault: p.isDefault,
            })),
          );
        }
      })().catch(() => {
        if (active) setFormError('That could not be loaded. Try again.');
      });
      return () => {
        active = false;
      };
    }, [id, seed]),
  );

  const set = <K extends keyof Seed>(key: K, val: Seed[K]) =>
    setSeed((s) => (s ? { ...s, [key]: val } : s));
  const patchRow = (i: number, patch: Partial<Row>) =>
    setSeed((s) =>
      s ? { ...s, rows: s.rows.map((r, j) => (j === i ? { ...r, ...patch } : r)) } : s,
    );
  const addRow = () => setSeed((s) => (s ? { ...s, rows: [...s.rows, blankRow()] } : s));

  // Moves the unbilled hours into the line table. They leave the list at the
  // same moment, or there is no way to tell the press worked.
  function addTrackedTime() {
    setSeed((s) => {
      if (!s) return s;
      const added: Row[] = pendingTime.map((t) => {
        const unitPrice = t.rate ?? '0';
        return {
          description: timeEntryLineDescription({
            entryDate: t.entryDate,
            note: t.note,
            jobName,
          }),
          quantity: t.hours,
          unitLabel: hoursUnitLabel(t.hours),
          unitPrice: formatUnitPrice(unitPrice),
          // Same multiplyMoney every typed row uses, so a billed hour and a
          // hand-typed hour cannot round differently.
          amount: multiplyMoney(t.hours, unitPrice),
          sourceItemId: null,
          timeEntryId: t.id,
          type: 'service' as LineItemType,
          // Taxability of labour varies by state and trade; a tick beats a guess.
          taxable: false,
          taxPolicyId: '',
        };
      });
      const keep = s.rows.filter((r) => r.description || r.quantity || r.unitPrice);
      return { ...s, rows: [...keep, ...added] };
    });
    setPendingTime([]);
  }
  const removeRow = (i: number) =>
    setSeed((s) => (s && s.rows.length > 1 ? { ...s, rows: s.rows.filter((_, j) => j !== i) } : s));
  const toggleRowTaxable = (i: number) =>
    setSeed((s) =>
      s
        ? {
            ...s,
            rows: s.rows.map((r, j) => {
              if (j !== i) return r;
              const turningOn = !r.taxable;
              return {
                ...r,
                taxable: turningOn,
                taxPolicyId:
                  turningOn && !r.taxPolicyId ? resolvePolicyId(taxPolicies, '') : r.taxPolicyId,
              };
            }),
          }
        : s,
    );
  const applyPick = (i: number, patch: ItemPatch) => {
    const { taxable, taxPolicyId, unitLabel, ...rest } = patch;
    setSeed((s) =>
      s
        ? {
            ...s,
            rows: s.rows.map((r, j) => {
              if (j !== i) return r;
              const merged: Row = { ...r, ...rest };
              // A pick carries the item's unit ('' when none); hand-typing the
              // description leaves unitLabel out of the patch, keeping the row's.
              if (unitLabel !== undefined) merged.unitLabel = unitLabel ?? '';
              if (taxable !== undefined) {
                merged.taxable = taxable;
                merged.taxPolicyId = taxable ? resolvePolicyId(taxPolicies, taxPolicyId ?? '') : '';
              }
              // A pick sets unit price + quantity; keep the amount in step.
              merged.amount = multiplyMoney(merged.quantity, merged.unitPrice);
              return merged;
            }),
          }
        : s,
    );
  };

  const computedRows = useMemo(
    () =>
      seed
        ? seed.rows.map((r) => {
            const rate = r.taxable ? policyRate(taxPolicies, r.taxPolicyId) : '0';
            return { ...r, tax: lineTax(r.taxable, rate, r.amount) };
          })
        : [],
    [seed, taxPolicies],
  );
  const subtotal = useMemo(() => sumMoney(computedRows.map((r) => r.amount)), [computedRows]);
  const taxTotal = useMemo(() => sumMoney(computedRows.map((r) => r.tax)), [computedRows]);
  const total = useMemo(() => addMoney(subtotal, taxTotal), [subtotal, taxTotal]);

  async function onSubmit() {
    if (!seed) return;
    setFormError(null);
    setFieldErrors({});

    const lineItems: InvoiceLineItemInput[] = seed.rows.map((r, i) => {
      const amount = multiplyMoney(r.quantity, r.unitPrice);
      const rate = r.taxable ? policyRate(taxPolicies, r.taxPolicyId) : '0';
      return {
        position: i + 1,
        description: r.description.trim(),
        quantity: r.quantity.trim(),
        unitLabel: r.unitLabel.trim() || undefined,
        unitPrice: r.unitPrice.trim(),
        amount,
        type: r.type,
        taxable: r.taxable,
        taxRatePct: rate,
        taxAmount: lineTax(r.taxable, rate, amount),
        taxPolicyId: r.taxable ? r.taxPolicyId || undefined : undefined,
        sourceItemId: r.sourceItemId ?? undefined,
        timeEntryId: r.timeEntryId ?? undefined,
      };
    });
    const sub = sumMoney(lineItems.map((li) => li.amount));
    const taxVal = sumMoney(lineItems.map((li) => li.taxAmount ?? '0'));
    const payload = {
      contactId: seed.contactId,
      number: seed.number.trim(),
      issueDate: seed.issueDate.trim(),
      dueDate: seed.dueDate.trim(),
      subtotal: sub,
      tax: taxVal,
      total: addMoney(sub, taxVal),
      notes: seed.notes.trim() === '' ? undefined : seed.notes.trim(),
      showAddress: seed.showAddress,
      showPhone: seed.showPhone,
      showEmail: seed.showEmail,
      lineItems,
    };

    const parsed = invoiceUpdateSchema.safeParse(payload);
    if (!parsed.success) {
      const errs: Record<string, string> = {};
      for (const issue of parsed.error.issues) {
        const top = String(issue.path[0] ?? '_');
        const key = top === 'lineItems' ? 'lineItems' : top;
        if (!errs[key]) errs[key] = issue.message;
      }
      setFieldErrors(errs);
      return;
    }

    setSubmitting(true);
    try {
      const res = await api.api.invoices[':id'].$patch({ param: { id }, json: parsed.data });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as { error?: string } | null;
        const code = apiErrorMessage(body?.error, 'That could not be saved. Try again.', body);
        setFormError(
          FRIENDLY[code] ?? apiErrorMessage(code, 'That could not be saved. Try again.'),
        );
        return;
      }
      router.replace(`/invoices/${id}`);
    } catch {
      setFormError('That could not be saved. Try again.');
    } finally {
      setSubmitting(false);
    }
  }

  if (!seed) {
    return (
      <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
        {formError ? (
          <Text className="mt-12 px-6 text-sm text-oxblood">Couldn't load this invoice.</Text>
        ) : (
          <View className="mt-12 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        )}
      </SafeAreaView>
    );
  }

  const canSubmit = !submitting && seed.contactId !== '' && seed.number.trim().length > 0;

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView contentContainerClassName="px-6 pt-6 pb-16" keyboardShouldPersistTaps="handled">
          <Pressable onPress={() => router.back()}>
            <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
              ← {seed.number || 'Invoice'}
            </Text>
          </Pressable>
          <Text className="mt-3 font-serif text-3xl font-light text-ink">Edit invoice</Text>

          {formError ? (
            <View className="mt-6 rounded-sm border border-oxblood/30 bg-oxblood/5 px-4 py-3">
              <Text className="text-sm text-oxblood">{formError}</Text>
            </View>
          ) : null}

          <View className="mt-8 gap-5">
            <ContactField
              label="Contact *"
              companyId={companyId}
              contactName={contactName}
              setContactName={setContactName}
              contactId={seed.contactId}
              setContactId={(v) => set('contactId', v)}
              allowCreate={false}
              error={fieldErrors.contactId}
            />

            <LabeledInput
              label="Number *"
              value={seed.number}
              onChangeText={(t) => set('number', t)}
              error={fieldErrors.number}
            />
            <DateField
              label="Issued *"
              value={seed.issueDate}
              onChange={(iso) => set('issueDate', iso)}
              error={fieldErrors.issueDate}
            />
            <DateField
              label="Due *"
              value={seed.dueDate}
              onChange={(iso) => set('dueDate', iso)}
              error={fieldErrors.dueDate}
            />

            {/*
              Hours logged after this draft was started. An explicit press, not
              an auto-seed: the lines here are already curated and silently
              mutating them would be wrong.
            */}
            {pendingTime.length > 0 ? (
              <View className="rounded-sm border border-gold-deep/30 bg-gold-deep/5 p-4">
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                  Unbilled hours on this job
                </Text>
                {pendingTime.map((t) => (
                  <View key={t.id} className="mt-2 flex-row items-center gap-3">
                    <Text className="w-24 text-sm text-ink/60">{t.entryDate}</Text>
                    <Text className="w-14 font-mono text-sm text-ink/80">
                      {formatUnitPrice(t.hours)} h
                    </Text>
                    <Text className="flex-1 text-sm text-ink/70" numberOfLines={1}>
                      {t.note ?? ''}
                    </Text>
                    <Text className="font-mono text-xs text-ink/60">
                      {t.rate ? `$${formatUnitPrice(t.rate)}/h` : 'no rate'}
                    </Text>
                  </View>
                ))}
                <Pressable
                  onPress={addTrackedTime}
                  className="mt-3 self-start rounded-sm bg-ink px-4 py-2.5 active:bg-gold-deep"
                >
                  <Text className="text-sm font-medium text-cream">Add to this invoice</Text>
                </Pressable>
              </View>
            ) : null}

            <LineItems
              rows={seed.rows}
              computed={computedRows}
              error={fieldErrors.lineItems}
              taxPolicies={taxPolicies}
              patchRow={patchRow}
              applyPick={applyPick}
              toggleRowTaxable={toggleRowTaxable}
              addRow={addRow}
              removeRow={removeRow}
            />

            <View className="rounded-sm border border-ink/10 bg-cream-warm p-4">
              <TotalRow label="Subtotal" value={subtotal} />
              <TotalRow label="Tax" value={taxTotal} />
              <View className="mt-3 border-t border-ink/10 pt-3">
                <TotalRow label="Total" value={total} emphasize />
              </View>
            </View>

            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">Notes</Text>
              <TextInput
                value={seed.notes}
                onChangeText={(t) => set('notes', t)}
                multiline
                className="mt-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
              />
            </View>

            <View>
              <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                Your details on this invoice
              </Text>
              <Text className="mt-1 text-xs text-ink/50">
                Only details you've added in Business settings will show.
              </Text>
              <Checkbox
                label="Show my address"
                value={seed.showAddress}
                onToggle={() => set('showAddress', !seed.showAddress)}
                className="mt-3"
              />
              <Checkbox
                label="Show my phone"
                value={seed.showPhone}
                onToggle={() => set('showPhone', !seed.showPhone)}
                className="mt-3"
              />
              <Checkbox
                label="Show my email"
                value={seed.showEmail}
                onToggle={() => set('showEmail', !seed.showEmail)}
                className="mt-3"
              />
            </View>

            <Pressable
              onPress={onSubmit}
              disabled={!canSubmit}
              className="mt-2 rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
            >
              {submitting ? (
                <ActivityIndicator color="#f4ede0" />
              ) : (
                <Text className="text-center text-sm font-medium text-cream">Save changes</Text>
              )}
            </Pressable>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

// Line-item editor — same markup as invoices/new's inline block, lifted to a
// local component since edit + new now both render it.
function LineItems({
  rows,
  computed,
  error,
  taxPolicies,
  patchRow,
  applyPick,
  toggleRowTaxable,
  addRow,
  removeRow,
}: {
  rows: Row[];
  computed: { amount: string; tax: string }[];
  error?: string;
  taxPolicies: TaxPolicyLite[];
  patchRow: (i: number, patch: Partial<Row>) => void;
  applyPick: (i: number, patch: ItemPatch) => void;
  toggleRowTaxable: (i: number) => void;
  addRow: () => void;
  removeRow: (i: number) => void;
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">Line items</Text>
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
      <View className="mt-2 gap-4">
        {rows.map((row, i) => (
          // biome-ignore lint/suspicious/noArrayIndexKey: rows are positional and reorder-free
          <View key={i} className="rounded-sm border border-ink/10 bg-cream-warm p-3">
            <ItemPickerField
              description={row.description}
              onChange={(patch) => applyPick(i, patch)}
            />
            <TypeRow value={row.type} onSelect={(t) => patchRow(i, { type: t })} />
            <View className="mt-2 flex-row gap-2">
              <View className="flex-1">
                <Text className="font-mono text-[10px] uppercase tracking-widest text-ink/50">
                  Qty
                </Text>
                <TextInput
                  value={row.quantity}
                  onChangeText={(t) =>
                    patchRow(i, { quantity: t, amount: multiplyMoney(t, row.unitPrice) })
                  }
                  inputMode="decimal"
                  className="mt-1 rounded-sm border border-ink/15 bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                />
              </View>
              <View className="flex-1">
                <Text className="font-mono text-[10px] uppercase tracking-widest text-ink/50">
                  Unit price
                </Text>
                <TextInput
                  value={row.unitPrice}
                  onChangeText={(t) =>
                    patchRow(i, { unitPrice: t, amount: multiplyMoney(row.quantity, t) })
                  }
                  inputMode="decimal"
                  className="mt-1 rounded-sm border border-ink/15 bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                />
              </View>
              <View className="flex-1">
                <Text className="font-mono text-[10px] uppercase tracking-widest text-ink/50">
                  Amount
                </Text>
                <TextInput
                  value={row.amount}
                  onChangeText={(t) =>
                    patchRow(i, { amount: t, unitPrice: unitPriceFromTotal(t, row.quantity) })
                  }
                  inputMode="decimal"
                  className="mt-1 rounded-sm border border-ink/15 bg-cream px-2 py-2 text-right font-mono tabular-nums text-ink"
                />
              </View>
            </View>
            <View className="mt-2">
              <Text className="font-mono text-[10px] uppercase tracking-widest text-ink/50">
                Unit
              </Text>
              <TextInput
                value={row.unitLabel}
                onChangeText={(t) => patchRow(i, { unitLabel: t })}
                placeholder="hr, day, sq ft"
                maxLength={50}
                className="mt-1 rounded-sm border border-ink/15 bg-cream px-2 py-2 text-ink"
              />
            </View>
            <TaxRow
              taxPolicies={taxPolicies}
              taxable={row.taxable}
              taxPolicyId={row.taxPolicyId}
              lineTaxAmount={computed[i]?.tax ?? '0.00'}
              onToggle={() => toggleRowTaxable(i)}
              onSelectPolicy={(pid) => patchRow(i, { taxPolicyId: pid })}
            />
            {rows.length > 1 ? (
              <Pressable onPress={() => removeRow(i)} className="mt-2 self-end">
                <Text className="font-mono text-xs uppercase tracking-wider text-oxblood">
                  Remove
                </Text>
              </Pressable>
            ) : null}
          </View>
        ))}
      </View>
      <Pressable onPress={addRow} className="mt-3">
        <Text className="text-sm font-medium text-gold-deep">+ Add row</Text>
      </Pressable>
    </View>
  );
}

function LabeledInput({
  label,
  value,
  onChangeText,
  error,
}: {
  label: string;
  value: string;
  onChangeText: (t: string) => void;
  error?: string;
}) {
  return (
    <View>
      <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">{label}</Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        className="mt-1 rounded-sm border border-ink/15 bg-cream-warm px-3 py-2 text-ink"
      />
      {error ? <Text className="mt-1 text-xs text-oxblood">{error}</Text> : null}
    </View>
  );
}

function TotalRow({
  label,
  value,
  emphasize,
}: { label: string; value: string; emphasize?: boolean }) {
  return (
    <View className="flex-row justify-between">
      <Text
        className={`font-mono text-xs uppercase tracking-widest ${emphasize ? 'text-ink/70' : 'text-ink/50'}`}
      >
        {label}
      </Text>
      <Text className={`font-mono tabular-nums text-ink ${emphasize ? 'text-lg' : ''}`}>
        {value}
      </Text>
    </View>
  );
}
