// apps/web/src/routes/(app)/reports/ar-aging/+page.svelte
<script lang="ts">
  import AsOfSelector from '$lib/components/AsOfSelector.svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  const { report } = $derived(data);

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  // Overdue rows get progressively redder; current (not yet due) stays ink.
  const tone = (days: number) =>
    days <= 0 ? 'text-ink/70' : days <= 30 ? 'text-ink' : days <= 90 ? 'text-gold-deep' : 'text-oxblood';
</script>

<div>
  <span class="eyebrow">Reports</span>
  <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
    A/R aging<span class="text-gold-deep">.</span>
  </h1>
</div>

<AsOfSelector asOf={report.asOf} />

<p class="mt-4 text-sm text-ink/60">
  As of {report.asOf}. Sent invoices that haven't been paid, by how overdue they are.
</p>

<!-- Bucket summary -->
<div class="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-5">
  {#each report.buckets as b (b.key)}
    <div class="rounded-sm border border-ink/10 bg-cream-warm p-4">
      <div class="font-mono text-xs uppercase tracking-widest text-ink/50">{b.label}</div>
      <div class="mt-2 font-mono text-lg tabular-nums text-ink">{fmt(b.amount)}</div>
      <div class="mt-0.5 text-xs text-ink/50">{b.count} invoice{b.count === 1 ? '' : 's'}</div>
    </div>
  {/each}
</div>

{#if report.invoices.length === 0}
  <p class="mt-8 text-ink/70">Nothing outstanding — you're all paid up.</p>
{:else}
  <div class="mt-6 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
    <table class="w-full text-left text-sm">
      <thead class="bg-cream">
        <tr class="font-mono text-xs uppercase tracking-widest text-ink/50">
          <th class="px-5 py-3">Number</th>
          <th class="px-5 py-3">Customer</th>
          <th class="px-5 py-3">Due</th>
          <th class="px-5 py-3 text-right">Overdue</th>
          <th class="px-5 py-3 text-right">Amount</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-ink/10">
        {#each report.invoices as inv (inv.id)}
          <tr class="hover:bg-cream">
            <td class="px-5 py-3">
              <a href="/invoices/{inv.id}" class="font-serif text-ink hover:text-gold-deep">
                {inv.number}
              </a>
            </td>
            <td class="px-5 py-3 text-ink/80">{inv.customerName ?? '—'}</td>
            <td class="px-5 py-3 text-ink/70">{inv.dueDate}</td>
            <td class="px-5 py-3 text-right font-mono tabular-nums {tone(inv.daysPastDue)}">
              {inv.daysPastDue <= 0 ? 'Current' : `${inv.daysPastDue}d`}
            </td>
            <td class="px-5 py-3 text-right font-mono tabular-nums text-ink">{fmt(inv.amount)}</td>
          </tr>
        {/each}
      </tbody>
      <tfoot class="border-t border-ink/10 bg-cream">
        <tr class="font-mono text-xs uppercase tracking-widest">
          <td class="px-5 py-3 text-ink/70" colspan="4">Total outstanding</td>
          <td class="px-5 py-3 text-right text-base tabular-nums text-ink">{fmt(report.total)}</td>
        </tr>
      </tfoot>
    </table>
  </div>
{/if}

// apps/mobile/src/app/(app)/more/reports/ar-aging.tsx
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { AsOfSelector } from '../../../../components/AsOfSelector';
import { ReportBody, ReportScaffold, TotalRow } from '../../../../components/ReportLayout';
import { api } from '../../../../lib/api';
import { fmt, todayYmd } from '../../../../lib/report-periods';
import { useReport } from '../../../../lib/use-report';

// Mirror of web's /reports/ar-aging — unpaid sent invoices bucketed by how
// overdue they are. Overdue rows get progressively redder.
const tone = (days: number) =>
  days <= 0
    ? 'text-ink/70'
    : days <= 30
      ? 'text-ink'
      : days <= 90
        ? 'text-gold-deep'
        : 'text-oxblood';

export default function ArAgingReport() {
  const router = useRouter();
  const [asOf, setAsOf] = useState(todayYmd());
  const { data, error } = useReport(
    (companyId) =>
      api.api.companies[':id']['ar-aging']
        .$get({ param: { id: companyId }, query: { asOf } })
        .then((res) => (res.ok ? res.json() : null)),
    [asOf],
  );

  return (
    <ReportScaffold
      title="A/R aging"
      selector={<AsOfSelector asOf={asOf} onChange={setAsOf} />}
      note={`As of ${asOf}. Sent invoices that haven't been paid, by how overdue they are.`}
    >
      <ReportBody data={data} error={error}>
        {(d) => (
          <>
            <View className="mt-8 flex-row flex-wrap gap-3">
              {d.buckets.map((b) => (
                <View
                  key={b.key}
                  className="grow basis-[45%] rounded-sm border border-ink/10 bg-cream-warm p-4"
                >
                  <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
                    {b.label}
                  </Text>
                  <Text className="mt-2 font-mono text-lg tabular-nums text-ink">
                    {fmt(b.amount)}
                  </Text>
                  <Text className="mt-0.5 text-xs text-ink/50">
                    {b.count} invoice{b.count === 1 ? '' : 's'}
                  </Text>
                </View>
              ))}
            </View>

            {d.invoices.length === 0 ? (
              <Text className="mt-8 text-ink/70">Nothing outstanding — you're all paid up.</Text>
            ) : (
              <View className="mt-6 overflow-hidden rounded-sm border border-ink/10 bg-cream-warm">
                {d.invoices.map((inv) => (
                  <Pressable
                    key={inv.id}
                    onPress={() => router.push(`/invoices/${inv.id}`)}
                    className="border-t border-ink/10 px-4 py-3 active:bg-cream"
                  >
                    <View className="flex-row items-center justify-between">
                      <Text className="font-serif text-ink">{inv.number}</Text>
                      <Text className="font-mono text-sm tabular-nums text-ink">
                        {fmt(inv.amount)}
                      </Text>
                    </View>
                    <View className="mt-1 flex-row items-center justify-between">
                      <View className="flex-1 pr-3">
                        <Text className="text-sm text-ink/70">{inv.customerName ?? '—'}</Text>
                        <Text className="font-mono text-xs text-ink/40">due {inv.dueDate}</Text>
                      </View>
                      <Text className={`font-mono text-xs tabular-nums ${tone(inv.daysPastDue)}`}>
                        {inv.daysPastDue <= 0 ? 'Current' : `${inv.daysPastDue}d`}
                      </Text>
                    </View>
                  </Pressable>
                ))}
                <TotalRow label="Total outstanding" amount={fmt(d.total)} />
              </View>
            )}
          </>
        )}
      </ReportBody>
    </ReportScaffold>
  );
}
