// apps/web/src/routes/(app)/reports/+page.svelte
<script lang="ts">
  // Reports hub. Static index of the available reports — no data fetch; each
  // card links to a report that loads its own data.
  const reports = [
    {
      href: '/reports/profit-and-loss',
      title: 'Profit & loss',
      blurb: 'Revenue minus expenses — what you actually made over a period.',
    },
    {
      href: '/reports/expenses-by-category',
      title: 'Expenses by category',
      blurb: 'Where the money went, grouped by your Schedule C buckets.',
    },
    {
      href: '/reports/balance-sheet',
      title: 'Balance sheet',
      blurb: 'What you own and owe — assets, liabilities, and equity.',
    },
    {
      href: '/reports/ar-aging',
      title: 'A/R aging',
      blurb: 'Unpaid invoices by how overdue they are — who to chase.',
    },
    {
      href: '/reports/sales-tax',
      title: 'Sales tax collected',
      blurb: 'Tax billed on invoices over a period, ready to remit.',
    },
    {
      href: '/reports/sales-by-customer',
      title: 'Sales by customer',
      blurb: 'Your best customers by revenue over a period.',
    },
    {
      href: '/reports/revenue-over-time',
      title: 'Revenue over time',
      blurb: 'Monthly sales trend across the period.',
    },
    {
      href: '/reports/estimate-win-rate',
      title: 'Estimate win rate',
      blurb: 'How many quotes turn into accepted work.',
    },
    {
      href: '/reports/top-products',
      title: 'Top products',
      blurb: 'Best-selling items and services by revenue.',
    },
  ];
</script>

<div>
  <span class="eyebrow">Reports</span>
  <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
    Reports<span class="text-gold-deep">.</span>
  </h1>
</div>

<div class="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2">
  {#each reports as r (r.href)}
    <a
      href={r.href}
      class="group rounded-sm border border-ink/10 bg-cream-warm p-5 transition-colors hover:border-gold-deep/40 hover:bg-cream"
    >
      <h2 class="font-serif text-xl text-ink group-hover:text-gold-deep">{r.title}</h2>
      <p class="mt-2 text-sm text-ink/60">{r.blurb}</p>
    </a>
  {/each}
</div>

// apps/mobile/src/app/(app)/more/reports/index.tsx
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

// Reports hub — the RN mirror of web's /reports/+page.svelte. A static index;
// each card links to a report that loads its own data. Lives under the "More"
// tab's Stack (reached from the More hub's Reports entry).
type ReportHref =
  | '/more/reports/profit-and-loss'
  | '/more/reports/expenses-by-category'
  | '/more/reports/balance-sheet'
  | '/more/reports/ar-aging'
  | '/more/reports/sales-tax'
  | '/more/reports/sales-by-customer'
  | '/more/reports/revenue-over-time'
  | '/more/reports/estimate-win-rate'
  | '/more/reports/top-products';

const REPORTS: { href: ReportHref; title: string; blurb: string }[] = [
  {
    href: '/more/reports/profit-and-loss',
    title: 'Profit & loss',
    blurb: 'Revenue minus expenses — what you actually made over a period.',
  },
  {
    href: '/more/reports/expenses-by-category',
    title: 'Expenses by category',
    blurb: 'Where the money went, grouped by your Schedule C buckets.',
  },
  {
    href: '/more/reports/balance-sheet',
    title: 'Balance sheet',
    blurb: 'What you own and owe — assets, liabilities, and equity.',
  },
  {
    href: '/more/reports/ar-aging',
    title: 'A/R aging',
    blurb: 'Unpaid invoices by how overdue they are — who to chase.',
  },
  {
    href: '/more/reports/sales-tax',
    title: 'Sales tax collected',
    blurb: 'Tax billed on invoices over a period, ready to remit.',
  },
  {
    href: '/more/reports/sales-by-customer',
    title: 'Sales by contact',
    blurb: 'Your best contacts by revenue over a period.',
  },
  {
    href: '/more/reports/revenue-over-time',
    title: 'Revenue over time',
    blurb: 'Monthly sales trend across the period.',
  },
  {
    href: '/more/reports/estimate-win-rate',
    title: 'Estimate win rate',
    blurb: 'How many quotes turn into accepted work.',
  },
  {
    href: '/more/reports/top-products',
    title: 'Top products',
    blurb: 'Best-selling items and services by revenue.',
  },
];

export default function ReportsHub() {
  const router = useRouter();
  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <Pressable onPress={() => router.push('/more')}>
          <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">← More</Text>
        </Pressable>
        <Text className="mt-3 font-serif text-3xl font-light text-ink">Reports</Text>

        <View className="mt-8 space-y-4">
          {REPORTS.map((r) => (
            <Pressable
              key={r.href}
              onPress={() => router.push(r.href)}
              className="rounded-sm border border-ink/10 bg-cream-warm p-5 active:bg-cream"
            >
              <Text className="font-serif text-lg text-ink">{r.title}</Text>
              <Text className="mt-1 text-sm text-ink/60">{r.blurb}</Text>
            </Pressable>
          ))}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
