// apps/web/src/routes/(app)/reports/sales-by-customer/+page.svelte
<script lang="ts">
  import { ShareBar } from '$lib/charts';
  import ExportCsvButton from '$lib/components/ExportCsvButton.svelte';
  import PeriodSelector from '$lib/components/PeriodSelector.svelte';
  import type { CsvCell } from '$lib/csv';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  const { report, presets, activeKey } = $derived(data);

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  const total = $derived(Number(report.totalSales));
  const rows = $derived(
    report.contacts.map((c) => ({
      ...c,
      share: total > 0 ? (Number(c.sales) / total) * 100 : 0,
    })),
  );

  const csvRows = $derived<CsvCell[][]>([
    ['Contact', 'Invoices', 'Sales', 'Share %'],
    ...rows.map(
      (c) => [c.name ?? '', c.invoiceCount, c.sales, c.share.toFixed(1)] as CsvCell[],
    ),
    ['Total', '', report.totalSales, ''],
  ]);
</script>

<div class="flex flex-wrap items-baseline justify-between gap-6">
  <div>
    <a href="/reports" class="eyebrow text-fg/60 hover:text-fg">← Reports</a>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-fg">
      Sales by contact<span class="text-accent">.</span>
    </h1>
  </div>
  <ExportCsvButton
    filename="sales-by-customer_{report.from}_{report.to}"
    rows={csvRows}
    disabled={rows.length === 0}
  />
</div>

<PeriodSelector {presets} {activeKey} from={report.from} to={report.to} />

<p class="mt-4 text-sm text-fg/60">
  {report.from} → {report.to}. Pre-tax sales from sent or paid invoices, top 25 contacts by
  revenue.
</p>

{#if rows.length === 0}
  <p class="mt-8 text-fg/70">No sales in this period.</p>
{:else}
  <div class="mt-8 overflow-hidden rounded-sm border border-fg/10 bg-surface-2">
    <table class="w-full text-left text-sm">
      <thead class="bg-surface">
        <tr class="label">
          <th class="px-5 py-3">Contact</th>
          <th class="w-1/3 px-5 py-3">Share</th>
          <th class="w-20 px-5 py-3 text-right">Invoices</th>
          <th class="w-36 px-5 py-3 text-right">Sales</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-fg/10">
        {#each rows as c (c.contactId)}
          <tr>
            <td class="px-5 py-3">
              <a href="/contacts/{c.contactId}" class="text-fg hover:text-accent">
                {c.name ?? '—'}
              </a>
            </td>
            <td class="px-5 py-3">
              <ShareBar value={c.share / 100} />
            </td>
            <td class="px-5 py-3 text-right font-mono tabular-nums text-fg/70">{c.invoiceCount}</td>
            <td class="px-5 py-3 text-right font-mono tabular-nums text-fg">{fmt(c.sales)}</td>
          </tr>
        {/each}
      </tbody>
      <tfoot class="border-t border-fg/10 bg-surface">
        <tr class="font-mono text-xs uppercase tracking-widest">
          <td class="px-5 py-3 text-fg/70">Total</td>
          <td></td>
          <td></td>
          <td class="px-5 py-3 text-right text-base tabular-nums text-fg">
            {fmt(report.totalSales)}
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
{/if}

// apps/mobile/src/app/(app)/more/reports/sales-by-customer.tsx
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { PeriodSelector } from '../../../../components/PeriodSelector';
import {
  ReportBody,
  ReportCard,
  ReportScaffold,
  TotalRow,
} from '../../../../components/ReportLayout';
import { ShareBar } from '../../../../components/charts';
import { api } from '../../../../lib/api';
import { fmt, ytdWindow } from '../../../../lib/report-periods';
import { useReport } from '../../../../lib/use-report';

// Mirror of web's /reports/sales-by-customer — pre-tax sales (sent or paid),
// top 25 contacts by revenue, each with its share of the total. Rows link to
// the contact.
export default function SalesByCustomerReport() {
  const router = useRouter();
  const [{ from, to }, setWindow] = useState(ytdWindow());
  const { data, error } = useReport(
    (companyId) =>
      api.api.companies[':id']['sales-by-customer']
        .$get({ param: { id: companyId }, query: { from, to } })
        .then((res) => (res.ok ? res.json() : null)),
    [from, to],
  );

  return (
    <ReportScaffold
      title="Sales by contact"
      selector={
        <PeriodSelector from={from} to={to} onChange={(f, t) => setWindow({ from: f, to: t })} />
      }
      note={`${from} → ${to}. Pre-tax sales from sent or paid invoices, top 25 contacts by revenue.`}
    >
      <ReportBody data={data} error={error}>
        {(d) => {
          const total = Number(d.totalSales);
          if (d.contacts.length === 0) {
            return <Text className="mt-8 text-ink/70">No sales in this period.</Text>;
          }
          return (
            <ReportCard>
              {d.contacts.map((c) => (
                <Pressable
                  key={c.contactId}
                  onPress={() => router.push(`/contacts/${c.contactId}`)}
                  className="border-t border-ink/10 px-4 py-3 active:bg-cream"
                >
                  <View className="flex-row items-center justify-between">
                    <View className="flex-1 pr-3">
                      <Text className="text-ink">{c.name ?? '—'}</Text>
                      <Text className="font-mono text-xs text-ink/40">
                        {c.invoiceCount} invoice{c.invoiceCount === 1 ? '' : 's'}
                      </Text>
                    </View>
                    <Text className="font-mono text-sm tabular-nums text-ink">{fmt(c.sales)}</Text>
                  </View>
                  <ShareBar value={total > 0 ? Number(c.sales) / total : 0} />
                </Pressable>
              ))}
              <TotalRow label="Total" amount={fmt(d.totalSales)} />
            </ReportCard>
          );
        }}
      </ReportBody>
    </ReportScaffold>
  );
}
