// apps/mobile/src/app/welcome/brand.tsx
import * as ImagePicker from 'expo-image-picker';
import { Redirect, useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { WelcomeHeader } from '../../components/WelcomeHeader';
import { pickActiveCompany } from '../../lib/active-company';
import { api } from '../../lib/api';
import { getServerUrl } from '../../lib/server-url';
import { uploadLogo } from '../../lib/upload';

// Step 3 — Make it yours. Optional logo, then the handoff into the first invoice.
// Mirror of web's welcome/brand. The logo path reuses the Business-settings
// pattern (image picker → multipart upload → signed-URL preview).
type Logo = { url: string; contentType: string };

const LOGO_ERRORS: Record<string, string> = {
  unsupported_media_type: 'Logo must be a PNG, JPEG, or WebP.',
  file_too_large: 'Logo must be under 2 MB.',
  storage_not_configured: 'Logo storage is not configured on this server.',
};

const absolutize = (url: string) => (url.startsWith('http') ? url : `${getServerUrl()}${url}`);

export default function WelcomeBrand() {
  const router = useRouter();
  const [load, setLoad] = useState<'loading' | 'ready' | 'gone' | 'error'>('loading');
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [logo, setLogo] = useState<Logo | null>(null);
  const [logoBusy, setLogoBusy] = useState(false);
  const [logoError, setLogoError] = useState<string | null>(null);
  const bootstrapped = useRef(false);

  const fetchLogo = useCallback(async (id: string, active: () => boolean) => {
    const res = await api.api.companies[':id'].logo.$get({ param: { id } });
    if (!active()) return;
    setLogo(res.ok ? ((await res.json()) as Logo) : null);
  }, []);

  useFocusEffect(
    useCallback(() => {
      if (bootstrapped.current) return;
      bootstrapped.current = true;
      let active = true;
      (async () => {
        const res = await api.api.companies.$get();
        if (!active) return;
        if (!res.ok) {
          setLoad('error');
          return;
        }
        const { companies } = await res.json();
        const picked = await pickActiveCompany(companies);
        if (!picked) {
          setLoad('gone');
          return;
        }
        setCompanyId(picked.id);
        await fetchLogo(picked.id, () => active);
        if (active) setLoad('ready');
      })().catch(() => {
        if (active) setLoad('error');
      });
      return () => {
        active = false;
      };
    }, [fetchLogo]),
  );

  async function onPickLogo() {
    if (!companyId) return;
    setLogoError(null);
    const perm = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!perm.granted) {
      setLogoError('Photo access denied.');
      return;
    }
    const result = await ImagePicker.launchImageLibraryAsync({
      quality: 0.9,
      mediaTypes: ['images'],
    });
    if (result.canceled || !result.assets[0]) return;
    setLogoBusy(true);
    try {
      const up = await uploadLogo(companyId, result.assets[0]);
      if (!up.ok) {
        setLogoError(LOGO_ERRORS[up.error] ?? 'Upload failed. Try again.');
        return;
      }
      await fetchLogo(companyId, () => true);
    } finally {
      setLogoBusy(false);
    }
  }

  if (load === 'gone') return <Redirect href="/" />;

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <ScrollView contentContainerClassName="px-6 pt-6 pb-16">
        <WelcomeHeader step={3} />

        {load === 'loading' ? (
          <View className="mt-16 items-center">
            <ActivityIndicator color="#0f1626" />
          </View>
        ) : load === 'error' ? (
          <Text className="mt-10 text-sm text-oxblood">Couldn't load your business.</Text>
        ) : (
          <>
            <Text className="mt-8 font-mono text-xs uppercase tracking-widest text-gold-deep">
              Almost there
            </Text>
            <Text className="mt-3 font-serif text-3xl font-light text-ink">Make it yours.</Text>
            <Text className="mt-3 text-sm text-ink/70">
              Add a logo and it'll appear on every invoice and estimate your customers see. Optional
              — you can always add one later from Settings.
            </Text>

            <View className="mt-8 rounded-sm border border-ink/15 bg-cream-warm p-6">
              {logo ? (
                <Image
                  source={{ uri: absolutize(logo.url) }}
                  resizeMode="contain"
                  className="h-24 w-48 self-start rounded-sm border border-ink/10 bg-cream"
                />
              ) : (
                <Text className="text-sm text-ink/50">No logo yet.</Text>
              )}
              <Pressable
                onPress={onPickLogo}
                disabled={logoBusy}
                className="mt-4 self-start rounded-sm bg-ink px-4 py-3 active:bg-gold-deep disabled:opacity-50"
              >
                <Text className="text-sm font-medium text-cream">
                  {logoBusy ? 'Uploading…' : logo ? 'Replace' : 'Upload a logo'}
                </Text>
              </Pressable>
              {logoError ? <Text className="mt-3 text-sm text-oxblood">{logoError}</Text> : null}
            </View>

            <View className="mt-10 gap-4">
              <Pressable
                onPress={() => router.replace('/invoices/new')}
                className="rounded-sm bg-ink px-6 py-3 active:bg-gold-deep"
              >
                <Text className="text-center text-sm font-medium text-cream">
                  Send your first invoice →
                </Text>
              </Pressable>
              <Pressable onPress={() => router.replace('/')} className="py-2">
                <Text className="text-center font-mono text-xs uppercase tracking-widest text-ink/50">
                  Go to dashboard
                </Text>
              </Pressable>
            </View>
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

// apps/web/src/routes/welcome/brand/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';

  let { data, form }: PageProps = $props();
</script>

<span class="eyebrow">Almost there</span>
<h1 class="mt-3 font-serif text-3xl font-light leading-tight tracking-tight text-ink">
  Make it yours<span class="text-gold-deep">.</span>
</h1>
<p class="mt-4 text-ink/70">
  Add a logo and it'll appear on every invoice and estimate your customers see. Optional — you can
  always add one later from Settings.
</p>

<div class="mt-8 rounded-sm border border-ink/15 bg-cream-warm px-6 py-6">
  {#if data.logo}
    <img
      src={data.logo.url}
      alt="Your logo"
      class="max-h-24 max-w-[16rem] rounded-sm border border-ink/10 bg-cream object-contain p-2"
    />
    <p class="mt-3 font-mono text-xs uppercase tracking-widest text-sage">Looking sharp.</p>
  {:else}
    <p class="text-sm text-ink/50">No logo yet.</p>
  {/if}

  <form
    method="POST"
    action="?/uploadLogo"
    enctype="multipart/form-data"
    class="mt-5 flex flex-wrap items-center gap-3"
  >
    <input type="hidden" name="companyId" value={data.company.id} />
    <input
      type="file"
      name="logo"
      accept="image/png,image/jpeg,image/webp"
      class="text-sm text-ink/70 file:mr-3 file:rounded-sm file:border-0 file:bg-ink file:px-3 file:py-1.5 file:text-sm file:font-medium file:text-cream hover:file:bg-gold-deep"
    />
    <button
      type="submit"
      class="rounded-sm border border-ink/25 px-4 py-2 text-sm font-medium text-ink transition-colors hover:border-ink"
    >
      {data.logo ? 'Replace' : 'Upload'}
    </button>
  </form>
  {#if form?.logoError}
    <p class="mt-3 text-sm text-oxblood">{form.logoError}</p>
  {/if}
</div>

<div class="mt-10 flex items-center justify-between gap-4">
  <a
    href="/"
    class="font-mono text-xs uppercase tracking-widest text-ink/50 hover:text-ink"
  >
    Go to dashboard
  </a>
  <a
    href="/invoices/new"
    class="rounded-sm bg-ink px-6 py-3 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
  >
    Send your first invoice →
  </a>
</div>
