// apps/mobile/src/app/(app)/more/items/index.tsx
import { useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../../../lib/api';
import { useMay } from '../../../../lib/role';
import { pageQuery, usePaginatedList } from '../../../../lib/use-paginated-list';

// Mirror of apps/web's /settings/items. Account-scoped via x-account-id; keyset
// infinite scroll. Archived items are hidden until the "Show archived" toggle
// flips includeArchived=true (the toggle changes fetchPage, which re-runs page
// 1). Items archive/restore instead of deleting — there's no item DELETE.
type ItemRow = {
  id: string;
  name: string;
  unitPrice: string;
  unitLabel: string | null;
  archivedAt: string | null;
};

const fmt = (s: string) =>
  Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const priceLabel = (unitPrice: string, unitLabel: string | null) =>
  unitLabel ? `${fmt(unitPrice)} / ${unitLabel}` : fmt(unitPrice);

export default function ItemsList() {
  const router = useRouter();
  const canCreate = useMay('sales:write');
  const [showArchived, setShowArchived] = useState(false);
  const [busyId, setBusyId] = useState<string | null>(null);

  const fetchPage = useCallback(
    async (cursor: string | null) => {
      const query = pageQuery(cursor);
      if (showArchived) query.includeArchived = 'true';
      const res = await api.api.items.$get({ query });
      if (!res.ok) return null;
      const { items, nextCursor } = await res.json();
      return {
        rows: items.map(
          (i): ItemRow => ({
            id: i.id,
            name: i.name,
            unitPrice: i.unitPrice,
            unitLabel: i.unitLabel ?? null,
            archivedAt: i.archivedAt ?? null,
          }),
        ),
        nextCursor,
      };
    },
    [showArchived],
  );

  const { list, loadingMore, loadMore, reload } = usePaginatedList(fetchPage);

  async function toggleArchive(item: ItemRow) {
    setBusyId(item.id);
    try {
      const res = item.archivedAt
        ? await api.api.items[':id'].restore.$post({ param: { id: item.id } })
        : await api.api.items[':id'].archive.$post({ param: { id: item.id } });
      if (res.ok) reload();
    } catch {
      // Leave the row as-is; a focus refetch will reconcile.
    } finally {
      setBusyId(null);
    }
  }

  return (
    <SafeAreaView className="flex-1 bg-cream" edges={['top']}>
      <View className="px-6 pt-6">
        <Pressable onPress={() => router.push('/more')}>
          <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">← More</Text>
        </Pressable>
        <View className="mt-3 flex-row items-end justify-between">
          <Text className="font-serif text-3xl font-light text-ink">Products &amp; services</Text>
          {canCreate ? (
            <Pressable
              onPress={() => router.push('/more/items/new')}
              className="rounded-sm bg-ink px-4 py-2 active:bg-gold-deep"
            >
              <Text className="text-sm font-medium text-cream">+ New</Text>
            </Pressable>
          ) : null}
        </View>
        <Pressable onPress={() => setShowArchived((s) => !s)} className="mt-4 self-start">
          <Text className="font-mono text-xs uppercase tracking-widest text-ink/50">
            {showArchived ? '← Hide archived' : 'Show archived'}
          </Text>
        </Pressable>
      </View>

      {list.state === 'loading' ? (
        <View className="mt-12 items-center">
          <ActivityIndicator color="#0f1626" />
        </View>
      ) : list.state === 'error' ? (
        <Text className="mt-8 px-6 text-sm text-oxblood">Couldn't load items.</Text>
      ) : list.rows.length === 0 ? (
        <Text className="mt-8 px-6 text-ink/70">
          {showArchived ? 'No items yet.' : 'No active items yet.'}
        </Text>
      ) : (
        <FlatList
          data={list.rows}
          keyExtractor={(i) => i.id}
          className="mt-6"
          contentContainerClassName="px-6 pb-6"
          ItemSeparatorComponent={() => <View className="h-px bg-ink/10" />}
          onEndReached={loadMore}
          onEndReachedThreshold={0.4}
          ListFooterComponent={
            loadingMore ? (
              <View className="py-4">
                <ActivityIndicator color="#0f1626" />
              </View>
            ) : null
          }
          renderItem={({ item }) => (
            <View className="flex-row items-center gap-3 bg-cream-warm px-5 py-4">
              <Pressable
                onPress={() => router.push(`/more/items/${item.id}`)}
                className="flex-1 active:opacity-70"
              >
                <View className="flex-row items-center gap-2">
                  <Text className="font-serif text-lg text-ink">{item.name}</Text>
                  {item.archivedAt ? (
                    <Text className="rounded-sm border border-ink/15 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-ink/50">
                      Archived
                    </Text>
                  ) : null}
                </View>
                <Text className="mt-1 font-mono text-xs uppercase tracking-widest text-ink/50">
                  {priceLabel(item.unitPrice, item.unitLabel)}
                </Text>
              </Pressable>
              <Pressable
                onPress={() => toggleArchive(item)}
                disabled={busyId === item.id}
                className="rounded-sm border border-ink/15 px-2 py-1 active:border-gold-deep disabled:opacity-50"
              >
                <Text className="font-mono text-xs uppercase tracking-widest text-ink/60">
                  {item.archivedAt ? 'Restore' : 'Archive'}
                </Text>
              </Pressable>
            </View>
          )}
        />
      )}
    </SafeAreaView>
  );
}

// apps/web/src/routes/(app)/settings/items/+page.svelte
<script lang="ts">
  import LoadMore from '$lib/components/LoadMore.svelte';
  import { fetchMore } from '$lib/load-more';
  import { may } from '$lib/perms';
  import { untrack } from 'svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  const showArchived = $derived(data.showArchived);

  // See /customers for the untrack() seed-and-re-seed pattern. Here load()
  // re-runs on both the archived-toggle nav and the archive/restore POST
  // (which redirects back), so the $effect keeps the list in sync.
  type Row = (typeof data.items)[number];
  let rows = $state<Row[]>(untrack(() => data.items));
  let cursor = $state<string | null>(untrack(() => data.nextCursor));
  let loading = $state(false);
  let loadError = $state(false);

  $effect(() => {
    const nextRows = data.items;
    const next = data.nextCursor;
    untrack(() => {
      rows = nextRows;
      cursor = next;
    });
  });

  async function more() {
    if (loading || cursor === null) return;
    loading = true;
    loadError = false;
    try {
      const page = await fetchMore<Row>('/settings/items/more', cursor, {
        archived: showArchived ? '1' : '',
      });
      rows = [...rows, ...page.rows];
      cursor = page.nextCursor;
    } catch {
      loadError = true;
    } finally {
      loading = false;
    }
  }

  const fmt = (s: string) =>
    Number(s).toLocaleString('en-US', { style: 'currency', currency: 'USD' });

  // Price line: "$65.00 / hour" when a unit label is set, otherwise the bare
  // amount. default_quantity is editor-side convenience, not shown in the list.
  function priceLabel(unitPrice: string, unitLabel: string | null): string {
    return unitLabel ? `${fmt(unitPrice)} / ${unitLabel}` : fmt(unitPrice);
  }
</script>

<div class="flex items-baseline justify-between gap-6">
  <div>
    <span class="eyebrow">Items</span>
    <h1 class="mt-3 font-serif text-4xl font-light leading-none tracking-tight text-ink">
      Products &amp; services<span class="text-gold-deep">.</span>
    </h1>
  </div>
  {#if may(data.role, 'sales:write')}
    <a
      href="/settings/items/new"
      class="rounded-sm bg-ink px-4 py-2 text-sm font-medium text-cream transition-colors hover:bg-gold-deep"
    >
      + New item
    </a>
  {/if}
</div>

<p class="mt-3 text-sm text-ink/60">
  A reusable catalog you can pull into any invoice, estimate, or recurring schedule.
</p>

<div class="mt-6">
  <a
    href={data.showArchived ? '/settings/items' : '/settings/items?archived=1'}
    class="font-mono text-xs uppercase tracking-widest text-ink/50 hover:text-gold-deep"
  >
    {data.showArchived ? '← Hide archived' : 'Show archived'}
  </a>
</div>

{#if rows.length === 0}
  <p class="mt-8 text-ink/70">
    {data.showArchived ? 'No items yet.' : 'No active items yet.'}
  </p>
{:else}
  <ul class="mt-6 divide-y divide-ink/10 rounded-sm border border-ink/10 bg-cream-warm">
    {#each rows as item (item.id)}
      <li class="flex items-center justify-between gap-4 px-5 py-4">
        <a href="/settings/items/{item.id}" class="min-w-0 flex-1 transition-colors hover:opacity-70">
          <span class="font-serif text-lg text-ink">{item.name}</span>
          {#if item.archivedAt}
            <span
              class="ml-2 rounded-sm border border-ink/15 px-1.5 py-0.5 font-mono text-[0.6rem] uppercase tracking-widest text-ink/50"
            >
              Archived
            </span>
          {/if}
        </a>
        <span class="font-mono text-xs uppercase tracking-widest text-ink/50">
          {priceLabel(item.unitPrice, item.unitLabel)}
        </span>
        <form method="post" action={item.archivedAt ? '?/restore' : '?/archive'}>
          <input type="hidden" name="id" value={item.id} />
          <button
            type="submit"
            class="rounded-sm border border-ink/15 px-2 py-1 font-mono text-xs uppercase tracking-widest text-ink/60 transition-colors hover:border-gold-deep hover:text-gold-deep"
          >
            {item.archivedAt ? 'Restore' : 'Archive'}
          </button>
        </form>
      </li>
    {/each}
  </ul>
  <LoadMore hasMore={cursor !== null} {loading} error={loadError} onclick={more} />
{/if}
